blocks/blockstore/blockstore.go, blocks/blockstore/blockstore_test.go, thirdparty/ds-help/key.go
In the filestore (#2634) i needed to convert from Cid to DsKey and the reverse in several places so I created two helper functions to that effect.
=> ds-help: add helper functions to convert from Cid to DsKey and the reverse

cmd/ipfs/daemon.go, test/sharness/t0600-issues-and-regressions-online.sh
I made last minute change last time and didn't test it properly.
This disabled metrics-interface as injection was being done after all collectors were being registered.
=> Fix metrics injection

commands/http/handler.go
Otherwise API clients block on pubsub subscriptions until the first packet is sent (see, well, #3304).
=> http api: makes sure header is sent even when r is not ready yet. fixes #3304

commands/files/file.go, core/coreunix/add.go, core/coreunix/add_test.go, importer/balanced/builder.go, importer/chunk/rabin.go, importer/chunk/splitting.go, importer/helpers/dagbuilder.go, importer/helpers/helpers.go, thirdparty/posinfo/posinfo.go
=> Create a FilestoreNode object to carry PosInfo

core/builder.go, core/commands/files/files.go, core/commands/get.go, core/commands/ls.go, core/commands/object/diff.go, core/commands/object/object.go, core/commands/object/patch.go, core/commands/pin.go, core/commands/publish.go, core/commands/refs.go, core/commands/resolve.go, core/commands/tar.go, core/commands/unixfs/ls.go, core/core.go, core/corehttp/gateway_handler.go, core/corerepo/pinning.go, core/coreunix/cat.go, core/pathresolver.go, core/pathresolver_test.go, fuse/ipns/ipns_unix.go, path/resolver.go, path/resolver_test.go, unixfs/io/resolve.go
This is some preliminiary work before we can get sharding in. Resolving a path now requires a certain bit of context and logic around what the path actually refers to (unixfs vs normal dag traversal)
License: MIT
=> make path resolver no longer require whole node for construction

core/commands/block.go, core/commands/dag/dag.go, core/commands/root.go, merkledag/merkledag.go, package.json, test/sharness/t0053-dag.sh
Alright, this is ready for some review now
License: MIT
=> Implement cbor ipld nodes and a first pass at the 'dag' command

core/commands/block.go, test/sharness/t0050-block.sh
=> allow cid format selection in block put command

core/commands/dht.go, core/core.go, package.json, routing/mock/dht.go, routing/supernode/client.go, routing/supernode/proxy/loopback.go, routing/supernode/proxy/standard.go, routing/supernode/server.go, routing/supernode/server_test.go
should make dht resolutions faster.
ref libp2p/go-libp2p-kad-dht#20
License: MIT
=> dht: update to dht code with fixed GetClosestPeers

core/commands/root.go
How does this look? See #2293
License: MIT
Signed-off-by: Richard Littauer richard.littauer@gmail.com
=> Added note about error codes

cmd/ipfs/daemon.go, cmd/ipfs/main.go, core/core.go
The filestore code (#2634) does not care if the daemon is in online or offline mode, it cares if it is running or not.  There is various tests throughout the code for this but no standardized way to get the information.  The p.r. attempts to rectify that.
For the full context see b34fd9c4c10c10139f5e692ab1add9e357a735a1.
License: MIT
Signed-off-by: Kevin Atkinson k@kevina.org
=> Distinguish between Offline and Local Mode.

namesys/routing.go
Previously, if this errored, the possibility for goroutines to get stuck sending a second result down the channel existed. This should prevent that from happening.
License: MIT
=> namesys: return right after errors

blocks/blockstore/arc_cache_test.go, blocks/blockstore/blockstore.go, blocks/blockstore/bloom_cache_test.go, blocks/blockstore/caching.go, blockservice/blockservice_test.go, core/builder.go, unixfs/mod/dagmodifier_test.go
Factored out of #3257 (Add support for multiple blockstores).
License: MIT
=> Separate out the G.C. Locking from the Blockstore interface.

merkledag/merkledag.go
A Raw Node can not possible have links, so there is no need to retrieve the node.
I mentioned this is this comment https://github.com/ipfs/go-ipfs/pull/3307#issuecomment-254061659.
Right now there are no tests for this and this doesn't need to go in right away, I just wanted to do this before I forgot about it.
=> merkledag: optimize DagService GetLinks for Raw Nodes.

diagnostics/diag.go
Noticed a few of these building up in long running stack dumps. Easy enough fix.
License: MIT
=> respect contexts when returning diagnostics responses

cmd/ipfs/main.go
This hasnt been needed since go started auto-detecting the correct number of processors to use.
License: MIT
=> no longer hard code gomaxprocs

misc/completion/ipfs-completion.bash
Add "bitswap" and "repo" to bash completion for `ipfs stats`. They are
listed under `ipfs stats --help`.
Also added their respective subcommands.
License: MIT
Signed-off-by: Nathan Musoke <nathan.musoke@gmail.com>
=> bash_completion: Add a couple missing commands

core/coreapi/coreapi.go, core/coreapi/interface/interface.go, core/coreapi/unixfs.go, core/coreapi/unixfs_test.go, core/corehttp/gateway.go, core/corehttp/gateway_handler.go, core/coreunix/add.go
Basing this PR on the feat/coreapi branch just so the diff is more obvious.
=> gateway: use core api for serving GET/HEAD/POST

blocks/blockstore/blockstore.go
=> blockstore: remove expensive debug statement in AllKeysChan

commands/command.go
To clarify that if you want to access the request body after writing need to use multipart requests.
This came up in https://github.com/ipfs/go-ipfs/issues/3304#issuecomment-259773883 and is relevant to #3367.
=> Add docs for `"commands".Command.Run`

misc/completion/ipfs-completion.bash
Some minor bug still exist but not breaking.
Everything is marked with "TODO" inline the script.
License: MIT
Signed-off-by: Elias Gabrielsson <elias@benefactory.se>
=> Updated Bash complete script

core/commands/stat.go, core/core.go, docs/config.md, repo/config/swarm.go
=> add config option to disable bandwidth metrics

core/corehttp/gateway_handler.go, core/corehttp/gateway_test.go
It logs all errors including expired IPNS keys and other non important
errors.
License: MIT
Signed-off-by: Jakub Sztandera kubuxu@protonmail.ch
=> gateway: degrade error in gateway to log to reduce noise

cmd/ipfs/daemon.go, cmd/ipfs/main.go, package.json, repo/fsrepo/fsrepo.go, repo/mock.go, repo/repo.go
Resolves #3191
License: MIT
Signed-off-by: Jakub Sztandera kubuxu@protonmail.ch
=> cmd: validate repo/api file and print nicer error message

core/coreunix/cat.go, test/sharness/t0110-gateway.sh, unixfs/archive/tar/writer.go, unixfs/io/bufdagreader.go, unixfs/io/dagreader.go, unixfs/io/dagreader_test.go, unixfs/io/pbdagreader.go, unixfs/mod/dagmodifier.go
This doesn't resolve issue yet, I have to refactor a bit so and I want to run CI over this refactor.
Resolves #3399
=> Fix panic in dagreader with raw nodes

core/commands/pin.go
Resolve() tries to fetch the object to check if it has to recursively do something with children (I think). It's overkill here (I think). See #3419
=> Issue #3419: Do not recursively resolve DAG just to obtain a CID

core/commands/pubsub.go
=> Send empty struct to pubsub cmd output to flush

exchange/bitswap/bitswap.go, exchange/bitswap/wantmanager.go, exchange/bitswap/workers.go
This is prep work for the bitswap fixes being discussed in #3398 
License: MIT
=> cleanup bitswap and handle message send failure slightly better

blocks/blockstore/util/remove.go, core/commands/block.go
Make the channel for the output of RmBlocks large enough to hold any result to avoid blocking while holding the GCLock.  Otherwise if you remove a large number of blocks and do something like:
```
ipfs block rm ... | less
```
The GCLock will be held indefinitely blocking all pinning related operations.
=> "block rm": make channel large enough to avoid blocking

exchange/bitswap/bitswap.go
I honestly thought this was removed a while ago, but here it is (see line 299). I'm going to bump this up to once per minute to make sure nothing weird starts happening. Then later we can completely remove it.
License: MIT
=> bitswap: increase wantlist resend delay to one minute

blocks/blockstore/blockstore.go
See ipfs/go-datastore#53 ipfs/go-datastore#54
=> Use NextSync method in Datastore

blocks/blockstore/util/remove.go, unixfs/pb/unixfs.pb.go, unixfs/pb/unixfs.proto
*** THIS IS A BREAKING CHANGE *** as per the google documentation: ["Required is forever"](https://developers.google.com/protocol-buffers/docs/proto#specifying-field-rules)
Nevertheless this seems like a good idea at this time: there are no known
producers ( nor consumers ) of MetaData nodes, and the current requirement
of MimeType has an extremely narrow application scope.
This change could very well be rejected in lieu of implementing a new type
of node ( e.g. TheRealMetadata ) in the DataType enum.
=> Switch unixfs.Metadata.MimeType to optional

exchange/bitswap/message/message.go, exchange/bitswap/message/message_test.go
=> bitswap: add wantlist fullness to protobuf messages

core/commands/add.go
This 
* reverts #2657 
* adds (back) the .Default(true) for the `--pin` option
* cleans up the default logic of the `--progress option`
Note: #2657 broke `--progress=false`.  After #2657 when `--progress=false` a useless progress bar is displayed:
```
$ ipfs add --progress=false afile 
added QmbWib2kLXUBpG8GZjRfmB3rEVE75SYCnN44AeLNz5Qe5V afile
0 B / 96.00 MB [----------------------------------------------------------------------------------------------]   0.00%
```
This pull request fixes that.
The last commit "add cmd: clean up default logic of --progress option" correctly does what I think @RichardLitt was originally trying to do in 03dd669430474ae8396e6fe9eba9e47f01c0ed75 (part of  #2657).  If necessary it can be separated out into its own pull request.
=> Revert Add Defaults to `ipfs add` / Fix default logic of `--progress` option

merkledag/coding.go, merkledag/merkledag.go, merkledag/merkledag_test.go, merkledag/node.go, merkledag/test/utils.go
Should address #3431
License: MIT
=> merkledag: retain cid types when roundtripping through a ProtoNode

cmd/ipfs/daemon.go, core/builder.go, core/core.go, core/mock/mock.go, package.json
=> add option to enable go-multiplex experiment

core/commands/pubsub.go, test/sharness/lib/iptb-lib.sh, test/sharness/t0180-pubsub.sh
=> add sharness test for pubsub

Makefile
It is covered by sharness
License: MIT
=> Do not include core/commands in coverage report

exchange/bitswap/network/interface.go, exchange/bitswap/network/ipfs_impl.go, exchange/bitswap/testnet/virtual.go, exchange/bitswap/wantmanager.go
Bitswap occasionally gets stuck because writes hang (yamux....). this should at least keep bitswap from getting stuck here due to yamux:
ref: https://ipfs.io/ipfs/QmQn8YDTHWJzF7GVKUKanBzoxbzd5jQpwsgM2PfFVTKuGR
License: MIT
=> bitswap: add a deadline to sendmsg calls

fuse/node/mount_darwin.go, package.json
=> fuse: Parse OSX fuse version properly

.gitignore, Makefile, circle.yml, cmd/ipfs/Makefile, codecov.yml
It works, coveralls stopped suddenly. It has also much nicer UI and more config options.
Still WIP, I will comment when it is ready.
=> Switch coverage to codecov from coveralls

core/commands/keystore.go, core/commands/publish.go, core/commands/root.go, core/core.go, keystore/keystore.go, keystore/keystore_test.go, keystore/memkeystore.go, repo/fsrepo/fsrepo.go, repo/mock.go, repo/repo.go
Thank you to @kyledrake for prompting me to just write this already
License: MIT
=> basic keystore implementation

codecov.yml
If travis fail (or is cancelled) or random build failure happens, or
js-ipfs-api test is down for a long time we still want the coverage.
WIP
License: MIT
=> Do not require CI to pass for coverage

cmd/ipfs/daemon.go
=> cmd/ipfs: error out on invalid routing option

core/commands/block.go, test/sharness/t0050-block.sh
=> cmd/block: add selection of multihash parameters to block put command

core/commands/swarm.go
=> swarm/peers: print 'n/a' instead of zero latency

core/commands/pubsub.go, test/sharness/t0180-pubsub.sh
=> cmd/pubsub: fix peers command topic filtering

unixfs/format.go, unixfs/format_test.go
Another PR for https://github.com/ipfs/go-ipfs/issues/3053
=> Test: unixfs @ 87% coverage

merkledag/merkledag.go
This should help solve a few 'cant pin giant things' issues.
License: MIT
=> merkledag: add a concurrency limit to merkledag fetch graph

CHANGELOG.md
=> changelog: add 0.4.4

package.json, repo/fsrepo/defaultds.go, repo/fsrepo/fsrepo.go
This means that now datastore metrics are collected in prometheus.
License: MIT
=> Update go-ds-measure to 1.1.0

namesys/namesys.go, namesys/publisher.go
=> namesys: add entry to DHT cache after publish

core/commands/root.go
added CmdDagGet to the read only command set.
tried to add a test, but dag get needs tests in general
=> dag get should be a read only command

namesys/namesys.go, namesys/namesys_test.go
=> namesys: fix case where there is no cache

merkledag/coding.go, merkledag/node.go, merkledag/node_test.go, test/sharness/t0053-dag.sh
previously `ipfs dag get` of a protobuf hash resulted in very unexpected output
License: MIT
=> merkledag: fix json marshalling of pbnode

core/corerepo/gc.go
Closes #3436 #2129
commit a9b8c8bbd5e243f12d44f67fdb46b80f7f096c5e
Author: Lars Gierth <larsg@systemli.org>
Date:   Fri Dec 9 17:26:53 2016 +0100
gc: remove wonky timeout
This timeout was:
- unneccessary
- based on a metric that doesn't make sense
License: MIT
commit 8f0c7ee3b02ad0a56358d46f32abd7729e05a791
Author: Lars Gierth <larsg@systemli.org>
Date:   Fri Dec 9 17:28:31 2016 +0100
gc: remove unneccessary full repo scan
GetStorageUsage() is super expensive as it involves a full repo scan,
and it's already bad enough that we have do it once.
The call that's being removed here is purely for cosmetical purposes:
printing the number of bytes freed by the GC run. Let's drop it.
License: MIT …
=> Remove GC timeout, fix GC tests

routing/offline/offline_test.go, thirdparty/testutil/gen.go
PR for the ongoing coverage effort (https://github.com/ipfs/go-ipfs/issues/3053).
This PR creates tests for the offline routing package and puts coverage at %78.9.  I'm putting together a PR next week to remove some of the cruft in this package (`FindProviders`) at which point coverage will be at %81.1.
=> Test/routing/offline 

core/commands/dag/dag.go, test/sharness/t0053-dag.sh
=> dag/get: accept paths and not just cids

core/coreunix/add.go
=> coreunix: fix Add() docs regarding pinning

test/sharness/t0022-init-default.sh
It conflicts with already running instance on the Dev's machine so
running this test requires disabling the normal ipfs.
The launch of ipfs here doesn't test much as we compare the config,
after initing from it and we also launch from default config in many
other cases (with few variables changed to not conflict with already
running standalone ipfs instance).
=> sharness: don't run go-ipfs instance with default config

commands/option.go, commands/option_test.go
Resolves https://github.com/ipfs/go-ipfs/issues/3520
License: MIT
=> commands: fix opt.Description panic when desc was empty

core/corehttp/gateway_handler.go
The Suborigins spec was changed and we have to adjust, the spec is still
unstable and it might change in future. Currently the only browser
supporting it (Chrome) errors out on it as it doesn't confront spec it
uses.
See https://github.com/ipfs/specs/issues/131
Part of https://github.com/ipfs/go-ipfs/issues/3209
Proper solution requires: deciding on suborigin prefix, propagating go-multibase changes and exposing cdi.EncodeWithBase.
We can do that but I would want this to be fixed in 0.4.5 and we want to release very soon.
License: MIT
=> gateway: disable Suborigins as it conflicts the spec

test/sharness/t0235-cli-request.sh
Uses `-d` option that is supported both by BSD and GNU nc.
Resolves: https://github.com/ipfs/go-ipfs/issues/3496
License: MIT
=> Fixes nc on macOS not closing socket when the stdin sends EOF

core/commands/ls.go, test/sharness/t0040-add-and-cat.sh, test/sharness/t0045-ls.sh
=> Fix "ipfs ls" so it works correctly with raw leaves.

core/core.go, test/sharness/t0020-init.sh
=> set the agent version based on version string

merkledag/merkledag_test.go
=> test: add test for dag service doing short circuit for raw.Links()

Makefile
I probably silienced it when I was working on some Makefile
License: MIT
=> make: unsilence gx

test/sharness/t0061-daemon-opts.sh
=> test: add test for invalid routing option

core/commands/keystore.go, test/sharness/t0165-keystore.sh
=> "ipfs key list": include the hash of the key id in addition to the name

core/commands/publish.go
=> "ipfs name publish": use path.ParsePath instead of casting input

cmd/ipfs/main.go
=> Fix weird trailing message in default os check.

blockservice/blockservice.go
Fixes
> 1173c00, in AddBlocks, append to array 'if !has' to avoid using extra flow control structures
in #3534
=> blockservice: avoid using unnecessary continue statement

merkledag/merkledag.go, merkledag/merkledag_test.go, test/sharness/t0081-repo-pinning.sh
#3550 made us realize how terribly fragile the EnumerateChildrenAsync code was, so this is a cleaner rewrite of it from scratch.
License: MIT
=> rewrite enumerate children async to be less fragile

test/sharness/t0020-init.sh, thirdparty/dir/dir.go
Should half-close #3632 (along with a flatfs update)
License: MIT
=> close file before removing it in check writeable

core/commands/dag/dag.go, merkledag/merkledag.go, package.json, test/sharness/t0053-dag.sh
=> dag/get: fix link formatting in json output

repo/fsrepo/migrations/migrations.go
@hsanjuan you should be able to build go-ipfs from this branch and copy it into the container, and it should work then.
Fixes #3661.
There are a couple of cases in which ldd won't operate on an executable,
for example when the executable is statically linked.
This patch makes the call to ldd to ldd more resilient against errors,
and looks for the system libc, instead of the libc go-ipfs was linked against.
License: MIT
=> migrations: make libc check more resilient

exchange/reprovide/reprovide_test.go, routing/mock/centralized_test.go, routing/mock/interface.go, routing/offline/offline.go
PR to address issues I raised in https://github.com/ipfs/go-ipfs/issues/3510 (routing mock contains the deprecated `FindProviders` method).
Tests that use this mock now call `FindProvidersAsync` instead.
=> Remove 'FindProviders` from routing mocks

.gx/lastpubver
The old hash had a bunch of test stuff that was hidden in it.
=> gx publish 0.4.5, cleaner

pin/set.go, pin/set_test.go
Making this deterministic keeps us from creating an exponential amount
of objects as the number of pins in the set increases.
closes #3621 for the most part
License: MIT
=> Make pinset sharding deterministic

merkledag/merkledag.go
Saves a whole lot of RAM on todobuffer
=> Pass cids instead of nodes around in EnumerateChildrenAsync

test/sharness/t0085-pins.sh
Test for already fixed #3688 
License: MIT
=> Add tests for recursively pinning a dag (i.e. large file).

repo/config/bootstrap_peers.go, test/sharness/t0120-bootstrap.sh
As the bootstrappers now have proper IPv6, we can start making use of it. Since configuring it over the weekend, IPv6 usage has already roughly quadrupled.
=> bootstrap: add a few /ip6 nodes

merkledag/merkledag.go
=> Fix formatting in merkledag.go

test/sharness/t0130-multinode.sh
=> print out all daemon stderr files when iptb stop fails

core/commands/block.go
=> block rm: use Marshalers instead of PostRun to process output

repo/fsrepo/migrations/migrations.go, test/sharness/lib/test-lib.sh, test/sharness/t0066-migration.sh, test/sharness/t0301-docker-migrate.sh
Note: the tests here are totally incomplete, I keep getting stuck :/
If someone else wants to take a look today, that'd be super helpful. The migrations code itself should be good.
------
The ldd command used for detection doesn't seem to have a
--version flag on Alpine Linux. It would print the expected
output, but instead of stdout, it would print it on stderr.
The musl detection code would only scan stdout for mentions
of "musl", and would thus *not* download the musl version
of the fs-repo-migrations executable.
This manifested in the well-known "fs-repo-migrations: not found"
error, which you get when executing something that was linked
against a different libc than the one present on the system.
License: MIT
=> WIP: fsrepo: fix musl detection for migrations

bin/Rules.mk
Previous version 0.10 was built with faulty version of Go 1.7 which has
problems with TCP -> DNS -> UDP timeouts.
This results in many failed calls to `gx install`
This wasn't easy to find.
License: MIT
=> Update gx to version 0.11

Dockerfile, Dockerfile.fast, bin/container_daemon
After the discussion in https://github.com/ipfs/go-ipfs/pull/3573 this patch prints a deprecation warning if:
1) the image has been executed with additional arguments
2) the first argument isn't daemon
This way people are able to migrate to the new syntax without any breaking changes.
License: MIT
=> Dockerfile: Deprecate implicit daemon argument

core/commands/pin.go, merkledag/merkledag.go, merkledag/merkledag_test.go, test/sharness/t0085-pins.sh
=> Report progress during `pin add`

README.md, Rules.mk
=> Add install_unsupported

Rules.mk
This is the cleanest the repo will get.
If you need to publish it, tar it or anything else like that use
`make distclean`.
License: MIT
=> make: use git clean in distclean target

cmd/ipfs/daemon.go
To prevent panic when daemon closes early.
Resolves #3710
License: MIT
=> daemon: move gateway start to latter

bin/dist_get
Also refactored the code a bit, and added httpie.
Note: I used redirection for httpie, as `http -d url -o output` complained its output was redirected.
=> Make bin/dist_get fall back to other downloaders if one fails

package.json
It isn't use in go-ipfs
License: MIT
=> deps: remove autobatch 

repo/fsrepo/migrations/mfsr.go, repo/fsrepo/migrations/mfsr_test.go
Adds tests for `msfr.go`. Does not hit coverage target of 80%.
Remove code that was transforming errs when the version file didn't exist, which may have confused callers of the `Version` method.
=> Tests for mfsr.go

misc/release-checklist.md
also prep it for templeating
License: MIT
=> misc: improve release checklist

core/commands/keystore.go, test/sharness/t0165-keystore.sh
Resolves https://github.com/ipfs/go-ipfs/issues/3566
License: MIT
=> keystore: add self key to the listing

cmd/ipfs/daemon.go, exchange/bitswap/bitswap.go, exchange/bitswap/wantmanager.go, package.json, repo/fsrepo/defaultds.go, repo/fsrepo/fsrepo.go
=> Add multiple performance metrics

cmd/ipfs/daemon.go, core/core.go, test/sharness/t0130-multinode.sh
- spdystream is not fully spdy spec compatible, creating issues when
doing interop with js, so it is removed
- muliplex is working well now in interop with js, so being enabled by
default
This means the new default muxers are `yamux,mplex`
=> feat: remove broken spdy multiplexer and enable multiplex by default as second option

fuse/ipns/ipns_unix.go
Bases of https://github.com/ipfs/go-ipfs/pull/3727
Resolves https://github.com/ipfs/go-ipfs/issues/3013
=> fix: ipfs mount crashing if there was no name published before

core/commands/dht.go, core/commands/pin.go, core/coreunix/add_test.go, merkledag/merkledag.go, merkledag/merkledag_test.go, pin/gc/gc.go
=> Refactor EnumerateChildren to avoid need for bestEffort paramater.

merkledag/merkledag.go
In certain situations the 8MB size limit here would result in a large number of objects in the batch, which combined with peer connections, can easily hit the file descriptor limit.
License: MIT
=> Limit number of objects in mdag batch to prevent too many fds issue

core/commands/get.go, thirdparty/tar/extractor.go
This has been bothering me for a while
=> Fix ipfs get progress bar

core/commands/get.go, test/sharness/t0090-get.sh, unixfs/archive/archive.go, unixfs/archive/tar/writer.go
=> make raw leaves work with 'ipfs get'

core/commands/pin.go, test/sharness/t0600-issues-and-regressions-online.sh
cc @ianopolous, this should fix it
License: MIT
=> fix pin add api break

core/commands/get.go, test/sharness/t0090-get.sh
=> fix: ipfs get panic with empty API call

core/commands/add.go, test/sharness/t0040-add-and-cat.sh
It will print out only the final hash
Resolves #3371
=> Add ipfs add --quieter

test/sharness/t0010-basic-commands.sh
It is marked as failed right now, as it fails
Part of https://github.com/ipfs/go-ipfs/issues/2783
=> Add 80 columns mans tests

commands/cli/parse.go
Previously when adding the root of a drive on Windows (either directly through `X:\` or via `.` while in `X:`), ipfs would prefix everything and not handle directories properly in a manner simillar to this issue:https://github.com/ipfs/go-ipfs/issues/1922
This does not happen with paths or files underneath the root, it's just when adding the root itself. 👻 
This can be fixed by preserving the full path `X:\` instead of using `X:` as a base when specifying the root of a drive only. As an aside it would not be valid to use `/` instead, since `/` is relative to the drive in your working directory on Windows, not an absolute path. Using `/` while adding `Y:\` from `X:\` would either give you N contents from `X`: or panic if `X:` contains less items in the root than `Y:` does. Preserving the …
=> add: [Windows] Drive root parse fix

mk/golang.mk
In workspace setups that have the source tree symlinked into GOPATH,
the `go list `command wouldn't recognize that we're technically within GOPATH,
because `pwd` doesn't look like it.
For example
/home/user/go/src/github.com/ipfs/go-ipfs
=> /home/user/go/ipfs/go-ipfs
produces the import path
_/home/user/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-random/random
which is not within GOPATH.
We get around this by using fully-qualified import paths instead:
starting in github.com/ipfs/go-ipfs/ instead of ./
License: MIT
=> make: fix build when symlinked into GOPATH

blocks/blockstore/bloom_cache.go
To prevent put we need to have conclusive information if item is
contained in the repo, bloom filter won't give this information.
It only says if it is for sure not contained.
License: MIT
=> fix: remove bloom filter check on Put call in blockstore

mk/golang.mk, mk/util.mk
=> make: readd the path check functionality

CHANGELOG.md
The command to enable the filestore did not work as-is. It is missing `--json` . Should be:
ipfs config --json Experimental.FilestoreEnabled true
=> CHANGELOG: Fix config command for FilestoreEnabled .

Dockerfile, Dockerfile.fast, README.md, bin/container_daemon
This patch is delaying the point where permissions are dropped into the `start_ipfs` script. This way, instead of exiting on permission issues, we can fix them on our own inside the script, then drop privileges and continue doing ipfs specific stuff with the correct user.
I've removed the `chmod 0777` step from the readme since it's not needed anymore.
License: MIT
=> docker: Automatically fix permissions

core/commands/ipns.go, core/commands/keystore.go, core/commands/name.go, core/commands/publish.go, core/commands/root.go
Adds the following ShortDescription to `ipfs key`:
'ipfs key gen' generates a new keypair for usage with IPNS and 'ipfs name publish'.
> ipfs key gen --type=rsa --size=2048 mykey
> ipfs name publish --key=mykey QmSomeHash
'ipfs key list' lists the available keys.
> ipfs key list
self
mykey
=> commands: improve name and key helptexts

commands/files/file_test.go
The fix contains the changing nil with io.EOF
because acording to the Read interface implementation
An instance, (in our case Part.Read) of this general case
is that a Reader returning a non-zero number of bytes at
the end of the input stream may return either err == EOF or err == nil.
So this means that the Part.Reader chose to return
io.EOF instead of nil.
=> test(commands): fix EOF failure with Multipart.Read

core/coreapi/coreapi.go, core/coreapi/interface/interface.go, core/coreapi/unixfs.go, core/coreapi/unixfs_test.go, core/corehttp/gateway.go, core/corehttp/gateway_handler.go
cc @hsanjuan @keks @kevina @Kubuxu 
Closes #3490  
commit e1c190a992ea2047a83ad3c9cd8dc303b5564ef7
Author: Lars Gierth <larsg@systemli.org>
Date:   Wed Nov 16 06:21:15 2016 +0100
coreapi: smarter way of dealing with the different APIs
License: MIT
commit 2e15ba92b4aa4945e122ee94c6ea30ce81379d74
Author: Lars Gierth <larsg@systemli.org>
Date:   Fri Dec 9 16:35:28 2016 +0100
coreapi: be more flexible about inputs
While coreapi functions previously only accepted path strings,
they now accept anything from Path structs and strings,
Multihash structs and strings, and most notably: Cid structs,
strings and byte arrays. See go-cid.Parse() for more information.
If the argument is a string containing at least one forward-slash,
it's treated as a path …
=> Core API refinements and efficiency improvements

pin/pin.go, pin/pin_test.go
This avoids revisiting already-searched branches and cut down
the IsPinned() check times considerably when recursive pins
share big underlying DAGs. Same mechanism as `merkledag.EnumerateChildren()`.
Here are some benchmarks with a randomly-selected list of 10 of my pins (and bad pins):
This runs `ipfs pin ls $pin` for each of the listed pins and measures how long it takes it.
With 0.4.7:
```
Time for good pin QmSUuF4bnRBRAmaRzJcXHAu7z7tdD8sx1c5hU5kuvdPuDV: 0:00.55elapsed   0
Time for bad pin QmSUuF4bnRBRAmaRzJcXHAu7z7tdD8sx1c5hU5kuvdPuD1: 0:07.84elapsed   1
Time for good pin QmPcd2ypbzvh5ew6DBw9yCR8HBPWDJrLXVEw5DFntKWemk: 0:01.82elapsed   0
Time for bad pin QmPcd2ypbzvh5ew6DBw9yCR8HBPWDJrLXVEw5DFntKWem1: 0:07.19elapsed   1
Time for good pin QmYihqmU45xvKGBW1cGHCSF1Qxe5DTXzYqwFNEuBCvsR4Y: …
```
=> Fix #3783: Improve IsPinned() lookups for indirect pins

cmd/ipfs/daemon.go, test/sharness/t0063-daemon-init.sh
Use fsrepo.IsInitialized to test for initialization instead of just testing if the directory exists.
Also add test cases for '--init' option, including one the creates an empty directory.
Closes #3773.
=> daemon: use fsrepo.IsInitialized to test for initialization

commands/response.go, core/commands/dns.go, core/corehttp/gateway_handler.go, core/corehttp/gateway_test.go
Fixes #2286 -- bonus: also kills gateway's namesys dependency
**But:** I just noticed that the CLI assumes "command not found" for 404 responses. Great.
=> Return 404 Not Found for failed path resolutions

bin/dist_get
=> misc: fix dist_get failing without failing

assets/assets.go, commands/request.go, core/builder.go, core/commands/files/files.go, core/commands/ls.go, core/coreunix/add.go, fuse/ipns/ipns_unix.go, mfs/dir.go, mfs/mfs_test.go, mfs/system.go, package.json, repo/config/experiments.go, test/sharness/t0040-add-and-cat.sh, test/sharness/t0250-files-api.sh, test/sharness/t0260-sharding-flag.sh, unixfs/format.go, unixfs/hamt/hamt.go, unixfs/hamt/hamt_stress_test.go, unixfs/hamt/hamt_test.go, unixfs/hamt/util.go, unixfs/hamt/util_test.go, unixfs/io/dagreader_test.go, unixfs/io/dirbuilder.go, unixfs/io/dirbuilder_test.go, unixfs/io/resolve.go, unixfs/pb/unixfs.pb.go, unixfs/pb/unixfs.proto
This PR implements a hash array mapped trie using merkledag nodes as a base layer for sharded unixfs directories. 
This changeset is broken up into three distinct parts:
1. Implement the HAMT structure itself. This is a bunch of algorithmic code that i'd like some well thought out sanity checking on.
- Need confirmation on hash code numbering
- Thoughts on willf/bitset vs stdlib `math/big.Int`
- Implementation correctness
- Consensus on addition of fields to unixfs protobuf
2. Integration of HAMT code into the directory builder logic.
- provides us a nice abstraction to think about things in terms of a filesystem
- optimizes smaller directories by not sharding until we hit a threshold
3. Integration of directory builder code into mfs
- moves mfs from using a simple merkledag `Node` object …
=> Implement unixfs sharding

.codeclimate.yml, blocks/blockstore/blockstore.go, blocks/blockstore/bloom_cache_test.go, blockservice/blockservice_test.go, cmd/ipfswatch/main.go, commands/http/handler.go, core/coreapi/unixfs_test.go, filestore/filestore.go, fuse/ipns/ipns_unix.go, path/path_test.go, pin/pin_test.go, pin/set_test.go, unixfs/mod/dagmodifier.go
=> fix: multiple govet warnings

blocks/blocks.go, blocks/blockstore/arc_cache.go, blocks/blockstore/arc_cache_test.go, blocks/blockstore/blockstore.go, blocks/blockstore/blockstore_test.go, blocks/blockstore/bloom_cache.go, blocks/blockstore/bloom_cache_test.go, blocks/blockstore/caching.go, blocks/blockstore/util/remove.go, blocks/blocksutil/block_generator.go, blocks/bloom/filter.go, blocks/set/set.go, core/builder.go, exchange/bitswap/testutils.go, filestore/filestore.go
This has required changing the order of some parameters and
adding HashOnRead to the Blockstore interface (which I have in turn
added to all the wrapper implementations).
I plan to do more, but let's merge little by little, submodule by submodule.
=> Make Golint happy in the blocks submodule.

core/commands/helptext_test.go
This is WIP. Not to be merged for a while.
@RichardLitt here you go :)
License: MIT
Signed-off-by: Jeromy why@ipfs.io
=> add test to enforce helptext on commands

cmd/ipfs/ulimit.go, test/sharness/lib/test-lib.sh, test/sharness/t0060-daemon.sh
This should serve as a decent stopgap for the too many file descriptors problem until we come up with a better solution (connection closing, QUIC, relay, sbs)
License: MIT
=> Bump default ulimit to 2048

.gx/lastpubver, CHANGELOG.md, package.json, repo/config/version.go
=> Ipfs 0.4.8

fuse/readonly/ipfs_test.go
They wouldn't compile
This should probably be merged into 0.4.8
License: MIT
=> test: fix fuse tests, they were broken some time ago

exchange/bitswap/wantmanager.go
This will be a breaking change for anyone who is currently monitoring the `ipfs_bitswap_wanlist_total` prometheus stat
=> Fix wanlist typo in prometheus metric name

ISSUE_TEMPLATE.md
Priority is very much subjective. Severity allows us to state examples
and decide on it objectivelly.
License: MIT
=> Change issue template to use Severity instead of Priority

Rules.mk, cmd/ipfs/Rules.mk
Resolves https://github.com/ipfs/go-ipfs/issues/3837
License: MIT
=> make: fix `make install` not using ldflags for git hash

cmd/ipfs/daemon.go
License: MIT
Signed-off-by: Timothy Hobbs <timothyhobbs@seznam.cz>
=> Refactor: use ctx var consistently in daemon.go

commands/response.go, commands/response_test.go
When `ErrNotFound` was added, it was not appended to the iota but inserted in the middle. This means that the numeric value of `ErrImplementation` changed, resulting in possible API breakage. This PR fixes the order.
=> commands: restore original error order

contribute.md
License: MIT
Signed-off-by: Timothy Hobbs <timothy@hobbs.cz>
=> Fix link to commit hook script in contribute.md

core/corehttp/gateway_handler.go, core/corehttp/gateway_test.go
We set the [Cache-Control: immutable header](https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/) on responses from the gateway's /ipfs route. That's fine, but we also set it on directory listings such as https://ipfs.io/ipfs/QmSwzyZ4zfHD9j4JZdXuzbWH4gXuDfZ7CdfMzpfqrMVcrz/go-libp2p-blankhost/ which effectively prevents us from changing e.g. the CSS on the listings, or really anything about the listing.
We should only ever set Cache-Control: immutable for responses that produce exactly the hash in the URL. This is only the case for unixfs files, not for the auto-generated directory listings.
=> gateway: fix erroneous Cache-Control: immutable on dir listings

core/corehttp/gateway_handler.go, core/corehttp/gateway_test.go
* Always use the fully resolved CID from api.ResolveNode
as the ETag (also for IPNS).
* Format the result as a valid "Strong Validator"
(double quotes around the encoded CID).
Fixes #3868
License: MIT
Signed-off-by: Remco Bloemen <remco@2π.com>
=> gateway: use CID as an ETag strong validator

core/corehttp/ipns_hostname.go, namesys/dns.go, package.json
It should resolve issues with newer gTLDs being not selected
License: MIT
=> deps: Update go-is-domain to contain new gTLD

exchange/bitswap/bitswap_test.go, exchange/bitswap/decision/engine.go, exchange/bitswap/workers.go
This is a fix for the bug detailed in https://github.com/ipfs/go-ipfs/issues/3875. I add the call to `MessageSent()` where it seemed to make the most sense, then manual testing (akin to the **Steps to reproduce** in the linked issue) was done and automated tests were added `bitswap_test.go` to verify that the update worked. Upon running the automated tests, I received a read/write conflict for the ledger that I fixed by adding `Lock()`/`Unlock()` calls for the ledger at the beginning of `MessageSent()`.
=> bug fix: Bitswap now records 'BytesSent' in ledger

bin/dist_get
This prevents a 404 page getting piped into tar.
It's also adding the openbsd http(s) client `ftp`.
License: MIT
=> dist_get: handle 404 correctly

core/commands/add.go, core/coreunix/add.go, importer/balanced/builder.go, importer/helpers/dagbuilder.go, importer/helpers/helpers.go, importer/trickle/trickledag.go, merkledag/coding.go, merkledag/node.go, mfs/dir.go, mfs/ops.go, mfs/system.go, test/sharness/t0040-add-and-cat.sh, test/sharness/t0043-add-w.sh, test/sharness/t0044-add-symlink.sh, test/sharness/t0260-sharding-flag.sh, unixfs/hamt/hamt.go, unixfs/io/dirbuilder.go
=> Add support for using CidV1 in 'ipfs add'

test/sharness/t0260-sharding-flag.sh, unixfs/io/dagreader.go
The gateway relies on the error output of the dagreader to tell if somethings a directory.
closes #3886 
License: MIT
=> Fix gateway handling of sharded directories

core/coreunix/add.go
If youre having trouble adding large amounts of directories to ipfs and run out of memory, try this
License: MIT
=> Flush cached directories every so often during an add

core/corehttp/gateway_handler.go
=> improved gateway directory listing for sharded nodes

core/commands/add.go
Fix for issue: https://github.com/ipfs/go-ipfs/issues/3894 
Typo in message.
License: MIT
Signed-off-by: Miguel Torres <migueltorreslopez@gmail.com>
=> Fix typo in message when file is not determined

core/commands/add.go, importer/helpers/dagbuilder.go, merkledag/merkledag.go, merkledag/raw.go, test/sharness/t0040-add-and-cat.sh
=> adder: add support for specifying the hash function

core/commands/repo.go, core/corerepo/stat.go, test/sharness/t0080-repo.sh
=> Add MaxStorage field to output of "repo stat".

core/commands/pubsub.go
Turns out, the Message will Marshal properly. I tested XML and Protobufs, but doesn't seem the "marshaller" is there. I'm still not familiar enough with the codebase to go poking around, so I'm just adding a bit of documentation that was missed, and is in my opinion pretty useful.
=> Adding documentation that PubSub Sub can be encoded.

core/corehttp/gateway_handler.go
This existed before but was disabled in 912a972 because the Suborigin spec
changed and it became incompatible.
This commit updates the generated Suborigin header to be conformant with the
latest spec.
Thank you Stskeeps, Kubuxu, and TUSF on IRC for holding my hand with this.
=> Add Suborigin header to gateway responses

core/commands/keystore.go, keystore/keystore.go, keystore/keystore_test.go, keystore/memkeystore.go, keystore/memkeystore_test.go, test/sharness/t0165-keystore.sh
@whyrusleeping So you don't waste time before implementing the good encryption stuff ;)
License: MIT
=> Implement ipfs key {rm, rename}

core/commands/root.go, core/commands/shutdown.go, test/sharness/t0023-shutdown.sh
=> Implement ipfs shutdown command

core/commands/object/diff.go, core/commands/pin.go, merkledag/merkledag.go, merkledag/utils/diff.go, merkledag/utils/diffenum.go, merkledag/utils/diffenum_test.go, pin/pin.go, pin/pin_test.go
Makes re-pinning a slightly changed dataset much faster
License: MIT
=> implement ipfs pin update

exchange/bitswap/bitswap.go, exchange/bitswap/decision/engine.go, exchange/bitswap/decision/engine_test.go, exchange/bitswap/decision/ledger.go
=> bitswap: clean up ledgers when disconnecting

core/commands/filestore.go, filestore/util.go, test/sharness/t0271-filestore-utils.sh
=> filestore: add "--file-order" option to "filestore ls" and "verify"

core/corehttp/corehttp.go
Theres still a very small chance it could happen, but this makes it much much less likely.
License: MIT
=> make odds of 'process added after close' panic less likely

core/commands/publish.go, test/sharness/t0100-name.sh
as discussed in #3807
License: MIT
Signed-off-by: Kerem Gocen <keremgocen@gmail.com>
=> WIP: add PeerID lookup

filestore/fsrefstore.go
I got very confused by what 'ipfs root' is. Hopefully this will help the next person.
License: MIT
=> Filestore: more verbose error when adding a file from outside of the root

core/corehttp/gateway_handler.go, core/corehttp/gateway_test.go
This enables `go get` to parse go-import meta tags from index.html files stored in IPFS. One tiny step toward whyrusleeping/gx-go#2.
For an import like `ipfs.io/ipfs/QmFoo/mypkg`, the gateway would previously redirect to `/ipfs/QmFoo/mypkg/` (note the trailing slash), which the `go get` tool can't deal with. Thankfully, `go get` sets a URL query parameter (`?go-get=1`) which we can use to switch off the redirect in this case.
=> gateway: don't redirect to trailing slash if it's go get

Dockerfile
Opening this again because it's been a reality in ipfs/infrastructure for a while.
Yes, the `/ws` listener is soon gonna be part of the gateway and a dedicated port no longer neccessary, but until then the lack of this exposed port is a pain.
=> docker: expose port 8081 for /ws listener

core/core.go, namesys/republisher/repub.go, namesys/republisher/repub_test.go, test/sharness/t0240-republisher.sh
=> Make sure non-self keys also get republished

core/commands/dht.go
Closes: #3839
I was looking for ways to add tests to findProviders command when new option --num-providers is given. But could not find a good example on existing commands to test options.
One possibility is to use a mocking library to mock the Node, but I didn't want to introduce new library dependencies for such a trivial change.
Please advice if new tests are needed.
License: MIT
Signed-off-by: Miguel Torres <migueltorreslopez@gmail.com>
=> Add 'ipfs dht findprovs --num-providers' to allow choosing number of providers to find

test/sharness/t0023-shutdown.sh
=> fix shutdown check in t0023

core/commands/pin.go, core/corerepo/pinning.go, core/pathresolver.go, test/sharness/t0250-files-api.sh
* Change ResolveToCid to take a Resolver and a NameSystem instead of an ipfs
Node.
* Make the pin/unpin methods use a Unixfs path resolver.
Closes: #3974
License: MIT
=> pinning + pathresolver: fix pinning/unpinning of sharded directories

core/corehttp/gateway_handler.go, core/corehttp/gateway_test.go
=> Show escaped url in gateway 404 message

package.json
These were directly used by go-ipfs but not listed in package.json.
=> gx import dependencies of dependencies used by go-ipfs

cmd/ipfs/init.go, repo/config/profile.go, test/sharness/t0020-init.sh
Closes #3987
This implements `ipfs init --profile ...` which allows to apply profiles to default config. The server profile does what was requested in #3987.
Profiles can be stacked, this may be very useful when the configurable datastore PR is merged and there are more datastores.
=> Implement --profile option in ipfs init

core/commands/block.go
Adding codecs found in https://github.com/ipfs/go-cid/blob/b42583c8bfdafac9965f450294b371d1b734c6f6/cid.go#L67-L79
=> Add CID Codecs to block put

cmd/ipfs/init.go, repo/config/profile.go, test/sharness/t0020-init.sh
This will be useful for sharness tests of external tools. Goal of this profile is to reduce external interference as much as possible.
=> Add test init profile

README.md, bin/Rules.mk, mk/golang.mk, package.json
=> docs: Require go 1.8

blocks/blocksutil/block_generator.go, blockservice/blockservice.go, core/commands/bitswap.go, core/corehttp/gateway_handler.go, exchange/bitswap/bitswap.go, exchange/bitswap/bitswap_test.go, exchange/bitswap/decision/engine.go, exchange/bitswap/get.go, exchange/bitswap/session.go, exchange/bitswap/session_test.go, exchange/bitswap/stat.go, exchange/bitswap/testutils.go, exchange/bitswap/wantlist/wantlist.go, exchange/bitswap/wantlist/wantlist_test.go, exchange/bitswap/wantmanager.go, exchange/bitswap/workers.go, exchange/interface.go, merkledag/merkledag.go
This is an implementation of the bitswap sessions enhancement i proposed in https://github.com/ipfs/go-ipfs/issues/3786
Its still a work in progress, and has a few potential issues around tracking of wantlist refcounts in failure modes (if peers don't have any of the things we want and we re-broadcast, it increases the wantlist refcounts unnecessarily), but it generally works quite well and makes bitswap faster and have much less bandwidth overhead. In cases of transferring large files just between one or two peers, i've seen over a 2x speed improvement.
=> Bitswap sessions

merkledag/coding.go, merkledag/merkledag.go, merkledag/raw.go
Later, we should:
1. Pull the other node formats out of IPFS (at least the raw one).
2. Pull out the decoder registration/management into a `go-ipld` library.
=> Change IPFS to use the new pluggable Block to IPLD decoding framework.

exchange/bitswap/testnet/peernet.go, exchange/bitswap/testnet/virtual.go, exchange/bitswap/testutils.go, exchange/bitswap/wantmanager.go
resolves #3651 for the most part. Theres still a deeper fix that needs to be done to eliminate this class of errors. 
License: MIT
=> Only open a message sender when we have messages to send

core/commands/dag/dag.go
=> fix determination of 'root' node in dag put

core/coreapi/unixfs_test.go, core/coredag/dagtransl.go, merkledag/merkledag.go, package.json
I previously optimized the IPLD cbor decoder to *not* encode and then re-decode
objects when constructing them with `WrapObject`. Unfortunately, we rely on this
to canonicalize the object before computing the tree/links.
=> gx: update ipldcbor

test/bench/bench_cli_ipfs_add/main.go, test/bench/offline_add/main.go
It doesn't mean anything anymore.
=> remove `-f` flags from calls to init

commands/http/parse.go, core/coreunix/add.go, test/sharness/t0600-issues-and-regressions-online.sh
Includes a general sanity check to skip further checks if user provided fewer arguments than minimum required and a specific check for corrupted data passed as file.
License: MIT
Signed-off-by: Mateja Milosevic <minima38123@gmail.com>
=> Fixes #4003

core/coreunix/add.go, test/sharness/t0410-api-add.sh
The `ipfs add` command was modified to include the added
node's size as a string. The size is included in the
dagnode info sent over the output channel.
License: MIT
Signed-off-by: Tom O'Donnell todonnel91@gmail.com
=> ipfs add: added size to response of `ipfs add` command

test/sharness/lib/test-lib.sh
This:
* Disables mdns and fixes #4098 (iptb nodes already have mdns disabled by default).
* Only listens on localhost (although iptb nodes still listen on all).
=> sharness: use test profile

cmd/ipfs/daemon.go, core/core.go, package.json, repo/config/addresses.go, repo/config/init.go, test/sharness/t0060-daemon.sh, test/sharness/t0140-swarm.sh
Fixes #3613
- Tests failing because it depends on libp2p/go-libp2p#196 which I haven't bubbled up yet
- I need to update a bunch of docs regarding the Addresses config section
- A tiny code comment here and there might be good as well
Overall this is good for CR though.
=> core: make announced swarm addresses configurable

test/sharness/lib/test-lib.sh, test/sharness/t0040-add-and-cat.sh
We were removing the file before testing, ignoring the error from stat, and then grepping for `Error: Unrecognized file type for named-pipe: ` (because nothing was sent to stdout).
This fix:
1. Changes our stat command to output failed to stdout on failure to ensure that bugs like this *can't* happen.
2. Checks to make sure stat actually succeeds.
=> sharness: fix the 'useful error message when adding a named pipe' test

core/corehttp/gateway_handler.go
The `Content-Range` header is necessary for extracting (only) the metadata of audio files.
License: MIT
Signed-off-by: Steven Vandevelde <icid.asset@gmail.com>
=> Expose Content-Range header

core/commands/object/object.go, test/sharness/t0051-object.sh
Closes #4092
Based off #4004. The question now is what to do about `object patch *` commands.
=> object put --pin option

core/builder.go, core/commands/bitswap.go, core/core.go, docs/config.md, exchange/reprovide/providers.go, exchange/reprovide/reprovide.go, exchange/reprovide/reprovide_test.go, repo/config/init.go, repo/config/reprovider.go, test/sharness/t0175-reprovider.sh
Reprovider strategies allow to specify which keys to provide to the content routing.
Supported strategies are:  `all` - all blocks,  `pinned` - all pinned blocks, `roots` - root/directly pined blocks.
Current reprovider is slow(~0.2keys/s with my setup), so constraining key set should speed the process up, announcing only pin roots should still work quite well in most cases.
TODO:
=> Reprovider strategies

core/commands/dag/dag.go, core/commands/root.go, core/coreapi/unixfs_test.go, core/coredag/cbor.go, core/coredag/dagpb.go, core/coredag/dagtransl.go, merkledag/merkledag.go, package.json, plugin/plugins/git/git.go, test/sharness/t0053-dag.sh
Closes #3771
* Added --hash to put
* --input-enc cbor input 'encoder'
* dag-pb support in put
TODO:
* Output cbor encoding
* Have the js-ipfs-api PR working
Depends on https://github.com/ipfs/go-ipld-cbor/pull/24
cc @diasdavid
=> Improve dag API

core/core.go, exchange/reprovide/reprovide.go, test/sharness/t0175-reprovider.sh
`ipfs bitswap reprovide` would hang if `Reprovider.Interval` was set to 0
=> reprovide: fix ipfs bitswap reprovide when interval set to 0

exchange/bitswap/bitswap.go
fixes #4062 (yay!)
License: MIT
=> add blocks to the blockstore before returning them from blockservice sessions.

repo/config/bootstrap_peers.go, test/sharness/t0120-bootstrap.sh
- Removes half of the static bootstrappers, and adds 4 /dnsaddr bootstrappers instead
- Updates go-libp2p for /dnsaddr support
- Updates go-libp2p-host because that was missed some time ago
=> bootstrap: add /dnsaddr nodes

cmd/ipfs/Rules.mk, commands/files/serialfile.go, mk/golang.mk, plugin/plugins/Rules.mk
* Fixes #4097
* Was caused by https://github.com/golang/go/commit/e3d7ec006f25385972c89f771d5d577adce3f024
* Will need to be propagated back to https://github.com/ipfs/go-ipfs/pull/3856 (Extract and rework commands package)
* There is 1 more issue I noticed when running sharness tests on that: when running `ipfs daemon --init` there is an error spam:
```
21:54:33.692 ERROR metrics-pr: Registering prometheus collector, name: ipfs_fsrepo_datastore_blocks_put_total, error: duplicate metrics collector registration attempted binding.go:74
```
* Might be related to https://github.com/ipfs/go-ipfs/issues/4132
* Probably isn't
=> Fix Go 1.9 issues

namesys/publisher.go, namesys/publisher_test.go
License: MIT
Signed-off-by: Justin Drake <drakefjustin@gmail.com>
=> Do not publish public keys extractable from ID

core/commands/ls.go, namesys/publisher_test.go, test/sharness/t0045-ls.sh
=> Fix "ipfs ls" to once again work on arbitrary dag objects.

core/commands/mount_unix.go, fuse/mount/mount.go, fuse/node/mount_unix.go, fuse/readonly/readonly_unix.go, merkledag/merkledag.go
Including:
- allow mount to work when running the daemon in offline mode
- allow /ipfs interface to handle raw nodes and sharded directories
- fix an issue in the dagservice where we were returning a blockservice not-found error
=> various fixes for /ipfs fuse code

fuse/readonly/readonly_unix.go
The fuse PR imported the old version.
License: MIT
=> fix go-ipld-format version

package.json, repo/config/profile.go, repo/fsrepo/datastores.go
=> [WIP] Badger datastore

docs/config.md, docs/datastores.md
=> Add documentation for datastore configs

.dockerignore, Dockerfile, Dockerfile.fast, bin/container_daemon, test/sharness/t0301-docker-migrate.sh
The fs-repo-migrations releases on dist.ipfs.io never worked with the go-ipfs docker image because it's based on musl. That means binaries linked against glibc don't work, and I manually built and patched in an additional musl-based tarball for each fs-repo-migrations release. This madness has to stop.
The Dockerfile now has two stages: build and assembly.
This allows for a full-fledged debian build container,
while still resulting in a super-thin glibc-based busybox image.
License: MIT
=> docker: switch from musl to glibc, and simplify stuff

package.json, repo/fsrepo/datastores.go
Update badger to current master, fix `ipfs gc` bug.
NOTE: This breaks previous badger ds-es as badger bumped their manifest version. I'm not sure if there is a migration for that, if someone wants to rescue their data, convert using ds-convert to flatfs (you prorably will need to remove `QmdfTbBqBPQ7VNxZEYEj14VmRuZBkqFbiwReogJgS1zR1n` using `block rm`)
=> Update badgerds to 0.3.0

core/commands/dag/dag.go, test/sharness/t0053-dag.sh
See https://github.com/ipfs/go-ipfs/issues/4234
=> dag: Support multiple files in put

core/commands/repo.go, core/corerepo/stat.go, test/sharness/t0080-repo.sh
=> "repo stat": Don't crash when Datastore.StorageMax is not defined

core/core.go, core/coreapi/unixfs_test.go, core/coredag/cbor.go, merkledag/merkledag.go, package.json
Depends on:
* https://github.com/ipfs/go-ipld-cbor/pull/28
* https://github.com/libp2p/go-libp2p-pnet/pull/13
=> gx: update cbor to 0.2.3

package.json, repo/fsrepo/datastores.go
This updates badger to 0.8 tag, including Windows mmap fix, should help with https://github.com/ipfs/go-ipfs/issues/3971#issuecomment-334913609
=> datastore: update badgerds to 0.4.1

CHANGELOG.md, docs/experimental-features.md, docs/plugins.md
=> docs: Add some docs on plugins

core/coredag/dagtransl.go, core/coredag/raw.go, test/sharness/t0053-dag.sh
`dag get` still doesn't properly support raw output but that's a bigger issue.
License: MIT
=> add raw support to the dag put command.

merkledag/batch.go, merkledag/merkledag.go
1. Modern storage devices (i.e., SSDs) tend to be highly parallel.
2. Allows us to read and write at the same time (avoids pausing while flushing).
This makes `ipfs add --local` ~3.5x faster with the flatfs datastore (untested
with badger).
fixes https://github.com/ipfs/go-ipfs/issues/898#issuecomment-331849064
License: MIT
=> parallelize batch flushing

docs/experimental-features.md
=> docs(pnet): add more info about bootstrap

test/sharness/t0180-p2p.sh
Hopefully fixes https://github.com/ipfs/go-ipfs/issues/4282
This should make the test way more reliable, if it doesn't I'll look into it more.
=> sharness: make t0180-p2p less racy

exchange/bitswap/session.go
We use "" to indicate that the block came from the local node. There's no reason to record "" as an active peer (doesn't really *hurt* but still...).
=> filter out "" from active peers in bitswap sessions

core/commands/files/files.go, core/coreunix/add.go, importer/helpers/dagbuilder.go, importer/trickle/trickle_test.go, importer/trickle/trickledag.go, merkledag/node.go, mfs/dir.go, mfs/file.go, mfs/mfs_test.go, mfs/ops.go, mfs/system.go, test/sharness/t0250-files-api.sh, test/sharness/t0260-sharding-flag.sh, unixfs/hamt/hamt.go, unixfs/io/dagreader_test.go, unixfs/io/dirbuilder.go, unixfs/mod/dagmodifier.go, unixfs/mod/dagmodifier_test.go, unixfs/test/utils.go
Closes  #3989 #3921
Status: https://github.com/ipfs/go-ipfs/pull/4026#issuecomment-322058542
=> Add full support for CidV1 in Files API and Dag Modifier

core/core.go
Should *massively* reduce the amount of memory used by each peer (by 60KiB).
License: MIT
=> lower yamux accept buffer size

Dockerfile, Dockerfile.fast
I think this was unintended: useradd -g sets the gecos field to "100".
Probably we meant to use -G to set the ipfs user group.
-G does not take gids, so it needs to be set by name.
The group with gid 100 is "users".
Additionally, since we install the ca-certificates package
(which is already installed), at least we should attempt to update it
to get the latest version of certs.
License: MIT
=> Dockerfiles: do not set gecos field on user add. Set group.

Dockerfile, Dockerfile.fast
These apparantly will become Dockerfile syntax errors at some point in the future.
=> docker: move comments to avoid "empty continuation lines"

core/commands/add.go
see https://github.com/ipfs/go-ipfs/issues/4276
License: MIT
Signed-off-by: Enrique Erne <enrique.erne@gmail.com>
=> adds more info about chunker option

package.json, repo/fsrepo/datastores.go
This PR updates badgerds to use new transaction API. On-disk format hasn't changed (at least this is what I observed)
Fixes #4322
=> gx: Update badgerds to 1.0

merkledag/utils/diffenum.go, merkledag/utils/diffenum_test.go
This handles merkle links that aren't named. And improves the
Peergos usage from worst case 30s to ~20ms
=> optimise pin update command

cmd/ipfs/daemon.go, core/commands/dag/dag.go, core/commands/files/files.go, core/commands/ipns.go, core/commands/keystore.go, core/commands/log.go, core/commands/name.go, core/commands/p2p.go, core/commands/publish.go, core/commands/root.go
Make all help command descriptions wrap under 80 characters, as per issue #2783
License: MIT
Signed-off-by: Richard Pajerski <devedge@outlook.com>
=> wrap-desc: Wrap help descriptions under 80 chars

ISSUE_TEMPLATE.md
In many cases issues reported are present only in older versions.
I've set 0.4.10 as a cut of as it is quite recent and contains many
fixes and performance improvements.
License: MIT
=> misc: add note about updating before reporting the issue

package.json, repo/fsrepo/datastores.go
This once again breaks the on-disk format, uses badger v1.0.0.
@whyrusleeping Should I write an upgrade script for the version in 0.4.12-rc1 too, or is just supporting the one in 0.4.11 fine?
=> gx: update go-ds-badger to 1.1.0

docs/experimental-features.md, package.json, repo/fsrepo/datastores.go
With this when opening unsupported datastore version the error will point to https://github.com/ipfs/badgerds-upgrade
=> Update badgerds to 1.1.2

exchange/bitswap/session.go
If a sessions context gets canceled during an `isInterested` request, bitswap (all of bitswap) can deadlock.
License: MIT
=> Buffer response channel to prevent deadlock

bin/container_daemon
This is perhaps the most insignificant contribution ever...
I was reading through `bin/container_daemon` and saw a reference to "this PR" which no longer made sense now that the code is in master. Thought I would offer the correction while I'm at it.
I apologize if this is too small to be worth the reviewer's time.
=> Remove reference to "this PR" in code

core/commands/get.go, core/commands/get_test.go
This change fixes issue https://github.com/ipfs/go-ipfs/issues/3729.
When using path with trailing slashes, ipfs get command had issues with trying to store content into '.' folder (as the file part of the path was empty). Now, it correctly stores the file into desired path,
thanks to the removal of trailing slash by introducing a getOutPath function in get command, which does proper parsing of the output path.
BEFORE:
```
$  ./ipfs get /ipns/multiformats.io/
Saving file(s) to  .
```
NOW:
```
$ ./ipfs get /ipns/multiformats.io/
Saving file(s) to multiformats.io
```
=> core: get cmd outPath remove trailing slash - fixes #3729

cmd/ipfs/ulimit_freebsd.go, cmd/ipfs/ulimit_unix.go, fuse/node/mount_darwin.go, package.json
(mostly)
syscall has been frozen and mostly deprecated. We can't *entirely* switch but
this brings us closer.
progress on #3267
(we still need to pull through some go-reuseport changes)
=> switch from syscall to golang.org/x/sys

core/commands/mount_windows.go
After https://github.com/ipfs/go-ipfs/pull/3856 I had build issues.
```
go install -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=225159bc"  ./cmd/ipfs
core\commands\mount_windows.go:6:2: cannot find package "gx/ipfs/QmadYQbq2fJpaRE3XhpMLH68NNxmWMwfMQy1ntr1cKf7eo/go-ipfs-cmdkit" in any of:
C:\Go\src\gx\ipfs\QmadYQbq2fJpaRE3XhpMLH68NNxmWMwfMQy1ntr1cKf7eo\go-ipfs-cmdkit (from $GOROOT)
C:\tmp\src\gx\ipfs\QmadYQbq2fJpaRE3XhpMLH68NNxmWMwfMQy1ntr1cKf7eo\go-ipfs-cmdkit (from $GOPATH)
make: *** [cmd/ipfs/Rules.mk:26: cmd/ipfs-install] Error 1
```
It seems like the hash in that file differs from the one in `package.json` for that dependency. I couldn't resolve the hash in this file (no peers seem to provide it) so I'm assuming it was an older version that was being tested and …
=> Fix orphaned gx dependency

core/commands/object/object.go, test/sharness/t0051-object.sh
Like --quitet for `ipfs add`, makes use in scripts a bit simpler.
=> object: --quiet flag to put

exchange/bitswap/session.go
This deadlock would happen when calling SessionsForBlock (holding bitswap.sessLk) while the session's main loop was trying to deregister the session (taking bitswap.sessLk).
I've also defensively added selects on contexts for two other channel writes just in case.
fixes #4394
...well, it fixes *a* deadlock showing up in that issue, there may be more.
=> fix deadlock in bitswap sessions

core/commands/add.go, core/commands/pin.go
=> Fix two race conditions (and possibly go routine leaks) in commands

core/commands/dht.go, core/commands/repo.go
There's a lot left but I'll just make an issue and advertise it on IRC.
=> Fix some goroutine leaks in commands

core/commands/pubsub.go
Fixes go-ipfs-api hanging on pubsub tests (currently all tests fail over there because of this)
=> core/commands/pubsub.go: flush output before iterating over received messages

core/commands/mount_windows.go
cc @keks @Stebalien somehow we missed updating this hash. I'm pretty sure that gx doesnt skip any files because due to build constraints.
License: MIT
=> fix builds on windows

test/sharness/t0088-repo-stat-symlink.sh
Top help track down random test failures.
See #4408
=> Increase verboseness of t0088-repo-stat-symlink.sh test.

cmd/ipfs/daemon.go, core/builder.go, core/commands/ipnsps.go, core/commands/mount_windows.go, core/commands/name.go, core/core.go, core/corehttp/gateway_test.go, namesys/interface.go, namesys/namesys.go, namesys/namesys_test.go, namesys/pubsub.go, namesys/pubsub_test.go, test/sharness/t0183-namesys-pubsub.sh
Implements a namesys publisher and resolver with pubsub.
=> namesys/pubsub: pubsub Publisher and Resolver

core/coreunix/add.go
AddWithContext should use the custom context when calling
NewAdder
License: MIT
Signed-off-by: ForrestWeston <forrest@protocol.ai>
=> AddWithContext wraps custom context

docs/config.md, namesys/republisher/repub.go
Found while looking into: https://discuss.ipfs.io/t/ipfs-name-failing-to-resolve/1524
1. Fix the republish docs. We republish every 4 hours by default.
2. Republish after 1min on start. The 1min delay gives us time to start up everything else but ensures that the IPNS record becomes resolvable quickly if we've been offline for a while.
3. Republish every 5min when republishing fails. I doubt this will cost us *that* much bandwidth/CPU usage and will ensure that IPNS will continue working properly even if the node is intermittently offline.
=> Fix various IPNS issues

test/sharness/lib/test-lib.sh, test/sharness/t0088-repo-stat-symlink.sh
This test assumed that the repo could only grow in size when it can also shrink. This commit makes the test actually test for the specific bug it was meant to detect.
fixes #4408
=> make repo size test pass deterministically

core/commands/add.go, core/commands/get.go
Closes #4452.
When `SetError` is called in a command, `res.Next()` returns the error "received command error" makes the error set by the command available by calling `res.Error()`. To make handling these errors easier, the functions `cmds.HandleError` was added. Unfortunately we forgot to use it in the get command.
The add command did the right thing, but manually instead of calling HandleError. I made it call that function instead.
=> Fix error handling in commands add and get

assets/assets.go, cmd/ipfs/init.go, core/corerepo/pinning.go, fuse/ipns/common.go, namesys/publisher.go, pin/pin.go
* Better allocation patterns
* Fix a very small race condition between GC and pinning.
* Fix #4122 by resolving nodes as needed instead of up-front.
* Avoid creating many unnecessary contexts (also related to #4122).
=> Pinning fixes

core/corehttp/webui.go
=> Update WebUI version

cmd/ipfs/Rules.mk, mk/golang.mk, mk/util.mk
fixes #4427
(I'm not a make expert, please review)
=> build for all supported platforms when testing

.travis.yml, README.md, bin/Rules.mk, ci/Dockerfile.buildenv, circle.yml, mk/golang.mk, package.json, unixfs/hamt/hamt.go, unixfs/hamt/hamt_test.go, unixfs/hamt/util.go
Found this while writing another hamt (using ipld :) )
License: MIT
=> fix hamt delete issue

core/corehttp/gateway_handler.go, namesys/base.go, namesys/dns.go, namesys/namesys.go, namesys/routing.go
The signal/noise ratio on the ipfs.io gateways is incredibly bad nowadays - this is a step to improving that.
All the logs here are based on user input, and they're neither WARN nor INFO worthy, so I'm degrading them all to DEBUG. Also removed a few useless log lines.
I'm already testing this on scrappy, where the logs are now actually readable.
=> Refine gateway and namesys logging

exchange/bitswap/wantmanager.go
Not being able to dial a peer we used to be connected to is interesting but definitely not an error.
fixes #4472
=> Demote bitswap error to an info

test/sharness/lib/test-lib.sh
Before it was only set when "test_init_ipfs" is called but that is not always used, for example in t0025-datastores.sh.
Fixes #4467.
=> Always set IPFS_PATH in test-lib.sh

Dockerfile.fast, test/ipfs-test-lib.sh, test/sharness/lib/test-lib.sh
1. Set TERM to dumb.
2. Strip any ANSI codes that make it into the docker output anyways.
3. Don't use empty continuation lines.
(probably overkill but...)
=> Fix sharness docker

exchange/bitswap/bitswap_test.go, exchange/bitswap/testnet/virtual.go
* fix races in testnet
* improve TestBasicBitswap (and make debugging it easier). 
In attempt to debug #4374 and #4108.
Also fixes #2444.
=> improve bitswap tests

exchange/bitswap/workers.go
Base58 encoding cids/peerIDs isn't exactly fast.
=> only construct bitswap event loggable if necessary

core/coreapi/coreapi.go, core/coreapi/dag.go, core/coreapi/dag_test.go, core/coreapi/interface/interface.go, core/coreapi/interface/options/dag.go, core/coreapi/unixfs_test.go
=> RFC: coreapi.Dag

cmd/ipfs/daemon.go, core/builder.go
The `core.BuildCfg` struct had a typo (IMHO) in one of the field names: `permaMent`. This PR fixes that to `permaNent`. I hope there won't be any API breakage from this (thinking about config files, no idea how ipfs works with this regard).
=> cmd, core: fix Permament -> Permanent typo

core/coreunix/add.go, importer/chunk/parse.go, importer/chunk/splitting.go, importer/chunk/splitting_test.go, importer/importer.go, package.json
This is part of #4505.
~It's WIP because we still need to use some form of buffer pool. As is, allocating and throwing away 256KiB buffers is killing GC.~
=> Don't lock up 256KiB buffers when adding small files

core/coreunix/add.go, mfs/system.go
During `ipfs add`, we periodically call flush on the mfs root to free up unused memory. Apparently `Flush` on the mfs root object wasnt actually calling `Flush` on its directory, which led to memory not actually being freed. I'm trying to think of the best way to test this.
License: MIT
=> Ensure that flush on the mfs root flushes its directory

cmd/ipfs/init.go, core/commands/config.go, docs/config.md, repo/config/init.go, repo/config/profile.go, repo/fsrepo/fsrepo.go, repo/mock.go, repo/repo.go, test/sharness/t0021-config.sh
=> config: command to apply profile after init

unixfs/io/dagreader_test.go, unixfs/io/pbdagreader.go
I would like to figure out how to add a test or two for this. I feel like testing the internals of the dagreader object is a bit pointless, and its pretty difficult to test if something has been garbage collected.
License: MIT
=> clear out memory after reads from the dagreader

core/coreapi/coreapi.go, core/coreapi/interface/interface.go, core/coreapi/interface/options/key.go, core/coreapi/interface/options/name.go, core/coreapi/key.go, core/coreapi/key_test.go, core/coreapi/name.go, core/coreapi/name_test.go, core/coreapi/unixfs_test.go, repo/mock.go
TODO:
Note that most of the implementation code comes form respective commands, if this get's merged, I'll rewrite them to use this API.
=> RFC: coreapi.Name,Key

core/commands/ping.go, test/sharness/t0041-ping.sh
* Return an error when pinging self (an alternative would be to fake the ping). fixes #4542.
* Better error messages.
* Return an error if the ping count is <= 0.
=> various ping fixes

cmd/ipfs/dist/install.sh
This is a very simple change, but took me a few minutes to resolve, since the documentation is specifically broken related to this.
https://ipfs.io/docs/install/#installing-from-a-prebuilt-package
```
...
After downloading, untar the archive, and move the ipfs binary somewhere in your executables $PATH using the install.sh script:
tar xvfz go-ipfs.tar.gz
./go-ipfs/install.sh # <-- install.sh cannot currently be run when not inside the go-ipfs directory
Test it out:
...
```
=> Allow install.sh to be run without being the script dir

core/commands/files/files.go, core/commands/name.go, core/commands/publish.go
A few minor corrections I noticed when reading through https://ipfs.io/docs/commands/.
In the case of name and publish, the example is currently confusing because the output shows the ipfs path being published to the same ipns as earlier despite the fact it was published with a new key. 
Also, the generated public page on ipfs.io is a bit out of date (April 2017), so some old commands are still there despite being removed from the latest versions, e.g. "ipfs tour"
=> Fix typos and inconsistencies in commands documentation

core/coreunix/add.go
This wasn't causing any problems because this function is actually dead code (but possibly useful?).
Should we just remove this function?
=> fix defered unlock of pin lock in AddR

circle.yml
environment variable expansion doesn't work in the cache_directories section.
=> fix circleci cache directory list

core/commands/config.go
=> fix outdated warning about private key in 'config show'

docs/file-transfer.md
This is a very common scenario that people frequently ask us about on IRC. While we work on things that make it better, this guide should help anyone having issues.
License: MIT
=> add a document to help troubleshoot data transfers

core/coreapi/coreapi.go, core/coreapi/interface/interface.go, core/coreapi/interface/options/object.go, core/coreapi/object.go, core/coreapi/object_test.go, core/coredag/dagtransl.go
=> coreapi: Basic object API implementation

core/commands/object/object.go, core/coreapi/object.go
We'll dedup the code later, for now:
1. Don't drop errors on the floor.
2. Don't modify anything returned by `Links()` directly...
=> minor drive-by code cleanup

ISSUE_TEMPLATE.md
* Direct users seeking support to the forums.
* Remove the severity field. It doesn't actually help (especially because we can't filter by it and, anyways, *we* end up deciding the severity).
* Put the section comments *inside* the sections. This has been annoying me from day 1.
* Put the welcome text *at the top* so users actually read it.
* Expand on what we want in a description.
=> expand the issue template and remove the severity field

core/coreapi/coreapi.go, core/coreapi/unixfs.go, merkledag/errservice.go, merkledag/merkledag.go, merkledag/readonly.go, merkledag/readonly_test.go, merkledag/rwservice.go, merkledag/session.go, path/resolver.go, unixfs/io/dagreader.go, unixfs/io/pbdagreader.go, unixfs/io/resolve.go
I'm actually not happy with how this turned out. Everything worked out fine until I had to deal with the Hamt code. Theres no distinction between reading from a hamt and writing to it. The solution i chose here was to separate that out, its a bit messy. The other approach would be to just make a hybrid `DagService` implementation that passes all Get calls to an underlying session, and then `Add` calls get routed normally. I think that method seems a lot cleaner... 
cc @Stebalien @magik6k @kevina let me know what you all think. 
License: MIT
=> Use a bitswap session for 'Cat'

mk/golang.mk
=> only run the build test on test_go_expensive

core/coreunix/add.go, importer/balanced/balanced_test.go, importer/balanced/builder.go, importer/chunk/parse.go, importer/chunk/rabin.go, importer/chunk/rabin_test.go, importer/chunk/splitting.go, importer/helpers/dagbuilder.go, importer/helpers/helpers.go, importer/importer.go, importer/trickle/trickle_test.go, importer/trickle/trickledag.go, unixfs/format.go, unixfs/mod/dagmodifier.go, unixfs/test/utils.go
This fixes all golint warnings in the importers module, adding
documentation and module descriptions.
License: MIT
=> Docs: golint-ify  "importers" module

core/coreapi/block.go, core/coreapi/block_test.go, core/coreapi/coreapi.go, core/coreapi/interface/interface.go, core/coreapi/interface/options/block.go
=> coreapi: Block API

.gitattributes, cmd/ipfs/util/ulimit_test.go, pin/pin_test.go, repo/fsrepo/serialize/serialize_test.go, routing/mock/centralized_test.go
This fixes windows issues @VictorBjelkholm had in https://github.com/ipfs/go-ipfs/pull/4430#issuecomment-352016810.
There is still one test failing:
```
--- FAIL: TestReprovide (0.05s)
reprovide_test.go:51: Should have gotten a provider
```
This will need a fix in https://github.com/libp2p/go-libp2p-peer/blob/master/test/utils.go#L23. The problem here is that `time.Now().UnixNano()` resolution on windows is really poor (multiple ms)
=> Fix go test on Windows

core/corerepo/gc.go, core/coreunix/add_test.go, pin/gc/gc.go, repo/fsrepo/datastores.go
Depends on https://github.com/ipfs/go-ds-measure/pull/13
I'm not sure how to approach adding tests for this. Badger does implement this interface and it does get called, though due to it's GC weirdness I'm unable to come up with scenario in which it will actually free-up some space.
(Badger was updated to current master, doesn't seem to break anything from my testing)
=> Make repo gc call CollectGarbage on datastore

merkledag/coding.go, merkledag/errservice.go, merkledag/merkledag.go, merkledag/merkledag_test.go, merkledag/node.go, merkledag/raw.go, merkledag/rwservice.go, merkledag/traverse/traverse.go, merkledag/utils/diff.go, merkledag/utils/utils.go
This fixes all golint warnings in merkledag (except in protobuf generated code).
Main change of note is that `NewDAGService` returns an `ipld.DAGService` and not a non-exported `dagService`.
=> Golint: fix golint warnings in merkledag submodule

docs/experimental-features.md
Not sure about "Road to being a real feature" and also would like to have clarified when this is being used. My understanding is that it'll shard automatically both when using the Files API and also when doing `ipfs add -r` but I'm not 100% about this.
=> Added sharding to experimental features

routing/mock/interface.go, routing/none/none_client.go, routing/offline/offline.go
=> Doc: golint-ify routing module

path/path.go, path/resolver.go
This removes all go-lint warnings in the path package.
=> Doc: golint-ify path package.

core/commands/pin.go, pin/gc/gc.go, pin/pin.go
This removes all golint warnings in the `pin` package.
Due to stuttering, I had to rename `pin.PinMode` to `pin.Mode`. I can revert that specific commit though.
Protobuf stuff not touched.
=> Doc: golint-ify pin package

exchange/bitswap/message/message.go, exchange/bitswap/notifications/notifications.go, exchange/bitswap/notifications/notifications_test.go, exchange/bitswap/session.go, exchange/bitswap/session_test.go, exchange/bitswap/testnet/virtual.go
=> shutdown notifications engine when closing a bitswap session

core/commands/add.go
According to https://github.com/ipfs/go-ipfs/issues/3397#issuecomment-317256365, the status of experimental features is now tracked in a file in the repo, not in an issue.
=> update link to filestore experimental status

blockservice/blockservice.go, exchange/interface.go
Blockservice has an explicit dependency on bitswap so it can
call NewSession. It should rely on the exchange interfaces though, not
on specific implementations.
License: MIT
=> Add exchange.SessionExchange interface for exchanges that support sessions

keystore/keystore.go, keystore/keystore_test.go
Modified keystore to ignore invalid key files inside the keystore directory to address #4681
* Has calls the validateName function before checking if we have the file
* List filters the returned list of file names by validateName.
=> Ignore invalid key files in keystore directory.

core/builder.go, core/commands/files.go, core/commands/ls.go, core/commands/pin.go, core/commands/unixfs/ls.go, core/core.go, core/coreapi/coreapi.go, core/corehttp/gateway_handler.go, core/corerepo/pinning.go, core/coreunix/cat.go, core/pathresolver.go, path/path.go, path/resolver/resolver.go, path/resolver/resolver_test.go
Currently the "path" module does two very different things:
* Defines how ipfs paths look like and provides tools to parse/split etc.
* Provides a resolver to resolve paths.
This moves the resolver stuff to `path/resolver` and leaves the
path utilities in `path`.
The result is that now the IPFS path is a free module
that can be exported without problems and with that we remove circular
dependency cycles (resolve_test -> merkledag/utils, merkledag->path),
which do prevent exportation of merkledag itself.
License: MIT
=> Feat: Separate "path" from "path/resolver"

core/commands/pubsub.go, test/sharness/t0180-pubsub.sh
=> fix pubsub pub reading stdin args

ci/Dockerfile.buildenv, test/sharness/t0090-get.sh, thirdparty/tar/extractor.go
Resolves https://github.com/ipfs/go-ipfs/issues/4781 https://github.com/ipfs/go-ipfs/pull/4785
Thanks to @schomatis for tracing it.
=> tar: fix Go 1.10 breakage

package.json, repo/config/version.go
Second release candidate, now with go1.10 support
License: MIT
=> ipfs release 0.4.14-rc2

core/commands/files.go, core/commands/object/object.go, core/commands/object/patch.go, core/commands/root.go
This should make the fix that @Stebalien is working on for the cmds lib argument stdin parsing a little bit simpler.
License: MIT
=> upgrade commands that used StringArguments

core/commands/commands.go, core/commands/files.go, core/commands/pubsub.go
Part of #4818 
Also fixes pubsub ls breakage.
License: MIT
=> fix: use EmitOnce where only single response is to be sent

cmd/ipfs/daemon.go, cmd/ipfs/ipfs.go, cmd/ipfs/main.go, commands/legacy/command.go, commands/legacy/legacy.go, commands/legacy/legacy_test.go, commands/legacy/request.go, commands/legacy/response.go, commands/request.go, core/commands/add.go, core/commands/bitswap.go, core/commands/block.go, core/commands/cat.go, core/commands/commands.go, core/commands/commands_test.go, core/commands/files.go, core/commands/filestore.go, core/commands/get.go, core/commands/get_test.go, core/commands/helptext_test.go, core/commands/object/object.go, core/commands/object/patch.go, core/commands/pubsub.go, core/commands/repo.go, core/commands/root.go, core/commands/stat.go, core/corehttp/commands.go, package.json, test/sharness/t0100-name.sh
otherwise, we block on required arguments from stdin before processing the help flag.
fixes #4837
=> check arguments after handling help

core/commands/block.go, test/sharness/t0050-block.sh
Closes https://github.com/ipfs/go-ipfs/issues/4741 ~Kubuxu
=> commands/block: use CIDv1 with custom mhtype

blockservice/blockservice.go
... and remove a few log lines that don't seem terribly useful.
This will be useful for ipfs-repeater. The `Bitswap.BlockGetRequest` start/end events don't really cut it, they don't tell me that the block has *actually* been fetched and stored, and that the blockservice is able to provide them.
I put in TODO() contexts there, doing context wiring for Add/Delete felt out of scope, but I can do that too.
=> blockservice: add BlockedFetched/Added/Removed events

merkledag/merkledag_test.go
This avoids using unixfs package and importer packages in
merkledag, which removes circular depedencies making it hard
to extract this module.
This comes pers @whyrusleeping suggestion on IRC:
```
22:20:28 <@whyrusleeping> hsanjuan: it would be great to work out those circular deps by using mocks of some sort
22:20:53 <@whyrusleeping> I think the merkledag_test stuff can be replaced with some code that just generates a dag manually
22:21:03 <@whyrusleeping> which is a little annoying, but needs to be done anyways
```
I'm very new here handling DAGs etc, so excuses in advance if something is terribly stupid.
=> Feat: remove circular dependencies in merkledag package tests

importer/trickle/trickledag.go
Refactoring of the logic of the trickle DAG builder to simplify the future patch that will add support for Filestore (#4052).
The `Layout` function is mirroring the logic in `fillTrickleRec` duplicating almost entirely its code. The refactored `fillTrickleRec` now absorbs both scenarios of building a trickle tree with or without a maximum depth (`Layout` didn't have a maximum depth, only `fillTrickleRec` did). This is accomplished abusing the `depth` parameter (now renamed as `maxDepth`) to make it optional (a negative value is interpreted as no maximum). This hack is due to the fact that Go doesn't support optional parameters, suggestions are welcome for a more elegant solution.
I'm submitting this WIP PR to have feedback on this refactoring, as it will be useful to extend it to other …
=> Refactor trickle DAG builder

test/sharness/t0090-get.sh, unixfs/archive/archive.go
Clean the path in the function `DagArchive` that prepares the output in a similar way as the resolver does in [`Segments`](https://github.com/ipfs/go-ipfs/blob/199a52d777e2b292fe430e8470d88037c43ed7ca/path/path.go#L46).
Fixes #4720.
=> unixfs: clean path in DagArchive

core/commands/add.go, test/sharness/t0043-add-w.sh
In the case that the `only-hash` option (`-n`) is set for `ipfs add`, use the same prefix from the `fileAdder` for the MFS root so it is processed using the same CID version and hash function.
Fixes #4652.
This is a work in progress, some tests should be added. Also, the comment is not very illustrative, it should clarify why is it that the prefix needs two be specified twice (for the file adder and the MFS root).
=> add: hash-only: set the prefix for MFS root

merkledag/utils/diff.go, test/sharness/t0052-object-diff.sh
The base case was assuming that the nodes were different (see [issue comment](https://github.com/ipfs/go-ipfs/issues/4591#issuecomment-368596386)).
Fixes #4591.
=> dag: diff: check CIDs in base case when comparing nodes

core/commands/get.go
This return value is used to open a platform native handle, as such platform native paths should be used.
Reference: https://github.com/ipfs/go-ipfs/issues/4808
Edit: put angle brackets around email to make gitcop happy
=> Fix get output path

cmd/ipfs/daemon.go, cmd/ipfs/init.go, test/sharness/t0063-daemon-init.sh
The test wouldn't pass when there was an ipfs daemon running on the system.
Added `init-profile` flag for `ipfs daemon`, works like the one in init.
Fixes #3457
=> Fix t0063-daemon-init.sh by adding test profile to daemon

test/sharness/t0010-basic-commands.sh
When any command is passed a flag it doesn't understand, like `--badflag` for example, it should just fail.
Let's check that in a sharness test.
See https://github.com/ipfs/go-ipfs/issues/4841 for more context.
=> sharness/t0010: check that all the commands fail when passed a bad flag

core/builder.go, filestore/fsrefstore.go, repo/fsrepo/fsrepo.go, test/dependencies/go-timeout/main.go, thirdparty/notifier/notifier.go
Before:
```
$ go vet ./...                
core/builder.go:176: github.com/ipfs/go-ipfs/thirdparty/verifbs.VerifBS composite literal uses unkeyed fields
core/builder.go:205: github.com/ipfs/go-ipfs/thirdparty/verifbs.VerifBSGC composite literal uses unkeyed fields
exit status 1
filestore/fsrefstore.go:80: possible formatting directive in Error call
exit status 1
repo/fsrepo/fsrepo.go:622: self-assignment of value to value
exit status 1
test/dependencies/go-timeout/main.go:24: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak
exit status 1
thirdparty/notifier/notifier.go:48: return copies lock value: notifier.Notifier contains sync.RWMutex
exit status 1
```
=> Fix go vet warnings

test/sharness/t0010-basic-commands.sh
Any IPFS command should accept the `--help` flag even if /dev/null is not piped to it. Let's properly check that this works.  
See https://github.com/ipfs/go-ipfs/issues/4841 for more context.
=> No dev null pipe

core/commands/get.go, package.json
It wasn't pinned and `gx publish -f` gave a different hash.
Depends on: https://github.com/whyrusleeping/tar-utils/pull/3
=> bump tar dep to make it resolvable

cmd/ipfs/init.go, cmd/ipfs/ipfs.go
Hello!
Wanted to start contributing, so first I've a changed initCmd, so that it uses now new interface from go-ipfs-cmds.
=> make init command use go-ipfs-cmds

cmd/seccat/util.go, repo/fsrepo/fsrepo.go, unixfs/io/pbdagreader.go, unixfs/mod/dagmodifier.go
follow up on #4790
review commit by commit
Note: I ignored all test cases.
=> fix incorrect Read calls

.gx/lastpubver
The hash is for a clean checkout of the v0.4.14 tag (please verify).
=> gx: bump version for 0.4.14 release

bin/check_go_path, mk/golang.mk
This came up while setting up a new system, and trying to do Go things without explicitly setting GOPATH.
=> build: match Go's GOPATH defaults behaviour

bin/archive-branches.sh
=> misc: add confirmation to archive-branches script

core/commands/unixfs/ls.go, test/sharness/t0260-sharding.sh, unixfs/archive/tar/writer.go, unixfs/io/pbdagreader.go
Makes ipfs get work on sharded directories.
fixes #4871
=> make the tar writer handle sharded ipfs directories

package.json, plugin/loader/initializer.go, plugin/tracer.go
define an interface for creating and configuring tracers
add the Jaeger tracer as a plugin
License: MIT
Signed-off-by: ForrestWeston <forrest@protocol.ai>
=> Add Opentracing plugin support

core/commands/ls.go
We don't need to fetch the linked node when it's a raw node, we already know it's a file.
=> infer type from CID when possible in ls command

merkledag/merkledag.go
No idea why this was changed this was introduced in:
08f342e8bada4f4eb0c5462a3623f0c2b828240f (part of #3598)
=> only visit nodes in EnumerateChildrenAsync when asked

test/sharness/t0260-sharding.sh, unixfs/hamt/hamt.go
We only need to get the child if it's a shard.
=> don't resolve children unnecessarily when listing a sharded directory

core/coreapi/block.go, core/coreapi/block_test.go, core/coreapi/coreapi.go, core/coreapi/dag.go, core/coreapi/dag_test.go, core/coreapi/interface/block.go, core/coreapi/interface/dag.go, core/coreapi/interface/key.go, core/coreapi/interface/name.go, core/coreapi/interface/object.go, core/coreapi/interface/options/block.go, core/coreapi/interface/options/dag.go, core/coreapi/interface/options/key.go, core/coreapi/interface/options/name.go, core/coreapi/interface/options/object.go, core/coreapi/interface/options/pin.go, core/coreapi/interface/pin.go, core/coreapi/key.go, core/coreapi/key_test.go, core/coreapi/name.go, core/coreapi/name_test.go, core/coreapi/object.go, core/coreapi/object_test.go, core/coreapi/pin.go, core/coreapi/pin_test.go
Based on #4802
Suggested by @Stebalien and @Kubuxu in https://github.com/ipfs/go-ipfs/pull/4643#discussion_r166689061.
=> coreapi: Refactor options

docs/experimental-features.md
=> document ipns pubsub

package.json, unixfs/hamt/hamt.go, unixfs/hamt/hamt_test.go, unixfs/hamt/util.go, unixfs/hamt/util_test.go
According to the go benchmarks (not testing the datastore, etc.), these changes
make iterating over HAMTs ~50x faster and creating them ~2x faster.
based on #4884, merge after.
=> improve performance of HAMTs

cmd/ipfs/init.go, core/commands/config.go, repo/config/profile.go
=> Fix missing profile docs

merkledag/merkledag.go, merkledag/merkledag_test.go
Otherwise, GetMany on the children of a node with duplicate links may fail
=> dedup keys in GetMany

repo/config/profile.go, test/sharness/t0021-config.sh
Fixes https://github.com/ipfs/go-ipfs/issues/4842
=> fix default-net profile not reverting bootstrap config

core/coreunix/metadata.go, importer/helpers/helpers.go, merkledag/merkledag_test.go, merkledag/node.go, merkledag/utils/utils.go, pin/pin_test.go, pin/set_test.go, tar/format.go, unixfs/io/dirbuilder.go, unixfs/mod/dagmodifier.go
=> dag: deduplicate AddNodeLinkClean into AddNodeLink

repo/fsrepo/fsrepo.go
I've never written a line of go in my life, but I came across this typo while using go-ipfs and thought I might as well just fix it myself. I'm pretty sure you guys are really busy.
=> Fix typo in error message

.gitignore, Rules.mk, bin/maketarball.sh, cmd/ipfs/Rules.mk, mk/git.mk, mk/gx.mk, mk/tarball.mk
You can create tarball by running: go-ipfs-source.tar.gz
License: MIT
=> mk: add tarball support

package.json
It was extracted here https://github.com/ipfs/go-ipfs/pull/4631
=> gx: remove unused lock dep

docs/windows.md
I rewrote this. Maybe it's better this way?
I'm not sure if the table alignment looks fine or crazy. Other options for that: left aligned table, separated command blocks with text annotations above, single paragraph explaining what will happen followed by a single command block.
I also have graphics that could be added but they're probably unnecessary. 
Embed underneath "Building on Windows": https://ipfs.io/ipfs/QmccXW7JSZMVXidSc7tHsU6aktuaiV923q4yBGHUsdymYo/build.gif
Add as a reference/link near the Cygwin setup portion: https://ipfs.io/ipfs/QmaYFSQa4iHDafcebiKjm1WwuKhosoXr45HPpfaeMbCRpb/cygwin%20-%20install.png
I added MSYS2 as a method, and basically redid everything else. I feel like it is more concise than it was previously, even with the repetition/explanations.
Criticisms …
=> Change Windows build documentation

package.json, repo/fsrepo/datastores.go
Includes (at least): https://github.com/ipfs/go-ds-flatfs/commit/ebb0ecaf912f365a40b91abfe82d82e495eb5042
Which fixes: https://github.com/ipfs/go-ipfs/issues/4527
And should fix:  https://github.com/ipfs/go-ipfs/issues/3971, and https://github.com/ipfs/go-ipfs/issues/4710
as well.
=> gx: update go-ds-flatfs

mk/git.mk
https://github.com/ipfs/go-ipfs/pull/4920 adds this as "commit"
https://github.com/ipfs/go-ipfs/blob/25352208642a62c23c84245ef64709c38d694b5c/mk/git.mk#L1
but uses it as "hash"
https://github.com/ipfs/go-ipfs/blob/25352208642a62c23c84245ef64709c38d694b5c/cmd/ipfs/Rules.mk#L16
https://github.com/ipfs/go-ipfs/blob/25352208642a62c23c84245ef64709c38d694b5c/mk/tarball.mk#L7-L8
As a result our commit in `ipfs version --all` is empty.
=> mk: fix commit string in version

package.json, plugin/plugins/git/git.go
Depends on https://github.com/ipfs/go-ipld-git/pull/19
=> gx: update go-ipld-git to fix mergetag resolving

core/commands/keystore.go, test/sharness/t0165-keystore.sh
fix: Error when renaming keys #4953
License: MIT
Signed-off-by: Xiaoyi Wang <wangxiaoyi@hyperchain.cn>
=> Fix key rename command output error

package.json, test/sharness/t0181-private-network.sh
Resolves the first point in #4961 by adding timeout to connect. Based on  #4965.
=> Fix: sharness iptb connect timeout

ci/Jenkinsfile
With this hanging jobs should fail a bit earlier. Currently the timeouts are set to about 2x what it takes for a given step normally.
=> ci: Add more timeouts to the jenkins pipeline

README.md
The previous link did not work anymore since the example project has been merged into the website.
=> Fixes the link to create a systemd for the `ipfs daemon`.

README.md
`ipfs/examples` repository was deprecated in favor of `ipfs/website.` This PR just adjusts the link.
=> Fix link to systemd init scripts in the README

core/core.go, repo/fsrepo/fsrepo.go
=> report error source when failing to construct private network

.travis.yml, Dockerfile, Dockerfile.fast, README.md, bin/Rules.mk, ci/Jenkinsfile, circle.yml, mk/golang.mk, package.json
https://github.com/whyrusleeping/tar-utils/pull/2 uses `strings.Builder` for windows paths, it's a go 1.10 feature.
=> ci: Use go 1.10 on jenkins

core/commands/mount_nofuse.go, fuse/node/mount_nofuse.go
License: MIT
Signed-off-by: Pierre-Alain TORET <pierre-alain.toret@protonmail.com>
=> Fix build on DragonFlyBSD

core/commands/dag/dag.go
In the unlikely case that the context is cancelled, and we're adding more than 8 files.
Part of #4414.
=> Fix goroutine leak in dag put

core/commands/refs.go
Description:
This addresses one of the listed problem files in #4414. I chose to
keep the return statement outside of the select statement on line
132 since that behavior was already there following the write to
out.
License: MIT
Signed-off-by: John Forstmeier <john.forstmeier@gmail.com>
=> Fix goroutine leaks in refs.go

test/sharness/t0130-multinode.sh
Reduces file tree in multinode test, related to #4961
=> fix: Reduce tree in multinode test

core/commands/mount_nofuse.go, core/commands/mount_unix.go, fuse/node/mount_nofuse.go, fuse/node/mount_unix.go
Followup to: https://github.com/ipfs/go-ipfs/pull/5031
@daftaupe was expressing issues on IRC when trying to build `go-ipfs` on DragonflyBSD. After investigating, it seemed like the only problem was in the build constraints. I suggested adding dragonfly to the list of build targets. This worked fine but may be unnecessary (see: https://github.com/ipfs/go-ipfs/pull/5031#issuecomment-390706466)
It may be best to just remove these constraints so people don't have to rediscovering this and make source modifications when using the `install_unsupported` `make` target on platforms that are not explicitly defined by us.
=> build: remove fuse platform constraints

core/commands/urlstore.go
=> Fix go-ipfs-chunker version desync due to bad merge

core/commands/swarm.go, package.json, repo/config/bootstrap_peers.go, test/sharness/t0140-swarm.sh
Mainly, make them work without specifying a full multiaddr.
=> improve swarm connect/disconnect commands

cmd/ipfs/daemon.go, core/core.go, core/corehttp/commands.go, core/corehttp/gateway_handler.go, core/corehttp/ipns_hostname.go
License: MIT
Signed-off-by: Brendan McMillion <brendan@cloudflare.com>
=> Fix panic. Don't handle errors with fallthrough.

README.md, docs/README.md
Adds a simple README to the `docs` folder. This is based on [the work in the new docs site](https://ipfs.io/ipfs/QmVUdHfpo9hyC8wXmgd2frRrsp83iRvuL8HWyp1LPzjsPq/reference/go/overview/), but differs slightly since it aims to list all the items in the folder (whereas they are spread across a couple different parts of the docs site).
Also adds a link to the authors list in the top-level README, since that seemed like a nice thing to do.
Fixes #5049.
=> Add README to docs folder

namesys/republisher/repub.go
This is almost never an error, it just means we don't have any connections. We could leave this at Warning but we'd like to be able to turn those on by default at some point.
fixes #5029
=> reduce log level when we can't republish

ci/Jenkinsfile
They've never really been enabled but they:
1. Are causing the tests to fail for various reasons (e.g., out of space).
2. Take time.
=> disable the MacOS tests in jenkins

namesys/republisher/repub_test.go
retry publishing with a longer EOL if the first attempt fails due to a timeout.
fixes #5099
=> make republisher test robust against timing issues

ci/Jenkinsfile
With this CI will archive any leftover sharness trash directories, this should help debugging failing sharness tests.
Example: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fgo-ipfs/detail/feat%2Fci%2Farchive-trash-dirs/46/artifacts
=> ci: Archive sharness trash dirs

repo/config/bootstrap_peers.go
We need it to parse the dnsaddr addresses. While we import it elsewhere, we
should really be importing it every where we need it so that other users can
import our packages directly.
fixes #5143
=> explicitly import go-multiaddr-dns in config/bootstrap_peers

blockservice/test/mock.go, core/builder.go, core/commands/dht_test.go, core/commands/ipns.go, core/core.go, core/coreapi/name.go, exchange/bitswap/bitswap_test.go, exchange/bitswap/testnet/network_test.go, exchange/bitswap/testnet/peernet.go, exchange/bitswap/testnet/virtual.go, exchange/reprovide/reprovide_test.go, fuse/ipns/ipns_test.go, fuse/node/mount_test.go, namesys/ipns_resolver_validation_test.go, namesys/namesys_test.go, namesys/publisher.go, namesys/publisher_test.go, namesys/republisher/repub.go, namesys/resolve_test.go, namesys/routing.go, package.json
=> add record validation to offline routing

test/sharness/t0170-dht.sh
(in preparation for libp2p/go-libp2p-kad-dht#165)
=> fixup DHT sharness tests

CHANGELOG.md, package.json, repo/config/version.go
=> Ipfs v0.4.16-rc1

core/commands/external.go, test/sharness/t0063-external.sh
This breaks commands like `ipfs update` that expect IPFS to *not* be running.
fixes #5191
=> when running an external command, only construct a node if running in online mode

CHANGELOG.md
I added a few minor language changes here on top of @Stebalien’s massive cleanup :)
This probably invalidates the `.gx/lastpubver` file. I *think* I’m supposed to update that with `gx publish`, but it doesn’t seem to want to work with my local IPFS node.
=> Tweak grammar and language in 0.4.16 changelog

core/corehttp/gateway_test.go, core/corehttp/ipns_hostname.go
Namesys returns `ErrResolveRecursion` when it stops recursing due to a depth limit. It doesn't return success.
Alternative to #5199.
=> correctly handle multi-hop dnslink resolution

core/corerepo/gc.go, core/coreunix/add.go, fuse/ipns/ipns_unix.go, mfs/mfs_test.go, mfs/ops.go, mfs/system.go
As discussed in https://github.com/ipfs/go-ipfs/issues/5066#issuecomment-395597562 and https://github.com/ipfs/go-ipfs/issues/5066#issuecomment-395706829 (different consecutive comments).
---------------------------
```
mfs: make `Root` value a `Directory`
Make `Root` value explicitly a `Directory` structure instead of the `FSNode`
interface (which also allowed the `File` type). This helps to make the code
easier to reason about: the root of an MFS layout is always a directory, not a
(single) file.
Rename `GetValue()` to `GetDirectory()` to also make it more explicit, the
renamed function now returns a `Directory` so there is no need for type
assertions that were previously done on the `FSNode` interface to check that it
was actually a `Directory`.
`NewRoot()` now doesn't allow to create …
```
=> mfs: make `Root` value a `Directory`

core/commands/object/object.go, test/sharness/t0051-object.sh
Adds a `--data-encoding` flag to `ipfs object get` to let the user specify base64 encoding for object data.
I've found that the text encoding used by default can get mangled during JSON serialisation/deserialisation so using base64 instead seems to make it more resilient.
This allows the test in ipfs/interface-ipfs-core#302 to pass.
--
I've not written much go, so hopefully this PR is ok - I couldn't find much in the way of unit tests around the `ipfs object` commands though may just have been looking in the wrong place so have added a sharness test.
=> feat: Allow specifing how object data is encoded

core/commands/repo.go, core/corerepo/stat.go, repo/fsrepo/fsrepo.go, test/sharness/t0080-repo.sh
This makes use of the PersistentDatastore DiskUsage method to obtain the Repo's storage usage (GetStorageUsage()).
Additionally, the --size-only flag has been added to the "ipfs repo stat" command. This avoids counting the number of objects in the repository and returns faster.
Overseeds #4550 
I had to make some gx magic to fix dependencies and be able to use latest go-datastore. go-libp2p-kad-dht depends on it and afaik the changes there cannot be integrated still etc. I'm happy to leave this hanging until this is sorted out. Thus, tagging this as blocked.
=> Efficient "repo stat" (DiskUsage) and "--size-only" flag

core/commands/files.go, test/sharness/t0250-files-api.sh
Fixes https://github.com/ipfs/go-ipfs/issues/5044.
=> cmd: fix `files ls` to report hash and size for files

cmd/ipfs/main.go
Keep the code style consistent. since all package alias are lowercase words, no need Camel Peak Name.
=> Refactor code

docs/config.md
During an IRC conversation, this information came up. I figured it might make for a useful suggestion here.
yay or nay?
>[2018.04.04] 14:28:47 <@hsanjuan> Can someone remind me the recommended values for bloom filter size in go-ipfs?
[2018.04.04] 14:46:58 <@stebalien> - num_blocks * 1.44 * logtwo(probability_of_false_positive)
[2018.04.04] 14:48:27 < djdv> I wonder if that should be noted in https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#datastore
[2018.04.04] 14:49:02 <@stebalien> So, for a 1% false positive rate and 1m blocks, you'd want a ~1MiB (mebibyte) filter.
[2018.04.04] 14:49:19 <@stebalien> Note: I havent' tested that, I'm just going off of wikipedia.
[2018.04.04] 14:49:28 <@stebalien> https://en.wikipedia.org/wiki/Bloom_filter#Optimal_number_of_hash_functions
=> Add information about bloom filter to config.md

unixfs/io/directory.go
Recently merged PR #5189 conflicted with #5160.
=> unixfs: fix `FSNode` accessor in `NewDirectoryFromNode`

importer/balanced/builder.go, importer/helpers/dagbuilder.go, importer/helpers/helpers.go
The `builder.go` file has been completely rewritten, should be reviewed as an entirely [new file](https://github.com/schomatis/go-ipfs/blob/fe2ce15e8619e4f3f709196453c18a1dc84a20c5/importer/balanced/builder.go).
The `dagbuilder.go` has mostly additions and can be reviewed as a [diff](https://github.com/ipfs/go-ipfs/pull/5118/files#diff-fdae772d2b35bc89d019b608d02c1755).
Closes #5106.
------------------------------
```
importer: remove `UnixfsNode` from the balanced builder
The `UnixfsNode` structure has multiple pointers to many (non-complementary)
mutually exclusive node types, only some of them are active (not-`nil`) at a
given time in the code path which made the code too convoluted. Specifically,
the most important distinction between node types was being hidden: leaf nodes
vs …
```
=> importer: remove `UnixfsNode` from the balanced builder

unixfs/io/dagreader_test.go, unixfs/io/pbdagreader.go
This should reduce stuttering when streaming.
Also, fix an unlikely bug where canceling a context from one read could fail a future read.
=> always try to read ahead by at least 5 blocks in the PBDagReader

mfs/mfs_test.go, unixfs/mod/dagmodifier.go
Fixes #4518.
(Taken from PR https://github.com/ipfs/go-ipfs/pull/4517.)
=> fix truncating when already at the correct size

mfs/mfs_test.go, test/sharness/t0250-files-api.sh, unixfs/mod/dagmodifier.go, unixfs/mod/dagmodifier_test.go, unixfs/unixfs.go
So, in a weird series of coincidences that I don't fully understand I need to fix this old bug (which I already fixed in the PR #4758 that I never finished) to be able to refactor some parts of the code of the DAG reader (see https://github.com/ipfs/go-ipfs/issues/5192#issuecomment-404216727).
I'm selfishly assigning this PR a high priority to get it merged as soon as possible after the upcoming release, as it will simplify my work on the DAG reader.
Fixes #4519.
-----------
```
unixfs: fix `dagTruncate` to preserve node type
Extract the original `FSNode` passed inside the `ipld.Node` argument and modify
its `Blocksizes` (removing all of them and re-adding the ones that were not
truncated). In contrast, the replaced code was creating a new `FSNode` that was
not preserving some of the …
```
=> unixfs: fix `dagTruncate` to preserve node type

unixfs/io/dagreader.go, unixfs/io/pbdagreader.go, unixfs/unixfs.go
Addresses part of #5192.
--------------------
```
unixfs: refactor switch in `precalcNextBuf`
Do not use `NewDagReader` just for the `RawNode` case.
Treat invalid UnixFS types in the same case.
```
---------------------
```
unixfs: split `precalcNextBuf`
Create new `loadBufNode` function to handle the `buf` logic which is unrelated
to the main `precalcNextBuf` logic of processing promises to fetch nodes.
```
=>  unixfs: refactor `precalcNextBuf`

core/commands/files.go
Fixes https://github.com/ipfs/go-ipfs/issues/5088.
=> commands/files: add error messages for `cp` paths

core/commands/files.go, mfs/dir.go, test/sharness/t0250-files-api.sh
Fixes https://github.com/ipfs/go-ipfs/issues/5181.
=> mfs: remove `sort` from `ListNames()`

plugin/loader/load_linux.go
Currently it's not possible to debug applications which use the "plugin" package (https://github.com/golang/go/issues/23733)
=> build tag to disable dynamic plugins

mfs/mfs_test.go
Right now this test isn't failing due to another bug that causes seeking to the end to return to the beginning of the file (https://github.com/ipfs/go-ipfs/issues/5255) and the read call works, but it would be nice to get this test fixed as it's failing in a refactoring of the DAG reader (https://github.com/ipfs/go-ipfs/pull/5257).
=> mfs: seek to 0 before reading in `TestTruncateAndWrite`

unixfs/mod/dagmodifier_test.go
This should be the last of the seek-before-reading errors in the tests.
Needed for https://github.com/ipfs/go-ipfs/pull/5257.
=> test: testLargeWriteChunks: seek before reading

path/resolver/resolver.go, test/sharness/t0260-sharding.sh
Fixes https://github.com/ipfs/go-ipfs/issues/5270
=> Fix resolving links in sharded directories on gateway

.gx/lastpubver, CHANGELOG.md, package.json, repo/config/version.go
This is a relatively small release to fix a performance regression I introduced.
Hopefully, it'll also get us into a fast release cadence.
The downside is that freezing due to an RC slows everything to a grind.
=> Release 0.4.17

filestore/fsrefstore.go
Some servers seem to return 200 OK when range header covers entire file.  If the content is wrong we will detect later so there is no harm in accepting either response.
Closes #5250.
=> urlstore: Accept "200 OK" in addition to "206 Partial Content".

core/commands/pin.go, test/sharness/t0085-pins.sh
* flush pins
* correctly print output
* add a sharness test
=> pin update fixes

package.json, test/sharness/lib/iptb-lib.sh, test/sharness/t0023-shutdown.sh, test/sharness/t0125-twonode.sh, test/sharness/t0130-multinode.sh, test/sharness/t0175-reprovider.sh, test/sharness/t0181-private-network.sh, test/sharness/t0182-circuit-relay.sh
Ideally, we'd fix this in IPTB but I'm tired of this bug and this is the easy fix.
fixes #5272
Pass: 5/5.
=> wait for the nodes to fully stop

core/commands/root.go, core/commands/shutdown.go, core/corehttp/corehttp.go, test/sharness/t0023-shutdown.sh
Using httpServer.Shutdown will:
1. Close the listener (preventing new connections).
2. Close each connection as outstanding requests finish.
Turns out this issue wasn't as tricky as I had thought.
This prevent us from shutting down before outstanding requests get a chance to respond.
fixes #4055
=> wait for all connections to close before exiting on shutdown.

ci/Jenkinsfile
Without this, if a job had to wait >4min for a node to execute on it would fail
=> ci: apply timeout for build steps after getting node

core/commands/dht.go, test/sharness/t0175-reprovider.sh
fix `ipfs dht findprovs` can't handle `/ipfs/$hash`  ref #5311
License: MIT
Signed-off-by: Xiaoyi Wang <wangxiaoyi@hyperchain.cn>
=> fix: dht findprovs unable to handle /ipfs/hash #5311

core/coreapi/dag.go, core/coreapi/dag_test.go, core/coreapi/interface/dag.go
I think this is the nicest way to get batching in coreapi, but if you have some better ideas, I'm happy to hear them
Part of https://github.com/ipfs/go-ipfs/issues/5215 / https://github.com/ipfs/go-ipfs/issues/4498
=>  coreapi: dag: Batching interface

core/builder.go, test/sharness/t0276-cidv0v1.sh, thirdparty/cidv0v1/blockstore.go
~~This is one way to do it.~~
~~Another way is to create (yet another) wrapper blockstore.  However, this block store needs to be implemented very carefully to avoid breaking things.  In particular only the `Get` method can be changed.~~
~~Although it would seam logical the `Has` method can not  be modified because otherwise that might prevent blocks from getting added that should as we check if a block exists before adding it in the blockservice.  This could create a problem if for example a CIDv0 block is in the blockstore and a CIDv1 of the block is added and pinned.  If the Has method was modified then the CIDv1 will never get added and if the CIDv0 version is not pinned it would get removed when the garbage collector is ran and both the CIDv0 and CIDv1of the block is will become …
=> Add ability to retrieve blocks even if given using a different CID version

ci/Jenkinsfile
Might make the builds a bit slower until optimized gx is used here, but the ci should at least be more stable.
=> ci: call cleanWs after each step

test/sharness/lib/test-lib.sh, test/sharness/t0080-repo.sh
When checking to see if GC fully reverses an `ipfs add`, we should check the size of the actual files, not the directory sizes. A bunch of empty directories won't use *that* much space and really shouldn't count against GC.
closes #1515
I'm not sure why this has been sitting around for so long but I never seem to have created this PR.
=> add correct test for 1515

core/coreunix/add.go
Code was just weird. I think it looks better now.
License: MIT
=> Fix some weird code in core/coreunix/add.go

core/commands/config.go
This doesn't change there CLI output, it just means that the server responds with a JSON output by default.
Fixes #5335.
=> return a json object from config show

fuse/ipns/ipns_test.go, fuse/ipns/ipns_unix.go
Recreated https://github.com/ipfs/go-ipfs/pull/5327
=> Fixed ipns address resolution in fuse unix mount

core/corehttp/gateway_handler.go, test/sharness/t0110-gateway.sh
Helps with referring to hashes by specific filename, eliminated unixfs node need for that
Example: http://ipfs.io/ipfs/Qmfoobar -- downloads Qmfoobar.zip (if mime was detected by first block)
http://ipfs.io/ipfs/Qmfoobar?filename=stuff.zip -- downloads stuff.zip
=> Set filename in Content-Disposition if filename=x is passed in URI query

core/commands/add.go, core/commands/bitswap.go, core/commands/block.go, core/commands/cat.go, core/commands/cmdenv/env.go, core/commands/dht.go, core/commands/dns.go, core/commands/files.go, core/commands/filestore.go, core/commands/get.go, core/commands/keystore.go, core/commands/mount_unix.go, core/commands/name/ipns.go, core/commands/name/ipnsps.go, core/commands/name/name.go, core/commands/name/publish.go, core/commands/object/patch.go, core/commands/p2p.go, core/commands/ping.go, core/commands/pubsub.go, core/commands/repo.go, core/commands/resolve.go, core/commands/root.go, core/commands/shutdown.go, core/commands/stat.go, core/commands/swarm.go, core/commands/urlstore.go
Just wanted to do this before `ipfs name resolve --stream`
* Moves `GetApi`/`GetNode` utils to subpkg to avoid duplicating them
* Port name commands to the new lib
* Move `ipns name` commands into a sub-package
=> name cmd: move subcommands to subdirectory

test/sharness/t0272-urlstore.sh
1. GC the intentionally broken files so we don't reuse their blocks.
2. Make sure we actually check the *new* output file instead of an old one.
=> fix the urlstore tests

core/commands/files.go, test/sharness/t0250-files-api.sh
Adds support for a `-p/--parents` flag to the `files.write` command similar to the one supported by the `files.mkdir` command. If this is true and the directory for the file is not `"/"`, try to create the containing directory before writing to the file.
=> Allow mfs files.write command to create parent directories

docs/gateway.md
~Blocked on https://github.com/ipfs/go-ipfs/pull/4177~
=> add some basic gateway documentation

cmd/ipfs/dnsresolve_test.go, cmd/ipfs/main.go, package.json, test/sharness/t0236-cli-api-dns-resolve.sh
_This is my first PR to go-ipfs, so please be gentle ;-)_
Imports `go-multiaddr-dns` and calls `madns.Resolve()` with the provided multiaddr. There's no need to call `Matches()` explicitly, as the resolution will do no-op if no DNS protocols are found in the input multiaddr (I'm assuming this is part of the contract of `madns.Resolve()`).
If multiple results are returned, only the first one is used. See https://github.com/ipfs/go-ipfs/issues/5249#issuecomment-412286842.
I've added several unit tests in the `dnsresolve_test.go` file. Not sure if that's the best place. I'm happy to change it.
I initially added the call to `madns.Resolve()` in `apiClientForAddr()` but I couldn't assert on the address of `http.Client` as its private, so I had to put it in a separate function to enable unit …
=> Run DNS lookup for --api endpoint provided in CLI

core/commands/add.go, test/sharness/t0040-add-and-cat.sh, test/sharness/t0046-id-hash.sh
Add support for inlining via the id-hash to the `ipfs add` command using the new Builder interface.
=> Add support for inlinling via the id-hash

core/commands/refs.go, test/sharness/t0095-refs.sh
This adds --max-depth to the "refs" commands and allows limiting
the fetching of refs per depth. Other than that, it works as before.
Note that clever branch pruning is only made when the --unique flag
is passed. Otherwise, we re-explore branches to the given depth.
---
First minimal approach. I wonder if we could utilize the EnumerateChildren functions here instead, @Stebalien ? Doing the printing inside the custom visit function. I'm not sure if there are reasons why the DAG traversal logic was re-implemented separately for this command.
Also, now or later, I would like to do an `--async` version of this, so it would be very easy if we re-use EnumerateChildrenAsync().
=> Feat: depth limited refs -r

core/commands/bitswap.go, core/commands/commands_test.go, misc/completion/ipfs-completion.bash
This command messes with internal state and doesn't even work at the moment. If
you don't want a block, you should cancel the request that's trying to fetch it.
An alternative is to replace this command with a dummy command that prints an
error but we'll break user code either way and I'd rather delete code.
fixes #5295
=> remove bitswap unwant

core/commands/ls.go
Fixes https://github.com/ipfs/go-ipfs/issues/5165.
=> core/commands/ls: wrap `NewDirectoryFromNode` error

namesys/routing.go, test/sharness/t0236-cli-api-dns-resolve.sh
No need to parse it as a hash first.
=> directly parse peer IDs as peer IDs

core/builder.go
=> don't bother caching if we're using a nil repo

core/commands/filestore.go
ipfs/go-ipfs/issues/4414
fix filestore.go goroutine leak
License: MIT
=> fix(commands): fix filestore.go goroutine leak

core/commands/ping.go
ipfs/go-ipfs/issues/4414
fix ping.go goroutine leaks
License: MIT
=> fix(commands): goroutine leaks in ping.go

core/bootstrap.go
=> add warning when no bootstrap in config

core/corehttp/gateway_test.go
Unfortunately, this doesn't really test the *actual* gateway config as it uses
the options specified by the test. However, it's a step in the right direction.
=> improve gateway options test

core/commands/object/object.go, test/sharness/t0051-object.sh
We're expecting a pointer, not a value. This works in daemon mode but not in offline mode.
fixes #5458
---
see: https://github.com/ipfs/go-ipfs-cmds/issues/120
=> fix output of object command

test/sharness/t0040-add-and-cat.sh
=> add rabin min error test

core/coreapi/key.go, core/coreapi/key_test.go
Renaming a key to the same name always succeeds regardless of force flag. Fixed bug whereby renaming to same name (with --force) would delete the key by accident
fixed #5450
License: MIT
Signed-off-by: Rob Deutsch <rdeutschob@gmail.com>
=> fix behaviour of key rename to same name

pin/gc/gc.go
License: MIT
Fixes: https://github.com/ipfs/go-ipfs/issues/4593
=> fix(pin): goroutine leaks

core/coreapi/name_test.go
It was too small causing tests to fail occasionally, like in https://github.com/ipfs/go-ipfs/pull/5472
=> coreapi name: Increase test swarm size

core/commands/name/ipns.go, core/commands/name/publish.go, test/sharness/t0100-name.sh, test/sharness/t0110-gateway.sh, test/sharness/t0160-resolve.sh
=> error when publishing ipns records without a running daemon

core/bootstrap.go
We only need to warn the user if we *can't* connect to the network.
=> make warnings on no bootstrap peers less noisy

core/commands/resolve.go, core/commands/root.go, core/coreapi/interface/options/name.go, core/coreapi/name.go, core/coreapi/path.go, core/coreapi/unixfs.go, test/sharness/t0260-sharding.sh
(This is assuming we want to make `ipfs resolve` operate on unixfs paths instead of ipld)
Fixes https://github.com/ipfs/go-ipfs/issues/5270#issuecomment-422112136
=> resolve: use unixfs ResolveOnce

fuse/mount/mount.go, fuse/node/mount_test.go
Fuse unmount test uses ipfs instead of ipns, because offline nodes dont actually mount ipns.
Factored out GOOS-aware function to determine unmount command in fuse/mount.
fixed #5475
License: MIT
Signed-off-by: Rob Deutsch <rdeutschob@gmail.com>
=> fix fuse unmount test

cmd/ipfs/Rules.mk
This somehow slipped in https://github.com/ipfs/go-ipfs/pull/5277
Found in https://github.com/ipfs/go-ipfs/pull/5503
=> mk: embed CurrentCommit in the right place

cmd/ipfs/daemon.go, test/sharness/t0060-daemon.sh
License: MIT
Fixes: https://github.com/ipfs/go-ipfs/issues/5498
=> feat(daemon): print version

core/commands/files.go, core/commands/ls.go, core/commands/unixfs/ls.go
License: MIT
Fixes: https://github.com/ipfs/go-ipfs/issues/5217
=> fix(unixfs): issue #5217 (Avoid use of `pb.Data`)

core/commands/name/publish.go, test/sharness/t0100-name.sh
**Note:** I would thoroughly appreciate if someone could do a real live test on their machine. My IPFS node is a tad broken at the moment.
**Motivation:** [This post on reddit](https://www.reddit.com/r/ipfs/comments/9h4wsn/is_there_a_way_to_get_ipfs_name_publish_to_output/
). 
**Details:**
Added a quieter/Q option to 'name publish' that, consistent with 'add', only outputs the value that was published.
=> add quieter option to name publish

cmd/ipfs/daemon.go, cmd/ipfs/util/ulimit.go, cmd/ipfs/util/ulimit_freebsd.go, cmd/ipfs/util/ulimit_test.go, cmd/ipfs/util/ulimit_unix.go, mk/util.mk
Raising FD limits was erroring when the OS's max was at the maximum signed integer value. Switched the code to using uint64 instead of int64.
Could someone please review, in particular, the FreeBSD parts? Integer checks are not my forte, and I don't have a FreeBSD machine to test on.
fixed #5495
Bonus: The `ManageFdLimit()` function contained a `fmt.Print` statement. That's really annoying because it was printing during tests. I've changed the `ManageFdLimit()` function so that it returns the new limit, and the calling function can do the fmt.Print statement (if it wishes).
=> fixed tests of raised fd limits

cmd/ipfs/daemon.go, core/corehttp/mutex_profile.go, test/sharness/t0110-gateway.sh
Allows to dynamically change the MutexProfileFraction to enable and
disable mutex profiling. It should be very useful for detecting
deadlocks, lock contention and general concurrency problems.
How to use:
To enable: `curl -X POST -v 'localhost:5001/debug/pprof-mutex/?fraction=10`
To disable: `curl -X POST -v 'localhost:5001/debug/pprof-mutex/?fraction=0'`
Fraction defines which fraction of events will be profiled. Higher it is
the lower performance impact but less reliable the result.
To fetch the result use:
`go tool pprof $PATH_TO_IPFS_BIN http://localhost:5001/debug/pprof/mutex`
License: MIT
=> pprof: create HTTP endpoint for setting MutexProfileFraction

pin/pin.go
Fix #5376 by allowing content to be fetched concurrently when pinning multiple hashes.
Simply release the pinner lock when fetching content and re-lock it immediately afterwards.
- Maybe this implementation is naive, but it appears to do the trick. Let me know what I've missed.
- @Stebalien mentioned using `GCLocker`, but it appears that gc locking is managed here: https://github.com/ipfs/go-ipfs/blob/def80817224835a4965849bd3ac1a1a8da458601/core/commands/pin.go#L71 Which, I think, can be left alone for now.
- This implementation allows for the following scenario:
```sh
ipfs dag put <<<'{"link": {"/": "QmdZmoS1b1jp9vL5vgTyebEYUVH6zjd6erhp3fpqV1Zktx"}}'
ipfs pin add zdpuAsWv1LNwtxvFB3iTQjtwDLxPxRaa3WeE4i6BoDuKDy4gf &
echo "thing" | ipfs add
```
- This implementation still blocks gc:
```sh …
```
=> Fix inability to pin two things at once

.dockerignore
The Docker client was blindly copying binaries from the bin/ directory to the Docker server, and then the Docker server would just try and run them blindly - causing an error.
It's better to not upload these binaries, and let the Docker server itself fetch the binaries that it wants.
Fixes #5038
=> added binary executable files to .dockerignore

docs/debug-guide.md
This would've been valuable to me while investigating #5530.
I discovered that more debug commands are also available, but I don't know enough about them to add them myself (e.g. `debug/pprof-mutex`, `debug/metrics/prometheus`).
=> debug-guide.md added memory statistics command

core/commands/add.go, core/coreunix/add.go, core/coreunix/add_test.go
=> add pin lock in AddallPin function

cmd/ipfs/ipfs.go, core/commands/cid.go, core/commands/commands.go, core/commands/commands_test.go, core/commands/filestore.go, core/commands/root.go, test/sharness/t0290-cid.sh
Implements #5357.
~Still needs tests.~
Closes #5229. Closes #5357.
=> Provide new "cid" sub-command.

core/commands/ls.go
Improve bandwidth usage for LS by adding Sessions
This is simply the code by @whyrusleeping referenced here -- https://github.com/ipfs/go-ipfs/compare/feat/ls-session?expand=1 - in #4979 . Regardless of the ultimate solution we end up using for HAMT directory speedup (#4908 ), is there any reason this can't be merged now? This seems like a tangible improvement, if not in speed at least in bandwidth usage
=> Add sessions when fetching MerkleDAG in LS

dagutils/diff.go, test/sharness/t0052-object-diff.sh
License: MIT
Fixes https://github.com/ipfs/go-ipfs/issues/5470
=> fix(object): add support for raw leaves in object diff

core/commands/name/ipns.go, core/commands/name/publish.go, core/coreapi/interface/options/name.go, core/coreapi/key.go, core/coreapi/name.go
Related to https://github.com/ipfs/go-ipfs/issues/5491
=> Switch name publish/resolve to coreapi

core/commands/files.go, test/sharness/t0250-files-api.sh
Refer to: https://github.com/ipfs/go-ipfs/issues/5538#issuecomment-426312110, https://github.com/ipfs/go-ipfs/issues/5554
License: MIT
=> feat(command): add force flag for files rm

core/commands/p2p.go, test/sharness/t0180-p2p.sh
=> add dns support in`ipfs p2p forward` and refactor code

plugin/datastore.go, plugin/loader/initializer.go, repo/fsrepo/datastores.go
This will make it a little bit easier to write your own datastores for ipfs (at least on platforms that go supports plugins >.>).
The next step is making it easier to initialize ipfs with a given datastore config
=> Add support for datastore plugins

core/commands/active.go, core/commands/bitswap.go, core/commands/block.go, core/commands/bootstrap.go, core/commands/cat.go, core/commands/cid.go, core/commands/config.go, core/commands/dht.go, core/commands/dns.go, core/commands/files.go, core/commands/filestore.go, core/commands/get.go, core/commands/id.go, core/commands/keystore.go, core/commands/ls.go, core/commands/p2p.go, core/commands/pin.go, core/commands/ping.go, core/commands/pubsub.go, core/commands/refs.go, core/commands/repo.go, core/commands/resolve.go, core/commands/stat.go, core/commands/swarm.go, core/commands/version.go, test/sharness/t0600-issues-and-regressions-online.sh
=> add offline id test #4978 and refactor command code

core/commands/pubsub.go, core/coreapi/coreapi.go, core/coreapi/interface/coreapi.go, core/coreapi/interface/errors.go, core/coreapi/interface/options/pubsub.go, core/coreapi/interface/pubsub.go, core/coreapi/pubsub.go, core/coreapi/pubsub_test.go, core/coreapi/unixfs_test.go
Based on https://github.com/ipfs/go-ipfs/pull/4802
Replaces https://github.com/ipfs/go-ipfs/pull/4774
TODOs:
=> coreapi: PubSub API

.travis.yml, Dockerfile, Dockerfile.fast, bin/Rules.mk, ci/Dockerfile.buildenv, ci/Jenkinsfile, circle.yml, cmd/ipfs/daemon.go, mk/golang.mk, package.json
Go 1.11 changes the output of `go fmt` slightly so we either need to
all *downgrade* or *upgrade*. Let's upgrade.
=> switch to go 1.11

bin/maketarball.sh
Just stop using realpath, should not matter.
Resolves #5064
License: MIT
=> fix: maketarball.sh for OSX

test/sharness/lib/test-lib.sh
`res=$?` erases `$?` (sets it to 0)
fixes #5577
=> test the correct return value

package.json
Using version 99 for these is going to cause *major* semver issues.
=> downgrade iptb to a 1.3 patch release

core/commands/files.go, test/sharness/t0250-files-api.sh
Fixes: https://github.com/ipfs/go-ipfs/issues/5601
License: MIT
=> fix(files): add slash for dir

core/commands/p2p.go, p2p/local.go, test/sharness/t0180-p2p.sh
Fixes: https://github.com/ipfs/go-ipfs/issues/5523
License: MIT
=> fix(p2p): issue #5523

Dockerfile
this pr addresses #5610. i have no clue what websocket transfer is in this context, that part may be very wrong.
=> Dockerfile: Specifies comments on exposed ports

core/commands/config.go, package.json, test/sharness/t0021-config.sh
=> feat: add dry-run flag for config profile apply command

core/commands/root.go
=> refact(command): replace option name with const string

core/commands/swarm.go
We used to have to do this as these addresses had `/ipfs/QmId` appended at the *transport* layer. However, we were able to remove this with the transport refactor so we can now remove this check.
fixes https://github.com/libp2p/specs/issues/72
=> remove p2p-circuit addr hack in ipfs swarm peers

core/commands/object/patch.go
This improves the docs and semantics of rm-link to be consistent with add-link, clarifying that you should specify the link _name_ as the thing to remove. I found the current docs, `<link>` ambiguous as to whether it was the name or the hash. 
```
USAGE
ipfs object patch - Create a new merkledag object based on an existing one.
SYNOPSIS
ipfs object patch
DESCRIPTION
'ipfs object patch <root> <cmd> <args>' is a plumbing command used to
build custom DAG objects. It mutates objects, creating new objects as a
result. This is the Merkle-DAG version of modifying an object.
SUBCOMMANDS
ipfs object patch add-link <root> <name> <ref> - Add a link to a given object.
ipfs object patch append-data <root> <data>    - Append data to the data segment of a dag node.
ipfs object patch rm-link <root> …
```
=> object patch rm-link: change arg from 'link' to 'name'

core/commands/dns.go, core/commands/id.go, core/commands/root.go, core/commands/tar.go, core/commands/version.go
=> refactor(cmds): use new cmds lib in version, tar and dns

core/coreapi/name_test.go, namesys/namesys.go
This got broken in the async namesys refactor, somehow there were no tests to catch this.
=> namesys: properly attach path in name.Resolve

core/commands/ping.go, core/commands/root.go
=> commands/ping: use new cmds lib

core/commands/ping.go, test/sharness/t0041-ping.sh
followup to the ping -> cmds 2.0 change
1. Use emit directly.
2. Abort immediately when the context is canceled (no need to wait a second for the sleep to elapse).
3. Ping once a second instead of once a second +TTL (to be more like ping)
4. Simplify ParsePeerParam
=> cleanup the ping command

core/commands/dag/dag.go, core/commands/dns.go, core/commands/pubsub.go, core/commands/stat.go, core/commands/tar.go, core/commands/version.go
* Always check errors returned by emit. Otherwise, we may not notice when the client goes away.
* Make sure to use EmitOnce instead of Emit when appropriate. Otherwise, we break javascript.
(thanks Magik6k for finding this before we cut the release...)
=> commands: fix a bunch of tiny commands-lib issues

core/commands/ping.go, core/core.go
We now configure the ping service in go-libp2p by default. Instead of creating a new (duplicate) ping service, we can now just (a) rely on this to handle incoming pings and (b) use the "Ping" function to ping peers.
TL;DR: don't register two ping services.
=> ping: switch to the ping service enabled in the libp2p constructor

core/coreapi/interface/errors.go
JavaScript expects this to be "this dag node is a directory". I'm almost of a mind to say "don't parse errors" but, well, we don't give any better alternatives.
=> coreapi: fix errisdir

core/commands/resolve.go, test/sharness/t0160-resolve.sh
This isn't the *correct* fix but it (mostly) restores the previous behavior.
Note 1: It *also* fixes resolution of `/ipld` paths by avoiding `path.FromCid`.
Note 2: This does not preserve the error. That was a DagCBOR specific error that has nothing to do with the issue.
=> error on resolving non-terminal paths

core/commands/log.go
Apparently, js-ipfs-api expects this. Really, I'm not sure why js-ipfs-api even cares about this endpoint but that's a different issue.
The real fix is to change back to ndjson in go-log but that would force us to update every package (not good when we're trying to push out a release like this).
=> re-format log output as ndjson

cmd/ipfs/daemon.go, core/corehttp/metrics.go, package.json
=> fix prometheus concurrent map write bug

CHANGELOG.md, version.go
Not quite ready yet but might as well get this started.
I'm not going to maintain a changelog between these RCs (unless someone really objects). It's probably more work than it's worth.
=> prepare for RC2

core/commands/cmdenv/env.go
=> cmds/env: add a config path helper

core/commands/files.go
=> commands/files: use new cmds

core/commands/object/diff.go, core/commands/object/object.go, core/commands/object/patch.go, core/commands/root.go
=> commands/object: use new cmds

core/commands/dht.go, core/commands/root.go
=> commands/dht: use new cmds lib

core/commands/p2p.go, core/commands/root.go
=> commands/p2p: use new cmds lib

core/commands/repo.go
=> enhance(cmd/verify): add goroutine count to improve verify speed

package.json, test/bin/Rules.mk, test/dependencies/iptb/iptb.go, test/sharness/lib/iptb-lib.sh, test/sharness/t0030-mount.sh, test/sharness/t0031-mount-publish.sh, test/sharness/t0041-ping.sh, test/sharness/t0101-iptb-name.sh, test/sharness/t0121-bootstrap-iptb.sh, test/sharness/t0125-twonode.sh, test/sharness/t0130-multinode.sh, test/sharness/t0131-multinode-client-routing.sh, test/sharness/t0140-swarm.sh, test/sharness/t0170-dht.sh, test/sharness/t0175-reprovider.sh, test/sharness/t0180-p2p.sh, test/sharness/t0180-pubsub-gossipsub.sh, test/sharness/t0180-pubsub.sh, test/sharness/t0181-private-network.sh, test/sharness/t0182-circuit-relay.sh, test/sharness/t0183-namesys-pubsub.sh, test/sharness/t0190-quic-ping.sh, test/sharness/t0240-republisher.sh, test/sharness/t0276-cidv0v1.sh
This contains a "unpublished" version of iptb v2. Just running tests in CI to make sure everything works (mostly around mount).
Related to #5521
=> Update IPTB test

cmd/ipfs/daemon.go, test/sharness/t0060-daemon.sh
fixes #5727 
License: MIT
Signed-off-by: Daniel Grossmann-Kavanagh <me@danielgk.com>
=> output link to WebUI on daemon startup

bin/maketarball.sh
* don't write the tarball in the directory we're taring (makes tar unhappy)
* fix permissions
* fix gopath
(for the purposes of the release, I'm pretending this made it into 0.4.18)
=> fix the maketarball script

core/commands/repo.go
=> refact(cmd/repo): repo's sub cmds uses new cmd lib

CHANGELOG.md
A few links to docs in this repo needed "blob/master/" in order to work properly.
=> Fix broken links

core/commands/filestore.go
=> commands/filestore: use new cmds lib

core/commands/active.go, core/commands/config.go, core/commands/diag.go, core/commands/log.go, core/commands/mount_nofuse.go, core/commands/mount_unix.go, core/commands/mount_windows.go, core/commands/root.go, core/commands/sysdiag.go
Use new cmds lib in diag, config, mount, log command.
=> refactor(cmds): use new cmds

mk/golang.mk
We want to explicitly pass these where we need them.
fixes #5733
=> unexport GOFLAGS

core/commands/bootstrap.go, core/commands/root.go
=> commands/boostrap: use new cmds

core/commands/pin.go, core/commands/root.go
=> commands/pin: use new cmds lib

core/commands/filestore.go, core/commands/refs.go, core/commands/root.go
=> commands/refs: use new cmds

core/commands/external.go, core/commands/root.go
=> cmds/update: use new cmds lib

ISSUE_TEMPLATE.md
The issue template is long. We need to make this *really* obvious*.
=> ISSUE_TEMPLATE: move the support question comment to the very top

core/bootstrap.go
When used in private network mode with `Bootstrap` set to `[]`, the daemon currently spits out the following message ever 30 seconds:
```
ERROR       core: no bootstrap nodes configured: go-ipfs may have difficulty connecting to the network bootstrap.go:144
```
While it is good to mention, I see two issues with this:
* In regular environments, running the daemon with no bootstrap nodes will in fact render it unusable, so there should be an error at daemon start time instead of a repetitive message
* For private network setups where nodes discover themselves via MDNS, this message is unnecessary.
This PR changes both the above, with one patch for each of them.
=> Suppress bootstrap error

core/corehttp/gateway_handler.go
Was looking through the http handler code. When we figured out this CloseNotify stuff initially, I remember being super excited. That was quite some time ago, things have gotten better since then. The request.Context() now will cancel when the client leaves, or when the http server is shutdown, which is exactly what we want here. 
This approach also frees us from having to run another extra goroutine. Yay.
License: MIT
=> Switch to using request.Context()

core/commands/ls.go, core/commands/root.go, test/sharness/t0045-ls.sh
Adds the option to stream results from ls -- so that large directories (particularly HAMT dirs) start returning data immediately instead of waiting for the whole DAG to be walked
Fixes #5600 
Requires https://github.com/ipfs/go-unixfs/pull/39
- Update LS Command to use go-ipld-cmds library
- Update LS Command with --stream option
- Consume EnumLinksAsync in Ls command instead of synchronous Links method
- Support breaking up of command output. Instead of LsObject having to be a full directory, it can  represent the beginning of a directory, one more more links in a directory, or the end of the directory - so that outputs can be CAT together to produce the same combined output
- Not mergable until go-unixfs is updated for referenced PR
- What is our preferred method for unit testing …
=> Add --stream option to `ls` command

README.md, bin/container_daemon
Added support for an `IPFS_PROFILE` environment variable in the `bin/container_daemon`. The variable, if present, is used with `ipfs init` to add a `--profile=$IPFS_PROFILE` argument which will apply to chosen profile to the newly created configuration.
This is useful for automatic IPFS deployments in hosted container environments, e.g. Kubernetes. In such situations, it's essential to use `--profile=server`.
Pull request helm/charts#7746 requires this change in order to add the `profile` configurable parameter to the IPFS Helm chart.
=> docker: allow IPFS_PROFILE to choose the profile for `ipfs init`

docs/datastores.md, plugin/plugins/badgerds/badgerds.go
Depends on https://github.com/ipfs/go-ipfs-config/pull/20 (merged).
Closes: #5275.
=> badger: add truncate flag

core/coreapi/pin.go
=> coreapi/pin: Use CID's directly in maps instead of converting to string

core/commands/p2p.go, p2p/remote.go, test/sharness/t0180-p2p.sh
Was suggested on IRC, when set it basically passes `QmPeerid\n` of connecting peer into listener stream.
(works but needs tests)
=> p2p: report-peer-id option for listen

README.md
It appears that Go version 1.11 is actually required.
License: MIT
Signed-off-by: Matt Joiner <anacrolix@gmail.com>
=> README: Update required Go version

docs/config.md
Make it clear where the config is stored in the IPFS_PATH.
License: MIT
Signed-off-by: Matt Joiner <anacrolix@gmail.com>
=> docs: Improve config documentation

Dockerfile, Dockerfile.fast
As of now,
$ docker pull ipfs/go-ipfs
Using default tag: latest
latest: Pulling from ipfs/go-ipfs
Digest: sha256:31cc5713ef3e3e81bf868cbb56c19de2d15d661743d8b6077804dee26e929ac5
Status: Image is up to date for ipfs/go-ipfs:latest
ipfs daemon will start as root user:
$ docker run --rm --entrypoint=/bin/sh ipfs/go-ipfs -c whoami
root
but later on will drop priviledges:
$ docker logs ipfs/go-ipfs |head -n 1
Changing user to ipfs
With this change applied, ipfs daemon starts as ipfs user right from
the begining:
$ docker run --rm --entrypoint=/bin/sh ipfs/go-ipfs -c whoami
ipfs
License: MIT
Signed-off-by: Mykola Nikishov <mn@mn.com.ua>
=> Really run as non-root user in docker container

core/commands/urlstore.go, test/sharness/t0272-urlstore.sh
=> add pinning support to the urlstore

cmd/ipfs/init.go, core/builder.go, core/commands/cat.go, core/commands/id.go, core/commands/resolve.go, core/core.go, core/coreapi/name.go, core/coreapi/unixfs_test.go, fuse/ipns/ipns_test.go, fuse/node/mount_test.go
Loading this at the last minute means we need a bunch of special cases in *every* command that needs routing, namesys, or even the public key.
If we ever have a case where we don't want to do this, we can add an option to the (eventual) IPFS constructor. Handling this up-front is going to be significantly less error prone.
Motivation: https://github.com/ipfs/go-ipfs/pull/5825/files#diff-fe35ea64d478c4f3fb767a3f618e5d01R863
=> startup: always load the private key

bin/maketarball.sh
Unfortunately, `readlink -f` doesn't work on macos. This change *manually* converts a relative path to an absolute path.
=> make: fix building source tarball on macos

cmd/ipfs/main.go, cmd/ipfs/util/signal.go, cmd/ipfs/util/signal_wasm.go
Based on https://github.com/ipfs/go-ipfs/pull/5871
For https://github.com/ipfs/go-ipfs/issues/5694
=>  main: move InterruptHandler to util 

docs/plugins.md
* Flesh out build documentation.
* Add datastore plugins to plugin list.
* Link to example plugin.
* Add a TOC.
=> docs: flesh out plugin documentation

core/commands/add.go, core/commands/tar.go, core/coreapi/interface/path.go, core/coreapi/interface/unixfs.go, core/coreapi/unixfs_test.go, core/coreunix/add.go, core/coreunix/add_test.go
CoreAPI shouldn't have to touch string paths because we don't want it to have to deal with CID encoding. Related to https://github.com/ipfs/go-ipfs/pull/5789
=> coreapi/unixfs: Use path instead of raw hash in AddEvent

core/coreapi/interface/tests/api.go, core/coreapi/interface/tests/block.go, core/coreapi/interface/tests/dag.go, core/coreapi/interface/tests/dht.go, core/coreapi/interface/tests/key.go, core/coreapi/interface/tests/name.go, core/coreapi/interface/tests/object.go, core/coreapi/interface/tests/path.go, core/coreapi/interface/tests/pin.go, core/coreapi/interface/tests/pubsub.go, core/coreapi/interface/tests/unixfs.go
It makes it much easier to start implementing `go-ipfs-http-api`
=> CoreAPI: Don't panic when testing incomplete implementions

docs/experimental-features.md
Fix for the #5746. Switch to Filestore need to restart the ipfs node.
License: MIT
Signed-off-by: Bamvor Zhang <jian.zhang@ipfsbit.com>
=> Improve the Filestore document

core/commands/ls.go, core/coreapi/interface/tests/unixfs.go, test/sharness/t0045-ls.sh, test/sharness/t0051-object.sh, test/sharness/t0260-sharding.sh
Need this for https://github.com/ipfs/go-ipfs-http-client/pull/1 to implement fast `api.Unixfs().Get()`.
=> ls: Report real file size

core/commands/object/object.go
=> refact(cmd/object): change option string to const

core/coreapi/interface/tests/dag.go, core/coreapi/interface/tests/path.go, core/coreapi/interface/tests/unixfs.go
With this https://github.com/ipfs/go-ipfs-http-client/pull/1 is passing all interface tests!
=> coreapi: few more error check fixes

README.md, docs/add-code-flow.md
License: MIT
Signed-off-by: Nitish Malhotra <nitish.malhotra@gmail.com>
=> docs/code-flow : Add code flow documentation for add cmd.

core/commands/files.go
We need to call `FlushPath` as `Flush` doesn't call `WaitPub` internally. The correct fix is to rework MFS such that Flush actually flushes but that's a larger project.
Fixes https://github.com/ipfs/go-ipfs/pull/5925#issuecomment-456252134 although I'm not sure what changed. In a followup PR, once https://github.com/ipfs/go-mfs/pull/58 is merged, we can fix go-ipfs to run the teardown function *before* it cancels the context.
=> mfs: make sure to flush after mv and chcid

core/commands/name/publish.go
=> clarification the document of --resolve flag in name.publish

namesys/dns.go, namesys/dns_test.go
This change **halves the number of DNS queries required** to lookup DNSLink information for "example.com" by forcing the use of a FQDN (e.g. `example.com.`).
* example.com
* example.com.local (removed)
* _dnslink.example.com
* _dnslink.example.com.local (removed)
Where .local is the local system's organization/domain name.
License: MIT
Signed-off-by: Daniel Aleksandersen
=> Only perform DNSLink lookups on fully qualified domain names (FQDN)

cmd/ipfs/init.go
=> refact(cmd/init): change string option to const

core/coreapi/interface/tests/unixfs.go
This tests dagreader in `go-unixfs/io`, and it turns out it's currently broken in 2 ways:
* <s>When seeking near end of the file and the reading into buffer larger than the file, `Read` seems to read the data, but incorrectly returns io.EOF</s> (this is valid behaviour, just not consistent across readers)
* When seeking with `io.SeekEnd`, DagReader incorrectly inverts the offset.
=> coreapi: add some seeker tests

cmd/ipfs/daemon.go, cmd/ipfs/main.go, docs/plugins.md, plugin/daemon.go, plugin/loader/loader.go, repo/fsrepo/config_test.go
=> plugin: add a daemon plugin with access to the CoreAPI

core/commands/name/publish.go
> -k,            --key      string - Name of the key to be used or a valid PeerID, as listed by 'ipfs key list -l'. Default: Default: self..
=> docs: duplicate default helptext in `name publish`

core/commands/ls.go, core/coreapi/interface/options/unixfs.go, core/coreapi/interface/tests/unixfs.go, core/coreapi/interface/unixfs.go, core/coreapi/unixfs.go
(Last) Part of https://github.com/ipfs/go-ipfs/issues/5929
=> Port `ipfs ls` to CoreAPI

core/commands/block.go, core/coreapi/block.go, core/coreapi/interface/options/block.go, core/coreapi/interface/tests/block.go
Needed in ipfs/go-ipfs-http-api#1
=> block put --pin

core/commands/name/publish.go, namesys/namesys.go, namesys/publisher.go
Also refactoring DefaultRecordTTL to DefaultRecordEOL as it represents default value for `lifetime` and not `ttl`.
=> Improve "name publish" ttl option documentation

docs/experimental-features.md
link was broken due to `/` in title. using `--` fixes.
=> fix HAMT bookmark ln

core/commands/resolve.go, test/sharness/t0160-resolve.sh
fixes #5703
This is a *breaking change*. We *used* to return an error if the path didn't end at a CID but, IMO, that's incorrect. We *should* allow resolution of paths that stop in the middle of an object.
=> fix: return the shortest, completely resolved path in the resolve command

core/corehttp/webui.go
Reverts ipfs/go-ipfs#6018
Opt-out analytics of any form is not OK.
=> Revert "chore: update to Web UI 2.4.0"

cmd/ipfs/dist/install.sh
When trying out the latest rc, i used the `./install.sh`
It hung, with no output. I removed the 2> /dev/null and
it turned out mv was waiting for user input to confirm
the change of file permssions from 555 to 755.
```console
override r-xr-xr-x  oli/staff for /usr/local/bin/./ipfs? (y/n [n])
```
This PR removes piping the output from mv to /dev/null
as it seems like the safest fix.
An alternative would be to just add -f but i've err'd
on the side of caution.
If also tweaked the second condition based on the
recommendations of shellcheck
see: https://github.com/koalaman/shellcheck/wiki/SC2166
License: MIT
=> fix: show interactive output from install.sh

.gx/lastpubver, CHANGELOG.md, package.json, version.go
Changes:
* Fix some goroutine leaks in bitswap.
* Fix never-terminating DHT queries.
* Fix an mplex deadlock.
* Fix two cmds issues around syncing stdout/stderr. 
* Better output from install.sh
* Reduced allocation in bitswap.
=> Release 0.4.19-rc2

.gx/lastpubver, CHANGELOG.md, package.json, version.go
I don't anticipate any other changes. I'll merge this and cut the release
tomorrow if nothing happens between now and then.
=> Release 0.4.19

Dockerfile, Dockerfile.fast
Reverts ipfs/go-ipfs#5048 (see discussion there).
=> Revert "Really run as non-root user in docker container"

core/commands/log.go, core/commands/root.go
Improved CLI help pages with updated synopsis and information about logging support in IPFS.
=> Improve CLI help pages

core/commands/bitswap.go
Fixed: https://github.com/ipfs/go-ipfs/issues/5763
License: MIT
=> feat/cmds: hide peers info default in bitswap stat

ci/Jenkinsfile, core/corehttp/gateway_test.go, mk/golang.mk, test/bin/Rules.mk
To test for stuff like https://github.com/ipfs/go-ipfs/issues/5367
There is also one test fail in gateway test code:
```
core/corehttp/gateway_test.go:42:9: constant 18446744073709551615 overflows uint
```
=> ci: test on 32bit os

cmd/ipfs/daemon.go, cmd/ipfs/init.go, cmd/ipfs/main.go, cmd/ipfswatch/main.go, commands/context.go, core/builder.go, core/commands/bitswap.go, core/commands/dht.go, core/commands/external.go, core/commands/id.go, core/commands/mount_unix.go, core/commands/p2p.go, core/commands/ping.go, core/commands/shutdown.go, core/commands/stat.go, core/commands/sysdiag.go, core/core.go, core/coreapi/coreapi.go, core/corehttp/gateway_handler.go, core/mock/mock.go, fuse/node/mount_unix.go
This could still be cleaner but hopefully it's a bit less cryptic.
=> cleanup daemon online logic

core/core.go
This _should_ be variable. But, until we can get around to fixing that, 8MiB means a max speed of 40MiB given a 200ms RTT. The current limit gives us a 2.5MiB max rate which _really_ hurts.
Note: We now auto-shrink this buffer as needed (using a buffer pool) so this
shouldn't leak memory.
=> yamux: increase yamux window size to 8MiB.

mk/golang.mk
mod.sum generation had a fix in this version which probably is the
reason for #6056
License: MIT
=> go: require Golang 1.11.4

coverage/Rules.mk, coverage/tools.go, go.mod, mk/golang.mk, test/bin/Rules.mk, test/dependencies/dependencies.go
Fixes https://github.com/ipfs/go-ipfs/issues/6039#issuecomment-470273864
=> mk: fix make install by not setting GOBIN

mk/git.mk
With this command we will get hash information as well as information if
build was made using uncommited files.
The difference is `0.4.20-dev-c8c0c48e2` vs `0.4.20-dev-c8c0c48e2-dirty`.
=> mk: change git-hash command to include information about modifications

core/commands/swarm.go
Fixes: https://github.com/ipfs/go-ipfs/issues/5522
License: MIT
=> fix(swarm): add dnsaddr support in swarm connect

core/commands/dns.go, core/commands/name/ipns.go, core/commands/resolve.go, test/sharness/t0160-resolve.sh
1. Recurse by default. This is what users expect and it should only un-break
applications. We have a default limit of 32.
2. When recursion is turned off, return the partial result. Otherwise, these
commands are pretty much useless
fixes #5635
fixes #5585
fixes #4181
fixes #4293
fixes #6086
=> resolve: fix recursion

core/builder.go, core/core.go, core/coreapi/coreapi.go, core/coreapi/pin.go, core/coreapi/provider.go, core/coreapi/unixfs.go, go.mod, provider/offline.go, provider/provider.go, provider/provider_test.go, provider/queue.go, provider/queue_test.go
Provide root node immediately when `ipfs add <cid>` and `ipfs pin add <cid>`.
This PR introduces part of the new provider subsystem from the rest of the ongoing provider work so it's more extensive than it might otherwise have been. This seemed like a good way to merge some of that work and begin using it. And he work to get this PR mergeable will get folded back into #5870 
Addresses: https://github.com/ipfs/go-ipfs/issues/6067
=> Provide root node immediately on add and pin add

core/commands/repo.go
Now use go-humanize when `--human` flag is provided.
https://github.com/ipfs/go-ipfs/issues/6103
=> Command repo stat: improve human flag behavior

fuse/node/mount_darwin.go
The command `ipfs --json config DontCheckOSXFUSE true` currently mentioned in the OSXFUSE error message returns `Error: unknown option "json"`.
This PR reorders the arguments in the error message, changes the `--json` option to probably more appropriate `--bool`, and adds the same option to all related error messages, as without any option the command returns `Error: failed to set config value: wrong config type, expected bool (maybe use --json?)`.
=> fix config options in osxfuse error messages

pin/gc/gc.go
Events:
1. User triggers a GC.
2. User aborts the GC.
3. We fail to delete a block when the output channel is already full.
This is really unlikely to happen in practice but it's still incorrect.
Could be related to #6107.
=> gc: fix a potential deadlock

test/sharness/t0080-repo.sh
I have not attempted to do an universal function to check output to keep things simple. But current result seems to me verbose. 
https://github.com/ipfs/go-ipfs/issues/6110
=> command repo stat: add human flag tests to t0080-repo.sh

ISSUE_TEMPLATE.md
Referenced file was removed in https://github.com/ipfs/go-ipfs/commit/ab33445190c3fac5f7f639c1f7e0f256c506cc1e when it was merged with the issue template.
=> Remove dead link from ISSUE_TEMPLATE.md

go.mod, go.sum, provider/queue.go, provider/queue_test.go
Query for provider head/tail per Steven's suggestion here: https://github.com/ipfs/go-ipfs/pull/6068#discussion_r266291056
=> Query for provider head/tail

cmd/ipfs/util/signal.go
If we get a signal while shutting down, we could end up sending on a closed channel.
=> interrupt: fix send on closed

docs/experimental-features.md
I was confused by ipfs-ds-convert returning command not found and
attempted to "ipfs ds-convert" and similar commands in case it was
typoed until I found out it was in a separate repo.
=> docs/experimental-features.md: link to ipfs-ds-convert

core/coreapi/unixfs.go, core/coreunix/add.go, test/sharness/t0270-filestore.sh, test/sharness/t0272-urlstore.sh
* Check dagservice commit errors on add.
* Allow `ipfs add --nocopy URL` without enabling the filestore.
=> fix add error handling

CODEOWNERS
IMO, this is just confusing new contributors because they always see @Kubuxu tagged for review but that doesn't actually mean anyone's going to review the PR.
It _also_ means _I_ can't ask @Kubuxu to review the PR.
=> chore: remove CODEOWNERS

core/coreapi/swarm.go
This doesn't _stop_ us from cutting these connections but indicates that there's some hidden usefulness to them.
fixes #6164
=> feat(coreapi): tag all explicit connect requests in the connection manager

cmd/ipfs/daemon.go, go.mod, test/sharness/t0060-daemon.sh
=> fix two bugs where the repo may not properly be closed

.circleci/config.yml
The `-O` option causes make to print out all the output from a single target all at once. This will make the test log readable again.
=> ci: avoid interleaving output from different sharness tests

.circleci/config.yml, coverage/main/main.go, go.mod, mk/golang.mk
Got some errors in version deps PR from updating to Go 1.12
Creating this PR to track it
=> Switch to Go 1.12

core/commands/commands_test.go, core/commands/version.go, test/sharness/t0010-basic-commands.sh, test/sharness/t0060-daemon.sh
=> feat: add version deps command [modversion]

core/commands/commands_test.go
Because steb did a bad thing and pushed to master. Not sure _why_ my pre-commit hook didn't catch this but...
=> test: remove version/deps from ro commands test

core/commands/object/object.go, test/sharness/t0051-object.sh
License: MIT
Signed-off-by: Eric Wu <myself659@163.com>
```
root@IA:~/ipfs-demo# ipfs object stat QmchMzwpT2c8qWn8JL3bfjTm3hFa45QDRe4DAUBTseitCD
NumLinks: 4
BlockSize: 200
LinksSize: 178
DataSize: 22
CumulativeSize: 947747
```
```
root@IA:~/ipfs-demo# ipfs object stat QmchMzwpT2c8qWn8JL3bfjTm3hFa45QDRe4DAUBTseitCD
NumLinks:       4
BlockSize:      200
LinksSize:      178
DataSize:       22
CumulativeSize: 947747
```
=> align output for the command ipfs object stat

bin/container_daemon
This finally removes support for the implicit daemon argument and unlocks full access to all subcommands.
=> Dockerfile: Remove 2 year old deprecation warning

core/core.go, provider/offline.go, provider/provider.go, provider/queue.go
This PR exists for me to trouble shoot some CI issues. Disregard.
=> Fix level db panic

go.mod, go.sum
* Update go-libp2p for some identify optimizations.
* Update go-libp2p-circuit for some allocation optimizations.
* Update go-ds-leveldb for some query performance improvements.
* Update go-libp2p-kbucket to fix a really stupid bug.
=> dep: update libp2p, circuit, leveldb, kbucket

go.mod, go.sum
Fixes a panic in identify's observed address handling.
https://github.com/libp2p/go-libp2p/pull/586
=> dep: update go-libp2p

.gitattributes
1. Default to LF line endings. Windows users should use a real text editor when coding.
2. Allow markdown/license files to be autoconverted so they're readable everywhere.
fixes #6195
=> gitattributes: default to LF

go.mod, go.sum
* go-bitswap: periodically resend wantlists to work around some connection state races.
* go-libp2p-circuit: improve allocations and avoid dialing new peers.
License: MIT
=> deps: update go-bitswap and go-libp2p-circuit

go.mod, go.sum
1. Fixes IG NAT detection.
2. Fixes port mapping with NATs that don't properly detect port mapping conflicts.
3. Keep addresses for 2 minutes to make the DHT work more reliably (needed due to the whole dial queue thing).
4. Use a buffer pool in the relay.
=> dep: update go-libp2p-nat, go-libp2p-peerstore, go-libp2p-circuit

CHANGELOG.md, docs/releases.md, version.go
This has been running on the gateways for several days. There are still a few issues unresolved but it looks good enough to ship.
closes #6223
=> release 0.4.20

core/corehttp/redirect.go
- tiny bug fix for the configuration of root redirection
when you setup root redirection for the gateway or endpoint, you can configure RootRedirect in your configuration file as
```
"Gateway": {
.... // omitted ...
"NoFetch": false,
"PathPrefixes": [],
"RootRedirect": "PATH_TO_REDIRECTION",
"Writable": false
},
```
currently the configuration doesn't seem to work well, because
```daemon.go
if len(cfg.Gateway.RootRedirect) > 0 {
opts = append(opts, corehttp.RedirectOption("", cfg.Gateway.RootRedirect))
}
```
and when path = "" Handler for redirection will be set to "//"
```redirect.go
return func(n *core.IpfsNode, _ net.Listener, mux *http.ServeMux) (*http.ServeMux, error) {
mux.Handle("/"+path+"/", handler)
return mux, nil
}
```
in local
```
curl localhost:5001 # returns 404
```
as I …
=> fix the wrong path configuration in root redirection

assets/assets.go, core/commands/block.go, core/commands/cat.go, core/commands/dag/dag.go, core/commands/files.go, core/commands/get.go, core/commands/ls.go, core/commands/name/publish.go, core/commands/object/diff.go, core/commands/object/object.go, core/commands/object/patch.go, core/commands/pin.go, core/commands/resolve.go, core/commands/unixfs/ls.go, core/coreapi/block.go, core/coreapi/dht.go, core/coreapi/key.go, core/coreapi/name.go, core/coreapi/object.go, core/coreapi/path.go, core/coreapi/pin.go, core/coreapi/unixfs.go, core/corehttp/gateway_handler.go, core/corehttp/gateway_test.go, core/coreunix/add.go, fuse/readonly/ipfs_test.go, go.mod, go.sum
See https://github.com/ipfs/interface-go-ipfs-core/pull/22 / https://github.com/ipfs/interface-go-ipfs-core/pull/20
=> coreapi: Drop error from ParsePath

core/commands/object/object.go, test/sharness/t0051-object.sh
Adds support for printing the `CumulativeSize` in the `ipfs object stat` command in a human readable form by using the `--human` flag.
Fixes #6226
=> Support --human flag in cmd/object-stat

cmd/ipfs/daemon.go, core/core.go, core/mock/mock.go, core/node/builder.go, core/node/core.go, core/node/groups.go, core/node/helpers.go, core/node/helpers/helpers.go, core/node/identity.go, core/node/ipns.go, core/node/libp2p/discovery.go, core/node/libp2p/libp2p.go, core/node/provider.go, core/node/storage.go, p2p/p2p.go, test/integration/bitswap_wo_routing_test.go
In preparation for https://github.com/ipfs/go-ipfs/issues/6232
=> constructor: cleanup some things

core/corehttp/gateway_handler.go
Hello,
I have tried to solve this bug [1]. 
idk, about "tctx" in the "deleteHandler". After tctx is defined some calls after still use original ctx. I have assumed that it is bug and changed to "tctx"     
1 - https://github.com/ipfs/go-ipfs/issues/4607
=> core/corehttp/gateway_handler: pass a request ctx instead of the node

core/commands/add.go, test/sharness/t0040-add-and-cat.sh
See https://github.com/ipfs/go-ipfs/issues/6254
=>  add: Fix adding multiple files

go.mod, go.sum
* secio: maybe fix an out of bounds read.
* swarm, dht: avoid wasting memory allocating/keeping large errors around.
* peerstore: reduce memory usage
=> dep: update libp2p, dht, peerstore, swarm, secio

core/node/libp2p/libp2p.go
=> Fix AutoNAT service for private network

cmd/ipfs/util/ulimit.go
fixes #6247
Really, we need a global _resource_ manager service that can sum requests from the datastore, libp2p, etc. for more file descriptors. However, we don't have that.
=> raise default fd limit to 8192

core/commands/bitswap.go, test/sharness/t0220-bitswap.sh
License: MIT
Signed-off-by: Eric Wu <myself659@163.com>
=> humanize for ipfs bitswap stat

core/commands/urlstore.go
This is the first step in deprecating this command and works towards fixing #6002.
=> commands(feat): use the coreapi in the urlstore command

go.mod, go.sum
Instead, golang's keccak and spaolacci's murmur3 (both of which are maintained outside of gxed).
=> dep: drop leb.io/hashland

docs/environment-variables.md, docs/experimental-features.md
=> docs: document environment variables

cmd/ipfs/daemon.go
tweak the daemon --help output to use escaped double quotes instead
of single quotes so the same command can be used on windows.
fixes: #2034
License: MIT
=> fix: windows friendly daemon help

core/corerepo/gc.go, pin/gc/gc.go
We were canceling the context in `GarbageCollect` but some functions call `GC` directly. Move the context cancelation down to where we actually _need_ it.
I'm not sure _where_ we failed to cancel the context but I'm hoping https://github.com/ipfs/go-ipfs-cmds/pull/163 will help with that.
=> gc: cancel context

Rules.mk, bin/check_go_version, bin/dist_get, bin/maketarball.sh, coverage/Rules.mk, mk/golang.mk, mk/tarball.mk
The usage of a native 'go' command has been replaced with a make &
environment variable $GOCC. This enables building with multiple go
versions on a single machine as documented:
* https://golang.org/doc/install#extra_versions
This enables the usage of:
```bash
$ make install
$ # OR
$ GOCC=go1.12.3 make install
$ # OR
$ GOCC=go1.12.4 make install
```
And the build and test tools now pick up on this change
On branch go-version-check
Changes to be committed:
modified:   Rules.mk
modified:   bin/check_go_version
modified:   bin/dist_get
modified:   bin/maketarball.sh
modified:   coverage/Rules.mk
modified:   mk/golang.mk
modified:   mk/tarball.mk
License: MIT
Signed-off-by: Chris Buesser <christopher.buesser@gmail.com>
=> GOCC implementation & fix in make & build scripts

core/commands/pin.go
This is a breaking change but the fallout should be minimal.
fixes #6269
=> commands(pin update): return resolved CIDs instead of paths

fuse/ipns/ipns_test.go, fuse/node/mount_test.go
go test ./... was panicking.
1. core.NewNode was called with a nil pointer to a core.BuildCfg object -- Fixed in: 9380660
1. Error() was called on nil error object -- Fixed in: 5ce2deb
go test ./... passes all tests.
=> Go test fix

COPYRIGHT, LICENSE, LICENSE-APACHE, LICENSE-MIT
This series of commits aims to update go-ipfs to follow a dual-licensing best practice based on research into open-source licensing by @ianjdarrow. He recommends a dual MIT and Apache 2.0 license -
> This has two major benefits:
> - There are concerns in the open source community about whether the MIT license leaves users vulnerable to patent infringement claims. We think the pure legal risk is small, but the way the open source community interacts with our project is really important. It makes sense to pick the license that makes the largest number of people comfortable.
- There's now no reason to adopt a separate DCO, since the Apache-2 license grant addresses the same issue.
> Why use a dual license, instead of just Apache-2? The Apache-2 license is incompatible with the GPLv2 license, …
=> License update to dual MIT and Apache 2

docs/config.md
This PR fixes `docs/config.md` to reflect that `Routing` is not a child of `Discovery`.
`Discovery` section was confusing users as they tried to do 
```
ipfs config Discovery.Routing dhtclient
```
instead of 
```
ipfs config Routing.Type dhtclient
```
Ref. https://github.com/ipfs/go-ipfs-config/blob/664ccd976e969e78364720ec5f1d1544bc99305f/routing.go#L6
cc @Stebalien to speed up review, as it is a bug in docs only
=> docs: fix Routing section

Dockerfile
Allow `ipfs mount` to be run with docker image built from Dockerfile
-- install fuse during build phase
-- copy fusermount to smaller busybox image for run phase
-- create mount directorys for `ipfs mount` (`/ipfs` & `/ipns`)
Because a portion of FUSE runs at the kernel level, you have utilize the host machine's FUSE device: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
This means for this command to work, you have to run:
```
docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse ipfs/go-ipfs
```
This raises the question of whether it makes sense to support `ipfs mount` in Docker at all. If so, we should probably update the readme, to clarify the requirements for running w/ ipfs mount
However, I wonder what use case @davidcittadini had in mind …
=> fix(Dockerfile): Allow ipfs mount in Docker container

core/coreapi/test/api_test.go
fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/321
cc @anacrolix
=> test(coreapi): use a thread-safe datastore everywhere

pin/pin.go
We do this _just_ to make the error nicer but it's really slow. Additionally, we do it while holding the pin lock, blocking all other pin operations.
fixes #6295
=> pin: don't walk all pinned blocks when removing a non-existent pin

cmd/ipfs/util/ulimit.go, cmd/ipfs/util/ulimit_test.go
Not sure why CI wasn't failing.
=> fix setting ulimit

core/commands/dht.go, test/sharness/t0170-dht.sh
Specifically, #3124
Unfortunately, `dht put` is still broken. However, I can confirm that this fixes
`dht get`.
=> work towards fixing dht commands

core/coreapi/object.go, test/sharness/t0051-object.sh
Fixes https://github.com/ipfs/go-ipfs/issues/1331
=> object put: Allow empty objects

cmd/ipfs/main.go, test/sharness/t0280-plugin-git.sh, test/sharness/t0280-plugin.sh
Otherwise, we simply panic later.
=> fail start when loading a plugin fails

core/node/groups.go
Most people weren't affected by this as those values are set in config at init, but for others it would be rather hard to debug.
=> core: Use correct default for connmgr lowWater

bin/maketarball.sh
TMPDIR is a special variable indicating the _system_ temporary directory root. Unfortunately, go refuses to honor `go.mod` files in this directory to prevent random `/tmp/go.mod` files from messing with modules cloned into `/tmp`.
The fix is simple: rename TMPDIR to TEMP.
Note: this is only an issue when TMPDIR is exported (e.g., you're like me and you put your temporary directory somewhere else).
=> fix vendoring dependencies when building the source tarball

.circleci/config.yml, core/commands/dht.go, core/commands/swarm.go, core/node/libp2p/addrs.go, namesys/resolve/pathresolver_test.go, plugin/plugins/gen_main.sh
also fixes #6320 (golangci-lint _will_ fail if something doesn't compile)
=> ci: actually enable golangci-lint

go.mod, go.sum
Accidentally added in #6361. The yamux transport now disables this globally by default.
=> remove yamux read buffer

version.go
Still no release notes but I want to throw this up on the gateways. It has some important fixes that affect the connection manager.
=> release: go-ipfs 0.4.21-rc2

go.mod, go.sum
Hopefully helps fix #6271 and a bunch of other related issues.
=> fix race between adding tags and registering services with the connection manager

core/builder.go, core/core.go
This might help with https://github.com/ipfs/go-ipfs/issues/6356 as calling `app.Stop` twice in parallel could cause a lot of weird races (It may not though).
(If it will help with anything, it will be the `mock repo` part of the issue, `context canceled` is caused by 'wrong' use of contexts in MFS)
=> core: call app.Stop once

core/corehttp/gateway_handler.go, core/corehttp/mutex_profile.go, core/corehttp/proxy.go, go.mod, go.sum
This sets a few headers that prevent browsers from misinterpreting the error text.
=> fix: use http.Error for sending errors

CHANGELOG.md, bin/mkreleaselog, docs/experimental-features.md
WIP. Please either add or mention in comments what should be featured.
=> Add 0.4.21 CHANGELOG

core/node/libp2p/routing.go
Routing provider receives Repo and does not use it. Probably this is kind of typo.
=> Remove Repo from routing fx provider parameter

core/commands/block.go, test/sharness/t0050-block.sh
This makes `block put` consistent with `dag put` (Addressing https://github.com/ipfs/go-ipfs/issues/4721)
This will be a minor breaking change for js, cc @vmx
=> block cmd: allow adding multiple blocks at once

docs/config.md
This is currently the case. It should be filpped to true, but in the meantime let's document the current situation.
See: https://github.com/ipfs/go-ipfs/issues/1152
=> docs: default value for HashOnRead is false

core/node/storage.go
Just small observation.
Also is not fixed in #6387
=> Usage of context helper in Blockstore provider

.circleci/config.yml
https://github.com/ipfs/go-ipfs/issues/6393
=> Run JS interop in CircleCI

core/corehttp/gateway_handler.go, core/corehttp/metrics.go
This is a metric I really want to see, I don't know what labels we should add here, but I want to get this running on our gateway nodes ASAP.
=> add unixfs get metric

core/node/groups.go
Prevents the MDNS server from starting when the host has zero addresses.
Re: https://github.com/libp2p/go-libp2p/issues/652
=> libp2p: moves discovery after host listen

pin/pin.go
Not sure why this didn't show up sooner.
fixes #6418
=> pin: fix concurrent map access race

mk/golang.mk
This should help fix some of our problems using plugins with go-ipfs.
=> build: strip GOPATH from build paths

cmd/ipfs/dist/install.sh
Installation script fails if current directory is not the directory where script is located:
```
$ ./go-ipfs/install.sh 
mv: cannot move './go-ipfs/ipfs' to '/usr/local/bin/./go-ipfs/ipfs': No such file or directory
$ /tmp/go-ipfs/install.sh 
mv: cannot move '/tmp/go-ipfs/ipfs' to '/usr/local/bin//tmp/go-ipfs/ipfs': No such file or directory
```
=> install.sh: Fix wrong destination path for ipfs binary

README.md
https://docs.ipfs.io/introduction/install/ -> https://docs.ipfs.io/guides/guides/install/
although (a) can we do redirects on docs.ipfs.io for dead links? and (b) what's with /guides/guides/?
=> docs: fix install guide link

go.mod, go.sum, test/sharness/t0062-daemon-api.sh
Replaces #6410 (which I blew away, thanks git).
=> Fix a typo

plugin/loader/load_unix.go
Previously plugins were only loaded on linux. Darwin also supports plugins. The build constraint matches that of the standard library `plugin` package ([see](https://github.com/golang/go/blob/f2a4c139c1e0cff35f89e4b5a531d5dedc5ed8e0/src/plugin/plugin_dlopen.go#L5)).
**Note:** The `plugin` package requires cgo. So builds for darwin should be build on darwin to support plugins.
=> Load plugins on darwin/macOS

plugin/loader/loader.go
See: https://github.com/ipfs/go-ipfs/pull/5955#discussion_r292395838
=> Close started plugins when one of them fails to start.

core/commands/block.go, core/coreapi/block.go
See https://github.com/ipfs/go-ipfs/issues/6428
=> Fix: flush pin on block put

core/coreapi/pin.go
See https://github.com/ipfs/go-ipfs/issues/6428
=> Fix: ensure pin rm takes a lock

go.mod, go.sum
Reduces long-term allocations.
=> dep: update go-bitswap and go-libp2p-kad-dht

provider/queue/queue.go, provider/queue/queue_test.go
Fixes https://github.com/ipfs/go-ipfs/issues/6467, by implementing a very simple version of https://github.com/ipfs/go-ipfs/issues/6260.
=> Fix node construction queue error

.circleci/config.yml
This ensures we catch any http client breakage as soon as possible.
=> ci: test the http clients

cmd/ipfs/main.go, plugin/loader/loader.go, repo/fsrepo/config_test.go
1. Allow loading from arbitrary and multiple directories.
2. Make it possible to directly load built-in plugins that _aren't_ in the preload list.
3. Check the plugin loading state transitions.
=> feat: make it easier to load custom plugins

docs/config.md
Shouldn't have to scan through an old issue to figure out what is happening
and why this is super important.
=> Document the AddrFilters option

core/commands/ls.go, core/commands/pin.go
Add a --stream flag to stream the results instead of
accumulating the final result in memory.
This is a rework of https://github.com/ipfs/go-ipfs/pull/5005
=> pin cmd: stream recursive pins

core/commands/pin.go
I was unable to actually understand what pin update does from the existing
description.
=> Improve pin/update description

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/doc.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/question.md
Label list should be a comma separated string instead of a yaml array.
Noticed when opening https://github.com/ipfs/go-ipfs/issues/6502 via the enhancement template didn't automatically add the label.
=> Fix automatic labels in issue templates

docs/EARLY_TESTERS.md
Adds Siderus as Early tester to help with [Siderus Orion](https://orion.siderus.io/) as well as on the gateway
=> Adds Siderus in early testers

core/commands/files.go, test/sharness/t0250-files-api.sh
Allow passing --long or ?long=true as a more descriptive option name than "l".
refs https://github.com/ipfs/go-ipfs/issues/5026#issuecomment-392477565
refs https://github.com/ipfs/interface-js-ipfs-core/pull/426
refs https://github.com/ipfs/js-ipfs-http-client/issues/1049
=> feat: add --long as alias for -l in files.ls

mk/golang.mk
Arguments where not being properly passed to `go` when `$GOPATH` contained whitespace.
Introduced in https://github.com/ipfs/go-ipfs/pull/6412
See also:
https://github.com/golang/go/issues/33223
=> mk: handle stripping paths when GOPATH contains whitespace

core/commands/dht.go, core/commands/pin.go, core/coreapi/dht.go, core/coreapi/pin.go, core/corehttp/gateway.go, core/corehttp/gateway_handler.go, dagutils/diffenum.go, go.mod, go.sum, pin/gc/gc.go, test/sharness/t0111-gateway-writeable.sh
1. Fix handling of PUT. The simple implementation was the correct implementation, I have no idea what was going on here.
2. Use MFS everywhere to reduce code duplication and add support for sharded directories.
3. _Correctly_ block IPNS.
4. Remove the dependency on `core.IpfsNode`.
=> fix and improve the writable gateway

namesys/namesys.go, namesys/namesys_test.go
As per https://github.com/protocol/collab-ens/issues/5 this PR handles the situation where IPNS names ending in `.eth` are unresolvable due to `.eth` not being a recognised TLD.
It does so by changing such names to end in `.eth.link`, which will be resolvable by the EthDNS nameserver to obtain data from the relevant ENS records on-chain in Ethereum.
=> Allow resolution of .eth names via .eth.link

docs/RELEASE_ISSUE_TEMPLATE.md, docs/releases.md
* Split out automated testing into a stage 0.
* Flesh out release _cycle_.
* Define the process for normal patch releases.
=> tweak the release process

core/corehttp/gateway_handler.go, core/corehttp/metrics.go
Register 'time to first block' metric for the gateway only.
=> register first block metric for gateway only

go.mod, go.sum
Ensures we don't trim important connections in favor of connections currently in
the grace period.
=> dep: update connmgr

.github/ISSUE_TEMPLATE/question.md
People tend not to read templates (I'm also guilty of this) unless something jumps out. Let's make this jump out (this template _exists_ to tell users not to ask questions here).
=> github: update question template to avoid click throughs

Dockerfile
* Explicitly switch to buster.
* Explicitly set the golang version (and use the latest patch release).
* Explicitly set the busybox version.
* Update the maintainer
=> docker: update the docker image

go.mod, go.sum
Fixes several unsafety issues. Works towards #4485.
=> dep: update blockstore + bbloom

cmd/ipfs/daemon.go, cmd/ipfs/init.go, test/sharness/lib/test-lib.sh, test/sharness/t0020-init.sh, test/sharness/t0060-daemon.sh
Related to:
https://github.com/ipfs/go-ipfs/issues/6262
This patch adds
`ipfs daemon --init --init-config-file=${PATH}`
and
`ipfs init --config-file=${PATH}`
allowing users to specify existing configuration files instead of (re)generating them.
Does not deal with merging of existing configs and/or profiles (yet?).
=> feat: add ability to use existing config during init

README.md
This should now "just work". Calling `make` on non-linux platforms will invoke
`gmake` automatically and we now disable fuse on *bsd platforms.
=> doc: remove gmake instructions

cmd/ipfs/main.go, commands/context.go, docs/plugins.md, go.mod, go.sum, plugin/loader/loader.go, plugin/plugin.go, plugin/plugins/badgerds/badgerds.go, plugin/plugins/flatfs/flatfs.go, plugin/plugins/git/git.go, plugin/plugins/levelds/levelds.go, repo/fsrepo/config_test.go, test/sharness/t0020-init.sh, test/sharness/t0280-plugin-data/example.go, test/sharness/t0280-plugin.sh
For now, configs specified in `daemon --init-config` and `init CONFIG` are not available. We should fix this eventually but isn't necessary for now (and supporting this will be annoying).
=> plugins: add support for plugin configs

Dockerfile
Docker build is currently broken due to an updated version of libdl.
```
Step 23/34 : COPY --from=0 /lib/x86_64-linux-gnu/libdl-2.24.so /lib/libdl.so.2
COPY failed: stat /var/lib/docker/overlay2/86ed53025341b07961f14ed4d63a25317be51264a0555b6f8a768cc9e749e8ca/merged/lib/x86_64-linux-gnu/libdl-2.24.so: no such file or directory
```
This copies the symlinked libdl.so.2 instead of specific version.
=> docker: libdl dependency

docs/RELEASE_ISSUE_TEMPLATE.md, docs/releases.md
Adds estimated shipping date (can be fuzzy) to the release issue template and clarifies the time before which the next release issue should be opened. This communicates expectations for when the new release is due and will help with planning of included features. The community could even suggest inclusions.
@Stebalien you had the idea of adding estimates for each of the stages - do you want me to add them? I think I might leave these out of the js-ipfs release process for now unless requested as I think the actual release date is most important and we do already clarify that it should take around 3 weeks in the releases documentation.
=> docs: add ship date and next release issue opening time

mk/git.mk
When building with docker, we don't have a _full_ git repo.
=> build: fix build when we don't have a full git tree

core/node/libp2p/discovery.go
* Don't warn when connecting to peers.
* Include the peer id when failing to connect to discovered nodes.
=> discovery: improve mdns warnings

namesys/namesys.go
fixes https://github.com/ipfs/go-ipfs/issues/6656#issuecomment-534252128
=> namesys: set the correct cache TTL on publish

pin/pin.go, test/sharness/t0085-pins.sh
We were pining Y then removing the pin for X. When X == Y, we'd remove the new pin.
fixes #6648
=> pin: fix pin update X Y where X==Y

bin/collect-profiles.sh
The version of `date` that ships with darwin does not support the `-Iseconds` flag.
Use a pattern with `date` to achieve the same thing but should have better cross platform support.
Also, makes collect-profiles.sh executable.
License: MIT
=> fix: make collect-profiles.sh work on mac

plugin/daemon.go, plugin/loader/loader.go, plugin/plugin.go, plugin/tracer.go
Most of the tracers available need to properly close to send the remaining traces before the process exit.
=> plugins: support Close() for Tracer plugins as well

cmd/ipfs/daemon.go
Adds `ipfs_info` prometheus metric with version and commit info to http://localhost:5001/debug/metrics/prometheus output...
```console
ipfs_info{commit="9ea7c6a11-dirty",version="0.5.0-dev"} 1
```
This follows the same pattern as go and other systems, adding a gauge metric that is set to 1, with the version info added as labels.
This is a common pattern for prometheus. It lets operators merge version info into other prometheus metrics by multiplying it with the other stat. As the value is always 1, it simply adds the labels to the aggregated info but does not change the other stats value... as described in https://www.robustperception.io/exposing-the-software-version-to-prometheus
For example, we already expose the go version info as
```console
go_info{version="go1.12.9"} 1
```
Part of …
=> feat: add ipfs version info to prometheus metrics

go.mod, go.sum
Manually removed some newly-appeared // indirect imports as
they seem to just pollute the go.mod.
=> Update go-libp2p-http (and go-libp2p-gostream)

README.md
Not sure if pointing to https://docs.ipfs.io/guides/guides/install/ is the "getting started guide" we want (or that we had). @ipfs/docs what is the best/new getting started guide now that the previous url is broken?
=> docs: fix broken url

docs/README.md
Not a big change, mostly me doing some work figuring out how these fit all together and with the rest of docs available
=> docs: link remaining docs available, guide people to the right locations

cmd/ipfs/daemon.go, cmd/ipfs/main.go, docs/config.md, go.mod, go.sum, test/dependencies/pollEndpoint/main.go, test/sharness/lib/test-lib.sh, test/sharness/t0040-add-and-cat.sh, test/sharness/t0060-daemon.sh, test/sharness/t0067-unix-api.sh, test/sharness/t0111-gateway-writeable.sh
All the work was client-side. Unix domain socket multiaddrs already worked server-side.
Motivation:
* Security. This way, browsers, other users, etc. can't access the local node.
* Performance. Unix domain sockets are simply faster.
fixes #4218
=> daemon: support unix domain sockets for the API/gateway

go.mod, go.sum, namesys/dns.go, namesys/dns_test.go, namesys/namesys.go, namesys/namesys_test.go
This should have been handled down inside the DNSLink resolver. Otherwise, we'll
break any name happens to end in `.eth`.
also fixes #6699
=> fix(resolve): correctly handle .eth domains

core/commands/add.go, go.mod, go.sum, test/sharness/t0040-add-and-cat.sh
It has the same properties as Rabin but is much faster. Benchmark results of just chunkers:
```
name             speed
Buzhash2/1K-4    1.71GB/s ± 4%
Buzhash2/1M-4    1.15GB/s ± 2%
Buzhash2/16M-4    892MB/s ± 1%
Buzhash2/100M-4   904MB/s ± 2%
Rabin/1K-4       13.8MB/s ± 3%
Rabin/1M-4        171MB/s ± 3%
Rabin/16M-4       182MB/s ± 4%
Rabin/100M-4      182MB/s ± 3%
Default/1K-4     1.74GB/s ± 4%
Default/1M-4     3.22GB/s ± 2%
Default/16M-4    3.88GB/s ± 2%
Default/100M-4   4.21GB/s ± 6%
```
=> Introduce buzhash chunker      

pin/pin.go, test/sharness/t0081-repo-pinning.sh
Otherwise, we could abort while fetching the graph and stay in a state where the direct pin is removed.
fixes #4650
=> fix(pin): wait till after fetching to remove direct pin

core/corehttp/metrics.go
This fixes what was a rather confusing issue in prometheus where the `http_response_size_bytes` metrics was confused to be coming from nginx but was actually from ipfs.
=> ipfs namespace is now being provided to prometheus

Dockerfile
The `MAINTAINER` Dockerfile instruction has been deprecated, and the [dockerfile documentation](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated) recommends using `LABEL maintainer="..."`. This commit updates the Dockerfile to use the recommended form.
=> update maintainer label

docs/examples/go-ipfs-as-a-library/README.md
=> docs: remove extra ) on the example README

README.md
=> doc(README): document requirements for cross-compiling with OpenSSL support

core/coreapi/unixfs.go
ipfs add with only hash, don't need to announce cid to other peer，because unable to get this file from IPFS network. And waste memery to store the useless cid.
when i modified this code, and close the mock repo(issue 6744)，no memery grow with large calls.
=> fix bug 6748

core/coreapi/unixfs.go
=> fix(coreapi/add): close the fake repo used when adding with hash-only

cmd/ipfs/daemon.go, core/coreapi/unixfs.go
IPFS daemon will create a IDENTITY for repo through function GenerateKeyPairWithReader. This action cost so much CPU resource. And IPFS daemon creates a fake repo for each `ipfs add -n xxx`.
So, i create a global fake node,  all the calls `ipfs add -n xxx` can use this fake node to avoid GenerateKeyPairWithReader.
=> fix issue 6760, adding with hash-only, high CPU usage.

blocks/blockstoreutil/remove.go, core/commands/pin.go, core/coreapi/block.go, core/coreapi/dag.go, core/coreapi/object.go, core/coreapi/pin.go, core/coreunix/add.go, fuse/ipns/common.go, go.mod, go.sum, namesys/publisher.go, pin/gc/gc.go, pin/pin.go, pin/pin_test.go
At Infura we have the need for a custom out-of-process (remote actually) `Pinner`. Problem is, at the moment this interface assume that the list of pins is loaded in memory and access are instant and can't fail.
This PR add a context for cancellation and a return error to most of the functions of `Pinner`. Almost everything else is a consequence of those changes (see my comment later for the excessive locking).
This PR use a forked `go-ipfs-provider` to follow those changes, PR at https://github.com/ipfs/go-ipfs-provider/pull/16
=> pin: add context and error return to most of the Pinner functions

core/commands/repo.go
This add -H (-h is obviously taken by the help) for human and -s for size only (I though of -so but multiple letters is automaticaly -- not -).
=> Adding alias for `ipfs repo stat`.
