ipfs/kubo

- cmd/ipfs/ipfsHandler.go
- importer/chunk/splitting.go
- importer/importer.go
- importer/importer_test.go
- merkledag/merkledag.go
- merkledag/merkledag_test.go
- server/http/ipfs.go
- test/t0040-add-and-cat.sh
- unixfs/format.go
- unixfs/io/dagmodifier_test.go
- unixfs/io/dagreader.go
Also cleaned up a bunch of code related to building and reading DAGs
> Implement recursive indirect block creation for DAGs

- core/commands/add.go
- merkledag/coding.go
- merkledag/merkledag.go
- test/t0040-add-and-cat.sh
Taking over from https://github.com/jbenet/go-ipfs/pull/393
> sharness test: ipfs add -r

- .gitignore
> Ignore debug profile files in .gitignore

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/jbenet/go-fuse-version/README.md
- Godeps/_workspace/src/github.com/jbenet/go-fuse-version/fuseprint/.gitignore
- Godeps/_workspace/src/github.com/jbenet/go-fuse-version/fuseprint/README.md
- Godeps/_workspace/src/github.com/jbenet/go-fuse-version/fuseprint/index.go
- Godeps/_workspace/src/github.com/jbenet/go-fuse-version/version.go
- Godeps/_workspace/src/github.com/jbenet/go-fuse-version/version_bsd.go
- Godeps/_workspace/src/github.com/jbenet/go-fuse-version/version_darwin.go
- Godeps/_workspace/src/github.com/jbenet/go-fuse-version/version_linux.go
- Godeps/_workspace/src/github.com/jbenet/go-fuse-version/version_windows.go
- core/commands/mount_darwin.go
- test/sharness/Makefile
> osxfuse: fix version check

- core/core.go
also move network setup into its own self-contained func
> core: make sure to call swarm.FilterAddrs

- core/commands/ping.go
- core/commands/root.go
- routing/dht/dht.go
- routing/dht/dht_test.go
- routing/dht/routing.go
- routing/mock/centralized_client.go
- routing/routing.go
This PR implements a basic `ping` command. By default it executes ten pings, once per second. But a different number can be specified with `-count`
> Implement ipfs ping

- p2p/net/swarm/swarm_dial.go
found some bugs in the swarm close calls.
One of them i think i introduced today.
The other has been lurking there a long time.
> p2p/net/swarm: fixed bugs in swarm err closes

- p2p/net/swarm/dial_test.go
- p2p/net/swarm/simul_test.go
- p2p/net/swarm/swarm.go
- p2p/net/swarm/swarm_addr.go
- p2p/net/swarm/swarm_dial.go
- p2p/net/swarm/swarm_net.go
- p2p/net/swarm/swarm_test.go
* filtering InterfaceListenAddresses(s) instead
* return error if for loops skip
* ~~large~~ med dial timeout
* async dialing of all peer's conns (fixes several problems)
* extensive dial tests
> p2p/net/swarm: more connection bugs

- diagnostics/d3/chord.html
maybe we should move these to another repo for faster iteration, and not
wasting resources on jenkins
> more d3 niceness.

- test/bench/bench_cli_ipfs_add/main.go
- test/epictest/addcat_test.go
- test/epictest/bench_test.go
- test/epictest/three_legged_cat_test.go
- test/epictest/unit.go
- test/epictest/unit_test.go
- thirdparty/unit/unit.go
- thirdparty/unit/unit_test.go
RFCR @jbenet @whyrusleeping 
offline...
```
10 MB               1       1505748119 ns/op           6.96 MB/s <-- auto updater :(
20 MB               2       1669360071 ns/op          12.56 MB/s
40 MB               1       2470719258 ns/op          16.98 MB/s
80 MB               1       1582573228 ns/op          53.01 MB/s
160 MB              1       3055764503 ns/op          54.90 MB/s <--lgtm
320 MB              1       11282053501 ns/op         29.74 MB/s
640 MB              1       20792035181 ns/op         32.28 MB/s
1 GB                1       63325554093 ns/op         21.19 MB/s
2 GB                1       136473098308 ns/op        19.67 MB/s <-- scaling issue :(
```
online is a TODO
> benchmark CLI `ipfs add`

- commands/command.go
- commands/http/client.go
- commands/http/handler.go
- commands/response.go
- core/commands/add.go
- core/commands/mount_unix.go
- core/commands/pin.go
- core/commands/ping.go
- core/commands/repo.go
- core/commands/root.go
- core/repo/gc.go
- core/repo/pinning.go
- fuse/ipns/ipns_unix.go
- importer/importer.go
- pin/pin.go
- pin/pin_test.go
- test/sharness/t0080-repo.sh
Pretty basic garbage collection command. Quick and easy verification of it working: it should remove the 'hello ipfs' block since it isnt pinned.
> initial implementation of repo-gc command

- exchange/bitswap/bitswap.go
- exchange/bitswap/decision/engine.go
- repo/config/config.go
- test/sharness/lib/test-lib.sh
- test/sharness/t0020-init.sh
- test/sharness/t0060-daemon.sh
Merge when sufficiently large
- rename coreio to coreunix
> Miscellaneous changes

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/jbenet/go-reuseport/addr.go
- Godeps/_workspace/src/github.com/jbenet/go-reuseport/impl_unix.go
- Godeps/_workspace/src/github.com/jbenet/go-reuseport/reuse_test.go
@whyrusleeping found that we were leaking fds.
This PR is to find them and destroy them.
Already fixed the worst offender.
https://www.youtube.com/watch?v=mrSWSx35Zok
> fixing fd leaks

- core/corehttp/gateway_handler.go
- exchange/bitswap/bitswap.go
- exchange/bitswap/decision/engine.go
- exchange/bitswap/network/ipfs_impl.go
- p2p/net/swarm/swarm_dial.go
- p2p/peer/queue/sync.go
- routing/dht/dht.go
- routing/dht/query.go
- routing/dht/routing.go
- thirdparty/eventlog/log.go
> remove prefix logger

- cmd/ipfs/main.go
- core/commands/get.go
- core/commands/log.go
- core/commands/root.go
- test/sharness/t0090-get.sh
- unixfs/tar/reader.go
Made some minor UX improvements and fixes for the CLI.
> CLI changes

- core/commands/cat.go
- core/corehttp/gateway_handler.go
- core/coreunix/cat.go
- fuse/ipns/ipns_unix.go
- fuse/readonly/readonly_unix.go
- importer/importer_test.go
- merkledag/merkledag.go
- merkledag/merkledag_test.go
- server/http/ipfs.go
- unixfs/io/dagmodifier_test.go
- unixfs/io/dagreader.go
- unixfs/tar/reader.go
This PR makes jbenet's dream of seeking through movies hosted in ipfs a reality, kinda, i didnt implement the seeking part in the filesystem or the web interface, just on the object.
> Implement io.Seeker on unixio.DAGReader

- cmd/ipfs-gateway-fs/main.go
- cmd/ipfs/init.go
- core/commands/bootstrap.go
- core/coreunix/add.go
- p2p/protocol/identify/id.go
- repo/config/bootstrap_peers.go
- repo/config/init.go
- routing/grandcentral/client.go
- routing/grandcentral/proxy/loopback.go
- routing/grandcentral/proxy/standard.go
- routing/grandcentral/server.go
- test/sharness/lib/test-lib.sh
after #642 
This doesn't necessarily need to be in this repository, but users may find these examples of IPFS used as a library instructive.
> New Binary: Gateway Fileserver

- core/commands/diag.go
Attempts to address issue #666
> add more help text for ipfs diag net

- p2p/protocol/identify/id.go
> fix nil pointer panic on version strings in ID message

- cmd/ipfs-gateway-fs/main.go
> decide whether to perform GC -- with flag

- test/epictest/test_config.go
- test/epictest/unit.go
- test/epictest/unit_test.go
- test/integration/Makefile
- test/integration/addcat_test.go
- test/integration/bench_test.go
- test/integration/bitswap_wo_routing_test.go
- test/integration/core.go
- test/integration/three_legged_cat_test.go
@whyrusleeping @jbenet This moves `test/epictest` to a dir called `test/integration`
> rename epictest -> integrationtest

- core/commands/resolve.go
> fix cast panic in ipfs name resolve when daemon is running

- cmd/ipfs-gateway-fs/main.go
- cmd/ipfs/daemon.go
- cmd/ipfswatch/main.go
- core/commands/config.go
- core/corehttp/gateway.go
- core/corehttp/gateway_handler.go
- fuse/ipns/ipns_unix.go
- fuse/readonly/readonly_unix.go
- merkledag/node.go
- path/resolver.go
- repo/config/gateway.go
- repo/config/init.go
- test/sharness/lib/test-lib.sh
- test/sharness/t0100-http-gateway.sh
- util/util.go
> HTTP: add handlers to allow object creation and modification

- cmd/ipfs/daemon.go
- routing/dht/notif.go
- test/sharness/lib/test-lib.sh
- thirdparty/notifier/notifier.go
- thirdparty/notifier/notifier_test.go
fixing:
- hanging connects
- daemon test output (must do stdout for now)
- added rate limiting to notifs
> misc fixes: hanging connects + test output

- test/sharness/t0090-get.sh
> test/sharness: improve t0090 by using printf

- test/sharness/lib/test-lib.sh
seems that the previous way isnt liked by all platforms
> sharness/lib: fixing gateway addr check

- test/sharness/t0111-gateway-writable.sh
> test/sharness: improve t0111 using test_cmp

- test/sharness/lib/test-lib.sh
And i think this is clearer on the reader. And makes it obvious
on test output which path was taken.
> sharness/lib: fix daemon startup check

- blockservice/worker/worker.go
- cmd/ipfs-gateway-fs/main.go
- cmd/ipfs/daemon.go
- cmd/ipfs/main.go
- core/core.go
- exchange/bitswap/bitswap.go
- exchange/bitswap/bitswap_test.go
- p2p/protocol/mux.go
- repo/fsrepo/component/datastore.go
- routing/dht/pb/message.go
- test/integration/three_legged_cat_test.go
- thirdparty/eventlog/log.go
- thirdparty/iter/iter.go
- thirdparty/waitable/waitable.go
@whyrusleeping @jbenet 
These are preparatory modifications for GCR. Handling these modifications upfront will cut the CR for grandcentral routing down by a factor of 2.
> Preparatory refactors/fixes/cleanups for GCR

- exchange/bitswap/bitswap.go
- exchange/bitswap/message/message.go
- exchange/bitswap/network/ipfs_impl.go
- p2p/crypto/secio/protocol.go
- p2p/net/conn/conn.go
- routing/dht/pb/message.go
- thirdparty/eventlog/log.go
- thirdparty/eventlog/loggable.go
@whyrusleeping @jbenet Additional changes in preparation for GCR PR.
> More preparatory refactors/fixes/cleanups for GCR  

- repo/config/config.go
- repo/config/init.go
- repo/config/log.go
- repo/fsrepo/component/component.go
- repo/fsrepo/component/config.go
- repo/fsrepo/component/datastore.go
- repo/fsrepo/component/datastore_test.go
- repo/fsrepo/component/eventlog.go
- repo/fsrepo/fsrepo.go
> Allow FSRepo components to depend on the config, add log config to eventlog

- core/commands/root.go
- routing/dht/query.go
We're leaking peer queues:
http://gateway.ipfs.io/ipfs/QmQxVA48CzVwwNYExUiFe56VrUBn8u368ZfchnCLoc7fSC/moriarty
> gc query queues

- core/corehttp/gateway_handler.go
ipns paths are mutable and should not be cached. this error is
a byproduct of the currently messy gateway route. We should split
the /ipfs and /ipns routes up.
> gateway: dont cache ipns paths

- p2p/crypto/secio/rw.go
- p2p/net/conn/dial.go
thanks @whyrusleeping for finding these.
> ctx.Done fixes

- cmd/ipfs/main.go
- core/commands/add.go
- core/core.go
- exchange/bitswap/decision/engine.go
- exchange/bitswap/wantlist/wantlist.go
- namesys/interface.go
Im trying to make godoc look much prettier.
> document some packages

- p2p/net/conn/dial.go
We were half-way with this. there's no way for net.Dialers to respect
contexts, so we have to let the dial finish in the background.
> p2p/net/conn: respect context on dialing

- cmd/ipfs/daemon.go
- core/builder.go
- core/core.go
I moved this over on top of master. I want to get it in soon so I can draw up some clean examples for working with the API.
> implement nodebuilder

- p2p/peer/peer.go
unsafe assertions will always come back to bite you. always. ALWAYS.
> fix for #757

- routing/dht/handlers.go
- routing/dht/providers.go
This is very likely why our resolving has sucked for so long.
> this might solve all our problems

- core/commands/refs.go
Yet another pull request where i instruct inanimate code on the finer points of dag requesting
> teach ipfs refs -r how to use GetBlocks

- Dockerfile
- bin/container_daemon
> Fix Dockerfile

- merkledag/coding.go
> more understandable errors from merkledag decoding

- core/corehttp/redirect.go
- test/sharness/t0110-gateway.sh
hopefully I finally got this right
bug #812
> fixing bug 812

- core/corehttp/webui.go
/ipfs/QmXX7YRpU7nNBKfw75VG7Y1c3GwpSAGHRev67XVPgZFv9R
https://github.com/protocol/ipfs-webui/commit/ee74f75d0b30d59326a813fb4467c91190cb87a6
> published new webui

- test/sharness/t0110-gateway.sh
This are the changes I suggested in:
https://github.com/BrendanBenshoof/go-ipfs/commit/ed179263f4987ae21cc8c0fde2cde0c22db9369c
License: MIT
> t0110: cleanup using expr

- fuse/readonly/readonly_unix.go
Breaking up changes from #841 , this is number 1
> take offset into account for computing read size

- core/commands/pin.go
i couldn't understand what those meant. it was explain (at least partly) in #590 so let's share the goods!
> explain what direct/indirect/recursive means

- test/sharness/t0110-gateway.sh
This removes the dependency on wget, and, while at it, cleanups a bit.
License: MIT
> t0110: replace wget with curl

- test/sharness/README.md
Add information from the discussion of PR #891.
While at it, suggest using -v and -i options to debug one test.
> sharness/README: add writing tests and debugging

- repo/fsrepo/serialize/serialize.go
- repo/fsrepo/serialize/serialize_test.go
> Config file is not executable, and must not be world accessible

- cmd/ipfs/daemon.go
- cmd/ipfs/main.go
- commands/request.go
Related issue: https://github.com/jbenet/go-ipfs/issues/854.
> Dirty hack to fix race conditions in the daemon

- util/util.go
- util/util_test.go
This thing looked awkward. I'm glad I wasn't used by anything.
> rm util.NewByteChanReader()

- blocks/blockstore/blockstore.go
- blocks/blockstore/blockstore_test.go
- blocks/blockstore/write_cache.go
- repo/repo.go
> Dead code cleanup

- pin/pin.go
> fix locking in the pinner

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/jbenet/goprocess/goprocess_test.go
- Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go
Thanks for stack trace @dylanPowers
> updated goprocess -- bugfixes

- namesys/publisher.go
- pin/pin_test.go
- test/sharness/t0080-repo.sh
should fix the issue that @cryptix and @zignig ran into last night after my ipnsfs merge
> fix for weird repo init issue

- test/sharness/t0060-daemon.sh
> t0060-daemon.sh: Add 1 test

- fuse/ipns/ipns_unix.go
- fuse/readonly/readonly_unix.go
> set proper UID and GID on fuse filesystems

- test/sharness/lib/test-lib.sh
- test/sharness/t0030-mount.sh
- Rewrite two tests into one
- 2 known breakages vanished
> t0030-mount.sh: 2 known breakages vanished (2)

- core/commands/dht.go
noticed this, thought it should be handled
> handle error from GetClosestPeers

- docs/fuse.md
Improved `fuse.md` doc as suggested in https://github.com/ipfs/go-ipfs/issues/813#issuecomment-89672102
> fuse.md: Added troubleshooting instructions for #813

- cmd/ipfs/main.go
Just a bit of cleanup on my travels
> Unify shutdown message format string

- core/corehttp/gateway_handler.go
This commit adds HEAD support to the IPFS Gateway.
Related: #840
> corehttp: added support for HEAD requests

- core/commands/add.go
bugfix: add was not setting error
> bugfix: add was not setting error

- core/commands/publish.go
- test/sharness/lib/test-lib-hashes.sh
- test/sharness/t0100-name.sh
Fixes #749
```
$ ipfs name publish /ipfs/QmV32WjiHoYMC5xTuiwZMcEFx686M7qKJmbMQ1cSEwkXvU/foo
Published name QmXmPBXfviRCFdcuVF9xn6VVwNgAXoKMc2majbbDKPvkZ3 to QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6
```
> Publish by path

- merkledag/node.go
```go
// AddRawLink adds a pre-provided link to this node
func (n *Node) AddRawLink(name string, lnk *Link) error
// Return the link with given name
func (n *Node) GetNodeLink(name string) (*Link, error)
```
> Add additional link manipulation functions

- docs/fuse.md
- docs/windows.md
Additional instructions on files that need to have permissions changed.
> DOCS: Updated FUSE docs

- core/commands/add.go
- core/commands/object.go
This significantly improves the performance of adding large directories
> don't readd entire directories recursively

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/whyrusleeping/iptb/LICENSE
- Godeps/_workspace/src/github.com/whyrusleeping/iptb/README.md
- Godeps/_workspace/src/github.com/whyrusleeping/iptb/main.go
- test/Makefile
- test/sharness/Makefile
- test/sharness/t0130-multinode.sh
This is a proof of concept, and a place for discussion on the further use of iptb for testing out ipfs network capabilities.
cc @jbenet @chriscool
> add clone of 3node test using iptb instead of docker

- cmd/ipfs/init.go
@jbenet I noticed this discrepency during your talk.
> Mention correct key size in help for init

- test/Makefile
- test/sharness/t0130-multinode.sh
I discussed these points with @whyrusleeping on IRC.
> Fix iptb tests

- Dockerfile
- bin/container_daemon
* Added VOLUME to enable users to keep a state of the repo outside the container
* Added ipfs user to let ipfs run as a normal user and not as root
* Set IPFS_PATH to push IPFS to use the exposed dir
* Improved start script to be more verbose about errors
> Improve Dockerfile

- README.md
> Change ipfs root path volume mount to /data/ipfs

- assets/init-doc/readme
Fixes https://github.com/ipfs/ipfs/issues/67
> use => Use

- misc/launchd/README.md
- misc/launchd/install.sh
- misc/launchd/io.ipfs.ipfs-daemon.plist
I found this useful to have, and figured it might save somebody else a few minutes of re-inventing the wheel.
> Add an OSX LaunchAgent plist

- blockservice/worker/bench/main.go
- commands/command.go
- core/commands/commands.go
- core/core.go
- core/corehttp/corehttp.go
- core/corerepo/pinning.go
- doc.go
I've been chipping away at this over the past two days while I survey
the repository.  Currently stumping me for a description is
core/corerouting, so I'd welcome some ideas for a brief description
there.  Otherwise, I'm trying to describe these packages based on a
quick skim, so feedback/clarification/fixes/etc. are welcome :).
I still have a few more packages to document, but I thought I'd push
this PR now to start getting feedback on the earlier docs while I work
through the remaining packages.
> Add package comments to packages that are missing them

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/jbenet/go-msgio/.travis.yml
- Godeps/_workspace/src/github.com/jbenet/go-msgio/fuzz.go
- Godeps/_workspace/src/github.com/jbenet/go-msgio/fuzz_test.go
- Godeps/_workspace/src/github.com/jbenet/go-msgio/msgio.go
- Godeps/_workspace/src/github.com/jbenet/go-msgio/varint.go
The MaxSize changes. Also see #1181.
> godep: update go-msgio

- p2p/crypto/secio/rw.go
I'm pretty sure this is the right way to address this, but it could definitely use a look over and some thought.
> quick fix for OOM panic that has been plaguing us

- README.md
> add link to community contributing #1088

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/codahale/metrics/runtime/fds.go
building for freebsd was broken because of this.
> godeps: update metrics (freebsd build fix)

- core/corehttp/gateway_handler.go
- unixfs/io/dirbuilder.go
This PR is a subset of #1191. I want to fix #1150 asap, as it's worse to
have that broken than the PUT handler.
> Refactor/http gateway quickfix (1191)

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/jbenet/go-peerstream/listener.go
https://github.com/jbenet/go-peerstream/commit/8d52ed2801410a2af995b4e87660272d11c8a9a4
> go-peerstream update (accept concurrency)

- .travis.yml
Following: https://github.com/ipfs/infrastructure/issues/20#issuecomment-102665147
License: MIT
> .travis: split go and sharness tests

- cmd/ipfs/init.go
- cmd/ipfs/main.go
- repo/fsrepo/fsrepo.go
- repo/fsrepo/lock/lock.go
- test/sharness/t0020-init.sh
> clean up and fix init permissions handling

- core/corehttp/ipns_hostname.go
For details see comment thread at #1233
> Fix: Using the `dnslink` feature led to infinite redirects

- core/corehttp/corehttp.go
this does a good job at shutting down when we tell it to.
> do http server properly so daemon can shut down

- core/pathresolver.go
- test/sharness/t0041-add-cat-offline.sh
also added a basic offline sharness test to verify
> fix offline full path resolution bug

- core/commands/bitswap.go
I want to do sharness tests for things like this, but i'm not sure where to put them...
> make bitswap commands error out properly offline

- docs/fuse.md
See go-ipfs/repo/config/mounts.go
> AllowOther -> FuseAllowOther

- core/commands/stat.go
Help text from --proto was copy pasted.
> Update option help for ipfs stats bw --poll

- blockservice/mock.go
- core/mock/mock.go
- core/pathresolver_test.go
- fuse/ipns/ipns_test.go
- fuse/readonly/ipfs_test.go
> move core mock into its own package

- core/corehttp/webui.go
this PR updates the webui version to 0.2.0
> updated webui to 0.2.0

- test/ipfs-test-lib.sh
- test/sharness/lib/test-lib.sh
> ipfs-test-lib: implement test_seq()

- core/builder.go
I was trying to build an app using an ipfs node, and the NodeBuilder panics if you dont specify a repo because the default repo setting doesnt provide a peerID and private key. So i added that generation logic into this.
> make the default repo for corebuilder work

- exchange/bitswap/wantmanager.go
Saw some goroutines hanging here while trying to kill a daemon. This should help.
License: MIT
> select with context when sending on channels

- core/commands/add.go
> Wired up the trickle dag flag for the add command

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/jbenet/goprocess/goprocess.go
- Godeps/_workspace/src/github.com/jbenet/goprocess/goprocess_test.go
- Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go
- util/sadhack/godep.go
> update goprocess godep

- core/commands/object.go
> Object put examples in help text

- cmd/ipfs/daemon.go
close these channels so we can exit.
License: MIT
> close channels and allow daemon to shutdown

- core/builder.go
- core/commands/add.go
- test/sharness/t0040-add-and-cat.sh
- test/sharness/t0041-add-cat-offline.sh
I'm not married to the placement of this command, but it works, and does what we expect it to! (its also realllly fast)
License: MIT
> add option to only hash input

- core/commands/object.go
The available templates were not listed so I went ahead and added the one template currently available. Is there a test for this template?
> Object new templates

- README.md
> add link to init system examples

- exchange/bitswap/bitswap.go
- exchange/bitswap/workers.go
I'm working on making a bitswap dashboard tool. This PR adds in some events that can be parsed out of the eventlog firehose to generate an informative dashboard to help us better understand what the hell bitswap is up to.
License: MIT
> add in some events to bitswap to emit worker information

- commands/files/is_hidden.go
- commands/files/is_hidden_windows.go
- commands/files/serialfile.go
- core/commands/add.go
- test/sharness/t0042-add-skip.sh
License: MIT
Signed-off-by: Gaetan Voyer-Perrault <gatesvp@gmail.com>
> Add hidden file support to add

- .travis.yml
> use travisCI's docker containers for testing

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/whyrusleeping/go-multistream/lazy.go
- Godeps/_workspace/src/github.com/whyrusleeping/go-multistream/multistream.go
- Godeps/_workspace/src/github.com/whyrusleeping/go-multistream/multistream_test.go
- p2p/host/basic/basic_host.go
- p2p/test/backpressure/backpressure_test.go
This is probably WIP, i need to look over it again to make sure. But i need to work on the GC stuff before i get back to this. 
License: MIT
> allow multistream to have zero rtt stream opening

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/jbenet/goprocess/.travis.yml
- Godeps/_workspace/src/github.com/jbenet/goprocess/context/context.go
- Godeps/_workspace/src/github.com/jbenet/goprocess/goprocess.go
- Godeps/_workspace/src/github.com/jbenet/goprocess/goprocess_test.go
- Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go
Waiting for gx.
Though should have done this earlier.
> Bump goprocess

- core/commands/mount_unix.go
- misc/completion/ipfs-completion.bash
> Add the missing long argument for ipfs mount

- routing/dht/dht_test.go
> mark other nodes in routing table on test-connect

- commands/http/client.go
> if no context set in request, use context.TODO()

- p2p/net/mock/mock_notif_test.go
- p2p/net/swarm/swarm_notif_test.go
We were assuming that the notifications would be received in the same order that they were sent, which is false. If multiple goroutines are trying to send on a channel, the scheduler randomly selects one.
License: MIT
> fix race condition in notifications test

- core/commands/pin.go
- test/sharness/t0081-repo-pinning.sh
seeing another random failure that I may be responsible for here: https://github.com/ipfs/go-ipfs/issues/1508
This should help figure out whats going on.
Also removed a debug statement i accidentally left in.
License: MIT
> print output on test failure for t0081

- cmd/ipfs/.gobuilder.yml
https://github.com/Luzifer/gobuilder/pull/52
License: MIT
> updated gobuilder dist

- core/commands/diag.go
- diagnostics/diag.go
> rmeove duplicate timeout option from diag

- commands/http/handler.go
> only set stream header on streamed output

- core/commands/object.go
- merkledag/coding.go
- merkledag/merkledag_test.go
- merkledag/node.go
- merkledag/node_test.go
- merkledag/utils/utils.go
- merkledag/utils/utils_test.go
- test/sharness/t0051-object.sh
Docker stuff is a headache without this option. We can also make it a different sub-command if that makes more sense.
License: MIT
> allow patch to optionally create intermediate dirs

- commands/http/client.go
This should address the issues seen here: https://travis-ci.org/ipfs/go-ipfs/jobs/73239014#L3661
I had special cased the error in one spot earlier where this error is always hit, but in cases where we pass the reader back directly, its a bit of a race on whether the final read happens before or after the body is closed. This embeds the error check into the reader wrapping the body so we always get that error checked properly and converted into an io.EOF
License: MIT
> should fix issue where 'read on closed body' error was leaking down

- merkledag/utils/diff.go
blame: @whyrusleeping on ed4274c9b75b513672fa674884a5df2cdb45276c
License: MIT
> fix master: make vendor

- core/core.go
- fuse/ipns/mount_unix.go
I could have sworn we PR'ed and merged this.
License: MIT
> dont create ipnsfs filesystem until its needed

- docs/implement-api-bindings.md
> small doc on implementing api bindings

- cmd/ipfs/daemon.go
- cmd/ipfs/main.go
- core/commands/root.go
- repo/fsrepo/fsrepo.go
- repo/mock.go
- repo/repo.go
- test/sharness/README.md
- test/sharness/lib/test-lib.sh
- test/sharness/t0060-daemon.sh
- test/sharness/t0061-daemon-opts.sh
- test/sharness/t0062-daemon-api.sh
This is a WIP to make the ipfs cli tool check for a running daemon
via the API, and make sure the APIs match.
I ran into some complexity i need to think more about before
attepting to fix... anyone feel free to pick this up!
License: MIT
> check for API -- WIP

- p2p/net/filter/filter.go
Callers assume this is safe to call whenever, let's make it so.
License: MIT
Signed-off-by: Tommi Virtanen <tv@eagain.net>
> p2p/net/filter: Guard with a mutex

- commands/http/handler.go
> recover and print panics that happen in API server

- test/sharness/t0062-daemon-api.sh
These are just clean ups to make sure that everything is tested and to avoid potential quoting problems.
> t0062 cleanup

- importer/chunk/rabin.go
> fix swaped argument in rabin.go

- core/commands/add.go
> remove error log i forgot to remove from another PR

- fuse/readonly/ipfs_test.go
License: MIT
Signed-off-by: Philip Nelson <me@pnelson.ca>
> Fix test case for fuse/readonly.

- fuse/ipns/ipns_test.go
the ipns fuse tests dont pass on master. This fixes that.
License: MIT
> dont use coremock for fuse tests

- cmd/ipfs/.gobuilder.yml
> Fix: Use the right repo to encrypt secrets.

- core/commands/bitswap.go
- exchange/bitswap/bitswap.go
- test/sharness/t0220-bitswap.sh
We've needed a way to remove blocks from the wantlist for a while. No better time than the present to implement it!
License: MIT
> implement unwant command to remove blocks from wantlist

- core/commands/dht.go
The get command currently will base58 decode the keys you specify, but the dht keys are generally formatted as `/prefix/<raw multihash>`. So using the CLI to query for ipns records and public keys was difficult.
Now you can do:
```
ipfs dht get @/ipns/<peer id>  #returns ipns record data
ipfs dht get @/pk/<peer id>    #returns public key corresponding to <peer id>
```
License: MIT
> allow for dht keys to be escaped

- contribute.md
We frequently have people who want to contribute, but have trouble with the way they need to set up the repo to work with go. This should help with that.
@RichardLitt Could you review this one?
License: MIT
> add some notes on how to hack on go-ipfs

- test/sharness/t0081-repo-pinning.sh
> t0081: swap test_cmp arguments

- test/sharness/t0051-object.sh
> t0051: swap test_cmp arguments

- test/sharness/t0100-name.sh
> t0100: swap test_cmp arguments

- test/sharness/t0044-add-symlink.sh
- test/sharness/t0141-addfilter.sh
- test/sharness/t0220-bitswap.sh
- test/sharness/x0045-add-cat-iptb.sh
- test/sharness/xt0130-multinode.sh
This PR replaces and completes the following PRs:
https://github.com/ipfs/go-ipfs/pull/1790
https://github.com/ipfs/go-ipfs/pull/1787
https://github.com/ipfs/go-ipfs/pull/1782
> Fix test cmp args

- p2p/net/mock/mock_conn.go
- p2p/net/mock/mock_link.go
> mocknet: conn close idempotent with process.

- core/commands/object.go
- test/sharness/t0051-object-data/brokenPut.xml
- test/sharness/t0051-object-data/testPut.xml
- test/sharness/t0051-object.sh
License: MIT
Signed-off-by: Forrest Weston <fweston@eecs.wsu.edu>
> Added an xml decoder, Fixes #1612

- p2p/net/swarm/simul_test.go
- p2p/net/swarm/swarm.go
- p2p/net/swarm/swarm_dial.go
This should prevent the crashes when adding large files and directories.
addresses #1654 and other similar issues.
License: MIT
> rate limit concurrent peer dials

- core/commands/cat.go
- core/commands/get.go
Where the progressbar wrapper is put before the stream is turned into tar.
> Use common progressbar function for cat and get

- p2p/net/swarm/swarm_dial.go
After [yet another goprocess bug](https://ipfs.io/ipfs/QmbYDMxoHfrehLdy5Ai3XZRBacjt3JojVuUUEdpRAHa9mn) I decided to just rip it out. Its gone now. bye bye.
I also figured that, while I was at it, I would add a bit of priority to the order in which we dial addresses. 
First: addresses that dont consume a file descriptor.
Second: localhost addresses, as they should either succeed or fail immediately.
Third: all normal tcp addresses.
Last: dockers '172.17' range of addresses, these are almost always trouble.
License: MIT
> refactor dialing to not panic, and to be smart about ordering

- p2p/net/swarm/dial_test.go
- p2p/net/swarm/swarm_dial.go
> order addresses to give certain address types priority

- test/sharness/t0010-basic-commands.sh
- test/sharness/t0060-daemon.sh
The first patch adds some tests in t0010.
The second patch is a cleanup patch.
> Test 'ipfs commands'

- core/commands/commands.go
> Make `ipfs commands --flags` option

- exchange/bitswap/workers.go
> fix panic in bitswap working limit spawning

- contribute.md
> Fix broken link

- cmd/ipfs/Makefile
- repo/config/version.go
fixes git failure seen in #1863, thanks @kpcyrd
License: MIT
> fix makefile failing when not in a git repo

- test/sharness/t0010-basic-commands.sh
> t0010: add tests for 'ipfs commands --flags'

- core/commands/id.go
- test/sharness/t0140-swarm.sh
> allow ipfs id to work on self

- commands/http/handler.go
> content type on command responses default to text

- test/sharness/t0220-bitswap.sh
> t0220: add 'ipfs bitswap stat' tests

- test/sharness/t0021-config.sh
> t0021: test 'ipfs config show'

- core/corehttp/webui.go
this update disables logs as there is a problem currently
with how the webui grabs them and go-ipfs
> webui updated to disable logs

- README.md
See https://github.com/ipfs/community/issues/62.
License: MIT
> Added a security section

- merkledag/coding.go
- merkledag/node.go
- merkledag/utils/utils_test.go
- test/sharness/t0051-object.sh
should address #1925
thanks @eminence for debugging this to root cause!
License: MIT
> set data and links nil if not present

- core/commands/version.go
To be used by `ipfs-update`
License: MIT
> add option to version command to print repo version

- notifications/query.go
- p2p/net/swarm/dial_test.go
- p2p/net/swarm/swarm_dial.go
- p2p/net/swarm/swarm_listen.go
- routing/dht/query.go
should address #1942 
Fixes dial backoff (probably) and adds in some extra notifications to be used by dht query visualization tools
> fix swarm dial backoff

- routing/dht/query.go
I missed this, my apologies
License: MIT
> drop error log down to debug

- dev/crypto-notes.md
See https://github.com/ipfs/go-ipfs/pull/1928#discussion_r43626195
License: MIT
> Moved TODO doc to issue #1929

- test/sharness/t0082-repo-gc-auto.sh
This file was accidentally not included during the gc branch rebase
> Add gc auto test

- commands/response.go
- test/sharness/t0051-object-data/expected_getOut
- test/sharness/t0200-unixfs-ls.sh
- test/sharness/t0230-channel-streaming-http-content-type.sh
Actually use real ndjson for streaming output
License: MIT
> no newlines in json objects

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/jbenet/go-peerstream/conn.go
- Godeps/_workspace/src/github.com/jbenet/go-peerstream/muxtest/muxt.go
- Godeps/_workspace/src/github.com/jbenet/go-peerstream/swarm.go
should fix #2022 
License: MIT
> update go-peerstream dep

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/jbenet/go-datastore/flatfs/flatfs.go
@jbenet looks like i pushed the branch and forgot to file a PR
License: MIT
> update to new flatfs code

- test/sharness/t0082-repo-gc-auto.sh
> disable auto repo gc tests temporarily

- core/commands/object.go
> Added quotes around command in long desc

- cmd/ipfs/daemon.go
Cf https://github.com/ipfs/support/issues/5
License: MIT
> Added a shutdown note to daemon description

- core/corehttp/webui.go
> feat: Update to the latest version of the webui

- core/bootstrap.go
- core/bootstrap_test.go
> combine multiple bootstrap addrs into single peer info

- cmd/ipfs/daemon.go
- cmd/ipfs/init.go
> Added env var info to init, dameon help

- Dockerfile
@jbenet PTAL
Please note: Merging this makes #2169 obsolete (close that one after merging this)!
> Build ipfs cmd inside docker container

- core/commands/block.go
> Added quotes around block put command

- test/sharness/lib/iptb-lib.sh
- test/sharness/lib/test-lib.sh
- test/sharness/t0101-iptb-name.sh
- test/sharness/t0121-bootstrap-iptb.sh
- test/sharness/t0130-multinode.sh
- test/sharness/t0240-republisher.sh
This removes some code duplication in tests using iptb.
> Refactor iptb tests

- core/commands/config.go
> Add quotes to ipfs config

- cmd/ipfs/main.go
- commands/command.go
- commands/files/file.go
- contribute.md
- core/commands/commands.go
- core/commands/mount_unix.go
- core/commands/swarm.go
- exchange/bitswap/decision/engine.go
- exchange/interface.go
- misc/completion/ipfs-completion.bash
- unixfs/format.go
- unixfs/io/dagreader.go
- util/eventlog/loggables/loggables.go
Here are some harmless changes I made while getting familiar with the codebase.
> trivial: various superficial fixes

- cmd/ipfs/daemon.go
> Change sample API origin settings from wildcard to example.com

- commands/reqlog.go
- core/commands/active.go
> command to clear inactive requests from request log

- core/commands/object/object.go
> Changed wording to make optional stand out

- test/sharness/lib/iptb-lib.sh
- test/sharness/t0240-republisher.sh
Another iptb related clean up.
> t0240 improvements

- README.md
> add some tips for making dep installs go smoothly

- core/commands/diag.go
Also added default notice about plain text
License: MIT
> Formatted diag net comments

- core/commands/unixfs/unixfs.go
> Fixed spelling errors, added oxford comma

- namesys/interface.go
> Capitalized could

- namesys/publisher.go
- namesys/resolve_test.go
- routing/mock/centralized_server.go
its uh... faster.
License: MIT
> put pubkey and ipns entry to dht in parallel

- core/commands/root.go
> Add dns and resolve commands to ROAPI

- test/sharness/lib/test-lib.sh
- test/sharness/t0040-add-and-cat.sh
- test/sharness/t0061-daemon-opts.sh
- test/sharness/t0062-daemon-api.sh
- test/sharness/t0110-gateway.sh
- test/sharness/t0111-gateway-writeable.sh
- test/sharness/t0112-gateway-cors.sh
- test/sharness/t0121-bootstrap-iptb.sh
- test/sharness/t0230-channel-streaming-http-content-type.sh
I got tired of sharness tests randomly failing due to port conflicts, so i started using port zero for the daemons addresses.
Its not done, its not pretty, and i'm not sure if what i'm doing is even sane. @chriscool if I could get any tips or feedback here, that would be super cool... 
License: MIT
> trying to use port zero for ipfs daemon in sharness tests

- appveyor.yml
- test/ipfs-test-lib.sh
- test/sharness/lib/test-lib.sh
- test/sharness/t0020-init.sh
> appveyor: sharness improvements

- .travis.yml
- Makefile
- appveyor.yml
- bin/check_gx_program
> Do not install gx if user explicitly didn't ask for it

- core/commands/config.go
- core/commands/mount_unix.go
- core/commands/object/object.go
- core/commands/object/patch.go
> Normalised Example heading, added dollar sign to examples

- core/commands/tar.go
> Capped IPFS, added period

- core/commands/unixfs/ls.go
See @dignifiedquire comments in https://github.com/ipfs/http-api-spec/pull/45
License: MIT
> Removed double space, hyphen

- core/commands/swarm.go
> Fixed spelling error

- README.md
- core/commands/dht.go
- core/commands/root.go
- dev.md
- routing/dht/dht_net.go
- routing/dht/dht_test.go
- routing/dht/handlers.go
- routing/dht/records.go
> Capitalized DHT

- core/commands/stat.go
> Added default false to stats bw poll

- test/sharness/t0062-daemon-api.sh
> t0062: fix indentation

- core/commands/dht.go
> Updated tagline for queryDhtCmd

- Makefile
- bin/check_go_version
This should fix issue  #2397 (makefile should check installed version of go).
> Check go version

- Makefile
Now it was doing whole nothing
> Make Makefile patch to use global gateway actually work

- core/commands/resolve.go
> Added `default false` to `resolve --recursive` help text 

- core/commands/files/files.go
This follows https://github.com/ipfs/go-ipfs/pull/2403/files.
License: MIT
> Change language for files read slightly

- core/commands/config.go
> Added an `as` to ensure good English

- core/commands/dns.go
See https://github.com/ipfs/http-api-spec/pull/41#discussion_r53164737
License: MIT
> Add default to dns resolve

- core/commands/refs.go
My bad. Introduced in #2366
License: MIT
> Fix spelling error

- docs/fuse.md
added sudo to usermod;
added --json to "ipfs config" command;
added modification to fuse.conf;
License: MIT
Signed-off-by: Giuseppe Bertone <bertone.giuseppe@gmail.com>
> Fixed some scripts

- test/sharness/lib/test-lib.sh
- test/sharness/t0060-daemon.sh
should address #2426 
License: MIT
> make t0060 use port zero

- test/sharness/t0300-docker-image.sh
This should help debug issue #2425 (t0300 hung on travis) as the actual file should contain some useful information.
> t0300: improve docker_build debug message

- commands/http/client.go
- commands/http/handler.go
- commands/http/handler_test.go
- test/sharness/t0110-gateway.sh
- test/sharness/t0230-channel-streaming-http-content-type.sh
cc @dignifiedquire make sure this works for you
License: MIT
Signed-off-by: Jeromy Johnson <why@ipfs.io>
> fix double transfer encoding header problem

- core/corehttp/webui.go
As reported in #2334 most people are happy with it :)
> feat: Update the webui to work with the latest changes in 0.4

- core/commands/diag.go
Noted in https://github.com/ipfs/http-api-spec/pull/40.
License: MIT
> Edited the grammar for diag

- core/commands/object/object.go
> Alphabetized object subcommands

- blocks/blockstore/blockstore_test.go
- blocks/key/key.go
- core/commands/block.go
- core/commands/object/object.go
- core/commands/refs.go
- core/coreunix/add.go
- exchange/bitswap/message/message.go
- fuse/ipns/ipns_unix.go
- fuse/readonly/readonly_unix.go
- namesys/resolve_test.go
- routing/dht/handlers.go
- routing/dht/pb/message.go
> clean deprecated Key.Pretty()

- fuse/ipns/ipns_test.go
- fuse/node/mount_test.go
- fuse/readonly/ipfs_test.go
> correct import in fuse tests

- repo/config/version.go
> bump ipfs dev version to 0.4.1

- roadmap.md
> add roadmap.md

- test/sharness/t0051-object.sh
Tests to ensure that object patching writes to the block store.
> Adds tests to make sure 'object patch' writes.

- core/commands/object/patch.go
Part of https://github.com/ipfs/http-api-spec/pull/32. Needs to be merged.
License: MIT
> Edited object patch set-data doc

- blocks/blockstore/write_cache.go
This PR add log events when are added/removed to/from the blockstore. I need these events for the Arbore project to track block locality.
License: MIT
Signed-off-by: Michael Muré <mure.michael@gmail.com>
> Add log events when blocks are added/removed to/from the blockstore

- Makefile
License: MIT
Signed-off-by: Andrew Chin <achin@eminence32.net>
> Adds 'toolkit_upgrade' to the makefile help target

- misc/launchd/io.ipfs.ipfs-daemon.plist
- repo/fsrepo/doc.go
- repo/fsrepo/fsrepo.go
- test/3nodetest/bootstrap/config
- test/3nodetest/client/config
- test/3nodetest/server/config
> repo: don't create logs directory, not used any longer

- core/commands/log.go
Follows logging levels as defined [here](https://github.com/whyrusleeping/go-logging/blob/master/level.go#L19)
> commands: update log command help text

- core/commands/object/diff.go
- core/commands/object/object.go
- merkledag/utils/diff.go
- test/sharness/t0052-object-diff.sh
While working on the ipfs distributions code, i wanted a way to easily see the difference between two versions of the site. So I wrote this command.
> implement object diff command

- core/commands/swarm.go
> Alphabetized swarm subcmds

- core/commands/swarm.go
Added as part of https://github.com/ipfs/http-api-spec/pull/56#discussion_r55576466. 
License: MIT
> Added a note about swarm disconnect

- core/commands/stat.go
> Added note to ipfs stats bw interval option

- core/commands/repo.go
> Small syntax changes to repo stat man

- core/commands/object/object.go
> add omitempty to Object struct tags

- core/commands/swarm.go
> Fix disconnect argument description

- CHANGELOG.md
- repo/config/version.go
Take a look and let me know if i missed anything
License: MIT
> add changelog for v0.4.1

- core/commands/active.go
> Fixed up comments for `diag cmds`

- cmd/ipfs/init.go
- cmd/ipfs/ipfs.go
- cmd/ipfs/main.go
- commands/command.go
- core/commands/repo.go
- repo/fsrepo/fsrepo.go
- repo/fsrepo/lock/lock.go
- test/sharness/t0083-repo-fsck.sh
This adds a repo fsck command as outlined in #2457.
> commands: repo fsck

- core/commands/repo.go
> Added a period to repo fsck

- debug-guide.md
Stolen from this comment https://github.com/ipfs/go-ipfs/issues/2594#issuecomment-212506980
License: MIT
> Added a debug-guidelines doc

- Godeps/_workspace/src/bazil.org/fuse/fs/serve.go
- Godeps/_workspace/src/github.com/cenkalti/backoff/exponential.go
- Godeps/_workspace/src/github.com/cheggaaa/pb/pb.go
- Godeps/_workspace/src/github.com/codegangsta/cli/app.go
- Godeps/_workspace/src/github.com/ipfs/go-datastore/leveldb/datastore.go
- Godeps/_workspace/src/github.com/ipfs/go-datastore/namespace/namespace.go
- Godeps/_workspace/src/github.com/rs/cors/cors.go
- Godeps/_workspace/src/github.com/syndtr/gosnappy/snappy/snappy_test.go
- Godeps/_workspace/src/gopkg.in/fsnotify.v1/open_mode_darwin.go
- core/commands/files/files.go
- core/commands/object/patch.go
- core/commands/refs.go
- core/core.go
- docs/fuse.md
- docs/implement-api-bindings.md
- fuse/node/mount_darwin.go
- merkledag/node.go
- pin/pin_test.go
- repo/config/bootstrap_peers.go
- repo/config/init.go
- roadmap.md
- routing/dht/dht.go
- routing/dht/handlers.go
- routing/dht/routing.go
- test/sharness/Makefile
- test/sharness/t0083-repo-fsck.sh
- thirdparty/loggables/loggables.go
- thirdparty/testutil/ci/travis/travis.go
- thirdparty/testutil/gen.go
> Capitalized `NOTE`, first letter of following word

- core/commands/mount_nofuse.go
- core/commands/mount_unix.go
- fuse/ipns/mount_unix.go
- fuse/node/mount_nofuse.go
- fuse/node/mount_unix.go
- fuse/readonly/mount_unix.go
- fuse/readonly/readonly_unix.go
with this patch i was able to build ipfs on NetBSD 7 with "gmake nofuse"
License: MIT
Signed-off-by: Stefan Hertenberger <github@hertenberger.bayern>
> add NetBSD support

- blocks/blocks.go
- blocks/blockstore/blockstore.go
- blocks/blockstore/blockstore_test.go
- blocks/blockstore/write_cache.go
- blocks/blocksutil/block_generator.go
- blockservice/blockservice.go
- blockservice/test/blocks_test.go
- core/commands/block.go
- exchange/bitswap/bitswap.go
- exchange/bitswap/bitswap_test.go
- exchange/bitswap/decision/engine.go
- exchange/bitswap/decision/engine_test.go
- exchange/bitswap/message/message.go
- exchange/bitswap/notifications/notifications.go
- exchange/bitswap/notifications/notifications_test.go
- exchange/bitswap/testnet/network_test.go
- exchange/bitswap/workers.go
- exchange/interface.go
- exchange/offline/offline.go
- importer/chunk/rabin_test.go
- merkledag/merkledag.go
- test/integration/bitswap_wo_routing_test.go
Factored out from pull request #2600
> Make blocks.Block an interface.

- .travis.yml
- Makefile
- bin/dist_get
- test/Makefile
> add a dist_get script for getting bins from dist.ipfs.io

- exchange/bitswap/network/ipfs_impl.go
> allow bitswap to read multiple messages per stream

- cmd/ipfs/init.go
> Added Default logic to `ipfs init`

- core/commands/ipns.go
- core/commands/name.go
> Updated resolve hash to Mars, added reference

- core/commands/ping.go
I think this is the right way to show -n and --count? What do you think? 
License: MIT
> Updated synopsis for ping

- core/commands/external.go
> Capitalize print statements, add period to `external`

- core/commands/ls.go
> Added Default logic to `ls` cmd

- core/commands/ping.go
> Added Default to ping, cleaned up logic

- core/commands/get.go
> Added Default logic to `get` cmd

- core/commands/commands.go
> Added Default to `commands` cmd

- core/commands/config.go
> Added Default to `config` cmd

- test/sharness/t0060-daemon.sh
> Increase timeout in t0060

- core/commands/dns.go
> Added Default to `dns` cmd

- core/commands/unixfs/ls.go
- core/commands/unixfs/unixfs.go
> Updated `file` helptext

- circle.yml
> make circle.yml use make deps instead of trying to be smart

- core/commands/pin.go
- pin/pin.go
This is a cleanup to add and use more consts in pin related code.
> Use consts for pin modes

- Makefile
- README.md
- appveyor.yml
This fixes leftover from PR #2584.
> Fix toolkit_upgrade Makefile target removal

- cmd/ipfs/ipfs.go
> Make ipfs config edit run on client

- commands/files/file.go
> Fix typo in files command error message

- README.md
Seemed more natural.
License: MIT
> Touch up language a bit

- cmd/ipfs/ipfs.go
> Require diag cmds command to run on daemon

- core/commands/files/files.go
> files: Adjust to fit ruler 78

- core/commands/files/files.go
> Fixed apostrope in files stat options

- core/commands/stat.go
> Adds aliases to stats command

- exchange/bitswap/wantmanager.go
> fix argument placement on log message

- routing/dht/providers/providers.go
> routing: Use correct error variable

- core/commands/get.go
Turned out to be a pretty simple fix
License: MIT
> fix progress bar in ipfs get

- cmd/ipfs/daemon.go
- test/sharness/t0110-gateway.sh
> gateway: on api, restrict to webui

- core/commands/repo.go
- test/sharness/t0084-repo-read-rehash.sh
> make repo verify work with running daemon

- bin/container_daemon
> docker: allow passing options to daemon

- CHANGELOG.md
Needs a bit more wording for the "notable changes".
License: MIT
> changelog: add v0.4.3

- commands/http/parse.go
- commands/request.go
- test/sharness/t0600-issues-and-regressions-online.sh
> commands: fix panic when expected files field is nil

- repo/fsrepo/migrations/migrations.go
- repo/fsrepo/migrations/unpack.go
Should address #3019 
We really need to work on some sort of CI for windows.
License: MIT
> extract binaries with .exe name on windows

- commands/cli/helptext.go
#Working on issue #2981. 
~~This is still work in progress and untested.~~
It seems to be working. :cow2:
> Sort SUBCOMMANDS section of help output

- routing/dht/routing.go
Debugging code to detect issue #3032 and prevent it from crashing the daemon.
License: MIT
> dht: add in code to detect and diagnose #3032

- CHANGELOG.md
- package.json
- repo/config/version.go
> CHANGELOG for 0.4.3-rc2

- blocks/blocksutil/block_generator_test.go
> test: 100% coverage for blocks/blocksutil

- core/commands/pin.go
> Add period to `ipfs pin rm`

- unixfs/mod/dagmodifier_test.go
> test: reach 80% coverage of unixfs/mod

- core/commands/add.go
> ipfs/add: make --local flag not write out providers

- test/sharness/t0080-repo.sh
Created in response of CR: https://github.com/ipfs/go-ipfs/pull/2598/files#r76388121
License: MIT
> test: accept more than one digit in repo version tests

- LICENSE
See https://github.com/ipfs/go-ipfs/pull/2883#issuecomment-227528997
License: MIT
> Change LICENSE year

- test/sharness/t0086-repo-verify.sh
Should address https://github.com/ipfs/go-ipfs/pull/2924/files#r76514755
> Improve sharness testing on ipfs repo verify

- misc/completion/ipfs-completion.bash
> bash: bring --unrestricted-api completion back (sorry!)

- core/commands/files/files.go
See https://github.com/ipfs/go-ipfs/pull/2667. 
License: MIT
> Add default True to files flush

- package.json
> gx: fix dvcsimport path in package.json

- core/commands/dht.go
This is a fix for ipfs/go-ipfs#3220
@whyrusleeping seems to pass locally, wanna see what travis says.
> [deps/extract-dht] Fix routing/notifications

- README.md
> readme: add `-u` to gx install commands in manual build instructions

- CHANGELOG.md
> changelog: update for 0.4.3

- test/sharness/t0040-add-and-cat.sh
- test/sharness/t0110-gateway.sh
> trying to debug random test failures

- package.json
- repo/config/version.go
> bump dev version to 0.4.5

- test/sharness/x0601-pin-fail-test.sh
> add test to be run to detect future regressions in pinsets

- tar/format.go
> dont buffer entire input for tar adds

- core/commands/dht.go
- core/commands/id.go
- core/commands/pubsub.go
- core/commands/swarm.go
- core/core.go
- core/corehttp/gateway.go
- core/corehttp/gateway_test.go
- core/corehttp/metrics_test.go
- core/mock/mock.go
- exchange/bitswap/bitswap_test.go
- exchange/bitswap/testnet/peernet.go
- exchange/bitswap/testutils.go
- namesys/republisher/repub_test.go
- package.json
- routing/mock/dht.go
- routing/supernode/client.go
- routing/supernode/proxy/loopback.go
- routing/supernode/proxy/standard.go
- routing/supernode/server.go
- routing/supernode/server_test.go
- test/integration/addcat_test.go
- test/integration/bench_cat_test.go
- test/integration/bitswap_wo_routing_test.go
- test/integration/grandcentral_test.go
- test/integration/three_legged_cat_test.go
License: MIT
Signed-off-by: Jeromy why@ipfs.io
> update go-libp2p-swarm with deadlock fixes

- CHANGELOG.md
> changelog: fix 0.4.3-rc dates

- core/commands/config.go
License: MIT
Signed-off-by: David Brennan <david.n.brennan@gmail.com>
> Put config keys in proper case

- cmd/ipfs/ulimit_unix.go
License: MIT
Signed-off-by: Vasily Kolobkov <polezaivsani@openmailbox.org>
> Tune resource limits on BSDs

- blocks/blockstore/blockstore.go
- thirdparty/ds-help/key.go
Doesn't help that much though, see #3376.
> blockstore: fix TODO and avoid calling ds.NewKey

- core/commands/pubsub.go
- core/core.go
- package.json
New floodsub! Now with cancellation and stuff.
> use floodsub version 0.8.1

- exchange/bitswap/wantmanager.go
> fix formatting on error call

- flags/flags_test.go
To address the flags coverage in #3053.
> Add test for flags package

- core/commands/root.go
> add a note about ipfs key in the main helptext

- cmd/ipfs/daemon.go
> add in option to use nil-routing

- core/commands/dht.go
- core/core.go
- package.json
- routing/mock/dht.go
- routing/supernode/client.go
- routing/supernode/proxy/loopback.go
- routing/supernode/proxy/standard.go
- routing/supernode/server.go
- routing/supernode/server_test.go
> update dht code to drop error log to warning

- core/commands/dag/dag.go
- merkledag/merkledag.go
- package.json
- test/sharness/t0053-dag.sh
> update to the correct ipld cbor code

- package.json
- repo/config/version.go
> Ipfs 0.4.5, pre-release 2

- core/commands/stat.go
License: MIT
Signed-off-by: Mateusz Naściszewski <matin1111@wp.pl>
> Fix link in `ipfs stats bw` help message

- package.json
- repo/fsrepo/defaultds.go
> update flatfs to v1.1.1, path -> filepath fixes

- .gx/lastpubver
- package.json
> gx publish v0.4.5-rc2

- core/core.go
> Add in env var to enable yamux debug logging

- core/corehttp/webui.go
Closes #3664
License: MIT
Signed-off-by: Friedel <dignifiedquire@gmail.com>
> feat(webui): update to new version

- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs 0.4.5

- Makefile
Fixes https://github.com/ipfs/go-ipfs/issues/3676
License: MIT
> make: fix PATH escaping

- package.json
- repo/config/version.go
> misc: increase version number to 0.4.6-dev

- README.md
License: MIT
Signed-off-by: rht <rhtbot@gmail.com>
> Add closed PRs, Issues throughput

- test/sharness/t0085-pins.sh
> Add back removed test.

- ci/Dockerfile.buildenv
git repo requires to have objects directory which I have missed.
License: MIT
> ci: Fix lack of commit hash during the build

- package.json
- repo/fsrepo/defaultds.go
> update flatfs to v1.1.2, directory fd closing fix

- repo/fsrepo/migrations/migrations.go
> update dists path with 1.2.2 migrations

- CHANGELOG.md
> Changelog update for ipfs 0.4.6

- .gx/lastpubver
- package.json
- repo/config/version.go
> Ipfs 0.4.6, release candidate 1

- .gx/lastpubver
- package.json
- repo/config/version.go
> Ipfs 0.4.6

- package.json
This should fix the random iptb failures. Hopefully
License: MIT
> update iptb with 'iptb stop' fix

- codecov.yml
> misc: require two coverage reports to create final report

- bin/archive-branches.sh
> misc: add branch archiving script

- README.md
> readme: add Arch install instruction

- core/commands/add.go
- test/sharness/t0270-filestore.sh
> fix: filestore silently being skipped on add if it wasn't enabled

- test/sharness/t0270-filestore.sh
you can use the test_debug by calling tests with
`debug=t verbose=t make test/sharness/t0000-xxx.sh
License: MIT
> test: small cleanup to the filestore sharness test

- test/sharness/t0010-basic-commands.sh
> test: small cleanup of t0010

- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs 0.4.7-rc1, Changelog and version bump

- dev.md
supercedes #3736 as it has gotten no response in a few weeks.
License: MIT
> update link to paper in dev.md

- .codeclimate.yml
> misc: try enabling codeclimate

- package.json
> update iptb with hopeful fix for travis hanging issue

- commands/files/is_hidden_windows.go
supercedes #3626 
License: MIT
> fix hidden file detection on windows

- bin/mkreleaselog
This is what i've been doing to generate the changelog for the past few releases, figured i'd automate it
License: MIT
> Add a script to help generate the CHANGELOG

- filestore/filestore.go
- filestore/fsrefstore.go
- filestore/util.go
Nothing out of the usual here, just comments for exported functions.
License: MIT
> Filestore: make golint happy

- cmd/ipfs/Rules.mk
> make: fix `make install` not installing dependencies

- core/core.go
- package.json
> deps: bubble up cbor update

- core/coreapi/coreapi.go
- core/coreapi/unixfs.go
- core/coreapi/unixfs_test.go
- core/coreunix/cat.go
- path/resolver.go
- test/sharness/t0260-sharding-flag.sh
- unixfs/hamt/hamt.go
- unixfs/io/dirbuilder.go
- unixfs/io/resolve.go
> Fix sharding memory growth, and fix resolver for unixfs paths

- README.md
- Rules.mk
- docs/openbsd.md
> Fix install_unsupported for openbsd, add docs

- CHANGELOG.md
- package.json
- repo/config/version.go
> Update changelog and bump version for 0.4.9-rc1

- .gx/lastpubver
- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs release 0.4.9

- package.json
this should help us debug the random failures
License: MIT
> update to iptb with better errors

- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs release 0.4.10-rc1

- test/sharness/t0180-p2p.sh
> rename and fix sharness issue in ptp test

- .gx/lastpubver
- CHANGELOG.md
- package.json
- repo/config/version.go
I'm a slow writer.
License: MIT
> Ipfs release 0.4.10

- docs/developer-certificate-of-origin
> contributing: add DCO

- core/commands/dag/dag.go
- test/sharness/t0053-dag.sh
This at least partially addresses #3544
> Add pin option for ipfs dag put

- namesys/namesys_test.go
> test: fix race in namesys tests

- package.json
- repo/config/version.go
I keep forgetting to do this
License: MIT
> bump version to 0.4.11-dev

- docs/experimental-features.md
So I was thinking whenever we do something about experimental features, instead of posting in https://github.com/ipfs/go-ipfs/issues/3397 we should update this new text document, and link the PR in that issue.
> docs: add experimental-features.md

- exchange/bitswap/session.go
- exchange/bitswap/session_test.go
I seem to have forgotten to clean up some things.
License: MIT
> fix closing and removal of sessions

- package.json
Someday, someone will have time to fix
https://github.com/whyrusleeping/gx-go/issues/17
> gx: import and fix gx deps

- core/commands/dag/dag.go
> remove some dead code

- core/core.go
- package.json
This should hopefully fix a lot of our CI problems.
> gx: update deps

- README.md
Based on response from @whyrusleeping. (https://github.com/ipfs/go-ipfs/issues/4048#issuecomment-313774707)
License: MIT
Signed-off-by: Jon Choi <choi.jonathanh@gmail.com>
> README.md: Notes on where to start reading code

- merkledag/merkledag.go
this comment wasn't updated to reflect changes in code
> trivial comment update

- bin/archive-branches.sh
> misc: add feat/zcash to go-ipfs-archived exemption

- package.json
This should fix sharness coverage.
> Update iptb to 1.2.2

- pin/gc/gc.go
> gc: add events for profiling GC

- docs/releases.md
ref: https://github.com/ipfs/go-ipfs/issues/4163#issuecomment-324288851
> docs: Update docs on release

- test/sharness/t0170-dht.sh
> test: query test might work sometimes, mark it as 'might fail' 

- test/sharness/t0130-multinode.sh
That iptb branch is whyrusleeping/iptb#31 -- I guess don't merge before that one lands :)
> sharness: add /ws multinode test

- package.json
> remove duplicate dep from gx deps

- docs/config.md
- docs/debug-guide.md
- docs/experimental-features.md
- docs/fuse.md
- docs/github-issue-guide.md
- docs/implement-api-bindings.md
- docs/openbsd.md
* Wrapped things to roughly 120 columns
* 'Refactored' FUSE docs
* Updated some things to reflect current state
> docs: Update and clean-up

- package.json
- repo/fsrepo/datastores.go
> update badgerds dep

- CHANGELOG.md
- package.json
- repo/config/version.go
> bump version to 0.4.11-rc1, update changelog

- CHANGELOG.md
- package.json
- repo/config/version.go
> update version and changelog for 0.4.11-rc2

- .gx/lastpubver
- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs v0.4.11

- package.json
- repo/config/version.go
> misc: increase version to 0.4.12-dev

- README.md
> README.md: Suggest safer docker flags

- exchange/bitswap/network/interface.go
- exchange/bitswap/network/ipfs_impl.go
- exchange/bitswap/session.go
- exchange/bitswap/testnet/virtual.go
> tag peers associated with a bitswap session

- core/core.go
- repo/config/init.go
> default settings for the connection manager

- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs v0.4.12-rc1

- core/commands/dht.go
- core/core.go
- package.json
> update dht to remove error log

- core/commands/add.go
Part II of #4276 adds the long description
> chunker long description first shot

- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs v0.4.12-rc2

- package.json
- repo/fsrepo/datastores.go
- test/sharness/t0025-datastores.sh
> Update badgerds to 1.1.3

- CHANGELOG.md
- bin/mkreleaselog
- package.json
- repo/config/version.go
Trying to get this out ASAP
License: MIT
> Ipfs v0.4.13-rc1

- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs v0.4.13

- docs/config.md
> docs: correct StorageMax config desc

- README.md
Adding instructions for downloading IPFS builds with IPFS
License: MIT
Signed-off-by: John Reed <john@re2d.xyz>
> adding how to download IPFS with IPFS

- plugin/plugins/git/git.go
> small typo in git plugin

- docs/config.md
config.md: updating the Addresses section
Adding documentation on Announce and NoAnnounce.
Fixing typo in API default value.
License: MIT
Signed-off-by: John Reed <john@re2d.xyz>
> updating Addresses section

- cmd/ipfs/daemon.go
- cmd/ipfs/ipfs.go
- cmd/ipfs/main.go
- cmd/ipfswatch/main.go
- core/commands/add.go
- core/commands/bitswap.go
- core/commands/block.go
- core/commands/cat.go
- core/commands/commands.go
- core/commands/filestore.go
- core/commands/get.go
- core/commands/get_test.go
- core/commands/helptext_test.go
- core/commands/pubsub.go
- core/commands/repo.go
- core/commands/root.go
- core/commands/stat.go
- core/corehttp/commands.go
- package.json
To include @ForrestWeston's log/uuid changes
> update go-ipfs-cmds to 0.4.11

- docs/releases.md
addresses issue @lgierth mentioned in #4478
> document gx release checklist item

- thirdparty/pollEndpoint/main.go
Seeing `%s` in debug messages makes me sad.
> pollEndpoint: use Debugf

- commands/command.go
@keks, do you know if this cod was supposed to do something?
> commands: remove dead code

- cmd/ipfs/Rules.mk
- mk/golang.mk
- mk/util.mk
- package.json
- repo/fsrepo/datastores.go
> badger: Update to fix i386 windows build

- .codeclimate.yml
ref: https://docs.codeclimate.com/docs/advanced-configuration
License: MIT
> disable codeclimate 'maintainability' checks

- core/coreapi/object.go
Oh for a CI that runs on merge...
> fix hidden merge conflicts

- ISSUE_TEMPLATE.md
Minor nit relavent to the issue template.
> Fix typo in template

- core/coreapi/unixfs.go
> dont use bitswap session for cat just yet

- namesys/republisher/repub.go
Not sure how this snuck through, but it needs to go
License: MIT
> remove a spurious debug message

- cmd/ipfs/daemon.go
- core/core.go
Replaces https://github.com/ipfs/go-ipfs/pull/4747
> Fix "PNetFingerpint" field typo of core.IpfsNode

- core/commands/files.go
Currently when the daemon is running, asking for `ipfs files stat QmDoesntExistLocally` will hang instead of returning immediately. This PR fix that by using the offline DAGService earlier. I guess I got confused in the test I was doing when implementing that the third time :-|
License: MIT
> make files stat --with-local return immediately when no data is present

- .gx/lastpubver
- CHANGELOG.md
- docs/releases.md
- package.json
- repo/config/version.go
> prepare for 0.4.14 release

- CODEOWNERS
This will cause me being tagged for review of every PR, unless we have
subsystem owners, then they will be tagged for review.
License: MIT
> misc: create CODEOWNERS file

- CHANGELOG.md
- package.json
- repo/config/version.go
@Kubuxu @magik6k wanna run through the api tests to make sure we've caught everything?
Hopefully this is it :)
License: MIT
> ipfs release 0.4.14-rc3

- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs v0.4.14

- contribute.md
License: MIT
Signed-off-by: Dominic Della Valle <ddvpublic@gmail.com>
> Update broken links

- exchange/bitswap/wantmanager.go
> bitswap: reduce level when logging about disconnected peers to info

- unixfs/io/dagreader.go
> misc: spelling of retrieval

- core/commands/bootstrap.go
- test/sharness/t0120-bootstrap.sh
This is probably what should happen here.
> Use prefix in bootstrapWritePeers

- mfs/dir.go
- mfs/mfs_test.go
Credit goes to @ridewindx
Closes #4800
License: MIT
> fix(mfs): Directory.Path not working, add test

- codecov.yml
> misc: allow for some coverage fall on commit

- contribute.md
> misc: remove link to IPFS paper in contribute.md

- core/commands/stat.go
> cmds/stat: remove useless header if not polling

- core/coreunix/add.go
Something broke imports on master, this is a fix
> fix unused imports

- cmd/ipfs/daemon.go
- cmd/ipfs/init.go
- cmd/ipfs/ipfs.go
- cmd/ipfs/main.go
- commands/legacy/command.go
- commands/legacy/legacy.go
- commands/legacy/legacy_test.go
- commands/legacy/request.go
- commands/legacy/response.go
- commands/request.go
- core/commands/add.go
- core/commands/bitswap.go
- core/commands/block.go
- core/commands/cat.go
- core/commands/commands.go
- core/commands/commands_test.go
- core/commands/files.go
- core/commands/filestore.go
- core/commands/get.go
- core/commands/get_test.go
- core/commands/helptext_test.go
- core/commands/object/object.go
- core/commands/object/patch.go
- core/commands/pubsub.go
- core/commands/repo.go
- core/commands/root.go
- core/commands/stat.go
- core/corehttp/commands.go
- package.json
~~Blocked on: https://github.com/ipfs/go-ipfs-cmds/pull/104~~
Resolves: https://github.com/ipfs/go-ipfs/issues/3266
> gx: update go-ipfs-cmds

- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs 0.4.15-rc1

- .gx/lastpubver
@whyrusleeping, don't forget to tag it.
> gx: release 0.4.15-rc1

- core/commands/pin.go
I'm looking to get into contributing to IPFS, so I'm taking a look at #4414. I'm not actually entirely sure how significant this might be, but it does look like it has a possibility of hanging.
> Fix goroutine leak in pin verify

- cmd/ipfs/dist/README.md
Fix typo of sudo install command.
> Fix typo of sudo install command

- cmd/ipfs/daemon.go
- cmd/ipfs/ipfs.go
- cmd/ipfs/main.go
- core/core.go
Are these sorts of PRs welcome?
> Remove leftover bits of code.

- cmd/ipfswatch/main.go
- fuse/ipns/ipns_test.go
- fuse/ipns/ipns_unix.go
- fuse/ipns/link_unix.go
- fuse/mount/fuse.go
- fuse/readonly/ipfs_test.go
- fuse/readonly/readonly_unix.go
- package.json
> fix the duplicate (multiple versions) sys import

- test/sharness/lib/iptb-lib.sh
> cat iptb logs on iptb failure (for debugging CI)

- core/builder.go
> Fix how filestore is hooked up.

- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs v0.4.16-rc3

- .gx/lastpubver
> publish the gx 0.4.16-rc3 release

- .gx/lastpubver
- CHANGELOG.md
- package.json
- repo/config/version.go
> Ipfs v0.4.17

- thirdparty/cidv0v1/blockstore.go
> add GetSize method to the v0v1 blockstore

- docs/gateway.md
reported by @sixcorners in https://github.com/ipfs/go-ipfs/pull/5393#issuecomment-417908209
> fix the default gateway port

- core/commands/filestore.go
issue #4414 
fix goroutine leaks in filestore.go
License: MIT
> fix goroutine leaks in filestore.go

- docs/gateway.md
> docs: add some minimal read-only API documentation

- core/commands/object/diff.go
License: MIT
Fixes: https://github.com/ipfs/go-ipfs/issues/5468
> fix(object): print object diff error

- core/core.go
> fix offline id bug

- core/commands/files.go
Closes https://github.com/ipfs/go-ipfs/issues/5302.
> files cp: wrap flush error

- core/commands/ls.go
- core/commands/unixfs/ls.go
- fuse/readonly/readonly_unix.go
Closes: https://github.com/ipfs/go-ipfs/issues/5055
License: MIT
> fix(unixfs): issue #5055

- test/sharness/t0040-add-and-cat.sh
> fix(command):update `add --chunker` test

- core/corehttp/webui.go
This brings us on-par with js-ipfs.
> update webui to 2.1.0

- CONTRIBUTING.md
License: MIT
Signed-off-by: Molly Mackinlay <molly@protocol.ai>
> docs: Update link format

- core/core.go
Fixes: https://github.com/ipfs/go-ipfs/issues/5641
License: MIT
> fix(core): ipns config RecordLifetime panic

- core/commands/dag/dag.go
- core/commands/root.go
> cmds/dag: use new cmds lib

- core/commands/repo.go
> fix(cmd/gc): Run func does not return error when Emit func returns error

- core/commands/version.go
> fix(flag/version): flag `all` should have a higher priority

- repo/fsrepo/config_test.go
Probably sneaked in with some outdated PR
> gx: fix broken import

- core/commands/bitswap.go
> commands/bitswap: use new cmds lib

- core/commands/add.go
> fix(cmd/add): progressbar output error when input is read from stdin

- core/commands/root.go
Fixes: https://github.com/ipfs/go-ipfs/issues/5722
License: MIT
> cmds: remove reduntant func

- core/commands/root.go
- core/commands/unixfs/ls.go
- core/commands/unixfs/unixfs.go
> cmds/file: use new cmds lib

- core/commands/bitswap.go
Fixes: https://github.com/ipfs/go-ipfs/issues/5758
License: MIT
> cmds/bitswap: sort wantlist

- core/commands/bitswap.go
- core/commands/block.go
- core/commands/cid.go
- core/commands/keystore.go
- core/commands/name/ipns.go
- core/commands/name/ipnsps.go
- core/commands/name/publish.go
- core/commands/pubsub.go
- core/commands/repo.go
- core/commands/resolve.go
- core/commands/swarm.go
> cmds: use MakeTypedEncoder

- core/commands/block.go
- test/sharness/t0050-block.sh
> block: rm extra output

- core/commands/cat.go
> refact(cmd/cat): remove useless code

- core/commands/add.go
- core/commands/get.go
- package.json
For https://github.com/ipfs/go-ipfs/issues/5694
> gx: update progress bar

- test/sharness/t0240-republisher.sh
We'd frequently hit a race where we'd end up sleeping till *after* the record
was republished.
> testing: slow down republisher sharness test

- cmd/ipfs/util/ulimit.go
> fix: ulimit docs mistake

- core/corehttp/webui.go
Check [release v2.3.2](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.3.2) to see latest changes.
> feat: update to Web UI v2.3.2

- core/corehttp/webui.go
This fixes a regression for adding files/folders introduced in the previous release.
Check the [release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.3.3) for more info.
> chore: update to Web UI v2.3.3

- core/commands/object/patch.go
> refact(cmd/patch): change string to const

- core/commands/dag/dag.go
- core/coreapi/coreapi.go
- core/coreapi/dag.go
- core/coreapi/interface/coreapi.go
- core/coreapi/interface/dag.go
Part of https://github.com/ipfs/go-ipfs/issues/5929
> Port dag commansds to CoreAPI

- assets/assets.go
- cmd/ipfswatch/main.go
- core/corehttp/gateway_test.go
- core/coreunix/add.go
- core/coreunix/add_test.go
- test/integration/addcat_test.go
- test/integration/bench_cat_test.go
- test/integration/three_legged_cat_test.go
I expected way smaller diff, but at least it's ---
> Drop some coreunix code

- core/commands/config.go
> refact(cmd/config): change string option to const

- test/sharness/t0250-files-api.sh
> fix(cmd/mv): dst filename error

- core/corehttp/webui.go
Check the [release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.0) for more info.
It would be awesome if this could be baked into the new release 😇
> chore: update to Web UI 2.4.0

- core/commands/dht.go
> Close #6044

- core/commands/files.go
- go.mod
- go.sum
- package.json
https://github.com/ipfs/go-ipfs/pull/6081 may take a while to merge, this updates go-mfs with changes to `FlushPath`
> gomod: update go-mfs

- docs/config.md
License: MIT
Signed-off-by: Li Zheng <flyskywhy@gmail.com>
> docs: document Gateway.Writable not Gateway.Writeable

- README.md
As pointed out in #6153, waffle is closing.
fixes #6153
> chore: remove waffle

- core/corehttp/webui.go
- Improved MFS file manager
- Opt-in, anonymised, self-hosted web analytics (see https://github.com/ipfs-shipyard/ipfs-webui/pull/985)
- Bug fixes and UX improvements
https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.4
License: MIT
> feat: update to IPFS Web UI 2.4.4

- core/coreapi/swarm.go
🤦‍♂️
fixes https://github.com/ipfs/go-ipfs/pull/6171/files/d21bb1eed85401412ad0e8749f60de75ee27051a#discussion_r271949856
> fix error check in swarm connect

- go.mod
- go.sum
> dep: update quic

- go.mod
- go.sum
Fixes a stream leak and a stdout sync issue (on macos, again).
> Update autonat & cmds

- cmd/ipfs/util/ulimit.go
Reverts ipfs/go-ipfs#6261
(I merged the wrong patch)
> Revert "raise default fd limit to 8192"

- go.mod
- go.sum
Unfortunately, I can't reproduce the bug locally and I'm not sure if my fix is correct. But it shouldn't hurt.
> attempt to fix concurrent websocket write

- go.mod
- go.sum
> dep: update multistream

- go.mod
- go.sum
- test/sharness/t0020-init.sh
- test/sharness/t0021-config.sh
> dep: update go-ipfs-config

- core/coreunix/add.go
- core/coreunix/add_test.go
Trivial fix for #6252
License: MIT
Signed-off-by: Erik Ingenito <erik.ingenito@protocol.ai>
> Test and fix GC/pin bug

- core/node/groups.go
- core/node/helpers.go
> core: fix autonat construction

- go.mod
- go.sum
> dep: update goprocess

- core/commands/object/object.go
> fix formatting in object get

- bin/mkreleaselog
> Add generation of dependency changes to mkreleaselog

- core/commands/p2p.go
- go.mod
- go.sum
> commands/swarm(fix): handle empty multiaddrs

- go.mod
- go.sum
See: https://github.com/libp2p/go-libp2p/issues/644
> disable write coalescing

- version.go
This time, we'll actually build it.
> release: v0.4.21-rc3

- docs/config.md
Feedback and/or more description here please!
> explain what dhtclient does

- CHANGELOG.md
- bin/mkreleaselog
- version.go
Also adds support to mkreleasenotes for generating a list of authors.
> release 0.4.21

- CHANGELOG.md
* Decreased connection initiation latency.
* Better help text.
> CHANGELOG: add some missed changes

- .gitignore
- Makefile
- Rules.mk
- bin/Rules.mk
Also,
* Make it possible to override the PROTOC binary.
* Remove gx targets.
> build: use protoc-gen-* from gomod

- core/corehttp/proxy.go
- go.mod
- go.sum
> Deps: update go-libp2p-http to its new libp2p location

- README.md
Add scoop package for scoop users.
> doc: add another Windows package to README

- go.mod
- go.sum
> dep: update go-bitswap

- go.mod
- go.sum
> dep: update bitswap

- go.mod
- go.sum
Reduces allocations/CPU when handling many inbound connections.
> dep: update swarm/maddr-filter

- go.mod
- go.sum
> dep: update go-multiaddr-dns

- core/commands/pin.go
- core/coreapi/pin.go
- pin/gc/gc.go
> fix: slightly faster gc

- core/commands/external.go
- core/commands/root.go
> feat: add install instructions for external commands

- README.md
> README: update minimum system requirements and recommend OpenSSL

- .circleci/config.yml
Also, use environment variables where appropriate.
> ci: use executors

- go.mod
- go.sum
fixes #6590 (potential non-OSS patent issue)
> switch from ARC cache to a 2Q cache

- core/commands/refs.go
- go.mod
> cmds/refs: fix ipfs refs for sharded directories

- docs/config.md
Adds information to the documentation about https://github.com/ipfs/go-ipfs-config/pull/11!
> docs: add multiple gateway and api addrs

- core/corehttp/webui.go
See https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.1.
> feat: web ui 2.5.1

- core/node/groups.go
- core/node/libp2p/peerstore.go
> fix: close peerstore on stop

- core/commands/swarm.go
These _are_ added/removed from the config.
fixes #4605
> cmds(help): fix swarm filter add/rm help text

- core/corehttp/webui.go
Relevant release notes can be found on [v2.5.5](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.5).
> feat: web ui 2.5.7

- docs/config.md
ConnMgr was missing from the ToC in config.md so I add it.
> docs: add connmgr to config.md toc

- go.mod
- go.sum
- test/dependencies/ma-pipe-unidir/main.go
- test/sharness/lib/test-lib.sh
- test/sharness/t0080-repo.sh
- test/sharness/t0180-p2p.sh
The new version of bitswap should improve server-side ("seeding") performance
with high-latency disks.
> dep: update bitswap for improved performance

- core/corehttp/webui.go
See https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.6.0.
> feat: web ui 2.6.0

- core/corehttp/webui.go
[Release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.7.1).
> feat: web ui 2.7.1

- bin/mkreleaselog
* Continue even when we fail to fetch something.
* Handle more version types.
> mkreleaslog: improve edge-cases

- docs/EARLY_TESTERS.md
> doc(release): add Charity Engine to the early testers programme

- core/commands/keystore.go
Add info about the default key type
> Help text update for 'ipfs key gen'

- cmd/ipfs/dist/LICENSE
- cmd/ipfs/dist/LICENSE-APACHE
- cmd/ipfs/dist/LICENSE-MIT
> Update the license distributed with dist builds to the dual one

- go.mod
- go.sum
Or..., maybe I'll just do this manually so I don't forget to close the issues.
fixes #6841
fixes #6860
> chore(dep): update

- .circleci/config.yml
fixes https://github.com/ipfs/interop/issues/100
> fix: broken interop tests

- go.mod
- go.sum
Dependabot needs to run go mod tidy...
> fix: tidy go.mod

- Dockerfile
Nice and fresh features & bugs.
> feat: update go in docker container

- README.md
Also tweaks "highly suggested" to "highly recommended". IMHO there are levels of recommendation but a suggestion is a boolean.
> docs: update licence info in README

- blocks/blockstoreutil/remove.go
> Fix a typo

- go.mod
- go.sum
fixes a timer race
fixes #7004
> chore(dep): update go-libp2p-yamux

- go.mod
- go.sum
* better logging
* `ipfs bitswap wantlist` now returns both want-haves and want-blocks.
> chore(dep): update bitswap

- go.mod
- go.sum
- test/sharness/t0185-autonat.sh
Specifically, fix an autonat issue where the service wouldn't actually start.
> chore: update deps

- go.mod
- go.sum
> Upgrade go-ipfs-chunker

- cmd/ipfs/daemon.go
- core/node/libp2p/routingopt.go
- docs/config.md
- docs/experimental-features.md
- go.mod
- go.sum
This upgrades to the next DHT version, but in backwards compatibility mode.
> feat(dht): update to cypress DHT in backwards compatibility mode

- go.mod
- go.sum
fixes https://github.com/ipfs/go-ipfs/issues/6986
> chore: update go-ds-badger

- docs/EARLY_TESTERS.md
Just learned about this page! We'd love to help do early testing. Putting myself in as contact person for now, although @icidasset and @dholms are the likely folks to be working on this directly.
> Adding Fission to IPFS early testers page

- go.mod
- go.sum
> chore: update flatfs

- go.mod
- go.sum
Hopefully fixes the message queue bloat issue.
> chore: update bitswap

- go.mod
- go.sum
> chore: update the DHT

- core/corehttp/webui.go
A few fixes: https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.7.5
> feat: webui 2.7.5

- go.mod
- go.sum
> fix: don't hang on bootstrap

- go.mod
- go.sum
Don't abort in Accept when a single relay connection aborts.
> chore: update circuit relay

- go.mod
- go.sum
> chore: update go-ipfs-provider

- go.mod
- go.sum
fixes a CPU issue when canceling find provider requests
> chore: update the dht & routing helpers

- go.mod
- go.sum
fixes a CPU issue when canceling find provider requests
backports #7253
> backport: update the dht & routing helpers

- misc/systemd/ipfs-sysusers.conf
- misc/systemd/ipfs.service
enable restart on crash and run as system user 'ipfs'
_add some optional parameters with short help texts_
> systemd service enhancements + run as system user

- namesys/publisher.go
This is the cherry-picked commit from #7256 that fixes #7244
> IPNS timeout patch from master

- README.md
Update go version required to build
based on mk/golang.mk `MIN_GO_VERSION`
> Update go version required to build

- misc/systemd/ipfs.service
fixes https://github.com/ipfs/go-ipfs/issues/7292
> systemd: disable swap-usage for ipfs

- plugin/plugin.go
> doc(plugin): document plugin config

- go.mod
- go.sum
* Update swarm to prefer QUIC addrs over other addrs.
* Update yamux to increase throughput.
> chore: update libp2p deps

- core/corehttp/hostname.go
Sorry took a while, distracting around me :(
> A bit smarter splitting

- .github/ISSUE_TEMPLATE/config.yml
> Change docs-beta link to its final path

- .circleci/config.yml
- core/commands/refs.go
- core/coreapi/dag.go
- core/corehttp/webui.go
- go.mod
- go.sum
* update quic transport
* fix interop tests
* use bitswap sessions for ipfs refs
* webui v2.9.0
> backport fixes

- docs/production/reverse-proxy.md
Hopefully, we can get the community to start pooling knowledge of how to run go-ipfs in production.
fixes #6402
> doc(prod): start documenting production stuff

- core/node/libp2p/transport.go
- go.mod
- go.sum
> update QUIC, enable the RetireBugBackwardsCompatibilityMode

- cmd/ipfs/daemon.go
- cmd/ipfs/init.go
- cmd/ipfs/ipfs.go
- cmd/ipfs/main.go
- cmd/ipfs/rotate.go
- core/commands/active.go
- core/commands/cid.go
- core/commands/commands.go
- core/commands/config.go
- core/commands/external.go
- core/commands/extra.go
- core/commands/keystore.go
- core/commands/log.go
- core/commands/repo.go
- core/commands/version.go
- go.mod
- go.sum
Moved some of the gross commands code into the commands lib to make things easier.
> refactor cmds

- assets/assets.go
- assets/bindata.go
- assets/bindata_version_hash.go
Set the "modtime" to the start of the IPFS project, and the mode to 0644.
> fix: make assets deterministic

- .circleci/config.yml
- core/commands/dht.go
- core/commands/keyencode/keyencode.go
- core/commands/keystore.go
- core/commands/name/ipnsps.go
- core/commands/name/publish.go
- docs/config.md
- go.mod
- go.sum
- mk/golang.mk
- version.go
Reminder: Do a rebase instead of a merge commit
> Release v0.7.0 rc2

- CHANGELOG.md
- core/commands/id.go
- core/corehttp/webui.go
- version.go
Waiting on changelog before merging. Rebase and merge.
> release v0.7.0 final changes

- core/corehttp/webui.go
<del>https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.3</del>
https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.4
> feat: ipfs-webui v2.11.4

- core/coreapi/object.go
- test/sharness/t0051-object.sh
> fix: return an error when an unknown object type is passed

- docs/RELEASE_ISSUE_TEMPLATE.md
Update IPFS Desktop maintainer in the release template. @lidel not completely sure if it's you, but I changed it to you. Please let me know!
> docs: update IPFS Desktop maintainer

- namesys/dns.go
> show the domain name with the error

- core/corehttp/metrics.go
> revert registration of metrics against unexposed prom registry

- core/commands/files.go
These also end up in API docs.
> Fix: innacuracies in MFS command documentation.

- core/commands/repo.go
> fix: return an error if repo verify is canceled

- docs/experimental-features.md
> docs: clarification of the Strategic Providing functionality

- core/commands/pin/pin.go
> Add info to "pin rm" help about how to tell if pin is indirect

- docs/config.md
Barely worth opening a request for, but I noticed it.
> Fix transposed words in docs/config.md

- bin/mkreleaselog
TODO: Add in asset related files from go-libp2p-asn-utils
> build: ignore generated files in changelog

- go.mod
- go.sum
> update go-libp2p to v0.14.3

- README.md
> link to the actual doc

- test/sharness/t0110-gateway.sh
Context: https://github.com/ipfs/go-ipfs/issues/8230
> test: gateway response for bafkqaaa

- plugin/loader/loader.go
fix function document name `StopDaemon` => `Close`
> fix document error

- core/coreapi/swarm.go
Improve getting the list of peers
> perf: set an appropriate capacity

- docs/examples/go-ipfs-as-a-library/go.sum
- go.mod
- go.sum
(once finished, see the commit message)
Fixes #8378
> make json, cbor, and git codecs error on empty input

- CHANGELOG.md
Some review, particularly of the changes to the `ipfs dag` text and if someone has better highlight/intro text would be appreciated.
> chore: update changelog for v0.10.0

- docker-compose.yaml
> add a docker-compose file

- README.md
> chore: fix link in README.md

- go.mod
- go.sum
> fix: update go-ds-flatfs to v0.5.1

- go.mod
- go.sum
Changes: https://github.com/ipld/go-ipld-prime/compare/v0.14.1...v0.14.2
> chore: update go-ipld-prime

- docs/windows.md
Separated CMD and PowerShell to add additional Windows Installation support.
> Adding PowerShell to Minimal Go Installation

- core/commands/files.go
Let me know if you'd prefer a different commit message. :)
> docs: fix typo

- docs/config.md
Adds docs suggested by @guseggert in https://github.com/ipfs/go-ipfs/pull/8615
> docs: optionalInteger|String|Duration

- go.mod
- go.sum
fixes https://github.com/ipfs/go-ipfs/issues/8724
> chore: update go-path

- core/node/libp2p/discovery.go
fix: https://github.com/ipfs/go-ipfs/issues/8645
> fix(discovery): fix daemon not starting due to mdns startup failure

- core/commands/root.go
- core/coreapi/unixfs.go
- docs/implement-api-bindings.md
- fuse/node/mount_notsupp.go
- test/sharness/t0112-gateway-cors.sh
#8920 But with two more changes
> docs: replace all git.io links with their actual URLs

- docs/config.md
We forgot to uncomment this section in #8901  :sweat_smile:
> docs: Swarm.ResourceMgr.Limits

- docs/environment-variables.md
This should have been updated as part of 967bd6932
> docs(tracing): update env var docs for new tracing env vars

- core/corehttp/webui.go
This bumps ipfs-webui to the latest release.
https://github.com/ipfs/ipfs-webui/releases/tag/v2.15.1
> feat: webui v2.15.1

- docs/changelogs/v0.14.md
- version.go
I want to see a green CI *one last time* before releasing.
> Temp v0.14 rc1

- mk/tarball.mk
Closes https://github.com/ipfs/distributions/issues/737 (when next release happens)
cc @Jorropo
> fix: kubo-source.tar.gz on dist.ipfs.io

- mk/golang.mk
Reopening of #9105 with CI that works.
Closes #7848
> Reproducible Builds: Update GOFLAGS for -trimpath

- core/commands/root.go
Closes https://github.com/ipfs/kubo/issues/8537.
> chore(cmd): add shutdown to CLI help

- .circleci/main.yml
- Dockerfile
> chore: bump Go version to 1.18.5

- cmd/ipfs/daemon.go
- test/sharness/t0064-api-file.sh
- test/sharness/t0110-gateway.sh
> chore: fix undiallable api and gateway files

- bin/mkreleaselog
> fix: pass the repo directory into the ignored_commit function

- core/corehttp/webui.go
https://github.com/ipfs/ipfs-webui/releases/tag/v2.18.0
> chore(deps): webui v2.18.0

- core/corehttp/webui.go
feat: ipfs-webui v2.18.1
https://github.com/ipfs/ipfs-webui/releases/tag/v2.18.1
> feat: ipfs-webui v2.18.1

- Dockerfile
> docs: small typo in Dockerfile

- core/commands/add.go
- test/sharness/t0042-add-skip.sh
> fix: ensure hasher is registered when using a hashing function

- version.go
Related to https://github.com/ipfs/kubo/issues/9237
> chore: bump version to 0.17.0-dev

- config/init.go
> fix: Set default Methods value to nil

- docs/changelogs/v0.17.md
To be filled out for https://github.com/ipfs/kubo/issues/9319
> chore: create v0.17.md changelog

- core/node/libp2p/rcmgr_logging.go
> Fix: Change RM log output to WARN level

- CHANGELOG.md
Related to https://github.com/ipfs/kubo/issues/9417
This PR is to add and link the changelog ahead of the v0.18.0 release.
> Changelog: v0.18.0

- version.go
Related to https://github.com/ipfs/kubo/issues/9417
This PR updates the main dev version as part of the v0.18 release.
> Update Version (dev): v0.18

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
https://github.com/libp2p/go-libp2p/releases/tag/v0.24.2
Fixes #9515. Fixes #9516.
> fix: update go-libp2p to v0.24.2

- config/pubsub.go
- core/node/groups.go
- core/node/libp2p/rcmgr_defaults.go
- docs/changelogs/v0.18.md
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- docs/libp2p-resource-management.md
- go.mod
- go.sum
- test/integration/pubsub_msg_seen_cache_test.go
- version.go
This PR creates release v0.18.1
> Release: v0.18.1

- .circleci/main.yml
- .github/workflows/build.yml
Since https://github.com/protocol/bifrost-infra/issues/2300 is resolved,  
this PR reverts commit a9fdf26eeb94ef6d548aeb6dabb04ddce86df6ec
> fix(ci): revert  fix for bifrost-infra/issues/2300

- CHANGELOG.md
- docs/changelogs/v0.19.md
This PR creates changelog: v0.19
> Create Changelog: v0.19

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
> chore: update iface with routing tests

- config/types.go
Missing method to create OptionalInteger
> feat: add NewOptionalInteger function

- docs/config.md
Addresses https://github.com/ipfs/kubo/pull/9386
cc: @Jorropo
> docs: be clear about swarm.addrfilters

- version.go
This PR updates version as part of the v0.19 release
> Update Version: v0.19

- docs/RELEASE_ISSUE_TEMPLATE.md
- docs/config.md
- docs/delegated-routing.md
> Fix: typos

- test/sharness/t0116-gateway-cache.sh
This PR ensures the test tests what it says it tests.
> fix: t0116-gateway-cache.sh

- README.md
- cmd/ipfs/daemon.go
- core/commands/pubsub.go
- docs/changelogs/v0.19.md
- docs/config.md
- docs/experimental-features.md
> chore: deprecate the pubsub api

- CHANGELOG.md
- docs/changelogs/v0.20.md
This PR creates changelog: v0.20
> Create Changelog: v0.20

- .github/workflows/gateway-conformance.yml
This PR adds gateway-conformance test suite to Kubo.
> ci: add gateway-conformance tests for kubo-gateway

- core/corehttp/gateway.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
This PR is exposing metrics and range request fixes from https://github.com/ipfs/boxo/pull/245
> feat(gw): new metrics and HTTP range support

- version.go
This PR updates version as part of the v0.20 release
> Update Version: v0.20

- core/corehttp/webui.go
see https://github.com/ipfs/ipfs-webui/releases/tag/v3.0.0
> feat: webui@3.0.0

- cmd/ipfs/daemon.go
- core/node/groups.go
- core/node/libp2p/routing.go
- core/node/libp2p/routingopt.go
- docs/changelogs/v0.19.md
- version.go
This PR creates release v0.19.2
> Release: v0.19.2

- CHANGELOG.md
- docs/changelogs/v0.21.md
This PR creates changelog: v0.21
> Create Changelog: v0.21

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-build.yml
- .github/workflows/gateway-conformance.yml
- .github/workflows/gobuild.yml
- .github/workflows/golang-analysis.yml
- .github/workflows/golint.yml
- .github/workflows/gotest.yml
- .github/workflows/sharness.yml
> ci: skip build on PRs modifying MDs only

- test/cli/delegated_routing_http_test.go
> test: add streaming delegated routing test

- docs/config.md
This updates docs to match new values from https://github.com/ipfs/kubo/pull/9326
> docs: Reprovider config

- plugin/loader/loader.go
> plugin: fix non-deterministic loading order

- docs/changelogs/v0.21.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/sharness/t0123-gateway-json-cbor.sh
> feat(gateway): human error pages, dag-cbor/dag-json preview

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
> chore: bump to boxo 0.10

- version.go
This PR updates version as part of the v0.21 release
> Update Version: v0.21

- core/corehttp/webui.go
see https://github.com/ipfs/ipfs-webui/releases/tag/v4.0.2
> feat: webui@4.0.2

- core/commands/swarm.go
Adds some clarity to resolve user confusion around #9895
> [skip changelog] docs: clarify contract of ipfs swarm connect

- core/node/libp2p/relay.go
Hello 👋 
This PR is aimed to fix reported bug in here https://discuss.ipfs.tech/t/kubo-relay-ignored-options-is-this-done-on-purpose/16739.
> fix(relay): apply user provided options [skip changelog]

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
> chore: bump boxo to v0.11.0 for release [skip changelog]

- version.go
This PR updates version as part of the v0.22 release
> Update Version: v0.22

- docs/changelogs/v0.21.md
This is a PR with cosmetic fixes for v21 changelog.
Feel free to add more, if needed
> docs: changelog v0.21 fixes

- .github/workflows/gateway-conformance.yml
> ci: add workflow_dispatch to gateway conformance

- core/node/provider.go
> chore: remove outdated comment

- .github/workflows/gateway-conformance.yml
- docs/changelogs/v0.23.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/gateway_test.go
- test/dependencies/go.mod
- test/dependencies/go.sum
This PR aims to test minimal fix from https://github.com/ipfs/boxo/pull/440  against minimal  test from https://github.com/ipfs/gateway-conformance/pull/131.
If tests pass, we can merge this and unblock both of the above PRs.
> fix(gw): useful IPIP-402 CARs on not found errors

- Dockerfile
> docker: change to releases that follow debian's updates

- .github/workflows/docker-image.yml
> ci: allow custom tags in docker-image workflow

- core/corehttp/webui.go
Update to webui v4.1.1
see: https://github.com/ipfs/ipfs-webui/releases/tag/v4.1.1
Only has translation updates
> deps: webui v4.1.1 [skip changelog]

- core/commands/block.go
- core/node/libp2p/rcmgr.go
- core/node/libp2p/rcmgr_defaults.go
- docs/config.md
- docs/libp2p-resource-management.md
- peering/peering.go
Some text corrections, guessing no need to add to changelog.
> Text corrections [skip changelog]

- docs/changelogs/v0.23.md
> changelog: generalize fuse 9044's entry

- version.go
This PR updates version as part of the v0.23 release
> Update Version: v0.23

- .github/workflows/gateway-conformance.yml
bump gateway-conformance version,
merge after: https://github.com/ipfs/gateway-conformance/pull/172
> [skip changelog] ci: gateway-conformance v0.4

- docs/changelogs/v0.23.md
> docs: capitalize headers for consistency

- client/rpc/object.go
- client/rpc/path.go
- client/rpc/unixfs.go
- core/commands/add.go
- core/commands/object/diff.go
- core/coreapi/object.go
- core/coreapi/path.go
- core/coreapi/unixfs.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Tracks https://github.com/ipfs/boxo/pull/481
> chore: update boxo for structification of ImmutablePath

- version.go
This PR updates version as part of the v0.24 release
> Update Version: v0.24

- core/commands/routing.go
- docs/changelogs/v0.24.md
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- docs/experimental-features.md
- go.mod
- go.sum
- test/cli/dht_legacy_test.go
- test/cli/routing_dht_test.go
- test/dependencies/go.mod
- test/dependencies/go.sum
- version.go
This PR creates release v0.24.0
> Release: v0.24.0

- CHANGELOG.md
- docs/changelogs/v0.25.md
This PR creates changelog: v0.25
> Create Changelog: v0.25

- cmd/ipfs/daemon.go
> docs: clarify ipfs id agent version

- docs/content-blocking.md
Forgive my opening a PR without an issue, just fleshing out the docs a little more as per Héctor's discussion [on discuss.ipfs.tech](https://discuss.ipfs.tech/t/double-hashed-entries-in-denylists/17199/3) in a hopefully uncontroversial way.
> [skip changelog - Docs errata only] Add detail to NOpfs instructions in content-blocking.md

- .github/workflows/build.yml
Fixes #10275
See https://github.com/ipfs/helia/issues/359#issuecomment-1882662783
> ci: fix helia interop

- version.go
This PR updates version as part of the v0.26 release
> Update Version: v0.26 [skip changelog]

- core/commands/profile.go
- profile/profile.go
- profile/profile_test.go
> profile: add trace

- CHANGELOG.md
- docs/changelogs/v0.27.md
This PR creates changelog: v0.27
> Create Changelog: v0.27

- docs/RELEASE_CHECKLIST.md
Avoid spam every time we copy this checklist.
> docs: remove whizzzkid from checklist

- docs/RELEASE_ISSUE_TEMPLATE.md
> docs: add changelog link to release issue template

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/gateway_test.go
- test/dependencies/go.mod
- test/dependencies/go.sum
> refactor: superfluous namespace test redirects

- version.go
This PR updates version as part of the v0.27 release
> Update Version: v0.27 [skip changelog]

- CHANGELOG.md
- docs/changelogs/v0.28.md
This PR creates changelog: v0.28
> Create Changelog: v0.28

- core/coreiface/tests/unixfs.go
> core: fix some typos

- version.go
This PR updates version as part of the v0.28 release
> Update Version: v0.28 [skip changelog]

- CHANGELOG.md
- docs/changelogs/v0.29.md
This PR creates changelog: v0.29
> Create Changelog: v0.29

- version.go
This PR updates version as part of the v0.29 release
> Update Version: v0.29 [skip changelog]

- Rules.mk
- client/rpc/errors.go
> chore: fix some typos

- CHANGELOG.md
- docs/changelogs/v0.30.md
This PR creates changelog: v0.30
> Create Changelog: v0.30

- docs/fuse.md
based on  
https://github.com/ipfs/kubo/issues/2383#issuecomment-187867923 and
https://github.com/ipfs/kubo/issues/2383#issuecomment-1436069101
> docs: "error mounting: could not resolve name"

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
https://github.com/ipfs/boxo/releases/tag/v0.22.0
> chore: boxo v0.22.0

- core/corehttp/webui.go
https://github.com/ipfs/ipfs-webui/releases/tag/v4.3.0
> feat: webui v4.3.0

- cmd/ipfs/kubo/daemon.go
> fix(daemon): panic in periodic bootstrap check

- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-build.yml
- .github/workflows/gateway-conformance.yml
- .github/workflows/gobuild.yml
- .github/workflows/golang-analysis.yml
- .github/workflows/golint.yml
- .github/workflows/gotest.yml
- .github/workflows/interop.yml
- .github/workflows/sharness.yml
- Dockerfile
- docs/examples/kubo-as-a-library/go.mod
- go.mod
Switching back until https://github.com/ipfs/kubo/issues/10501 is resolved.
cc #10436
> fix: switch back to go1.22

- client/rpc/README.md
> docs: replace outdated package paths described in rpc README

- docs/EARLY_TESTERS.md
- docs/RELEASE_CHECKLIST.md
- docs/RELEASE_ISSUE_TEMPLATE.md
- docs/releases_thunderdome.md
Below are improvements introduced during Kubo 0.30 (https://github.com/ipfs/kubo/issues/10436) and its RC's:
> docs: update RELEASE_CHECKLIST.md

- docs/RELEASE_CHECKLIST.md
> chore: clarify dep update in RELEASE_CHECKLIST.md

- docs/RELEASE_CHECKLIST.md
Update distribution publishing procedure
> chore: update RELEASE_CHECKLIST.md

- CHANGELOG.md
- docs/changelogs/v0.32.md
This PR creates changelog: v0.32
> Create Changelog: v0.32

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
minor dependency update without functional change
> chore: update go-unixfsnode

- core/corehttp/webui.go
- docs/changelogs/v0.32.md
https://github.com/ipfs/ipfs-webui/releases/tag/v4.4.0
> feat: ipfs-webui v4.4.0

- docs/config.md
**Description**:  
This pull request addresses multiple issues in the documentation to improve clarity and correctness. Ensuring accurate and clear documentation is essential for both new and existing users to avoid confusion and ensure a better understanding of the system's functionality. Below are the changes made:  
1. **Addresses.API**  
- **Original**: "Multiaddr or array of multiaddrs describing the address to serve the local Kubo RPC API (/api/v0)."  
- **Fixed**: Replaced "address" with "addresses" to align with the description of "Multiaddr or array of multiaddrs." This change ensures consistency in terminology and avoids potential misunderstandings.  
2. **API.Authorizations**  
- **Original**: "bellow"  
- **Fixed**: Corrected the spelling to "below," ensuring proper usage of …
> Typos Update config.md

- docs/changelogs/v0.33.md
> docs(changelog/v0.33): bitswap reprovide changes

- README.md
This is an accumulation of minor spelling and wording changes.
Closes #10627
> Minor spelling and wording changes

- core/commands/config.go
> Add example of setting array to config command help

- docs/changelogs/v0.33.md
> update changelog for boxo and go-libp2p

- docs/changelogs/v0.33.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
> Upgrade to Boxo v0.27.2

- docs/RELEASE_CHECKLIST.md
Fixes from 0.33.1 (https://github.com/ipfs/kubo/issues/10580#issuecomment-2634561087)
> docs(release): update RELEASE_CHECKLIST.md

- core/commands/add.go
This code appears unused, so remove it.
> Remove unused TimeParts struct

- docs/changelogs/v0.33.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- version.go
https://github.com/ipfs/kubo/issues/10580#issuecomment-2657224691
> Release v0.33.2

- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/bin/Rules.mk
- test/dependencies/dependencies.go
- test/dependencies/go.mod
- test/dependencies/go.sum
Latest go-test that is go-multiaddr v0.15 forward compatible
> Update to new go-test

- FUNDING.json
IPFS is applying for Optimism's retroactive public funding round for developer tooling. This PR adds a json file to associate Kubo with IP Shipyard's application
> chore: Create FUNDING.json for Optimism RPF

- core/corehttp/webui.go
- docs/changelogs/v0.34.md
https://github.com/ipfs/ipfs-webui/releases/tag/v4.5.0
> feat: ipfs-webui v4.5.0

- docs/changelogs/v0.34.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
> Upgrade to Boxo v0.29.0

- config/bootstrap_peers.go
- core/commands/cid.go
- core/commands/cid_test.go
- repo/fsrepo/migrations/setup_test.go
- test/cli/files_test.go
> Nonfunctional

- docs/changelogs/v0.34.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
> Upgrade to Boxo v0.29.1

- core/corehttp/webui.go
- docs/changelogs/v0.34.md
https://github.com/ipfs/ipfs-webui/releases/tag/v4.6.0 for https://github.com/ipfs/kubo/issues/10685
> feat: ipfs-webui v4.6

- cmd/ipfs/kubo/daemon.go
- docs/config.md
- fuse/ipns/ipns_unix.go
- Part of https://github.com/ipfs/kubo/issues/10760
- Closes #10710
- Closes #8095
- Closes #2167
- Closes #3013
> fix(fuse): ipns error handling and friendly errors

- docs/environment-variables.md
> docs/env variables: Document LIBP2P_SWARM_FD_LIMIT

- README.md
- docs/changelogs/v0.10.md
- docs/changelogs/v0.4.md
> docs: fix minor typos

- client/rpc/api_test.go
> client/rpc: re-enable tests on windows.

- docs/RELEASE_CHECKLIST.md
Improvements to release process as part of:
- https://github.com/ipfs/kubo/issues/10867
> docs: simplify release process
