ipfs/kubo

blockservice/blockservice.go
routing/dht/routing.go

desc
```
08:25 <•jbenet> whyrusleeping oh another weird fail: try  "ipfs daemon && ipfs add somefile" i get "Error: failed to find any peer in table" :(
08:28 <•jbenet> https://gist.github.com/jbenet/d3bf9c654f206635c09f
08:29 <•jbenet> this BlockService error should propagate back to the client (to the dagService)
08:29 <•jbenet> or maybe bitswap should suppress it. not sure.
```

blockstore: suppress exchange error

---

exchange/bitswap/network/ipfs_impl.go

@jbenet @whyrusleeping 
Fairly certain this'll cause the client worker to hang.

fix(bitswap/network): return when context is done

---

.travis.yml
Makefile
test/Makefile
test/README.md
test/bin/fsh
test/lib/test-lib.sh
test/t0010-basic-commands.sh
test/t0020-init.sh
test/t0030-mount.sh
test/t0040-add-and-cat.sh
test/t0050-block.sh
test/t0060-daemon.sh

This PR adds verbose output for sharness.
* acf4759 Juan Batiz-Benet - (HEAD, origin/sharness-verbose, sharness-verbose) travis: enable verbose sharness output (77 seconds ago)
* 481c19a Juan Batiz-Benet - sharness: note in makefile describing TEST_VERBOSE (8 minutes ago)
* 3510a82 Juan Batiz-Benet - makefile fix: order of env vars (10 minutes ago)
* e5f24dc Juan Batiz-Benet - sharness: expanded on readme (16 minutes ago)
* be4191d Juan Batiz-Benet - sharness: nice verbose ouput (16 minutes ago)
* d06e7e3 Juan Batiz-Benet - sharness: set verbosity from env (2 hours ago)
In particular, addresses #492:
````
Make sharness tests' output helpful when verbose. This means cating certain
files, or running diagnostic commands. I used a construction like:
test_expect_success ".go-ipfs/ has been …
```

sharness: verbose output

---

test/t0020-init.sh

This test was failing on my machine because the newline wasnt being parsed as a newline, it was being printed literally as '\n'. This oughta fix that

fix sharness test for ipfs init output

---

core/bootstrap.go
routing/dht/dht.go
routing/dht/dht_test.go
util/util.go

A WIP 
``` go
// in supervised, call dht.Bootstrap(ctx, 10) or 25. 
// Bootstrap builds up list of peers by requesting random peer IDs
func (dht *IpfsDHT) Bootstrap(ctx context.Context, queries int) {
```
What's the measure of success for this feature? Is the routing table exposed through any commands?

feat(dht) Bootstrap

---

core/commands/bootstrap.go
test/lib/test-lib.sh
test/t0060-daemon.sh

this PR:
- `ipfs bootstrap rm` args now optional. (no-op)
- adds `ipfs bootstrap rm --all` option
- makes sharness remove bootstrap nodes

sharness bootstrap rm

---

cmd/ipfs/init.go
config/config.go
core/bootstrap.go
core/commands/bootstrap.go

this commit adds the "bootstrap add --default" option,
which adds back hardcoded bootstrap peers. this makes it
easy to test ipfs with different bootstrap nodes:
ipfs bootstrap rm --all
ipfs bootstrap add <peer-addr>
<testing to your satisfaction>
ipfs bootstrap rm --all
ipfs bootstrap add --default

bootstrap add --default option

---

commands/channelmarshaler.go
commands/command.go
commands/http/client.go
commands/http/handler.go
commands/option.go
commands/request.go
commands/response.go
commands/response_test.go
core/commands/add.go
core/commands/block.go
core/commands/bootstrap.go
core/commands/commands.go
core/commands/config.go
core/commands/diag.go
core/commands/id.go
core/commands/log.go
core/commands/ls.go
core/commands/mount_unix.go
core/commands/object.go
core/commands/pin.go
core/commands/publish.go
core/commands/refs.go
core/commands/resolve.go
core/commands/root.go
core/commands/swarm.go
core/commands/update.go
core/commands/version.go

This PR lets commands return channels, which allows for streaming object output. Now the add command will show hashes of files as they are added. :smile:
It's pretty satisfying to watch it add the whole go-ipfs directory.
Thanks to the sharness tests for catching various edge-case bugs I wouldn't have noticed. :+1:

Command channel output 

---

core/commands/object.go
merkledag/merkledag.go
merkledag/merkledag_test.go
merkledag/node.go

```
> ipfs object stat -h
USAGE:
ipfs object stat <key> - Get stats for the DAG node named by <key>
'ipfs object stats' is a plumbing command to print DAG node statistics.
<key> is a base58 encoded multihash. It outputs to stdout:
NumLinks        int number of links in link table
BlockSize       int size of the raw, encoded data
LinksSize       int size of the links segment
DataSize        int size of the data segment
CumulativeSize  int cumulative size of object and its references
Use 'ipfs object stat --help' for more information about this command.
```

ipfs object learned stat

---

Makefile

The dockertest/ directory has been moved into test/ and
it has been renamed 3nodetest/ in commit 28cf220d
(dockertest -> test/3nodetest).
License: MIT

Fix test_docker Makefile target and rename it test_3node

---

commands/command.go
core/commands/object.go

This fixes a bug in `object stat` that causes it to error when run locally (not on the daemon). This is because commands must return pointer values (sadly there's no way around it with our crazy `interface{}` magic in the commands package).
I added a check for this that will panic if a developer makes their command return a non-pointer to prevent the mistake from happening in the future.

Assert output types

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/jbenet/go-peerstream/conn.go
Godeps/_workspace/src/github.com/jbenet/go-peerstream/swarm.go
Godeps/_workspace/src/github.com/jbenet/go-peerstream/transport/muxado/muxado.go
Godeps/_workspace/src/github.com/jbenet/go-peerstream/transport/transport.go
Godeps/_workspace/src/github.com/jbenet/go-peerstream/transport/yamux/yamux.go
p2p/net/conn/secure_conn.go
p2p/test/reconnects/reconnect.go
p2p/test/reconnects/reconnect_test.go

This PR updates go-peerstream to handle closed conn GC.
This _may_ fix #496 but not sure.

gc closed conns

---

test/sharness/lib/install-sharness.sh

This is the first step to address issue #500 (Start using `multihash` tool instead of `shasum`)
License: MIT

install-sharness.sh: use git instead of wget and shasum

---

p2p/crypto/bench_test.go

#525 proposes signatures for DHT `Provides` records. Wanted to make sure that the runtime cost is well understood and that feasibility can be evaluated based on empirical evidence.
```
BenchmarkSign1B             1000           2406924 ns/op
BenchmarkSign10B            1000           2360527 ns/op
BenchmarkSign100B           1000           2354136 ns/op
BenchmarkSign1000B           500           2361775 ns/op
BenchmarkSign10000B          500           2415993 ns/op
BenchmarkSign100000B         500           2718051 ns/op
BenchmarkVerify1B          30000             52117 ns/op
BenchmarkVerify10B         30000             50968 ns/op
BenchmarkVerify100B        30000             51037 ns/op
BenchmarkVerify1000B       30000             56768 ns/op
BenchmarkVerify10000B      10000 …
```

benchmark Sign and Verify operations

---

fuse/ipns/ipns_test.go
fuse/ipns/ipns_unix.go
unixfs/io/dagmodifier_test.go

Skip a few tests, and disable all paths for the fuse FS creating new content through that interface.
@jbenet filing this as a PR against yours, just as a formality.

mark ipns as readonly

---

exchange/bitswap/bitswap.go

I kept seeing a lot of extra work being done for no reason. This just provides an early out for the bitswap clientWorkers rebroadcast.

early out if no entries in wantlist

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/jbenet/go-peerstream/listener.go
Godeps/_workspace/src/github.com/jbenet/go-temp-err-catcher/.travis.yml
Godeps/_workspace/src/github.com/jbenet/go-temp-err-catcher/README.md
Godeps/_workspace/src/github.com/jbenet/go-temp-err-catcher/doc.go
Godeps/_workspace/src/github.com/jbenet/go-temp-err-catcher/example/example.go
Godeps/_workspace/src/github.com/jbenet/go-temp-err-catcher/tec_test.go
Godeps/_workspace/src/github.com/jbenet/go-temp-err-catcher/temp_err_catcher.go
p2p/net/conn/dial.go
p2p/net/conn/dial_test.go
p2p/net/conn/interface.go
p2p/net/conn/listen.go
p2p/net/swarm/swarm_listen.go

Our listeners used to hang on accept errors, becuase:
* the listeners were bailing on secure conn fails
* peerstream would hang after 10 temp errors
This PR fixes all that and adds some tests.
thanks so much for finding these @whyrusleeping

fix listener problems

---

cmd/ipfs/daemon.go
cmd/ipfs/gatewayHandler.go
cmd/ipfs/ipfsHandler.go
config/config.go
test/sharness/lib/test-lib.sh

This PR adds a second HTTP server that serves IPFS objects, without giving access to the command API (so that it can be used for public services, like ipfs.io). It is off by default, but will listen when there is an address specified at the `Addresses.Gateway` key in the config.
This also fixes MIME type handling in the gateway so that web apps will be function correctly when served from the gateway or API server.
@zignig's directory listing changes were included. 
A redirect was added from `/webui` on the API server to the hash of the webui app root. In the future, we can change the hash to an IPNS path, and update the webui by publishing to that IPNS name.

Gateway Server

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/jbenet/go-peerstream/conn.go
Godeps/_workspace/src/github.com/jbenet/go-peerstream/listener.go
Godeps/_workspace/src/github.com/jbenet/go-peerstream/stream.go
Godeps/_workspace/src/github.com/jbenet/go-peerstream/swarm.go
core/commands/diag.go
diagnostics/diag.go
p2p/net/swarm/peers_test.go
p2p/net/swarm/swarm.go

Using `Network().Peers()` led to some incorrect things. Namely, duplicate peers showing up in the listing like:
```
ID QmUqfiKyst7x9rUCjpLr9DF45Z1e6SQE2Z8yX8otfnQ4kS
up 432 seconds
connected to 9...
ID Qmd71aoXHswYuKUsvFSWhxx4Yh4RnEaaFguWtr2oCVBJkc
latency: 172186183 ns
ID QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
latency: 356768419 ns
ID QmSoLpPVmHKQ4XTPdz8tjDFgdeRFkpV8JgYq8JVJ69RrZm
latency: 211111688 ns
ID QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z
latency: 237909867 ns
ID QmUqfiKyst7x9rUCjpLr9DF45Z1e6SQE2Z8yX8otfnQ4kS
latency: 0 ns
ID QmUqfiKyst7x9rUCjpLr9DF45Z1e6SQE2Z8yX8otfnQ4kS
latency: 0 ns
ID QmUqfiKyst7x9rUCjpLr9DF45Z1e6SQE2Z8yX8otfnQ4kS
latency: 0 ns
ID QmUqfiKyst7x9rUCjpLr9DF45Z1e6SQE2Z8yX8otfnQ4kS
latency: 0 ns
ID QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm …
```

use conns to enumerate peers for network diagnostic

---

core/core.go
p2p/net/swarm/addr/addr.go
p2p/net/swarm/addr/addr_test.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_addr_test.go
p2p/net/swarm/swarm_dial.go

This adds two checks after a successful conn.Dial
* if the remote peer is not who we wanted, close conn
* if the remove peer is outselves, close conn
(the second is redundant, but the codebase may evolve to end up disabling the
first check, so keeping the second in place helps)
note: Loopback addresses are actually sent out (they _have to be_, in cases
where there are >1 node in the same machine), so many times when trying
connections, nodes end up dialing themselves.

p2p/net/swarm: fix connect self problems

---

p2p/net/swarm/simul_test.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_dial.go

This PR makes swarm dials wait for each other.

p2p/net/swarm: dial once at a time

---

commands/cli/parse.go
core/commands/add.go
core/commands/block.go
core/commands/cat.go
core/commands/id.go
core/commands/ls.go
core/commands/object.go
core/commands/pin.go
core/commands/ping.go
core/commands/publish.go
core/commands/refs.go
core/commands/resolve.go
core/commands/swarm.go

This PR enables stdin input for `add` and `cat`. Also, the CLI parser now splits lines into multiple arguments for  stdin string arguments.
Now you can do some cool things, like:
* `echo "hello, world" | ipfs add`
* `ipfs refs <some object> | ipfs cat`
* `ipfs add <some file> -q | ipfs cat`
It seems like we really might want to just enable stdin for any argument, should we go through and turn it on for everything where it makes sense, or should we make arguments use it by default? It would be cool to be able to `ipfs add <file> -q | ipfs object get`, or even `ipfs bootstrap list | ipfs swarm connect`.

Stdin Input

---

fuse/ipns/ipns_test.go
p2p/net/conn/conn_test.go
p2p/net/conn/secure_conn_test.go
p2p/net/swarm/dial_test.go
util/ctx/fracctx_test.go
util/testutil/ci/ci.go
util/testutil/ci/jenkins/jenkins.go
util/testutil/ci/jenkins/jenkins_test.go
util/testutil/ci/travis/travis.go
util/testutil/ci/travis/travis_test.go

Before, we checked the env vars all over the place.
This PR moves all that into own packages. And adds
some nice env vars, should they become relevant to
other, tougher tests, or orchestration tools. And,
it caught a bug! We weren't checking it right...
@briantigerchow will like this PR.

testutil ci pkgs check env vars

---

importer/importer_test.go
merkledag/merkledag_test.go
pin/pin.go
pin/pin_test.go

This is a PR to get rid of all the nasty race problems.
Now we have tests running all the time for 'em, it'll
be way easier to do it incrementally (thanks @briantigerchow!)
)
Let's get this party started:
- https://build.protocol-dev.com/job/race/16652/console

race fixes

---

util/eventlog/example_test.go
util/eventlog/log.go
util/eventlog/loggable.go

```Go
e := log.EventBegin(ctx, "provide")
e.Done()
e := log.EventBegin(ctx, "provide")
e.Close() // implements io.Closer in case you want to register with some lifecycle management system.
```

feat(eventlog): e := EventBegin; e.Done()

---

repo/fsrepo/assert/assert.go
repo/fsrepo/component/datastore.go
repo/fsrepo/component/datastore_test.go
repo/fsrepo/fsrepo_test.go

RFCR @jbenet @whyrusleeping @mappum 
doh! I forgot to make sure leveldb is only opened once. thanks for catching this @mappum
* **on the package locks** You may be wondering why we don't just share pointers to FSRepos. We
want to manage the lifecycle (unopened, opened, closed) of the FSRepo.
This requires instance variables. Thus each  `fsrepo.At(p)` caller must receive its own goroutine.
* **on having multiple tests** There's a test in `fsrepo` because callers desire the ability to Open
from multiple goroutines. There's a test in `component` because this
is where the actual work needs to go in order to provide the desired
contract. If the `component` package moves, the assurances need to
move along with it.

hotfix(FSRepo) allow multiple goroutines to call 

---

p2p/host/basic/basic_host.go
p2p/protocol/mux.go
p2p/protocol/mux_test.go

lock is made private so outsiders cannot lock the mux.
handlers made private to force outsiders to use accessors.

fix: privatize Mux fields

---

exchange/bitswap/network/ipfs_impl.go
routing/dht/handlers.go
routing/dht/query.go
routing/dht/routing.go

see #573
mitigated adding our own addresses where received from peers
This may not be everything yet.

addr-explosion mitigated adding

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/cenkalti/backoff/.gitignore
Godeps/_workspace/src/github.com/cenkalti/backoff/.travis.yml
Godeps/_workspace/src/github.com/cenkalti/backoff/LICENSE
Godeps/_workspace/src/github.com/cenkalti/backoff/README.md
Godeps/_workspace/src/github.com/cenkalti/backoff/backoff.go
Godeps/_workspace/src/github.com/cenkalti/backoff/backoff_test.go
Godeps/_workspace/src/github.com/cenkalti/backoff/exponential.go
Godeps/_workspace/src/github.com/cenkalti/backoff/exponential_test.go
Godeps/_workspace/src/github.com/cenkalti/backoff/retry.go
Godeps/_workspace/src/github.com/cenkalti/backoff/retry_test.go
Godeps/_workspace/src/github.com/cenkalti/backoff/ticker.go
Godeps/_workspace/src/github.com/cenkalti/backoff/ticker_test.go
Godeps/_workspace/src/github.com/jbenet/go-fuse-version/version_bsd.go
Godeps/_workspace/src/github.com/jbenet/go-fuse-version/version_linux.go
Godeps/_workspace/src/github.com/jbenet/go-fuse-version/version_windows.go
core/commands/mount_darwin.go
core/core.go
exchange/reprovide/reprovide.go
exchange/reprovide/reprovide_test.go

This PR currently has basic functionality, im not sure what else we would need, so im RFCR

basic reprovider implementation

---

core/commands/mount.go

See the note:
// this file is only here to prevent go src tools (like godep) from
// thinking fuseversion is not a required package by non-darwin archs.

core/mount: make non-darwin archs see fuseversion

---

cmd/ipfs/init.go
core/core.go
fuse/ipns/ipns_unix.go
routing/dht/dht.go
routing/dht/dht_test.go
routing/dht/ext_test.go
routing/dht/records.go
routing/dht/routing.go
routing/offline/offline.go
routing/record/record.go
routing/record/validation.go

This PR fixes the issue of `ipfs mount` hanging. The changes required to do so were non-trivial. Included is:
- Offline Node will now load Private Keys for managing ipns locally
- Implementation of an 'offline' routing system that only interfaces with the local datastore
- Initialization of ipns keyspace to an empty directory upon `ipfs init`
The root cause of the hang from before was that when constructing the ipns filesystem before mounting, it would try to resolve the ipns record for your local keypair, and take forever (no context to respect) to resolve since no value exists for that.
Note, while I am RFCR, im still doing a couple things to clean up my changes, just wanted to get the PR out first.

fix fuse mounting issues

---

exchange/bitswap/bitswap.go
exchange/bitswap/decision/engine.go
exchange/bitswap/decision/engine_test.go

Bitswap prioritizes sending of blocks using a PQ. A decision engine worker 
pops tasks off the queue and gives bitswap packaged messages to be sent
to partners.
Before, the engine worker would pop a task and block on send to the
bitswap worker even if the bitswap worker wasn't to receive. Since the
task could have been invalidated during that blocking send, a small
number of stale (already acquired) blocks were sent to partners.
Now, tasks are only popped off of the queue when bitswap is ready to
send them over the wire. This is accomplished by removing the
outboxChanBuffer and implementing a two-phase communication sequence.

fix(bitswap.decision.Engine) send only the freshest messages

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/jbenet/go-reuseport/.travis.yml
Godeps/_workspace/src/github.com/jbenet/go-reuseport/available_unix.go
Godeps/_workspace/src/github.com/jbenet/go-reuseport/impl_windows.go
Godeps/_workspace/src/github.com/jbenet/go-reuseport/interface.go
p2p/net/conn/dial.go
p2p/net/conn/listen.go

This PR makes reuseport check whether the sockopt is available.
Older linux kernels (<=3.8, etc) don't have it. see
http://stackoverflow.com/questions/21454879/how-to-detect-so-reuseport-availibility-at-run-time

p2p/net/conn: only reuseport if avail

---

blockservice/blocks_test.go
blockservice/blockservice.go
blockservice/worker/bench/main.go
blockservice/worker/bench_worker_test.go
blockservice/worker/worker.go
blockservice/worker/worker_test.go
core/core.go
routing/dht/dht_net.go
routing/dht/routing.go
test/epictest/Makefile
test/epictest/addcat_test.go
test/epictest/three_legged_cat_test.go

@whyrusleeping @jbenet RFCR
* :bulb: In debug mode, the worker periodically prints the number of blocks in the provide queue.
* :beetle: When a file is added twice in quick succession, blocks are queued up to be provided twice. We'll probably want to de-dupe.

fix #424: when adding blocks, provide to exchange asynchronously

---

cmd/ipfs/daemon.go
core/corehttp/commands.go
core/corehttp/corehttp.go
core/corehttp/gateway.go
core/corehttp/gateway_handler.go
core/corehttp/webui.go

This PR extracts the core HTTP API functionality from the `go-ipfs/cmds/main` package.
It allows Golang IPFS developers to mount the `core.IpfsNode` onto an HTTP server. It ships with Commands, WebUI, and Gateway options.
An example of where this is used is the `ipfswatch` binary. https://github.com/jbenet/go-ipfs/blob/faded83473dc63a86e7921ef183c967c20379f66/cmd/ipfswatch/main.go#L71
```Go
package http
func ListenAndServe(n *core.IpfsNode, addr ma.Multiaddr, options ...ServeOption) error {}
type ServeOption func(*core.IpfsNode, *http.ServeMux) error {}
func DaemonOption(cctx commands.Context) ServeOption {}
func GatewayOption(n *core.IpfsNode, mux *http.ServeMux) error {}
func WebUIOption(n *core.IpfsNode, mux *http.ServeMux) error {}
```
Alternatively, this package could be called …

refactor(core) extract http

---

core/core.go
core/coreunix/cat.go
test/epictest/addcat_test.go
test/epictest/three_legged_cat_test.go

The previous interface to Cat just took a Key, which didnt allow the user to specify a path, i changed this to accept a path.

fix interface for coreunix.Cat, now takes a path

---

core/commands/dht.go
core/commands/root.go
notifications/query.go
p2p/peer/peer.go
routing/dht/lookup.go
routing/dht/query.go
routing/dht/routing.go

This PR allows the user to control the DHT a little more precisely by giving them the ability to issue `FindPeer`, `FindProvider`, and `GetClosestPeers` requests. I may also consider adding a `GetValue` command if requested.
I also think that @jbenet said his commits 'dont work' so... im not sure what to do with that, WIP i guess?

dht query command

---

core/commands/get.go
core/commands/root.go
test/sharness/t0090-get.sh
thirdparty/tar/extractor.go
unixfs/tar/reader.go

(This PR should be merged after #613)
This adds the `ipfs get` command, which downloads unixfs files to disk. It differs from cat in that it can download directories, and it outputs to a file path instead of Stdout.
It supports some options:
`--output` or `-o`: the path where the output files should be saved
`--archive` or `-a`: output a TAR archive instead of individual files
`--compress` or `-c`: GZIP the output (useful when downloading from a remote daemon, or use with `-a` if you want a .tar.gz.
`--compression-level` or `-l`: The level of compression (1-9)

`ipfs get` Command

---

test/Makefile
test/dependencies/Makefile

This is to avoid problems like those in PR #591 (Fix bad commit sha1 for go-multiaddr-net dependency).
License: MIT

Add "test/dependencies" dir and "godep restore" test

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/jbenet/go-peerstream/.gitignore
Godeps/_workspace/src/github.com/jbenet/go-peerstream/.travis.yml
Godeps/_workspace/src/github.com/jbenet/go-peerstream/conn.go
Godeps/_workspace/src/github.com/jbenet/go-peerstream/swarm.go
Godeps/_workspace/src/github.com/jbenet/go-peerstream/transport/test/ttest.go
exchange/bitswap/bitswap.go
exchange/bitswap/network/interface.go
exchange/bitswap/network/ipfs_impl.go
exchange/bitswap/testnet/network_test.go
p2p/net/interface.go
p2p/net/mock/mock_conn.go
p2p/net/mock/mock_notif_test.go
p2p/net/mock/mock_peernet.go
p2p/net/mock/mock_stream.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_net.go
p2p/net/swarm/swarm_notif_test.go
routing/dht/dht.go
routing/dht/notif.go
routing/kbucket/bucket.go
routing/kbucket/table.go

This PR introduces network notifications. These are
typesafe (with the Notifiee pattern) and well scoped
in their own notification-responder "objects". (I say
"objects" because many times they're just another obj
casted)
The network notifications interface is:
```go
// Notifiee is an interface for an object wishing to receive
// notifications from a Network.
type Notifiee interface {
Connected(Network, Conn)      // called when a connection opened
Disconnected(Network, Conn)   // called when a connection closed
OpenedStream(Network, Stream) // called when a stream opened
ClosedStream(Network, Stream) // called when a stream closed
// TODO
// PeerConnected(Network, peer.ID)    // called when a peer connected
// PeerDisconnected(Network, peer.ID) // called when a peer disconnected
}
```

Network Notifications

---

p2p/peer/addr/addrsrcs.go
p2p/peer/addr/addrsrcs_test.go
p2p/peer/peerstore.go
p2p/peer/peerstore_test.go
p2p/protocol/identify/id.go

This PR reduces the effects of addr-splosion.
receive ground truth from the peer itself.
TTL (for now set to 1hr). After which nodes
must resolve addrs again. (this may be too
aggressive and can be revisited once we bring
in proper addr management)
Related to: #573, #603

AddrSplosion -- Partie Deux Avec Vengeance

---

test/sharness/lib/test-lib.sh

Since commit 76d9d89aff230895dd3bb1171085eb85633fcbc3, there is
"Initializing daemon..." printed on the standard output when
the daemon is started.
This means that tests have to be fixed accordingly.
License: MIT

Fix daemon initialization output change

---

test/sharness/lib/test-lib.sh
test/sharness/t0080-repo.sh
test/sharness/t0090-get.sh

This PR allows sharness tests to run daemon tests when the
FUSE option is off. Unsure why this was previously included,
I'm likley missing something, which I will find out if travis
fails now.
I included some general fixes, too:
- use `>file` not `> file`
- **_always_** make sure variables are in quotes. `"$HASH"`
Also:
- @whyrusleeping: were not escaping.
- @mappum: were accidentally unescaping. check it out.
- @mappum: this _may_ fix your tar problem.

Allow sharness to run daemon without FUSE

---

p2p/net/conn/dial.go
p2p/net/swarm/swarm_dial.go
util/eventlog/loggables/loggables.go

This commit turns all dial logs into log.Events.
Everything's great except for one problem: The LoggableMap I'm using does not
print out things correctly. I gave it peer.IDs, and Multiaddrs and both got
logged as nothing `{}` (didn't even call their String() methods!) So, for now,
this function encodes it when called... This is wrong and should be fixed
before being merged in. Otherwise we  will be constantly encoding peer.IDs and
Multiaddrs without needing to.
@briantigerchow how do you suggest doing this? I don't know my way around your
Loggable things.

p2p/net: dial log -> events

---

core/bootstrap.go
exchange/bitswap/bitswap_test.go
exchange/bitswap/network/ipfs_impl.go
p2p/net/swarm/simul_test.go
test/epictest/bitswap_wo_routing_test.go
test/epictest/three_legged_cat_test.go

Also:
- epictest: added test for bitswap wo routing
- fixed three-legged-cat (i think)

return connected peers as providers

---

core/commands/cat.go
core/commands/get.go
core/commands/ls.go
core/commands/object.go
core/commands/refs.go
core/core.go
core/corehttp/gateway_handler.go
core/corerepo/pinning.go
core/coreunix/cat.go
fuse/ipns/ipns_unix.go
fuse/readonly/readonly_unix.go
path/path.go
path/resolver.go
server/http/ipfs.go
test/epictest/addcat_test.go
test/epictest/three_legged_cat_test.go
unixfs/tar/reader.go
util/key.go

This PR implements a path type for ipfs. The goal, is to avoid type safety problems between using strings and keys to specify an object to work with. My aim with this was utter simplicity, so the type is just a typedefed string, which allows it to be compared via `==`.
I considered making a constructor `path.FromString` that would clean up the input (call `gopath.Clean`, strip off leading `/ipfs/`, etc), But i didnt want people to be able to create a path type outside of the constructor, if it provides extra safety/assumptions

implement path type

---

fuse/ipns/ipns_unix.go
fuse/readonly/readonly_unix.go

This commit changed the "ReadAll" to do proper read requests.
Seeking in fuse mounted fs now works. Note: this is why opening a
mounted video didnt work... we just didnt look at this code in
months.

fuse/ipfs: seeking

---

p2p/net/interface.go
p2p/net/mock/mock_peernet.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_net.go

network interface now allows setting Listeners after the fact.
This is useful to create the network and start listening as
separate steps. And to keep the network up to date on new
addresses the node might have to listen to.

p2p/net: network interface Listen func

---

core/coreunix/add.go
core/coreunix/cat.go
path/path.go
test/integration/addcat_test.go
test/integration/three_legged_cat_test.go

@briantigerchow Let me know how this looks.

address concerns about user interface with new Path type

---

blockservice/worker/worker.go

see: https://gist.github.com/jbenet/6b8b45bde9d9fce17d57
I want to make the goprocess API nicer so it doesnt lead
users into this problem. any ideas?

blockservice/worker: fix proc/limiter sync

---

core/core.go
exchange/bitswap/network/ipfs_impl.go
p2p/host/basic/basic_host.go
p2p/host/basic/natmgr.go
p2p/nat/nat.go
p2p/net/interface.go
p2p/net/mock/mock_notif_test.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_listen.go
p2p/net/swarm/swarm_notif_test.go
routing/dht/dht.go
routing/dht/notif.go

This PR makes the online services start up and register
themselves in the muxer before the network starts listening
officially. This solves one problem we had where bitswap messages
were getting lost becuase they were being received _before_ the
bitswap network interface signed itself up.
This PR also:
- makes network notify as listeners start or close
- makes nat mappings change as the network listeners change
(this is still unable to detect an underlying network change such
as a laptop moving from one network to another. we still need to
listen to such events and readjust our network listeners. a future
PR will add this functionality).

online services started before network listens

---

test/sharness/t0080-repo.sh

The following changes are made to make t0080
cleaner, safer and more canonical:
- remove useless stuff,
- don't use a pipe after ipfs commands,
- use test_must_fail before ipfs commands instead of !
License: MIT

test/sharness: improve t0080

---

core/commands/cat.go
test/sharness/lib/test-lib.sh
test/sharness/t0021-config.sh
test/sharness/t0090-get.sh
test/sharness/t0110-gateway.sh
test/sharness/t0111-gateway-writable.sh
unixfs/io/dagreader.go

This PR makes cat use the proper unixfs filesize
for its length calculations. This should address #705

cat length output now uses unixfs size

---

core/commands/cat.go

I beleive i found a goroutine leak bug, if a cat were to be killed before all the data was read, it wouldnt release the underlying processes. This makes sure to pass the correct context into the DagReader

ensure dagreaders are cleaned up after 'cat' command finishes

---

cmd/ipfs/main.go
test/3nodetest/Makefile
test/3nodetest/bin/save_profiling_data.sh
test/3nodetest/bootstrap/Dockerfile
test/3nodetest/build/.gitignore
test/3nodetest/client/Dockerfile
test/3nodetest/client/run.sh
test/3nodetest/fig.yml
test/3nodetest/run-test-on-img.sh
test/3nodetest/server/Dockerfile
test/3nodetest/server/run.sh

This PR adds profiling data retrieval to the 3-node integration test.
In addition to the logs, profiling data is now saved to the `build` directory after runs. Data is kept for the bootstrap, server, and client nodes.

feat: keep profiling data from test runs

---

README.md
docs/fuse.md

re https://github.com/jbenet/go-ipfs/pull/260, https://github.com/jbenet/go-ipfs/issues/259

docs folder and some fuse docs. closes #259

---

core/commands/add.go
core/coreunix/add.go
test/sharness/t0040-add-and-cat.sh

This PR adds a `-w` or `--wrap-with-directory` flag to `ipfs add`, so that files can have their name preserved. For example, `ipfs add -w file.txt` should output `added <hash>/file.txt file.txt`.

ipfs add -w

---

test/sharness/lib/test-lib.sh

The pattern "cat FILE | COMMAND" can be simplified
to just "COMMAND FILE" when COMMAND accepts files as
arguments.
License: MIT

sharness/test-lib: remove some "cat" followed by |

---

.travis.yml
blocks/set/dbset.go
blockservice/blockservice.go
cmd/ipfs/main.go
commands/http/handler.go
core/commands/ping.go
core/commands/refs.go
core/commands/swarm.go
core/corehttp/gateway_handler.go
core/corerepo/gc.go
diagnostics/diag.go
exchange/bitswap/bitswap.go
exchange/bitswap/network/ipfs_impl.go
exchange/reprovide/reprovide.go
fuse/ipns/ipns_unix.go
fuse/mount/mount.go
fuse/readonly/readonly_unix.go
importer/chunk/splitting.go
merkledag/merkledag.go
namesys/publisher.go
p2p/net/swarm/swarm_listen.go
p2p/net/swarm/swarm_test.go
p2p/protocol/mux.go
p2p/test/backpressure/backpressure_test.go
routing/dht/dht_test.go
routing/grandcentral/client.go
routing/grandcentral/proxy/loopback.go
routing/grandcentral/server.go
tour/tour.go
updates/updates.go

Let's save log.Error for things the user can take action on.
Moved all our diagnostics to log.Debug. We can ideally reduce them
even further.

logs: removed all log.Errors unhelpful to users

---

repo/config/init.go
repo/config/log.go
repo/fsrepo/component/config.go
thirdparty/eventlog/option.go

RFCR @jbenet @whyrusleeping 
This addresses one part of #740. Now, the config is validated before being written to disk. Mismatched types will be rejected instead of being written to disk and breaking the config.

when setting config keys, validate against struct before writing to disk

---

core/coreunix/metadata.go
core/coreunix/metadata_test.go
unixfs/format.go
unixfs/io/dagreader.go
unixfs/pb/unixfs.pb.go
unixfs/pb/unixfs.proto
util/key.go

This allows you to add a Mime-Type to ipfs objects, example:
```
m := &unixfs.Metadata{
MimeType: "application/json",
}
keywithmeta, err := coreunix.AddMetadataToKey(mykey, m, dagservice)
metadata := coreunix.Metadata(keywithmeta, dagservice)
```

implement metadata node for unixfs and other

---

cmd/ipfs/daemon.go
commands/files/multipartfile.go
commands/http/handler.go
commands/http/multifilereader.go
core/corehttp/gateway.go
core/corehttp/gateway_handler.go
core/corehttp/webui.go
repo/config/init.go
test/sharness/t0110-gateway.sh

Miscellaneous changes and fixes for the gateway and command HTTP handler.
* Security fixes (Suborigins, CSRF protection, API server path whitelist)
* Turn on gateway server by default in initial config
* Fixed multipart filename escape bug (now supports names with quotes)

Gateway Changes

---

p2p/peer/addr_manager.go
p2p/protocol/identify/id.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_test.go

- time them out (already was doing that with addrbook)
- keep count to counter symmetric nats

p2p/protocol/identity: smarter tracking observed addrs

---

cmd/ipfs/daemon.go
core/corehttp/webui.go

Otherwise we break users links! cc @mappum

corehttp: allow all webui paths we published.

---

blockservice/worker/worker.go
p2p/net/swarm/swarm_dial.go
thirdparty/notifier/notifier.go

Use of the ratelimiter should be conscious of the ratelimiter's
potential closing. any loops that add work to ratelimiter
should (a) only do so if the rate limiter is not closed,
or (b) prevent limiter while work is added
(i.e. use limiter.Go(addWorkHere))

ratelimiter: fixing rate limiter use

---

exchange/bitswap/bitswap.go

I got this panic:
```
2015/02/12 19:05:18 http: panic serving 127.0.0.1:56989: runtime error: invalid memory address or nil pointer dereference
goroutine 38133 [running]:
net/http.funcÂ·012()
/home/whyrusleeping/go/src/net/http/server.go:1187 +0xb8
github.com/jbenet/go-ipfs/merkledag.(*dagService).Get(0x11632f20, 0x11cc7b30, 0x22, 0x11cc7b30, 0x0, 0x0)
/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/merkledag/merkledag.go:102 +0x160
github.com/jbenet/go-ipfs/path.(*Resolver).ResolvePathComponents(0x11632758, 0x11e66325, 0x2e, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/path/resolver.go:77 +0x1cc
github.com/jbenet/go-ipfs/path.(*Resolver).ResolvePath(0x11632758, 0x11e66325, 0x2e, 0x1, 0x0, 0x0) …
```

fix a panic caused by context cancelling closing a promise channel

---

cmd/ipfs/daemon.go
core/corehttp/commands.go
core/corehttp/corehttp.go
core/corehttp/gateway.go
core/corehttp/gateway_test.go
core/corehttp/ipns_hostname.go
core/corehttp/redirect.go

This allows someone to host a static site by pointing a TXT record at their
content in IPFS, and a CNAME record at an IPFS gateway.
Note that such a setup technically violates RFC1912 (section 2.4; "A CNAME
record is not allowed to coexist with any other data."), but tends to work in
practice.
We may want to consider changing the DNS->IPFS resolution scheme to allow this
scenario to be RFC-compliant (e.g. store the mapping on a well-known subdomain
to allow CNAME records on the domain itself).
Also note that while this has been tested by hand, I don't see a good way to
test it with the existing sharness gateway tests -- how do you mock a DNS entry
from a shell script?

gateway: attempt to resolve hostname to ipfs path

---

repo/fsrepo/fsrepo.go

As I work through examples, I feel like it would be much easier for the fsrepo to tilde expand paths given to it. This makes it much easier for users to write the following code:
```
r := fsrepo.At("~/.go-ipfs")
```
instead of:
```
home := os.GetEnv("HOME")
if len(home) == 0 {
panic("WHAT IS HAPPENING?")
}
r := fsrepo.At(home + "/.go-ipfs")
```

have repo tilde expand paths

---

core/core.go
core/corenet/net.go
core/corerouting/core.go
core/net.go
p2p/host/basic/basic_host.go
p2p/host/host.go
p2p/host/routed/routed.go
p2p/protocol/mux.go
test/integration/core.go

@jbenet tell me what you think of this. I wanted to write code like this:
```
list, err := nd.Listen("/myapp")
for {
con, err := list.Accept()
go handleConnection(con)
}
```
I had a few cool example ipfs apps that i wanted to write using this, but it was ugly (but still very easily possible) without this abstraction.

add dial and listen methods to the core for super awesomeness

---

core/core.go
exchange/bitswap/bitswap.go
exchange/bitswap/decision/engine.go
merkledag/merkledag.go

This PR makes better use of contexts to cancel work that is no longer needed. It also re-introduces the ability to send wantlist updates to peers you are directly connected to. A couple other minor bugfixes are also included.

move blocking calls out of single threaded loops, cancel contexts ASAP

---

p2p/net/swarm/swarm_dial.go

This should address the panic seen in #781 (and potentially others)

fix weird race condition in goprocess that caused a few panics

---

fuse/readonly/readonly_unix.go

In linux, fuse will try to read a 4096 block chunk,  which would cause the read call to return EOF (when the file size is less than 4096) we would return this error up to fuse, and fuse would give the user an `Input/output error`. This makes some more of the sharness tests turn green.

fix fuse reading on linux

---

core/commands/object.go

This changes the "Node" object in the CLI to use strings instead of `[]byte`s, this make the json marshaller use escape codes to print out non printable characters instead of converting the whole thing to base64. So I can now do the following:
```
$ echo '{Data:"Testing!"}'  > file
$ ipfs object put file json
```
It would be nice if `ipfs object put` could accept standard in. ( cc @mappum )
This addresses #769

make it easier to create custom dag objects via the CLI

---

core/commands/dht.go
notifications/query.go
routing/dht/dht.go
routing/dht/handlers.go
routing/dht/routing.go

Implement `ipfs dht get` and `ipfs dht put`. Im open to some feedback on this, but this is just part one of a set of changes for getting ipns working well.

Implement dht put and get CLI commands

---

routing/dht/handlers.go
routing/dht/providers.go
routing/dht/providers_test.go
routing/dht/routing.go

The send in AddProvider was hanging when routing was disabled. Making it respect the context causes the test to pass every time.

make the providers manager respect contexts

---

core/mock.go
fuse/readonly/ipfs_test.go

This achieves around 75% code coverage, which is pretty good considering some of the code is platform specific, and it counts not hitting the error returns.

Add a few tests to fuse/readonly

---

exchange/bitswap/bitswap.go
exchange/bitswap/workers.go

I spent some time debugging why the gateway nodes have been slow recently, and it came down to these sends taking a long time for certain peers. Since bitswap uses a routed peerhost, I think that some peers in the ledger werent connected to, and it was maybe trying to reconnect to them to send them a message.

make wantlist updates to connected peers happen async

---

core/commands/ls.go
core/commands/object.go
test/sharness/t0045-ls.sh

As discussed in #799, this PR pimps the output of `ipfs ls` and `ipfs object links` in text mode to use [text/tabwriter](https://golang.org/pkg/text/tabwriter/) which indents it nicely.
In `ipfs ls` the DAG service is used to lookup the `Data` of the node to find out it's datatype. If it is a directory, it sets the new Links `IsDir` field to true, which is then used by the text marshallers to append a `/` to the name.
I wasn't sure if we want this for `object links` as well. would be trivial to add.
before:
after:

beautify 'ipfs ls' and 'ipfs object links'

---

test/sharness/t0111-gateway-writable.sh

There was basically:
curl ... "$URL 2>curl.out"
instead of:
curl ... "$URL" 2>curl.out
So "curl.out" was not properly overwritten by the curl command.
License: MIT

t0111: fix broken test due to bad double quoting

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/jbenet/go-detect-race/LICENSE
Godeps/_workspace/src/github.com/jbenet/go-detect-race/README.md
Godeps/_workspace/src/github.com/jbenet/go-detect-race/race.go
Godeps/_workspace/src/github.com/jbenet/go-detect-race/race_test.go
Godeps/_workspace/src/github.com/jbenet/go-detect-race/withoutrace.go
Godeps/_workspace/src/github.com/jbenet/go-detect-race/withrace.go
cmd/ipfs/daemon.go
exchange/bitswap/bitswap_test.go
fuse/ipns/ipns_unix.go
fuse/ipns/link_unix.go
fuse/readonly/readonly_unix.go
routing/kbucket/table.go
test/sharness/lib/test-lib.sh
test/sharness/t0040-add-and-cat.sh
test/sharness/t0110-gateway.sh
test/sharness/t0111-gateway-writable.sh

this PR will get our tests back to green

fix the tests

---

p2p/peer/peer.go

peer short tags are still the same length, but skips the first 2 characters which are identical sha256 peerIDs.

peer short tags are improved

---

exchange/bitswap/bitswap.go
exchange/bitswap/workers.go

This PR grabs all the keys that need to be provided and consolidates them into a single buffer of keys. In doing so, it releases the reference to the block being provided, allowing the GC to remove it from memory, and also preventing the HasBlock goroutines from building up blocking on provide sends.

implement a worker to consolidate HasBlock provide calls into one 

---

core/commands/mount_darwin.go
core/commands/mount_nofuse.go
core/commands/mount_unix.go
fuse/ipns/mount_unix.go
fuse/readonly/mount_unix.go
fuse/readonly/readonly_unix.go

Build tag syntax only supports ` `, `,` and `!`
https://github.com/golang/go/blob/84f53339befccbb4c3449955e205a6a727282f10/src/go/build/doc.go#L73
https://github.com/golang/go/blob/84f53339befccbb4c3449955e205a6a727282f10/src/go/build/build.go#L1233

Fix nofuse build tags syntax

---

dev.md

This trivial commit fixes the link to the IPFS paper.

Correct link to paper

---

cmd/ipfs/daemon.go

this more clearly explains that the daemon is listening on the network. it also hints as to how to change the listening ports. this is also related to #874

document how to change daemon ports

---

core/commands/object.go
test/sharness/t0051-object-data/expected_getOut
test/sharness/t0051-object-data/testPut.json
test/sharness/t0051-object-data/testPut.pb
test/sharness/t0051-object.sh

Ipfs object put from stdin

---

core/commands/id.go
core/commands/ping.go
core/corenet/net.go
diagnostics/diag.go
exchange/bitswap/bitswap.go
exchange/bitswap/workers.go
merkledag/merkledag.go
namesys/publisher.go
p2p/net/swarm/swarm_dial.go
pin/pin.go
routing/dht/dht.go
routing/dht/records.go
unixfs/tar/reader.go

context: Always call returned cancel funcs

---

test/sharness/t0045-ls.sh

This makes the following changes:
- remove some superfluous \ at the end of some lines
- use `cat <<-\EOF >expected` to ignore the starting tabs
in the here document
- add missing && after some `cat`
- use test_cmp to compare files
License: MIT

t0045: style cleanup and add missing &&

---

commands/request.go

I wanted to play with the daemons JSON API a little, so I hacked together a tiny [example in go](https://gist.github.com/cryptix/d8635dff3cf0e1b5c41f) that just does the equivalent of `ipfs ls <hash>` .
I only hit a small problem: [commands.NewRequest()](https://godoc.org/github.com/jbenet/go-ipfs/commands#NewEmptyRequest)'s 2nd argument is an unexported map type. This PR removes this. Alternatively we could export it but i don't see much use in that.

commands.NewRequest() has unexported type in it's arguments

---

core/commands/root.go

not exactly elegant, but fixes #871 in the short term. in the mid term, unless more `repo` commands show up, i suggest just replacing `repo gc` simply by `gc`.

`gc` is actually `repo gc`, reflect in docs

---

exchange/bitswap/bitswap.go

This PR fixes the '7MB bursts' that @anarcat reported. While this fix works, if the lower calls 'hang', those goroutines *may* build up, but the contexts are cancelled so they should exit sooner rather than later. Shouldnt be an issue.

respect contexts in a more timely manner

---

core/commands/ls.go
core/commands/object.go

This PR removes `IsDir` from the object plumbing commands, as discussed in #907.
Maybe this can be carried over to the latter `unixfs` specific commands?
They were only used by the marshalers in `ipfs ls` and `ipfs object links`. SInce they operate on different types now, there is no reuse that makes it useful.

ls: introduce specific output types 

---

test/sharness/lib/test-lib.sh
test/sharness/t0110-gateway.sh

This should improve the output messages in case of error.
This will help in case of issues like #892.
License: MIT

sharness: add function to test curl response

---

core/commands/object.go
test/sharness/t0051-object-data/brokenPut.json
test/sharness/t0051-object.sh

This should fix #883.
I added a check after `json.Unmarshall()` to see if the `Data` field __and__ the `Links` slice are empty.
Ideally we could just compare a struct to it's zero value but with the `Links` slice, this doesn't work. (http://play.golang.org/p/mx6qhEM6SC)

ipfs object put: return error if object is empty

---

test/sharness/t0060-daemon.sh

This is a solution to issue #886 (Fix or discard t0060-daemon.sh?)
Tests in this script had been deactivated because
there was no good way to wait until the daemon was
ready. Now that we can use pollEndpoint for that
it's time to reactivate the tests.
License: MIT

t0060: reactivate daemon tests

---

test/sharness/t0051-object.sh

Fix indentation and use > instead of >> to create
an expected file.
License: MIT

t0051: fix indentation

---

test/bin/continueyn

It looks like there were two problems:
- "read" command probably needs the name of the variable
it reads into
- [[ didn't work
This might be because on Linux /bin/sh is sometimes not
bash. For example on Ubuntu it is a symlink to dash.
This should fix issue #927 
License: MIT

test/bin: fix continueyn on Linux

---

core/corehttp/gateway_handler.go
core/corehttp/gateway_test.go

Simplifies web error handling slightly for the getHandler, and fixes the issue of sending a 404 on a failed path resolve.

Fixes issue #924

---

dev/crypto-notes.md

I've added some explanation and references to golang source code; using /dev/urandom instead of /dev/random in GNU/Linux (according to wikipedia) seems to be safe. I'll try to dig some explanation on gpg internal pool (perhaps it would go faster during second generation) and if urandom could be trusted.

add /dev/crypto-notes.md

---

test/sharness/t0110-gateway.sh

the test cases were failing for me on osx. Removing /s fixes them.
It should be fine not to check the /s.

sharness/t0110-gateway: fix /s fail on osx

---

routing/dht/dht_bootstrap.go

move to a less aggressive period. 5m instead of 20s

dht: tone down dht bootstrap

---

test/README.md

See issue #906 (sharness test command coverage) that
discussed this.
License: MIT

test: add README with sharness test command coverage

---

test/sharness/t0090-get.sh

To do that the current tests are move inside a
test_get_cmd() function. This function is then first
called before running the daemon for offline tests
and then after starting the daemon for online tests.
License: MIT

t0090: test ipfs get offline as well as online

---

fuse/mount/fuse.go

FUSE: Stop treating "no errors" as an error

---

thirdparty/pollEndpoint/main.go

After seeing the comments on  #933, I realized the output of the errors was not good.
It now prints the errors as strings. i.e.:
```
error="Get http://127.0.0.1:10044/version: dial tcp 127.0.0.1:10044: connection refused"
```
instead of
```
error="wrong url or endpoint error from http.Get() &url.Error{Op:\"Get\", RL:\"http://127.0.0.1:5836/version\", Err:(*net.OpError)(0xc208032600)}"
```

pollEndpoint: improve error output

---

README.md
misc/completion/ipfs-completion.bash

Does auto-complete for the ipfs commands, subcommands and parameters.
Reported to works for bash and zfs
The completion could be smarter for some parameters (marked as #TODO)

Add a basic command line completion for IPFS

---

test/sharness/t0045-ls.sh

To do that the current tests are move inside a test_ls_cmd() function. This function is then first called before running the daemon for offline tests and then after starting the daemon for online tests.
This will improve sharness test coverage (see issue #906, sharness test command coverage).
License: MIT

t0045: test ipfs ls online as well as offline

---

test/sharness/t0051-object.sh

To do that the current tests are move inside a test_object_cmd() function. This function is then first called before running the daemon for offline tests and then after starting the daemon for online tests.
This will improve sharness test coverage (see issue #906, sharness test command coverage).
License: MIT

t0051: test ipfs object online as well as offline

---

test/sharness/t0030-mount.sh

It looks like some tests that were expected failures
are now always succeeding, so let's mark them as such.
License: MIT

t0030: replace some expect_failure with expect_success

---

routing/dht/handlers.go
routing/dht/records.go
routing/dht/routing.go

A couple small changes to reduce overall dht bandwidth consumption

reduce dht bandwidth consumption

---

namesys/routing.go
routing/dht/records.go
routing/routing.go

created a new interface for optimized public key fetching that the DHT implements, otherwise fall back to a standard routing search.

cache public keys and use better method for fetching

---

test/sharness/t0060-daemon.sh

As `ipfs version` and `ipfs help` are basic commands
it is ok to test them online in t0060.
This will improve sharness test coverage (see issue #906, sharness test command coverage).
License: MIT

t0060: add tests for version and help commands

---

test/README.md

This is related to issue #906 (sharness test command coverage).
License: MIT
Signed-off-by: Christian Couder chriscool@tuxfamily.org

test/README: update sharness test coverage

---

.gobuilder.yml
cmd/ipfs/.gobuilder.yml
cmd/ipfs/README.md
cmd/ipfs/dist/LICENSE
cmd/ipfs/dist/README.md
cmd/ipfs/dist/install.sh

- README.md
- install.sh script
- LICENSE
- trigger in main repo

gobuilder improvements

---

fuse/ipns/mount_unix.go
fuse/mount/fuse.go
fuse/readonly/mount_unix.go
repo/config/mounts.go

Fixes #991
Fixes #968 
```
ipfs config Mounts.FuseAllowOther --bool true
ipfs daemon --mount
```
Currently, `allow_root` does not work for some reason. However, `allow_other` does. Took out the `allow_root` option.

Fuse allow options

---

test/ipfs-test-lib.sh
test/sharness/t0080-repo.sh

This implements a test_sort_cmp() shell function that just sorts the files passed as arguments before  calling test_cmp() on the sorted files. This simplifies test scripts.

Test sort cmp

---

assets/init-doc/quick-start
assets/quick-start.go
test/sharness/lib/test-lib-hashes.sh

`quick-start` has a few examples that need to be on the local gateway server rather than the API server. Test hash has also been updated.

Correct port in quick-start examples

---

test/integration/bench_cat_test.go
test/sharness/t0090-get.sh

these benchmarks ignore the time to start up nodes and add the file.

Add benchmark for just the time it takes to cat

---

exchange/bitswap/decision/engine.go
exchange/bitswap/decision/peer_request_queue.go
exchange/bitswap/decision/peer_request_queue_test.go
exchange/bitswap/workers.go

I dont yet add in any parallelism to bitswap, but I could probably do that on this PR as well.

refactor task queue to have queues per peer

---

test/.gitignore
test/Makefile
test/bin/checkflags
test/sharness/Makefile

This is an alternative implementation of PR #1013 (Run tests with race flag) using a "checkflags" script. 
As for PR #1013 the goal is to make it easier to find race conditions like issue #1012.

Run tests with race flag using checkflags script

---

p2p/crypto/secio/protocol.go

Trying to pin down the cause of #1016

Extend logging when peer handshake detects clashing/same keys

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/mtchavez/jenkins/.gitignore
Godeps/_workspace/src/github.com/mtchavez/jenkins/.travis.yml
Godeps/_workspace/src/github.com/mtchavez/jenkins/Makefile
Godeps/_workspace/src/github.com/mtchavez/jenkins/README.md
Godeps/_workspace/src/github.com/mtchavez/jenkins/jenkins.go
Godeps/_workspace/src/github.com/mtchavez/jenkins/jenkins_suite_test.go
Godeps/_workspace/src/github.com/mtchavez/jenkins/jenkins_test.go
blocks/bloom/filter.go
blocks/bloom/filter_test.go

These did not work before, and had some unnecessary complexity.
Now the filters use only one hashing function, no bignum arithmetic, and gets the additional bit positions by repeatedly hashing the result of prior hash.
Since we're not concerned about crypto hashing here, this should be a win.
External interfaces unchanged.

Make bloom filters simpler

---

test/Makefile
test/bin/checkflags
test/sharness/Makefile

- Fix broken glob dependency from test bin targets
- Ensure sharness test (clean, build, test, aggregate) is run sequentially
- Ensure we don't remake binaries due to missing IPFS-BUILD-OPTIONS

Fix various issues in the test makefiles

---

p2p/net/conn/dial.go
p2p/net/conn/listen.go
p2p/net/conn/reuseport.go

reuseport is a hack. It is necessary for us to do certain kinds of
tcp nat traversal. Ideally, reuseport would be available in go:
https://github.com/golang/go/issues/9661
But until that issue is fixed, we're stuck with this. In some cases,
reuseport is strictly a detriment: nodes are not NATed. This commit
introduces an ENV var IPFS_REUSEPORT that can be set to false to
avoid using reuseport entirely:
IPFS_REUSEPORT=false ipfs daemon
This approach addresses our current need. It could become a config
var if necessary. If reuseport continues to give problems, we should
look into improving it.

reuseport: env var to turn it off

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/jbenet/goprocess/goprocess_test.go
Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go
Godeps/_workspace/src/github.com/jbenet/goprocess/link.go
Godeps/_workspace/src/github.com/jbenet/goprocess/periodic/periodic_test.go

updated goprocess to deal with memory leak

---

cmd/ipfs/main.go

This prevents the commands client from trying to open a node when communicating with the daemon. Although it still prints:
```
Received interrupt signal, shutting down...
```
Which I am not sure I want printed clientside
also, addresses #1053

fix ugly error message when killing commands

---

p2p/net/swarm/swarm_listen.go

I have a sneaking suspicion that listeners might be randomly dying. No way to know other than logging them, and debug logs are impossible to grep through.

log listeners dying as at least a warning

---

README.md

Updated README.md to include instructions on how to start a `go-ipfs` docker container, connect to peers and add files to ipfs. (extra instructions for boot2docker vm too).
Fix for #1052

Added documentation for docker usage. 

---

README.md

I had changed the url to reference /u/ipfs in a commit that is now skipped but it should really be /u/jbenet
Now the docker hub url is hub.docker.com/u/jbenet/go-ipfs

Fix hub.docker.com URL

---

README.md

hub.docker.com/jbenet/go-ipfs didn't have "http://" prefix so the link returned 404

Fixed broken http link in README.md

---

p2p/crypto/secio/al.go
p2p/crypto/secio/protocol.go

The same keys + nonces in secio were being observed. As described in
https://github.com/ipfs/go-ipfs/issues/1016 -- the handshake must
be talking to itself. This can happen in an outgoing TCP dial with
REUSEPORT on to the same address.

secio: better error detection

---

routing/dht/dht_net.go
routing/dht/handlers.go

I've been using loglevel warning for my development/bad-things-potentially-happening-on-gateways logging recently, I'd like to clean it up a bit.

move log messages out of warning level

---

p2p/net/swarm/swarm.go

improving overall transfer speed.
Since our blocksize is 256k, a window size of 256k incurs an extra RTT to send a single block. Bumping the window size to 512k goes a long way to improve the performance of bitswap transfers

increase window size for yamux streams

---

commands/argument.go
commands/cli/parse.go
p2p/net/swarm/swarm.go

New argument type StreamArgs which will create a file object from stdin.

Add support for StreamArgs

---

assets/contact.go
assets/help.go
assets/quick-start.go
assets/readme.go
assets/security-notes.go
cmd/ipfs/daemon.go
cmd/ipfs/init.go
cmd/ipfs/main.go
core/commands/add.go
core/commands/bootstrap.go
core/commands/swarm.go
core/core.go
exchange/bitswap/bitswap.go
exchange/reprovide/reprovide.go
p2p/net/conn/dial.go
p2p/net/conn/secure_conn.go
p2p/net/swarm/swarm_test.go
repo/config/bootstrap_peers.go
repo/config/gateway.go
repo/config/init.go
repo/config/log.go
repo/fsrepo/fsrepo.go
repo/fsrepo/lock/lock.go
repo/fsrepo/serialize/serialize.go
routing/dht/routing.go
routing/mock/dht.go
routing/supernode/client.go
routing/supernode/proxy/loopback.go
routing/supernode/proxy/standard.go
routing/supernode/server.go

We now consider debugerrors harmful: we've run into cases where
debugerror.Wrap() hid valuable error information (err == io.EOF?).
I've removed them from the main code, but left them in some tests.
Go errors are lacking, but unfortunately, this isn't the solution.
It is possible that debugerros.New or debugerrors.Errorf should
remain still (i.e. only remove debugerrors.Wrap) but we don't use
these errors often enough to keep.

remove debugerrors

---

core/bootstrap.go

the random permutaton for bootstrap peers was not working as
intended, returning the first four bootstrap peers always.
this commit fixes it to be a random subset.

core: bugfix: bootstrap random permutation

---

cmd/ipfs/init.go
test/sharness/t0020-init.sh

If the daemon is running we do not want to proceed with an
an initialization.
Return a client error telling the user to kill the daemon
before proceeding with the command.
Fixes #1102

Check to see if the daemon is currently running

---

cmd/ipfs/daemon.go
cmd/ipfs/main.go
commands/http/client.go
commands/request.go
core/corehttp/corehttp.go

Fixes in my quest to make the daemon shut down cleanly on Ctrl+C. Having the daemon stuck, especially without any logging/info to the user of why it's stuck, gives a bad impression to new users, as it's not evident that pressing Ctrl+C a second time will not interrupt an important task and corrupt something.
Spawned from ipfs/webui#28

Harden shutdown logic

---

test/sharness/lib/test-lib.sh
test/sharness/t0030-mount.sh

sharness should only send the kill signal once, as that is what a graceful shutdown should do. in the event that doesn't happen, we should send it again, and then kill -9 to prevent it lingering and messing with other tests.
(this sadly makes our tests longer. but that's good motivation to make graceful shutdown faster)

sharness: wait for graceful shutdown

---

cmd/ipfs/init.go

I think we should lower the default rsa key size to 2048 for now -- until we have a proper focus on securing everything. It's always a pain for new users to get hung on 4096 rsa key gen, when we have not even made sure we're using the keys perfectly correctly yet. (And 2048 is still considered secure)

init: lower default rsa key size to 2048 for now

---

test/sharness/lib/test-lib.sh

As test directories contain a space, we need to
properly quote paths, otherwise we get errors like:
```
umount: /home/christian/gocode/src/github.com/ipfs/go-ipfs/test/sharness/trash is not mounted (according to mtab)
umount: /home/christian/gocode/src/github.com/ipfs/go-ipfs/test/sharness/trash is not mounted (according to mtab)
```
instead of:
```
umount: /home/christian/gocode/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0030-mount.sh/ipfs is not mounted (according to mtab)
umount: /home/christian/gocode/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0030-mount.sh/ipns is not mounted (according to mtab)
```
License: MIT

test-lib.sh: fix umount calls

---

test/sharness/t0030-mount.sh

This should fix issue #1109 (sharness: t0030-mount test_must_fail fails on osx).

sharness: encapsulate ipfs mount

---

README.md
docs/command-completion.md

I have instructions for installing command completion in Linux bash. If anyone would like to add instructions for other shells and OSX. That would be great.

Instructions for installing command completion

---

ipnsfs/system.go

If you have an invalid ipns entry, or simply one that points to a non-existant block, the daemon will fail to initialize completely. This adds a timeout to that process (but still errors out if the object is not found)

Add timeout to ipns resolution at startup

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/whyrusleeping/iptb/README.md
Godeps/_workspace/src/github.com/whyrusleeping/iptb/main.go
cmd/ipfs/daemon.go
core/commands/publish.go
core/commands/resolve.go
core/corehttp/gateway_handler.go
core/corehttp/gateway_test.go
core/corehttp/ipns_hostname.go
core/pathresolver.go
fuse/ipns/common.go
fuse/ipns/ipns_test.go
fuse/ipns/ipns_unix.go
fuse/ipns/mount_unix.go
ipnsfs/system.go
namesys/dns.go
namesys/dns_test.go
namesys/interface.go
namesys/namesys.go
namesys/proquint.go
namesys/publisher.go
namesys/resolve_test.go
namesys/routing.go
path/path.go
test/sharness/t0100-name.sh
test/sharness/t0101-iptb-name.sh

Also changed the ipns dns resolution to use the "dnslink" format

refactored ipns records to point to paths

---

core/commands/add.go
core/coreunix/add.go

The change to an array of readers comes from e096060b
(refactor(core/commands2/add) split loop, 2014-11-06), where it's used
to setup readers for each path in the argument list.  However, since
6faeee83 (cmds2/add: temp fix for -r. horrible hack, 2014-11-11) the
argument looping moved outside of add() and into Run(), so we can drop
the multiple-reader support from add().
Adding a file can create multiple nodes (e.g. the splitter can chunk
the file into several blocks), but:
1. we were only appending a single node per reader to our returned
list, and
2. we are only using the final node in that returned list,
so this commit also adjusts add() to return a single node reference
instead on an array of nodes.
I'm having trouble running the test suite locally:
$ make test
cd cmd/ipfs && go build …

core/commands/add: Change add() to only accept a single reader

---

cmd/ipfs/main.go
commands/cli/helptext.go
commands/cli/parse.go
commands/cli/parse_test.go
repo/fsrepo/fsrepo.go
test/sharness/lib/test-lib.sh
test/sharness/t0021-config.sh
test/sharness/t0080-repo.sh
test/sharness/t0081-repo-pinning.sh
test/sharness/t0100-name.sh

Fixes #1078 
I used the syntax I would usually expect from a unix command. This is a breaking change, but some of this breakage could be avoided with more code.
- short flags no longer use `=`. `-a=1` is now `-a 1` or `-a1`
- sub-command specific flags cannot apear before the sub-command, such as `--bar foo` instead of `foo --bar`
- `ipfs help` no longer works, it was only a by-product of errors being ignored. `ipfs` or `ipfs -h` can be used instead.
Here are some trimmed examples:
```
$ ipfs pin ls --help
-t, --type  string - The type of pinned keys to list. Can be "direct", "indirect", "recursive", or "all". Defaults to "direct"
-n, --count bool   - Show refcount when listing indirect pins
$ ipfs pin ls -t
Error: Missing argument for option 't'
$ ipfs pin ls -t foo
Error: Invalid type …
```

Improve command line parsing

---

p2p/host/basic/basic_host.go

This should close #1143.
I've seen that error sometimes too and meant to fix it, if only for the '%s' not being used properly.

only warn about io.EOF from mux.ReaderHeaders (fixes #1143)

---

core/commands/pin.go
test/sharness/t0080-repo.sh

Please bear with me as these are my first lines of Go code :smile:
This fixes issue https://github.com/ipfs/go-ipfs/issues/1134
I tried following the convention on other files (for example, I named the struct `RefKeyObject` following the pattern on [`LsObject`](https://github.com/ipfs/go-ipfs/blob/master/core/commands/ls.go#L26-L29)), but let me know if I got something wrong.
It follows the usage pattern @jbenet described in the issue:
```bash
vitor@clarisse:~/go/src/github.com/ipfs/go-ipfs$ cmd/ipfs/ipfs pin ls 
QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o direct
vitor@clarisse:~/go/src/github.com/ipfs/go-ipfs$ cmd/ipfs/ipfs pin ls --type=indirect --count                          
QmTumTjvcYCAvRRwQ8sDRxh8ezmrcr88YFU7iYNroGGTBZ indirect 1
QmUFtMrBHqdjTtbebsL6YGebvjShh3Jud1insUv12fEVdA …
```

core/commands: pin ls: display types by default

---

blocks/blockstore/blockstore.go
cmd/ipfs/main.go
commands/cli/helptext.go
repo/fsrepo/fsrepo.go

Commit 1192be196b3d0acca2e2dce5ffd5d12a924fdc5a tried to do this, but
had a simple mistake. Functions returning `bool, error` pretty much
never return `true, anError`, so that branch was never taken.
Also fix the partial sentence in the

blocks: Don't re-Put blocks we already have

---

README.md

Hey, just a small doc fix. I noticed that no data was placed in my host system's folder. wking on IRC pointed out that the folder moved in 0.3.0 and the documentation hasn't been updated.

Fix docker $ipfs_data mount path in README

---

util/util_test.go

im on a perf kick, again. a common bit of code between all 'critical' paths is out hash function. This just makes sure its not bottlenecking us.

add a benchmark for our hash function

---

core/core.go

The issue was that mdns discovery was returning peers before node initialization was completed. 
Node construction right now is kinda sketch, and needs a refactor. But in the meantime, this fixes #1171 and lets people continue using ipfs.

hotfix: dont use nodes context because it might not be set yet

---

p2p/discovery/mdns.go

nodes were failing to connect to eachother on my LAN because they advertised their loopback address instead of their lan local address. just skip loopback addresses because any node on the same machine can connect via any of the interface addresses just the same.

advertise multiple addresses over mdns

---

exchange/bitswap/workers.go

Well, it seems that my perf kick is turning up more bugs than perf improvements... *sigh*
But this one is a pretty ugly and subtle one which i believe is the cause of #1036 
A ticker starts a timer that continuously sends on the given channel, every loop, a new one was being created.
I wrote the following program and let it run for a few minutes, watching the number of context switches start out around an idle 600/s, slowly rise to over 10k/s before i killed the program, and the number of context switches resumed to the normal 600/s.
```go
package main
import (
"fmt"
"time"
)
func main() {
a := make(chan int)
for {
select {
case <-time.Tick(time.Second / 10):
fmt.Println("LOOP")
case <-a:
}
}
}
```
I searched the codebase for any other similar mistakes and found none.

dont create a new ticker each loop

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/codahale/hdrhistogram/.travis.yml
Godeps/_workspace/src/github.com/codahale/hdrhistogram/LICENSE
Godeps/_workspace/src/github.com/codahale/hdrhistogram/README.md
Godeps/_workspace/src/github.com/codahale/hdrhistogram/hdr.go
Godeps/_workspace/src/github.com/codahale/hdrhistogram/hdr_test.go
Godeps/_workspace/src/github.com/codahale/hdrhistogram/window.go
Godeps/_workspace/src/github.com/codahale/hdrhistogram/window_test.go
Godeps/_workspace/src/github.com/codahale/metrics/.travis.yml
Godeps/_workspace/src/github.com/codahale/metrics/LICENSE
Godeps/_workspace/src/github.com/codahale/metrics/README.md
Godeps/_workspace/src/github.com/codahale/metrics/metrics.go
Godeps/_workspace/src/github.com/codahale/metrics/metrics_test.go
Godeps/_workspace/src/github.com/codahale/metrics/runtime/doc.go
Godeps/_workspace/src/github.com/codahale/metrics/runtime/fds.go
Godeps/_workspace/src/github.com/codahale/metrics/runtime/fds_test.go
Godeps/_workspace/src/github.com/codahale/metrics/runtime/fds_windows.go
Godeps/_workspace/src/github.com/codahale/metrics/runtime/goroutines.go
Godeps/_workspace/src/github.com/codahale/metrics/runtime/goroutines_test.go
Godeps/_workspace/src/github.com/codahale/metrics/runtime/memstats.go
Godeps/_workspace/src/github.com/codahale/metrics/runtime/memstats_test.go
Godeps/_workspace/src/github.com/jbenet/go-datastore/Godeps/Godeps.json
Godeps/_workspace/src/github.com/jbenet/go-datastore/measure/measure.go
cmd/ipfs/daemon.go
repo/fsrepo/fsrepo.go

Inspirational command lines:
```
curl -s http://localhost:5001/debug/vars | json-prettyprint
go tool pprof http://localhost:5001/debug/pprof/profile
```

Record Datastore metrics for flatfs and leveldb

---

commands/cli/parse_test.go

This improves go tests in parse_test.go so that it is easier to write more tests and tests are checking more things.
This will help if we want to fix issue #1141 (ipfs cat "multihash too short" error when using stdin).

Improve parse_test.go

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/whyrusleeping/iptb/main.go
test/sharness/t0101-iptb-name.sh
test/sharness/t0130-multinode.sh

This moves each iptb test to its own port range and also ensures that daemons are fully bootstrapped if the `-wait` option is specified to prevent the 'no peers in routing table' errors we were seeing.

increase iptb test stability

---

core/commands/bitswap.go
exchange/bitswap/bitswap.go
exchange/bitswap/bitswap_test.go
exchange/bitswap/decision/peer_request_queue.go
exchange/bitswap/stat.go
exchange/bitswap/workers.go

I havent tested this in the field yet, need to get some better metrics in place first. But this should help out quite a bit with transfer speeds, if my hunch is correct.

try harder to not send duplicate blocks

---

p2p/crypto/secio/protocol.go

Reviewing the secure channel I noticed some places where the comments said something different to what the code did. I have fixed the comments to match the code.
The first thing was in the cipher selection step, the comments said `cmp(hash(lr || rpub), hash(rr || lpub))`
but the code joined those the other way around. Also there was a spot later on where an earlier comment had been copypasted from before, and didn't make sense anymore.
I also noticed a few small improvements that could be made to the cipher selection process, but will post another issue.

make comments match the code in secure channel implementation

---

importer/helpers/helpers.go
test/sharness/t0040-add-and-cat.sh

This has been wrong for a while, and ive known about it for a while, but i finally decided to fix it.

correct the blocksize calculation for link blocks

---

exchange/bitswap/bitswap.go
exchange/bitswap/network/interface.go
exchange/bitswap/testnet/network_test.go
exchange/bitswap/testnet/virtual.go

This is a mild cleanup of bitswap to remove some unused code and return errors from a few more functions because i hate not returning errors when i am able to. Functionally, nothing is changed.
I also removed a test from `exchange/bitswap/testnet` that was testing unused code.

mild refactor of bitswap

---

ipnsfs/system.go

From 93b06f34 (Add timeout to ipns resolution at startup, 2015-04-24, #1133).

ipnsfs/system: Fix 'retreive' -> 'retrieve' typo

---

Godeps/_workspace/src/github.com/whyrusleeping/iptb/main.go

not sure how the tests passed before... __sigh__ can't wait until we no longer have to rewrite imports...

godeps: rewrite import path

---

commands/http/handler.go
core/commands/cat.go
core/commands/get.go
core/commands/ls.go
core/commands/object.go
core/commands/publish.go
core/commands/refs.go
core/corehttp/gateway_handler.go
core/corerepo/pinning.go
core/coreunix/cat.go
core/pathresolver.go
fuse/readonly/readonly_unix.go
ipnsfs/system.go
path/resolver.go
test/sharness/x0111-gateway-writable.sh

Following the discussion of #1150, we need to be able to pass a context to core.Resolve() so that a user is able to stop it.

core: add context.Context param to core.Resolve()

---

path/resolver.go
path/resolver_test.go

I'm not entirely clear on Go's scoping (there's some text I can't
quite parse [here][1]), but it seems like the := version (because this
is the first time we use 'err') was masking the function-level 'nd'
just for this if block.  That means that after we get out of the if
block and return to the start of the for-loop for the next pass,
nd.Links would still be pointing at the original object's links.
This commit drops the :=, which fixes the earlier:
$ ipfs ls QmXX7YRpU7nNBKfw75VG7Y1c3GwpSAGHRev67XVPgZFv9R/static/css
Error: no link named "css" under QmXX7YRpU7nNBKfw75VG7Y1c3GwpSAGHRev67XVPgZFv9R
so we get the intended:
$ ipfs ls QmXX7YRpU7nNBKfw75VG7Y1c3GwpSAGHRev67XVPgZFv9R/static/css
Qme4r3eA4h1revFBgCEv1HF1U7sLL4vvAyzRLWJhCFhwg2 7051 style.css
It also means we're probably missing (or …

path/resolver: Fix recursive path resolution

---

p2p/crypto/secio/interface.go
p2p/crypto/secio/protocol.go
p2p/net/conn/dial_test.go
p2p/net/conn/secure_conn.go
p2p/net/conn/secure_conn_test.go

We had a very nasty problem: handshakes were serial so incoming
dials would wait for each other to finish handshaking. this was
particularly problematic when handshakes hung-- nodes would not
recover quickly. This led to gateways not bootstrapping peers
fast enough.
The approach taken here is to do what crypto/tls does:
defer the handshake until Read/Write[0]. There are a number of
reasons why this is _the right thing to do_:
- it delays handshaking until it is known to be necessary (doing io)
- it "accepts" before the handshake, getting the handshake out of the
critical path entirely.
- it defers to the user's parallelization of conn handling. users
must implement this in some way already so use that, instead of
picking constants surely to be wrong (how many handshakes to run
in …

net/p2p + secio: parallelize crypto handshake

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/rs/cors/.travis.yml
Godeps/_workspace/src/github.com/rs/cors/LICENSE
Godeps/_workspace/src/github.com/rs/cors/README.md
Godeps/_workspace/src/github.com/rs/cors/bench_test.go
Godeps/_workspace/src/github.com/rs/cors/cors.go
Godeps/_workspace/src/github.com/rs/cors/cors_test.go
Godeps/_workspace/src/github.com/rs/cors/examples/alice/server.go
Godeps/_workspace/src/github.com/rs/cors/examples/default/server.go
Godeps/_workspace/src/github.com/rs/cors/examples/goji/server.go
Godeps/_workspace/src/github.com/rs/cors/examples/martini/server.go
Godeps/_workspace/src/github.com/rs/cors/examples/negroni/server.go
Godeps/_workspace/src/github.com/rs/cors/examples/nethttp/server.go
Godeps/_workspace/src/github.com/rs/cors/examples/openbar/server.go
Godeps/_workspace/src/github.com/rs/cors/utils.go
Godeps/_workspace/src/github.com/rs/cors/utils_test.go
commands/http/handler.go
commands/http/handler_test.go

Add CORS middleware handler to the API.

---

.travis.yml
Makefile
core/commands/config.go
test/sharness/lib/test-lib.sh
test/sharness/t0021-config.sh

This PR:
- config set: allow arbitrary json input
- sharness: randomize swarm address too.
- travis: use the KVM setup
- travis-ci: make test_all_commits
Ideally, after this, our travis runs:
- will randomize Swarm addr (and stop clashing \o/)
- will run faster (kvm setup)
- will test all commits.
Note: after this PR users can set arbitrary json input to config:
ipfs config --json Addresses.Swarm '["/ip4/0.0.0.0/tcp/4002"]'
A future commit should introduce "-" as a value param (or --stdin)
to allow users to give the value in stdin.

Get travis to test all commits

---

core/commands/swarm.go

Issue #873.
A small change to get my feet wet and used to the code base. =)

Fix documentation on swarm connect.

---

commands/cli/parse.go
commands/cli/parse_test.go

This should fix issue #1141 (ipfs cat "multihash too short" error when using stdin).

Improve stdin parsing

---

core/commands/add.go

This cuts add time by a lot. we were being dumb, there was no reason to flush after the importer call because we do all our pinning at once after the add completes.

remove unnecessary flush, and buffer output channel

---

.travis.yml
exchange/bitswap/bitswap_test.go

Travis has been timing out recently. the bitswap test is massive.
it should not run parallel there and should be smaller.
See #1249

bitswap/test: fix timeout on travis

---

test/sharness/t0040-add-and-cat.sh

These tests make sure that issue #1141 (ipfs cat "multihash too short" error when using stdin) is fixed and also adds more tests related to changes made in PR #1238.
License: MIT

t0040: add tests for ipfs cat with stdin

---

core/commands/dns.go
core/commands/ipns.go
core/commands/name.go
core/commands/publish.go
core/commands/resolve.go
core/commands/root.go
core/corehttp/gateway_test.go
core/corehttp/ipns_hostname.go
core/pathresolver.go
fuse/ipns/ipns_test.go
fuse/ipns/ipns_unix.go
ipnsfs/system.go
namesys/base.go
namesys/dns.go
namesys/dns_test.go
namesys/interface.go
namesys/namesys.go
namesys/namesys_test.go
namesys/proquint.go
namesys/publisher.go
namesys/routing.go
path/path.go
path/resolver_test.go
test/sharness/t0100-name.sh

There are detailed notes in the individual commits, but the meat is in
the opening "namesys: Add recursive resolution".  This is a work in
progress towards the separation sketched out [here][1] and endorsed
[here][2].  For example, with this PR you can:
$ ipfs dns ipfs.tremily.us
/dnslink/tremily.us
$ ipfs dns tremily.us
/dnslink/tremily.us
$ ipfs dns --recursive ipfs.tremily.us
/ipns/QmbqDJaoZYoGNw4dz7FqFDCf6q9EcHoMBQtoGViVFw2qv7
However, I'm currently sticking on the multihash encoding.  The
/ipns/… and /ipfs/… multihashes are base-58, but there's also the
proquint encoding.  However, proquint isn't a *protocol*, you can have
proquint-encoded multihashes in the IPNS and IPFS protocol spaces.
How do we distinguish that?  The heavy approach is:
/ipfs-proquint/…
/ipns-proquint/…
in which …

Rework mutable namespace resolution to handle recursion

---

cmd/ipfs/main.go
core/commands/refs.go

errors were being ignore in main.go, and on top of that, errors returned by readers cant be passed over http.

fix silent refs failure

---

commands/cli/parse.go
commands/cli/parse_test.go

This should fix issue #1260 (Ipfs crashes when run as a node subprocess).
This is based on top of @lgierth 's PR #1255 (parse: fix handling of unwanted stdin) as it modifies the same line of code.

Stdin parsing optional arg

---

ipnsfs/system.go

This error always shows on shutdown, no matter what, dropping it down to a notice for now.

silence error log on shutdown

---

exchange/bitswap/README.md
exchange/bitswap/bitswap.go
exchange/bitswap/bitswap_test.go
exchange/bitswap/decision/engine.go
exchange/bitswap/decision/engine_test.go
exchange/bitswap/decision/peer_request_queue.go
exchange/bitswap/message/message.go
exchange/bitswap/message/message_test.go
exchange/bitswap/network/interface.go
exchange/bitswap/network/ipfs_impl.go
exchange/bitswap/peermanager.go
exchange/bitswap/stat.go
exchange/bitswap/testnet/network_test.go
exchange/bitswap/testnet/virtual.go
exchange/bitswap/testutils.go
exchange/bitswap/wantmanager.go
exchange/bitswap/workers.go

This PR moves all wantlist update logic into the wantmanager, this ensures that outgoing messages are synchronized and coalesced as needed. This greatly improves bitswap performance and correctness.

large refactor of bitswap, implement wantmanager to manage wantlist

---

repo/fsrepo/lock/lock.go
test/sharness/t0020-init.sh

I beleive that i've solved the permissions error in t0020-init.sh
the Lock function arbitrarily returns a different error that doesnt mean what you expect it to.
this has been run quite a four times with no repro of the issue, assuming its fixed

trying to debug permissions failure

---

core/pathresolver.go
core/pathresolver_test.go

If no path after `/ipfs/` or `/ipns/` is given, then the daemon will
panic with a slice bounds out of range error. This checks to see if we
have anything after `ipfs` or `ipns`.

Daemon panics if no path is given

---

test/sharness/t0040-add-and-cat.sh

Let's test 'ipfs add' with stdin input too.
License: MIT

t0040: test ipfs add with stdin

---

core/corehttp/ipns_hostname.go

fixes #1234 & #1267
@jbenet PTAL

Fix: dnslink domain resolving was broken; Add: no caching for those

---

test/sharness/t0060-daemon.sh

If the names are reused, you might stare at the wrong output from another command, wondering what is going on.

sharness/t0060-daemon: don't reuse expect/actual names

---

cmd/ipfs/ipfs.go
commands/cli/parse.go
commands/response_test.go
core/commands/bootstrap.go
core/commands/commands.go
core/commands/diag.go
core/commands/diag_test.go
core/commands/ls.go
core/commands/mount_darwin.go
core/commands/object.go
core/commands/refs.go
core/commands/repo.go
core/commands/root.go
core/commands/swarm.go
core/commands/tour.go
core/commands/tour_test.go
core/commands/update.go
exchange/bitswap/message/message_test.go
merkledag/traverse/traverse_test.go
p2p/crypto/secio/protocol.go
p2p/protocol/mux_test.go
repo/config/config.go
test/integration/addcat_test.go
test/integration/bench_cat_test.go
test/integration/grandcentral_test.go
test/integration/three_legged_cat_test.go
test/supernode_client/main.go
util/ctx/ctxio_test.go
util/testutil/gen.go

Cleanup tour

---

core/commands/add.go
core/corehttp/gateway_handler.go
core/coreunix/add.go
core/coreunix/metadata_test.go
fuse/readonly/ipfs_test.go
importer/helpers/dagbuilder.go
importer/helpers/helpers.go
importer/importer.go
importer/importer_test.go
merkledag/merkledag_test.go
unixfs/mod/dagmodifier.go
unixfs/mod/dagmodifier_test.go

this does the pinning for the add command inline (as it was intended to be) instead of after the fact. This has a significant perf improvement over the current speed of add, and that improvement increases the larger the file being added is.

change pinning to happen in a callback

---

repo/fsrepo/fsrepo.go
test/sharness/t0020-init.sh

Add test for cat error message when `ipfs init` hasn't been run

---

repo/fsrepo/lock/lock.go

this should address the bug that @cryptix and @zignig ran into.
```
zignig | is anyone else getting Error: can't Lock file "/root/.ipfs/repo.lock": has non-zero size , on the latest master ?                                               
zignig | command line commands started failing.
```

catch other error that means the file is locked

---

exchange/bitswap/bitswap.go
exchange/bitswap/wantmanager.go
exchange/bitswap/workers.go
test/integration/bitswap_wo_routing_test.go

This PR makes bitswap really fast. but the organization is a bit weird, some feedback would be nice

move findproviders out of critical path

---

test/sharness/t0101-iptb-name.sh
test/sharness/t0130-multinode.sh

Otherwise they clash with each other if running on the same machine

iptb sharness tests: randomize ports

---

routing/dht/providers.go

This was broken, its better now. provider records still arent signed, but now our gateways wont inadvertently run themselves out of memory.

fix rampant memory leak in providers records storage

---

core/commands/name.go

Change help text to display proper results from an `ipfs name resolve`.

Text under `ipfs name --help` incorrect

---

blockservice/test/blocks_test.go
blockservice/test/mock.go
merkledag/merkledag_test.go

fix up some dependencies so i dont run into a loop dependency when working on the records spec.

fix up some dependencies to avoid circular record deps

---

core/commands/ls.go
core/commands/mount_unix.go
core/commands/pin.go
core/commands/refs.go
fuse/ipns/ipns_test.go
importer/balanced/balanced_test.go
importer/chunk/splitting_test.go
importer/trickle/trickle_test.go
p2p/test/backpressure/backpressure_test.go
p2p/test/reconnects/reconnect_test.go
util/testutil/gen.go

Swap all 'crypto/rand' rng in tests with 'math/rand'

---

core/commands/object.go
routing/record/record.go

This PR implements a basic DAG object patching utility, and another command to create new objects.

implement patch command

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/cheggaaa/pb/README.md
Godeps/_workspace/src/github.com/cheggaaa/pb/format.go
Godeps/_workspace/src/github.com/cheggaaa/pb/pb.go
Godeps/_workspace/src/github.com/cheggaaa/pb/pb_nix.go
Godeps/_workspace/src/github.com/cheggaaa/pb/pb_test.go
Godeps/_workspace/src/github.com/cheggaaa/pb/pb_x.go

This reduces the number of race conditions found with:
```
make GOFLAGS=-race verbose=t deps t0090-get.sh
```
See #1012 (ipfs get race conditions) and #1323 (Revert "godeps: update everything to master").
License: MIT

Godeps: update cheggaaa/pb to the latest version

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/chriscool/go-sleep/LICENSE
Godeps/_workspace/src/github.com/chriscool/go-sleep/README.md
Godeps/_workspace/src/github.com/chriscool/go-sleep/go-sleep.go
test/Makefile
test/sharness/Makefile
test/sharness/lib/test-lib.sh

This is because sleep cannot portably sleep for less than one second as discussed in PR #1326.

Use github.com/chriscool/go-sleep

---

p2p/protocol/identify/id.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_test.go

p2p/protocol/identify: dont double count observers
If the same peer observed the same address twice, it would be double
counted as different observations. This change adds a map to make sure
we're counting each observer once.
This is easily extended to require more than two observations, but i have
not yet encountered NATs for whom this is relevant.
p2p/net/identify: clump addr observers into groups
Different mutliaddrs is not enough. Nodes may share transports. NAT port
mappings will likely only work on the base IP/TCP port pair. We go one step
further, and require different root (IP) addrs. Just in case some NATs
group by IP. In practice, this is what we want: use addresses only if hosts
that are on different parts of the network have seen this address.

Better symmetric NAT avoidance.

---

cmd/ipfs/daemon.go
core/corehttp/corehttp.go

Prints out the chosen port and puts it into the config so the cli works over it too.
Fixes #1288

httpGw: make /tcp/0 work

---

exchange/bitswap/wantmanager.go

got tired of not being able to figure out the spdy problem. So I went to something that I could solve.
the context for the runQueue is actually just the context for the entire wantmanager. It never really gets cancelled before the daemon shuts down. I added a timeout to the Connect and Send calls within the runQueue to prevent this from happening.
This still leaves one problem unsolved, what do we do if we cannot connect to a given peer, but bitswap insists on sending them a message? (line 157)

prevent wantmanager from leaking goroutines (and memory)

---

test/ipfs-test-lib.sh

As Sharness now includes test_seq we can remove
our implementation.
License: MIT

ipfs-test-lib: use test_seq from sharness

---

cmd/ipfs/.gobuilder.yml

This configuration is supported since GoBuilder 1.16.0 so now we should be able to build windows binaries in GoBuilder

Added nofuse tag for windows builds

---

core/commands/ls.go
test/sharness/t0045-ls.sh
test/sharness/t0051-object.sh

Since 607468a9 (beautify 'ipfs ls' and 'ipfs object links', #833)
we've had these.  That pull request was about [text/tabwriter][1] and
[elastic tabstops][2], but we don't need a column separator at the end
of each line.
[1]: https://golang.org/pkg/text/tabwriter/
[2]: http://nickgravgaard.com/elastic-tabstops/index.html

core/commands/ls: Remove trailing tabs

---

core/commands/mount_unix.go

There has been a regression such that ./t0030-mount.sh fails on
'ipfs mount' fails when there is no mount dir
The issue was a change in how fuse errors are reported to the client
process. We have introduced an optimistic categorization that hides
the obscure fusermount error and replaces it with something a bit
more helpful.
Fixes: #1369
@chriscool: I tested this on linux, but would you mind testing
as well to confirm it is fixed for you too?

fix fuse mount error in linux

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/jbenet/go-multiaddr-net/multiaddr/.gitignore
Godeps/_workspace/src/github.com/jbenet/go-multiaddr-net/net.go
Godeps/_workspace/src/github.com/jbenet/go-multiaddr-net/net_test.go

works around off nil conn failure:
- https://travis-ci.org/ipfs/go-ipfs/jobs/67385491

update go-multiaddr-net with a nil check

---

core/commands/ipns.go
core/commands/name.go
core/commands/publish.go

[ipfs-shell][1] accesses the Command objects directly to construct
requests for an external IPFS daemon API.  This isn't a terribly
robust approach, because it doesn't handle version differences between
the version of go-ipfs used to build the daemon and the version used
to build the ipfs-shell-consuming application.  But for cases where
you can get those APIs to match it works well.  Making these two
commands public allows us to write ipfs-shell wrappers for them.
Until we figure out how to get ipfs-shell working without access to
core/commands, I think the best approach is to make future command
objects and their returned structures public, and to go back and
expose existing commands/structures on an as-needed basis.
In this case, I need the public PublishCmd for the Docker-registry …

core/commands: Make IpnsCmd and PublishCmd public

---

core/commands/publish.go
test/sharness/t0100-name.sh

Instead of raising "keychains not yet implemented" whenever we have an
explicit node ID, only raise the error when the given node ID isn't
the local node.  This allows folks to use the more-general
explicit-node-ID form in scripts and such now, as long as they use the
local node name when calling those scripts.
Also add a test for this case, and update the comment for the
one-argument case to match the current syntax for extracting a
multihash name string.
License: MIT
Signed-off-by: W. Trevor King <wking@tremily.us>

core/commands/publish: Allow explicit local node ID

---

core/commands/object.go
test/sharness/t0051-object.sh

Lets patch do bubbling up
License: MIT

allow patch add-link to add at a path

---

core/commands/object.go

"object" added to the descriptions of object patch and object data

---

fuse/ipns/ipns_test.go

This fixes issue #1411 (go test error in TestConcurentWrites: slice bounds out of range).
License: MIT

ipns_test: fix slice bounds out of range

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/whyrusleeping/multiaddr-filter/mask.go
Godeps/_workspace/src/github.com/whyrusleeping/multiaddr-filter/mask_test.go
core/core.go
p2p/net/conn/interface.go
p2p/net/conn/listen.go
p2p/net/filter/filter.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_listen.go
p2p/net/swarm/swarm_test.go
repo/config/config.go
util/sadhack/godep.go

So this *works* but i'm not sure if i like the construction. Its probably fine, because we are going to redo the daemon init/construction at some point anyways.
License: MIT

add in basic address dial filtering

---

commands/response.go
core/commands/root.go
core/commands/unixfs/ls.go
core/commands/unixfs/unixfs.go
test/sharness/t0200-unixfs-ls.sh

This is mostly to get an interface for listing the file-sizes for Unix
files (vs. the Merkle-ancestor sizes listed by `ipfs ls …`).  For
background, see #543.  For details on the individual commits, see the
commit messages.
The intended space for `ipfs unixfs …` is for folks operating with
Unix-filesystem trees (obviously), so the API should tranparently
resolve any fanout.  The current Merkle-level commands (`ipfs ls …`,
etc.) on the other hand should be operating below the UnixFS level.
They probably shouldn't handle fanout, and they almost certainly
shouldn't be converting Merkle nodes to UnixFS nodes.  For example,
`ipfs cat …` might print the appended set of all constituent chunks,
but it shouldn't be stripping the magic Data wrappers (`Type`,
`Filesize`, `Blocksizes`, … in …

Add 'ipfs file ls …'

---

test/sharness/t0041-add-cat-offline.sh

A test that should have made it into #1417 
License: MIT

add test for only-hash to ensure no blocks are added to datastore

---

cmd/ipfs/daemon.go
core/commands/id.go
core/commands/swarm.go
p2p/net/conn/dial.go
p2p/net/conn/interface.go
p2p/net/conn/listen.go
p2p/net/mock/mock_notif_test.go
p2p/net/swarm/swarm_notif_test.go
p2p/net/swarm/swarm_test.go
test/sharness/lib/test-lib.sh
test/sharness/t0060-daemon.sh
test/sharness/t0061-daemon-opts.sh
test/sharness/t0110-gateway.sh
test/sharness/t0140-swarm.sh

This PR adds:
- `ipfs swarm addrs local` - command to list out local addresses
- `ipfs id -f=<addrs>` - format to print out addrs too
- `ipfs id -f=\n\t` - handle `\n` and `\t` correctly
- test for daemon that checks encryption is on
- `--disable-transport-encryption` daemon option (see below)
- test for restricted api
- test for `--unrestricted-api`
Left TODO:
Changes:
```
commit f0d3d19d9dcb6c793a251d1c7836229de08b8440
Author: Juan Batiz-Benet <juan@benet.ai>
Date:   Fri Jun 19 05:53:00 2015 -0700
added sharness/t0061-daemon-opts
Test odd daemon options, like:
- unrestricted-api
- disable-transport-encryption (known breakage atm)
License: MIT
commit a763bb7d74f129b68f949c7a741a669f2d998f8b
Author: Juan Batiz-Benet <juan@benet.ai>
Date: …
```

Swarm Addrs, Disable secio opt, + tests

---

core/commands/get.go

Currently `ipfs get -C <hash>` returns error even if <hash> is a file.
This PR is for the case when the compress flag is enabled, always
archive the output before the compression.

Don't use tar reader for '-C' flag

---

p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_net.go

Connection notifications tend to not fire exactly-once, so we always update the metric with the total number, instead of incrementing/decrementing.
License: MIT

swarm: fix peers_total metric

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/whyrusleeping/multiaddr-filter/LICENSE
Godeps/_workspace/src/github.com/whyrusleeping/multiaddr-filter/README.md
Godeps/_workspace/src/github.com/whyrusleeping/multiaddr-filter/mask.go
Godeps/_workspace/src/github.com/whyrusleeping/multiaddr-filter/mask_test.go
core/commands/swarm.go
core/core.go
p2p/net/filter/filter.go
p2p/net/swarm/swarm.go
repo/config/config.go
repo/config/swarm.go
test/sharness/t0141-addfilter.sh

add filters from config to addr filter in swarm

---

cmd/ipfs/daemon.go

Convey the basic idea, plus an example.  Don't encourage using `*`.
This would have saved me some code spelunking.

daemon help docs for CORS

---

core/commands/get.go
core/commands/publish.go
core/pathresolver_test.go
path/path.go
path/resolver.go
test/sharness/t0090-get.sh

Because path.ParsePath is always called whenever Resolve is called

Remove redundant path validation

---

core/commands/config.go
docs/fuse.md
repo/fsrepo/fsrepo.go

Basically with this PR, 'true' is parsed as boolean, making explicit '--bool'/'--number'/'--string' optional if there is already config struct.
Lower dose version of https://github.com/ipfs/go-ipfs/pull/1355 that doesn't break backward compatibility.

Assert and convert config value into predefined struct

---

core/commands/unixfs/ls.go

The old text belonged to an earlier iteration that didn't land in the
rebased 434871ba (core/commands/unixfs: Add 'ipfs unixfs ls ...',
2015-06-09).

core/commands/unixfs/ls: Drop multi-column example from --help

---

blocks/blockstore/blockstore.go
blocks/blockstore/write_cache.go
blocks/key/key_set.go
core/commands/add.go
core/commands/pin.go
core/core.go
core/coreunix/add.go
merkledag/merkledag.go
merkledag/merkledag_test.go

The addition of a locking interface to the blockstore allows us to
perform atomic operations on the underlying datastore without having to
worry about different operations happening in the background, such as
garbage collection.
Also implement a few merkledag package changes.
License: MIT

Add locking interface to blockstore

---

core/commands/add.go
core/commands/pin.go
core/corehttp/gateway_handler.go
core/corerepo/gc.go
core/coreunix/add.go
core/coreunix/metadata_test.go
importer/helpers/dagbuilder.go
importer/helpers/helpers.go
importer/importer.go
importer/importer_test.go
merkledag/merkledag_test.go
pin/gc/gc.go
pin/pin.go
pin/pin_test.go
test/sharness/t0080-repo.sh
unixfs/mod/dagmodifier.go
unixfs/mod/dagmodifier_test.go

This PR implements mark and sweep garbage collection and completely removes the concept of indirect pinning.

implement mark and sweep garbage collection

---

core/commands/swarm.go

makes `ipfs swarm filters` not panic when run offline.
License: MIT

error out swarm filter when no daemon is online

---

exchange/bitswap/bitswap.go

Tells bitswap to retry writing the block multiple times with a progressively larger delay to try and avoid 'too many open file descriptor' temporary errors.
License: MIT

allow bitswap to attempt to write blocks to disk multiple times

---

exchange/bitswap/bitswap.go

Doing the publish before the `blockstore.Put` would cause a race where callers of `GetBlock` (in tests) would finish, and then immediately try to read the blocks from the blockstore to verify that the block was received, and the block hadnt quite made it to disk yet by the time that call was made.
repro was running:
```
while go test ./exchange/bitswap -run=TestLargeFile; end
```
for a few minutes, before the fix would fail within a minute, after the fix, ran for ten minutes before i got bored and killed it.
License: MIT

fix race introduced in bitswap

---

exchange/bitswap/wantmanager.go
p2p/host/basic/natmgr.go
p2p/net/swarm/swarm.go

Some changes that help the daemon shutdown more quickly. There are more to come hopefully
License: MIT

making the daemon shutdown quicker

---

path/path.go
path/path_test.go
test/sharness/t0051-object.sh

with this we can now do
```
ipfs object stat <hash>/a/b/c
```
License: MIT

fix parsing for paths of format <hash>/path

---

Dockerfile
bin/container_shacheck

Migrated Dockerfile to use alpine linux

---

p2p/net/swarm/dial_test.go
util/testutil/ci/ci.go

we were actually ignoring the `CI` environment variable, and in some places werent actually checking it in a platform agnostic way.
License: MIT

make timing tests actually not run under CI

---

exchange/bitswap/testutils.go
p2p/net/mock/interface.go
p2p/net/mock/mock_link.go
p2p/net/mock/mock_notif_test.go
p2p/net/mock/mock_stream.go
p2p/net/mock/mock_test.go
p2p/net/mock/ratelimiter.go

This PR incorporates the transport logic from feat/netsim in streams to simulate latency in mocknet.  It also simulates bandwidth in links.
Bandwidth is limited using a ratelimiter object. It uses the token bucket algorithm to determine how long to wait before sending data. Latency and rate limiting are applied on stream writes.
I use the existing LinkOptions struct for configuration.

add transport from netsim and bandwidth to mocknet

---

merkledag/merkledag_test.go
merkledag/node.go

this way i can do: `ipfs object stat a/b/c/d/e/f/g` and get the hash of `g`. Essentially exposing core.Resolve through the API.
License: MIT

include hash of resolved object in object stat output

---

commands/http/client.go
commands/http/handler.go
commands/response.go

This 'fixes' the random API http errors we have been seeing, with the catch that you have to always call close on the commands.Response when youre done with it. (which sucks)
License: MIT

attempt at properly closing http response bodies

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/cheggaaa/pb/pb_win.go
Godeps/_workspace/src/github.com/olekukonko/ts/.travis.yml
Godeps/_workspace/src/github.com/olekukonko/ts/LICENCE
Godeps/_workspace/src/github.com/olekukonko/ts/README.md
Godeps/_workspace/src/github.com/olekukonko/ts/doc.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_darwin.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_linux.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_other.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_test.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_unix.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_windows.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_x.go
util/sadhack/godep.go

We should be able to get windows builds again after this. They might have NAT issues due to not having implemented SO_REUSEPORT on the platform, but its a start.
License: MIT

vendor lib so windows builds work again

---

commands/http/client.go
commands/http/handler.go
core/commands/get.go
thirdparty/tar/extractor.go
unixfs/tar/reader.go

This PR started off as a quick fix for the get command, but turned into a moderately large refactor of the http commands library.

Implement http trailers for error handling

---

core/commands/add.go
core/commands/cat.go

Close #1345 
like `ipfs add`, but not wget/curl.

Clear progress bar on `ipfs cat` exit

---

test/sharness/lib/test-lib.sh
test/sharness/t0080-repo.sh

Add reversible gc test

---

core/commands/refs.go
test/sharness/t0080-repo.sh

commit 490ed41c454184aa01b0a6a1d534c88d6997ad5f
Author: Juan Batiz-Benet <juan@benet.ai>
Date:   Tue Jul 28 06:13:27 2015 -0700
sharness/ipfs refs bigger tests
License: MIT
commit 8fe7d2f571ea3f7c68e34f1b4d9867a2ba3d4e4c
Author: gatesvp <gatesvp@gmail.com>
Date:   Tue Jul 28 03:05:01 2015 -0400
Fix refs -r -u for #1211
License: MIT
Signed-off-by: Gaetan Voyer-Perrault <gatesvp@gmail.com>
commit a5521fcc765f391616b58beb91ea05ffe5652869
Author: Juan Batiz-Benet <juan@benet.ai>
Date:   Tue Jul 28 05:56:14 2015 -0700
sharness/repo: fix pinning test
looks like the test was broken by GC-ing everything.
the pin expects $HASH to still be there.
License: MIT

Fix refs u

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/texttheater/golang-levenshtein/levenshtein/levenshtein.go
Godeps/_workspace/src/github.com/texttheater/golang-levenshtein/levenshtein/levenshtein_test.go
commands/cli/cmd_suggestion.go
commands/cli/parse.go
test/sharness/t0150-clisuggest.sh

License: MIT
Signed-off-by: Shaun Bruce <shaun.m.bruce@gmail.com>

Better error message on unrecognized command

---

cmd/ipfs/daemon.go
commands/http/handler.go
commands/http/handler_test.go
core/corehttp/commands.go
core/corehttp/gateway.go
core/corehttp/gateway_handler.go
core/mock/mock.go
repo/config/api.go
repo/config/config.go
repo/config/gateway.go

This PR
- Fixes CORS bugs
- Improves support for CORS options
- Removes Referrer Checking
- Defaults to localhost/127.0.0.1 CORS Origins
- Allows Setting arbitrary HTTP headers on API responses

Fix CORS Support

---

core/core.go
core/mock/mock.go

The fuse tests were failing because the mock node didnt have the identity set.
License: MIT

set identity on core mock to fix ipns tests

---

ipnsfs/system.go

fixes #1534
8a4c15d (Juan Batiz-Benet, 2 minutes ago)
ipnsfs: remove context.TODO(), wire to FS context
License: MIT Signed-off-by: Juan Batiz-Benet <juan@benet.ai>
d4037f5 (Juan Batiz-Benet, 8 minutes ago)
ipnsfs: remove "Publishing!" println
use `log.Info(...)` and `defer log.Event(...).Done()` instead
License: MIT Signed-off-by: Juan Batiz-Benet <juan@benet.ai>

remove "Publishing!" println

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/jbenet/go-random-files/LICENSE
Godeps/_workspace/src/github.com/jbenet/go-random-files/Makefile
Godeps/_workspace/src/github.com/jbenet/go-random-files/README.md
Godeps/_workspace/src/github.com/jbenet/go-random-files/lib.go
Godeps/_workspace/src/github.com/jbenet/go-random-files/random-files/.gitignore
Godeps/_workspace/src/github.com/jbenet/go-random-files/random-files/README.md
Godeps/_workspace/src/github.com/jbenet/go-random-files/random-files/main.go
Godeps/_workspace/src/github.com/jbenet/go-random-files/ringreader/ringreader.go
Godeps/_workspace/src/github.com/jbenet/go-random-files/ringreader/ringreader_test.go
Godeps/_workspace/src/github.com/jbenet/goprocess/goprocess.go
Godeps/_workspace/src/github.com/jbenet/goprocess/goprocess_test.go
Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go
commands/files/multipartfile.go
core/commands/add.go
core/commands/mount_unix.go
core/core.go
fuse/mount/fuse.go
fuse/mount/mount.go
test/Makefile
test/sharness/Makefile
test/sharness/lib/random-dep.go
test/sharness/t0040-add-and-cat.sh
test/sharness/t0043-add-w.sh

a8dae30 (Juan Batiz-Benet, 4 minutes ago)
add -w: fix to work correctly with dirs.
this commit changes the behavior of ipfs add -w:
- it makes it able to work with ipfs add -r <dir>
- instead of hacking around the add, we simply just add a wrapper
directory around the whole result of the add. this means that
ipfs add -w calls will output _two_ lines, but this is actually
more correct than outputting one line, as two objects were added.
this _may_ break scripts out there which expect the output to
look a certain way. we should consider whether the old output is
more _useful_ (even if less in-line with the model.)
License: MIT Signed-off-by: Juan Batiz-Benet <juan@benet.ai>
578fd02 (Juan Batiz-Benet, 7 minutes ago)
fuse unmount fixes
unmounting wasn't happening, mostly because of a recent …

ipfs add -w directories (and FUSE fixes)

---

README.md

The go installation docs only instruct you to add /usr/local/go/bin to PATH. You also need $GOPATH/bin.

Update README.md re $GOPATH/bin

---

cmd/ipfs/daemon.go
commands/http/handler.go
commands/http/handler_test.go
core/corehttp/commands.go
core/corehttp/corehttp.go
core/corehttp/gateway.go
core/corehttp/gateway_test.go
core/corehttp/ipns_hostname.go
core/corehttp/logs.go
core/corehttp/prometheus.go
core/corehttp/redirect.go

I'm not really sure what these changes mean, All I know is that the webui now works and I can add files through that interface again.
cc @mappum @diasdavid @jbenet and anyone else who can tell me if what i've done here is right.
License: MIT

fix allowed origins to make webui work again

---

p2p/crypto/key.go
p2p/crypto/secio/al.go

Fedora/RedHat distros comply with US patent law and remove this curve,
which makes it impossible to run ipfs with distro provided Golang.
I hope the change is OK, but I have not tested it.
I sent more or less the same issue to Ethereum project and it was accepted here: https://github.com/ethereum/go-ethereum/commit/3f07afbbd21a0458830461f06d818aa1f9fa51fe

remove elliptic.P224 usage

---

exchange/bitswap/bitswap.go
exchange/bitswap/workers.go

this PR greatly speeds up providing and add.
(1) Instead of idling workers, we move to a ratelimiter-based worker.
We put this max at 512, so that means _up to_ 512 goroutines. This
is very small load on the node, as each worker is providing to the
dht, which means mostly waiting. It DOES put a large load on the DHT.
but i want to try this out for a while and see if it's a problem.
We can decide later if it is a problem for the network (nothing
stops anyone from re-compiling, but the defaults of course matter).
(2) We add a buffer size for provideKeys, which means that we block
the add process much less. this is a very cheap buffer, as it only
stores keys (it may be even cheaper with a lock + ring buffer
instead of a channel...). This makes add blazing fast-- it was being
rate limited by …

bitswap/provide: improved rate limiting

---

README.md

Update link to ipfs installation guide

---

core/commands/refs.go

fixes the newline issue from #1477 
License: MIT

dont put newlines in refs json output

---

repo/common/common.go
test/sharness/t0021-config.sh

Also, now, if ipfs config foo.bar has value of anything that is not map (0, "0", 0.1),
then ipfs config foo.bar.baz now returns an error instead of a panic
Fixes #1561

Config: allow to set maps on null value

---

blockservice/blockservice.go
blockservice/test/blocks_test.go
blockservice/test/mock.go
core/core.go
core/coreunix/metadata_test.go
core/mock/mock.go
importer/balanced/balanced_test.go
importer/importer_test.go
importer/trickle/trickle_test.go
merkledag/merkledag_test.go
merkledag/test/utils.go
merkledag/utils/utils_test.go
path/resolver_test.go
pin/pin_test.go
unixfs/mod/dagmodifier_test.go

I noticed the blockservice constructor only returned an error if the blockstore it was given was nil. thats silly.
Especially since it doesnt catch the following:
```
var bs *MyConcreteBlockstoreType // nil blockstore, concrete type
bserv, err := blockservice.New(bs, exchange)
// err == nil here.
```
License: MIT

blockservice.New doesnt need to return an error

---

cmd/ipfs/daemon.go
core/commands/root.go
core/corehttp/commands.go
test/sharness/t0110-gateway.sh

Based on https://github.com/ipfs/go-ipfs/pull/1389
(wip)

Add readonly api to gateway

---

core/core.go
routing/none/none_client.go
test/integration/bitswap_wo_routing_test.go

@whyrusleeping 
I added a new nilrouting package and routing option that could be useful for future routerless tests.
License: MIT
Signed-off-by: Karthik Bala <karthikbala444@gmail.com>

Add router that does nothing for bitswap_wo_routing test

---

routing/dht/lookup.go
routing/dht/routing.go

I was trying to diagnose some dht issues i was noticing and i noticed that some entries were absent from the output of the query notifications. It looks like i was relying on the context to be passed through to the query functions. but at some point the goprocess stuff got shoved in the middle of it, so now we derive a context from a process that is derived from a context and pass that to the queryFunc. I put a little closure in that allows us to have the correct context within the queryFuncs to properly publish events.
License: MIT

use correct context for dht notifs

---

merkledag/utils/diff.go

I got bored and wrote this, not entirely sure if its that useful to us right now. But here it is.
It doesnt work on files because we dont name the links of files. But it will work on directory structures and general dags just fine.
License: MIT

implement a basic DAG diffing algorithm

---

repo/config/version.go

` @jbenet | whyrusleeping: we should update the version number after a release, so that _master_ is ahead of the last released version.`
License: MIT

bump development version

---

core/corehttp/gateway_handler.go
core/corehttp/gateway_test.go
core/corehttp/ipns_hostname.go

IPNSHostnameOption() touches the URL path only on the way in,
but not on the way out. This commit makes it complete by
touching the following URLs in responses:
- Heading, file links, back links in directory listings
- Redirecting /foo to /foo/ if there's an index.html link
- Omit Suborigin header
License: MIT

gateway: make IPNSHostname work on responses too

---

cmd/ipfs/daemon.go
test/sharness/t0060-daemon.sh

Notify when daemon is ready

---

fuse/ipns/ipns_unix.go
fuse/ipns/link_unix.go
fuse/readonly/ipfs_test.go
fuse/readonly/readonly_unix.go

commit 44757b64f210ea6f5c8efe95cc7ea1377c7a8560
Author: Tommi Virtanen <tv@eagain.net>
Date:   2015-09-01 15:34:12 -0700
fuse/ipns: Only change file size in Setattr if asked to
This used to cause files e.g. being edited with `vi` to become 0-size.
License: MIT
Signed-off-by: Tommi Virtanen <tv@eagain.net>
commit 4be9bd1093229c8592e9aef1c1aa3a3defe53935
Author: Tommi Virtanen <tv@eagain.net>
Date:   2015-08-31 18:03:59 -0700
fuse/ipns, fuse/readonly: Let the fuse library set defaults for Attr
Without this, all entries will have nlink==0, which confuses a bunch
of tools. Most dramatically, systemd-nspawn enters a busy loop in its
lock utility function.
License: MIT
Signed-off-by: Tommi Virtanen <tv@eagain.net>
commit c0edb6329889e7adfb07103edf2704059fd5235f
Author: Tommi Virtanen …

FUSE fixes

---

commands/cli/parse.go
commands/files/linkfile.go
commands/files/multipartfile.go
commands/files/serialfile.go
commands/http/multifilereader.go
core/commands/add.go
core/commands/unixfs/ls.go
fuse/readonly/readonly_unix.go
test/sharness/t0044-add-symlink.sh
thirdparty/tar/extractor.go
unixfs/archive/tar/writer.go
unixfs/format.go
unixfs/io/dagreader.go
unixfs/pb/unixfs.pb.go
unixfs/pb/unixfs.proto

Implemented basic symlink support. Most commands dont follow them yet, need to figure out semantics for things like `ipfs cat QmSymlink`. But they are supported in the fuse mounts.
License: MIT

implement symlinks in unixfs, first draft

---

test/sharness/t0020-init.sh

t0020: simplify peerid check

---

commands/files/serialfile.go

Because `filepath.Walk` uses only fileinfo (no os.Open() is ever used) and Lstat.
(no actually, filepath.Walk did use os.Open from its readDirNames)

Use filepath.Walk to compute serialfile total size

---

unixfs/pb/unixfs.pb.go

build failure to do incorrect import path.
@rht can I get a :+1: to merge asap? (pretty sure jbenet is out for a while)
License: MIT

fix import path of generated proto files

---

p2p/net/mock/mock_notif_test.go
p2p/protocol/identify/id.go

This should fix the mock notifications test for good, i ran
```
while go test ./p2p/net/mock -run TestNotifications
echo pass
end
```
for about 15 minutes with zero failures.
I looked at making the same changes to the `p2p/net/swarm` notifications test, but it appears to be failing for a different reason, and has a slightly different structure.
License: MIT

fix mock notification test

---

blockservice/blockservice.go
commands/channelmarshaler.go
commands/response.go
core/commands/dht.go
core/commands/ping.go
core/commands/refs.go
core/commands/repo.go
core/commands/stat.go

This doesnt fix the add issue, but it does allow us to actually see the error for it. 
Previously, the goroutine in add would fail, and call `res.SetError`, but nothing would ever check that. 
License: MIT

allow channel marshaler to return errors from cmds.Response

---

commands/files/serialfile.go
test/sharness/lib/test-lib.sh
test/sharness/t0040-add-and-cat.sh
test/sharness/t0041-add-cat-offline.sh

"Fixes" #1409 (if the fix is to err when input is a namedpipe)
This PR changes the behavior so that ipfs add on daemon returns err for all cases instead of hangs.
~ a more lightweight version of #1413 except that it doesn't have fileinfo mime types.

Serialfile: Explicit err on unrecognized file type

---

exchange/bitswap/bitswap.go

This commit changes the order of the proc/ctx wiring, to ensure
that the proc has been setup correctly before exiting.
License: MIT

bitswap/workers: fix proc / ctx wiring

---

blockservice/blockservice.go
core/commands/add.go
core/commands/object.go
merkledag/merkledag.go
merkledag/utils/diff.go
merkledag/utils/utils.go
merkledag/utils/utils_test.go

Using this, we would be able to pass an 'offline' dagstore to the editor, and then use the `WriteOutputTo` method on the editor to write the changed nodes to our actual dagservice.
@jbenet thoughts?
License: MIT

an attempt at making the editor more efficient

---

core/commands/root.go
core/commands/tar.go
tar/format.go
test/sharness/t0210-tar.sh

Allows the importing of tar files into ipfs, provides greater dedupe than simple using 'ipfs add' on the tar file. Also adds a command to export a tar back out from the added hash
License: MIT

first pass at a tar importer

---

test/sharness/lib/test-lib.sh
test/sharness/t0020-init.sh
test/sharness/t0060-daemon.sh
test/sharness/t0062-daemon-api.sh
test/sharness/t0100-name.sh
test/sharness/t0110-gateway.sh

This is a followup from PR #1625.

Generalize peerid check

---

cmd/ipfs/.gobuilder.yml

As discussed in #1685 this trigger will fire after the ipfs cmd has been built and trigger a DockerHub build for the `jbenet/go-ipfs` repo on DockerHub.
Encrypted target was created by using this command:
```bash
Go ahead and type your secret ...
U2FsdGVkX18fMPhIZ3k1QDCwnB49ln6DdyvIH2tDDHxTZi3Q3DQ7AKWllo9KngxwteX2dBFQ2P+jLEBh12PEEqOkN2SePNbMhMtmk/c4siHVAqo5wnf8Utgqob0jB40sobmqNN9X3Y/W2yb72LuGJg==
```
closes #1685

Added dockerhub trigger

---

bin/container_daemon

This incorporates feedback from @RX14 in #1685 and might fix #1537 as the ipfs daemon would get the stop signal from the docker daemon... Maybe that way it stops in a cleaner manner...

Use exec to start IPFS daemon

---

README.md
contribute.md

This will alert the user to check the contributing guidelines before opening a PR if they never have before for this repo. It will also provide a place for us to easily mention what GitCop is doing.

Added a Contribute file

---

core/commands/get.go

If "compression-level" is set, the compression is set to gzip.NoCompression.

Fix gzip compression level not being set.

---

core/commands/object.go

achin in irc mentioned that he wish he could do 'ipfs object patch $hash set-data < file.dat'.
Its totally a thing already, so heres some docs.
License: MIT

document the set-data and append-data commands in patch

---

commands/http/handler.go
test/sharness/t0230-channel-streaming-http-content-type.sh

Fixes #1721
There was a stale assumption that streaming output from a channel would
always be json.
This commit removes that code, allowing Content-Type to appropriately be
set like other, non-channel-streaming commands.
New output:
```bash
$ mkdir testdir
$ echo "hello test" > testdir/test.txt
$ ipfs add -r testdir
added QmRmPLc1FsPAn8F8F9DQDEYADNX5ER2sgqiokEvqnYknVW testdir/test.txt
added QmTcJAn3JP8ZMAKS6WS75q8sbTyojWKbxcUHgLYGWur4Ym testdir
$ curl -i "http://localhost:5001/api/v0/refs?arg=QmTcJAn3JP8ZMAKS6WS75q8sbTyojWKbxcUHgLYGWur4Ym&stream-channels=true&encoding=text"
HTTP/1.1 200 OK
Content-Type: text/plain
Transfer-Encoding: chunked
X-Chunked-Output: 1
QmRmPLc1FsPAn8F8F9DQDEYADNX5ER2sgqiokEvqnYknVW
$ curl -i "http://localhost:5001/api/v0/refs?arg=QmTcJAn3JP8ZMAKS6WS75q8sbTyojWKbxcU …
```

remove hard-coded json content-type for streaming http output

---

cmd/ipfs/main.go

The first run does not try to connect to API, as an address is not
yet saved in configuration. The second run did not recognize
corrently a refused connection.

Fix #1661 IPFS crashes on windows after first run

---

cmd/ipfs/daemon.go

allows us to properly use port zero for the api address
License: MIT

write correct address to api file

---

core/commands/bitswap.go
exchange/bitswap/bitswap.go
exchange/bitswap/stat.go

@ion1 This adds the counter for the total number of bytes received due to duplicate blocks. Is there anything else you think we need here?
License: MIT

allow bitswap stat to return total number of bytes wasted

---

test/sharness/t0090-get.sh

`test_ipfs_get_flag ".tar.gz" "-zxf" -a -C -l 9` fails until #1704 is merged.

Sharness: add test for compression level

---

test/ipfs-test-lib.sh

This function can be usefull in many places.
See for example:
https://github.com/ipfs/go-ipfs/pull/1742
Git has `git rev-parse --sq-quote` that does the same thing.
License: MIT

ipfs-test-lib: add shellquote()

---

README.md

I added the instructions to make the ipfs_data and ipfs_staging globally readable, which prevents permission errors. 
It may be better to limit permissions in some way, to prevent potential security risks.
License: MIT
Signed-off-by: sroerick <sweeney@roerick.me>

added docker file permission instructions.

---

core/commands/log.go

So the command line prompt stay where it should. What happend before was this:
```
~ $ ipfs log level all panic
Changed log level of '*' to 'panic' ~ $
̀``

Add a new line in the output of ipfs log level

---

core/core.go
fuse/ipns/common.go
namesys/namesys.go
namesys/publisher.go
namesys/republisher/repub_test.go
namesys/resolve_test.go
routing/dht/handlers.go
routing/dht/pb/dht.pb.go
routing/dht/pb/dht.proto
routing/dht/records.go
routing/mock/centralized_client.go
routing/mock/centralized_server.go

dont error out if prexisting record is bad, just grab its sequence number
and continue on with the publish.
License: MIT

fix publish fail on prexisting bad record

---

test/sharness/t0240-republisher.sh

This is a small series of small cleanups.

Improve t0240

---

test/ipfs-test-lib.sh
test/sharness/t0015-basic-sh-functions.sh

Fix shellquote() implementation and add tests as discussed in PR #1757.
Thanks @ion1!

Shell quote

---

core/builder.go
core/commands/files/files.go
core/commands/root.go
core/core.go
mfs/ops.go
test/sharness/t0250-files-api.sh
unixfs/mod/dagmodifier.go
unixfs/mod/dagmodifier_test.go

@jbenet 
@diasdavid @mappum Heres the mfs api, Its gonna make things pretttty cooooool.
License: MIT

implement ipfs files command

---

cmd/ipfs/daemon.go
core/corehttp/prometheus.go

So that we can graph them using Prometheus. See #1763 and #1422.
This gets us the following metrics:
```
http_requests_total{code="200",handler="api",method="get"} 54
http_requests_total{code="200",handler="gateway",method="get"} 60
http_requests_total{code="304",handler="gateway",method="get"} 30
http_request_duration_microseconds{handler="api",quantile="0.5"} 593.504
http_request_duration_microseconds{handler="api",quantile="0.9"} 852.337
http_request_duration_microseconds{handler="api",quantile="0.99"} 1054.733
http_request_duration_microseconds_sum{handler="api"} 35359.53
http_request_duration_microseconds_count{handler="api"} 54
http_request_duration_microseconds{handler="gateway",quantile="0.5"} 21147.23
http_request_duration_microseconds{handler="gateway",quantile="0.9"} 337680.504 …
```

daemon: instrument the gateway and api HTTP handlers

---

core/commands/cat.go
core/coreunix/cat.go
fuse/readonly/ipfs_test.go
test/integration/addcat_test.go
test/integration/bench_cat_test.go
test/integration/grandcentral_test.go
test/integration/three_legged_cat_test.go
test/supernode_client/main.go

In the tests, `node.Context()` are always derived from `ctx` used in this PR.
However, in core/commands, it is not the case for daemon context and `req.Context()`.

Add context to coreunix.Cat argument

---

core/commands/add.go

Remade the PR because GitCop complained about the licensing.
Fixes #1814.

Adds -H as short option for 'ipfs add --hidden'

---

core/commands/ipns.go

For instant resolution of ipns names solely based on what information is on the datastore, use `ipfs name resolve --local`
License: MIT

allow ipfs name resolve to respect --local

---

.travis.yml
README.md
circle.yml
cmd/ipfs/go_req.go
commands/http/handler.go
test/sharness/t0230-channel-streaming-http-content-type.sh

It turns out they implemented http trailers in go's std http lib. I am happy.
License: MIT

use go's built in handling of trailers and dont do custom chunking

---

Makefile
cmd/ipfs/Makefile
core/commands/version.go
repo/config/version.go

It sets the variable ```config.CurrentCommit``` in the Makefile with the short SHA1 hash of the current commit.
It also adds the ```--commit``` option to ```ipfs version``` so that:
```
$ ipfs version
ipfs version 0.3.8-dev
$ ipfs version --commit
ipfs version 0.3.8-dev-4de5eaa
$ ipfs version --number
0.3.8-dev
$ ipfs version --number --commit
0.3.8-dev-4de5eaa
```

Adds the option to see the current git commit with `ipfs version --commit`

---

cmd/ipfs/go_req.go

removing this temporarily so we can merge 0.3.8 and still get gobuilder builds
License: MIT

remove version requirement file so gobuilder can build still

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/shirou/gopsutil/common/common.go
Godeps/_workspace/src/github.com/shirou/gopsutil/common/common_darwin.go
Godeps/_workspace/src/github.com/shirou/gopsutil/common/common_freebsd.go
Godeps/_workspace/src/github.com/shirou/gopsutil/common/common_linux.go
Godeps/_workspace/src/github.com/shirou/gopsutil/common/common_test.go
Godeps/_workspace/src/github.com/shirou/gopsutil/common/common_unix.go
Godeps/_workspace/src/github.com/shirou/gopsutil/common/common_windows.go
Godeps/_workspace/src/github.com/shirou/gopsutil/disk/binary.go
Godeps/_workspace/src/github.com/shirou/gopsutil/disk/disk.go
Godeps/_workspace/src/github.com/shirou/gopsutil/disk/disk_darwin.go
Godeps/_workspace/src/github.com/shirou/gopsutil/disk/disk_darwin_amd64.go
Godeps/_workspace/src/github.com/shirou/gopsutil/disk/disk_freebsd.go
Godeps/_workspace/src/github.com/shirou/gopsutil/disk/disk_freebsd_amd64.go
Godeps/_workspace/src/github.com/shirou/gopsutil/disk/disk_linux.go
Godeps/_workspace/src/github.com/shirou/gopsutil/disk/disk_test.go
Godeps/_workspace/src/github.com/shirou/gopsutil/disk/disk_unix.go
Godeps/_workspace/src/github.com/shirou/gopsutil/disk/disk_windows.go
Godeps/_workspace/src/github.com/shirou/gopsutil/disk/types_freebsd.go
Godeps/_workspace/src/github.com/shirou/gopsutil/mem/mem.go
Godeps/_workspace/src/github.com/shirou/gopsutil/mem/mem_darwin.go
Godeps/_workspace/src/github.com/shirou/gopsutil/mem/mem_darwin_test.go
Godeps/_workspace/src/github.com/shirou/gopsutil/mem/mem_freebsd.go
Godeps/_workspace/src/github.com/shirou/gopsutil/mem/mem_linux.go
Godeps/_workspace/src/github.com/shirou/gopsutil/mem/mem_test.go
Godeps/_workspace/src/github.com/shirou/gopsutil/mem/mem_windows.go
cmd/ipfs/ipfs.go
core/commands/diag.go
core/commands/sysdiag.go
test/sharness/t0151-sysdiag.sh

Provide a command to easily gather system information to streamline the issue reporting process.
Saves us from having to ask for a laundry list of information about the users environment whenever they report a bug.
License: MIT

system diagnostics command

---

contribute.md

Dependent upon https://github.com/ipfs/community/pull/58. Do not merge if that is not merged. 
License: MIT

Pared down contribute to link to new go guidelines

---

commands/option.go
core/commands/id.go
core/commands/ls.go

Fix cli flag orders (long, short)

---

test/sharness/t0060-daemon.sh

This is an alternative 'fix' for issue #1821 (t0060-daemon fails if nc is not installed).
The previous fix is PR #1849 (t0060: don't fail if no nc).

t0060: fail if no nc

---

fuse/ipns/ipns_test.go

There is the following error otherwise:
```
$ go test github.com/ipfs/go-ipfs/fuse/ipns
../../fuse/ipns/ipns_test.go:116: not enough arguments in call to namesys.NewNameSystem
FAIL    github.com/ipfs/go-ipfs/fuse/ipns [build failed]
```
License: MIT

ipns_test: fix namesys.NewNameSystem() call

---

commands/http/handler.go
commands/http/handler_test.go
core/corehttp/commands.go

License: MIT
Signed-off-by: Artem Andreenko <mio@volmy.com>

fix races in http cors

---

p2p/net/mock/mock_net.go
p2p/net/mock/ratelimiter.go

PSA: if you think you need a RWMutex, you probably dont, if you *really* think you do, double check that your data is safe to read concurrently. (go's maps are not)
License: MIT

fix a few race conditions in mocknet

---

commands/http/handler.go
test/sharness/t0060-daemon.sh

after the refactor to use go1.5 trailers the http lib started buffering output, so commands like `ipfs ping` and `ipfs stats bw --poll` would either print all at the end, or wait until the buffer filled to print.
License: MIT

fix streaming output to flush per write

---

core/commands/bitswap.go
exchange/bitswap/bitswap.go

I was quite confused the first time I saw an "dup data received" in `ipfs bitswap stat` that was bigger than several megabytes.
Also fixed the formatting of the `received un-asked-for block` logging statement.
License: MIT
Signed-off-by: Henry <cryptix@riseup.net>

bitswap: clean log printf and humanize dup data count

---

core/commands/swarm.go

@diasdavid made me look at this code a little more and i realized that if it fails, you wont know about it through the api.
This should fix that.
License: MIT

make swarm connect return an error when it fails

---

.gobuilder.yml
cmd/ipfs/goreq.go

ensures we dont accidentaly run into #1880 by building with go1.4
License: MIT

purposely fail builds pre1.5

---

test/Makefile
test/sharness_test_coverage_helper.sh

This is a first version of a script that automatically shows Sharness test coverage.
Currently it outputs something like:
```
ipfs file ls
6 t0200
ipfs get
1 t0050
3 t0051
7 t0090
ipfs id
2 t0062
3 t0100
2 t0140
2 t0160
ipfs init
4 t0020
2 t0060
ipfs log
ipfs log level
ipfs log tail
ipfs ls
2 t0045
1 t0051
6 t0080
12 t0081
6 t0200
```
This tells us that `ipfs file ls` appears 6 times in t0200, while `ipfs log` appears nowhere.

Sharness coverage script

---

core/corehttp/gateway_handler.go
path/resolver.go
test/sharness/t0111-gateway-writeable.sh

trying to finally get a working `putHandler` for the writable http gateway.
License: MIT
Signed-off-by: Henry <cryptix@riseup.net>

fixing putHandler

---

CHANGELOG.md
misc/release-checklist.md
repo/config/version.go

you all know the drill.
One minor difference from previous releases, i'm adding a second commit here to bump the dev version to 0.3.10-dev. The *first* commit in this PR is the one that needs to be tagged as 0.3.9

Version bump 0.3.9

---

core/commands/cat.go
core/coreunix/cat.go
test/sharness/t0100-name.sh

Partially address #1898.
Why should an ipns key be stored in blockstore instead of the ipfs hash it resolves to?
There is already caching in #1887.

Allow `ipfs cat` on ipns path

---

core/commands/ipns.go
core/commands/publish.go
core/core.go
fuse/ipns/ipns_test.go
namesys/namesys.go
namesys/pb/namesys.pb.go
namesys/pb/namesys.proto
namesys/publisher.go
namesys/republisher/repub_test.go
namesys/resolve_test.go
namesys/routing.go
repo/config/init.go
repo/config/ipns.go
test/sharness/t0240-republisher.sh

This adds a quick minute long cache to ipns entry resolution. 
Currently, ipns is pretty much unusable for webpages as each sub-request must re-resolve the entry.
License: MIT

cache ipns entries to speed things up a little

---

contribute.md

I did some small edits, moved Juan's email to ipfs/contribute where it should get more eyes, and added the commit sign off section back in. 
Related: https://github.com/ipfs/community/pull/65, https://github.com/ipfs/community/issues/63.

Edited contribute

---

cmd/ipfs/main.go
repo/fsrepo/fsrepo.go

fixes #1950 and also makes things more likely to work on windows (decided to fix the filepath stuff while i was at it)
License: MIT

add another error to the isConnRefused check

---

metrics/conn/conn.go
p2p/net/conn/dial.go
p2p/net/conn/dial_test.go
p2p/net/conn/interface.go
p2p/net/conn/listen.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_listen.go
p2p/net/transport/reuseport.go
p2p/net/transport/tcp.go
p2p/net/transport/transport.go

refactor as discussed with @jbenet. (with a couple extra methods on the interfaces)
This has the nice effect of removing go-multiaddr-net imports from a lot of places.
License: MIT

refactor net code to use transports, in rough accordance with libp2p

---

cmd/ipfs/daemon.go
commands/request.go
core/commands/add.go
core/commands/cat.go
core/corerepo/gc.go
repo/config/datastore.go
repo/config/init.go
repo/fsrepo/fsrepo.go
repo/mock.go
repo/repo.go
test/sharness/lib/test-lib.sh
test/sharness/t0080-repo.sh

WIP sketch.
1. Ok with configurable GC frequency?
2. go-datastore doesn't have size check, so a local system call is used instead
Address #972

Add fixed-period and conditional repo GC

---

repo/config/config.go
repo/config/init.go
repo/config/log.go
repo/config/logs.go

We stopped logging to files in a676b5a8ac2848a57318283f4b2b52d7d8686323
and this config section was missed.
License: MIT

repo: remove Log config

---

core/commands/add.go
core/coreunix/add.go
test/sharness/t0081-repo-pinning.sh

Implements a solution for #1908
This PR replaces #1909
>

Add a --no-pin option to `ipfs add`

---

routing/kbucket/sorting.go
routing/kbucket/table.go

If the bucket chosen by the common prefix length doesnt have as many peers as we are requesting, grab some from the buckets on either side, This should help dht queries complete faster as they are more likely to query a larger number of peers.
License: MIT

if bucket doesnt have enough peers, grab more elsewhere

---

core/corehttp/gateway_handler.go
core/corehttp/gateway_test.go
core/corehttp/ipns_hostname.go

The other option would be a config option to rule them all. This one here, lets the reverse proxy signal the path prefix, which allows having the same gateway accessible at multiple paths.
Fixes #1955

gateway: add path prefix for directory listings

---

core/corehttp/gateway_handler.go

gateway requests that fail to resolve would cause goroutines to build up indefinitely.
License: MIT

add closenotify and large timeout to gateway

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/jbenet/go-datastore/coalesce/coalesce.go
Godeps/_workspace/src/github.com/jbenet/go-datastore/elastigo/datastore.go
Godeps/_workspace/src/github.com/jbenet/go-datastore/flatfs/flatfs.go
Godeps/_workspace/src/github.com/jbenet/go-datastore/flatfs/flatfs_test.go
Godeps/_workspace/src/github.com/jbenet/go-datastore/lru/datastore_test.go
Godeps/_workspace/src/github.com/jbenet/go-datastore/timecache/timecache.go
repo/config/datastore.go
repo/fsrepo/defaultds.go

closes #1963 
Moved this onto a branch in this repo so i could rebase it before merging.
License: MIT
Signed-off-by: rht <rhtbot@gmail.com>

Add config option for flatfs no-sync

---

cmd/seccat/seccat.go

It was panicking because of the `nil` context

seccat: fix secio context

---

Makefile
fuse/mount/fuse.go

reviving #1705 so we can get it closed.
License: MIT
Signed-off-by: Jeromy Johnson <why@ipfs.io>

disable building fuse stuff on windows

---

core/commands/files/files.go

dont check types of child entries if `-l` isnt specified.
License: MIT

ipfs files ls without -l is faster

---

core/commands/root.go

This was probably overlooked after copy-pasting.

commands: fix description of --api

---

commands/cli/parse.go
commands/command.go
commands/http/client.go
commands/http/parse.go
core/commands/dht.go
core/commands/files/files.go
core/corehttp/gateway_handler.go
fuse/ipns/ipns_unix.go
merkledag/utils/utils.go
merkledag/utils/utils_test.go
mfs/mfs_test.go
mfs/ops.go
p2p/crypto/key.go
p2p/peer/addr/addrsrcs_test.go
path/path.go
routing/record/selection.go
routing/record/validation.go
tar/format.go
util/ipfsaddr/ipfsaddr.go
util/ipfsaddr/ipfsaddr_test.go

Just small fixes.
Another option, it would be faster to just use strings.Join(elms, "/") and put it in path/path.go, since golang's path does path.Clean of every elements.

Remove hardcoded "/"

---

core/corerepo/gc.go

Caveat: if pin size > watermark or storagemax, the gc will trigger but won't clean the pinned files.
cc: @lgierth

Fix maybeGC trigger condition

---

core/commands/root.go
core/commands/sysdiag.go
core/corehttp/gateway.go
core/corehttp/gateway_test.go

I'm not 100% sure this is a good idea, but I though I'd put it up for discussion. Chatted about this briefly with @harlantwood, and think it's useful.
Need to build with `make build` so that `repo/config.CurrentCommit` gets set, otherwise it'll just be an empty string.

gateway: /version tests, add CurrentCommit

---

core/commands/ipns.go
core/commands/object.go
core/commands/resolve.go
core/commands/tar.go
test/sharness/t0051-object.sh
test/sharness/t0100-name.sh
test/sharness/t0160-resolve.sh
test/sharness/t0240-republisher.sh

License: MIT
Signed-off-by: Nick Hamann <nick@wabbo.org>

Add newline to end of `ipfs object put` text output.

---

importer/balanced/balanced_test.go
importer/helpers/dagbuilder.go
importer/importer.go
importer/trickle/trickle_test.go
unixfs/mod/dagmodifier.go

PR to keep track and measure the time and memory perf of `ipfs add` with channel iterator replaced with chunker object. Perhaps have to wait until go2.x when channel iterator becomes about as fast as counter object.
Ran perf test on lots of 1MB files, `ipfs add` is about O(rsync) (faster than `git add`?)
Edit: this plot below is misleading (the add operation is run under a goroutine, and without outputDagnode checking, the client exits long before the (ephemeral) daemon has finished the process), updated plot is in my last comment.

Remove chunker channel

---

core/commands/root.go

I couldn't find this piece of information in the official docs, just scattered over a few issues on GitHub.

--help: Add a note on using IPFS_PATH to the footer of the helptext.

---

test/sharness/t0020-init.sh

This is needed on OSX otherwise the trash directory for the
t0020-init.sh test fails to be removed due to a permissions
error.
This fixes issue https://github.com/ipfs/go-ipfs/issues/2026.
License: MIT

t0020: cleanup dir with bad perms

---

README.md
commands/cli/parse.go
commands/command.go
core/commands/external.go
core/commands/root.go

Allows us to have `ipfs-update` as a separate binary be called as `ipfs update`
License: MIT

initial support for commands to use external binaries

---

.travis.yml

License: MIT
Signed-off-by: Juan Benet <juan@benet.ai>

travis-ci: use go 1.5.2

---

commands/http/handler.go
commands/http/handler_test.go
core/corehttp/gateway_handler.go
repo/config/init.go
test/sharness/t0230-channel-streaming-http-content-type.sh

this is #1979 I just hardcoded the values.
@Dignifiedquire, give this a shot

Dignifiedquire fix/access controll headers

---

repo/config/init.go
test/sharness/t0230-channel-streaming-http-content-type.sh

Nedded to fix https://github.com/ipfs/js-ipfs-api/issues/76 and for https://github.com/ipfs/js-ipfs-api/issues/128 for details why this is needed see: https://github.com/ipfs/js-ipfs-api/issues/76#issuecomment-158216527
--- 
Probably lots wrong with this, so please excuse any obvious mistakes

Add correct access control headers to the default api config

---

p2p/net/swarm/addr/addr.go
p2p/net/swarm/addr/addr_test.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_addr_test.go
p2p/net/transport/utp.go
test/sharness/t0130-multinode.sh

implement utp transport

---

test/sharness/t0080-repo.sh

This may not fix https://github.com/ipfs/go-ipfs/issues/2028.
But it might help us get more information when it fails.

t0080 improvements

---

core/commands/root.go

Allows the use of 'get' on the gateways.
License: MIT

add 'get' to the allowed gateway commands

---

exchange/bitswap/bitswap_test.go
fuse/readonly/ipfs_test.go
merkledag/merkledag_test.go
test/supernode_client/main.go

This should fix at least part of issue #2043.
License: MIT

fix t.Fatal in a goroutine

---

misc/launchd/README.md
misc/launchd/install.sh
misc/launchd/io.ipfs.ipfs-daemon.plist

For some reason, I had to sudo launchctl load, after doing sudo chmod 600 ~/Library/LaunchAgents/io.ipfs.ipfs-daemon.plist and sudo chown root ~/Library/LaunchAgents/io.ipfs-daemon.plist on el capitan.

Have install.sh put the full path to ipfs binary if detected

---

commands/cli/parse.go
commands/files/serialfile.go
core/commands/add.go
core/corehttp/gateway_handler.go

Parse paths with filepath instead of just path
https://github.com/ipfs/go-ipfs/issues/1922

Fix path parser in add command

---

cmd/ipfs/main.go
commands/http/client.go
commands/http/handler.go
commands/http/parse.go
repo/config/version.go

#2003 but on master.
closes #1990, #2003
Addresses https://github.com/ipfs/go-ipfs/pull/2003#discussion_r46231266 by checking if the repo is process-locked.

Move api version check to header

---

core/core.go

Minor typo, change "incorrectly formatter" to "incorrectly formatted"

fix typo in AddrFilters error message

---

commands/cli/parse.go
commands/files/file_test.go
commands/files/multipartfile.go
commands/files/serialfile.go
commands/files/slicefile.go
commands/http/client.go
commands/http/multifilereader.go
commands/http/multifilereader_test.go
core/commands/add.go
core/coreunix/add.go
exchange/bitswap/workers.go
importer/importer.go
mfs/dir.go
mfs/ops.go

This is based on #2039 so wait until it merges to review this.
But this removes the whole recursive multipart thing.
The multipart 'Next()' bug in #1688 is what i set out to fix, but that was apparently fixed in go version 1.5.2

flatten multipart transfers

---

commands/cli/parse.go
commands/http/client.go
commands/http/handler.go
core/corehttp/gateway_handler.go
test/sharness/t0235-cli-request.sh

Our multipart file code cannot handle sending zero files. So if the number of input files is nil, don't do any multipart stuff.
Also did some other cleanup along the way to make debugging easier.

fix close notify

---

routing/dht/dht.go
routing/dht/routing.go

Peers who send records with expired validity are currently not sent a 'fixup' record after a peer does a get operation. This makes invalid records just return a blank record so that the later fixup logic can send them a better record.
License: MIT

send record fixes to peers who send outdated records

---

cmd/ipfs/main.go
test/sharness/t0063-external.sh

Fixes a slight bug where external commands would be executed in the cwd of the daemon, as opposed to the client.
License: MIT

run external commands client side

---

core/commands/object/object.go
core/commands/object/patch.go
core/commands/root.go
test/sharness/t0051-object.sh

refactor object patch command to work more betterer

---

namesys/dns.go
namesys/dns_test.go
namesys/namesys.go
namesys/routing.go

Also fixes non-recursive resolve erring instead showing one step.
The patch of `core/commands/resolve.go` could be done better but I don't know how to get access to `ErrResolveRecursion`.
It allows for dnslinks into sub-segments. So ie. hosting multiple blogs on just domains from one pubkey.
Fixes #2059

namesys: Make paths with multiple segemnts work. Fixes #2059

---

README.md

Created with https://github.com/dkhamsing/frankenstein
Was | Now 
--- | --- 
http://github.com/ipfs/go-ipfs/issues | https://github.com/ipfs/go-ipfs/issues 
http://golang.org/doc/install | https://golang.org/doc/install 
Was | Now 
--- | --- 
http://hub.docker.com/r/jbenet/go-ipfs | https://hub.docker.com/r/jbenet/go-ipfs/ 
http://ipfs.io/docs/install | http://ipfs.io/docs/install/ 
https://code.google.com/p/protobuf/downloads/list | https://github.com/google/protobuf 
Previously #2123

Update README URLs based on HTTP redirects 

---

core/commands/dht.go

cleanup dht cmd output and fix unrecognized events

---

core/commands/object/patch.go
test/sharness/t0051-object.sh

We didnt have any tests for set and append data. This adds some and fixes a bug that they exposed (hint: it didnt work)
License: MIT

add tests for and fix {set/append}-data

---

.travis.yml
Dockerfile
circle.yml
p2p/net/swarm/dial_test.go
test/ipfs-test-lib.sh
test/sharness/lib/test-lib.sh
test/sharness/t0300-docker-image.sh

This PR contains @ChristianKniep's fix from PR #1806 (change Dockerfile order to create VOLUME under user ipfs) and add a Sharness test script (t0300) with some docker tests.
@ChristianKniep's fix is fixing issue #1804 (Boot2Docker: VOLUME prevents chown to have effect).

Docker image volume fix and Sharness tests 

---

mfs/dir.go

a small amount of cleanup in mfs dir

---

.gitignore
test/bin/.gitignore
test/bin/ipfs-pin-stat
test/sharness/lib/test-lib.sh
test/sharness/t0081-repo-pinning.sh

t0081-repo-pinning.sh looks buggy to me without those 2 fixes.
Because when we grep for just "direct", it matches "indirect":
```
> echo "indirect" | grep direct
indirect
> echo "indirect" | egrep "\bdirect\b"
> echo "direct" | egrep "\bdirect\b"
direct
```
Unfortunately with those 2 fixes, now some tests are failing. This either means that we have bugs in go-ipfs that were previously hidden or that the tests that fail are wrong.
cc @whyrusleeping @jbenet

Fix test str contains

---

test/sharness/lib/test-lib.sh

With GNU "grep" \b works but it's safer to use "egrep" which is also
POSIX rather than "grep" as not all the "grep"s out there might support \b.
License: MIT

test-lib: improve on previous fix

---

namesys/routing.go

Retrieve the ipns record and public key concurrently for a bit of speedup on name resolves.
License: MIT

do resolve operations concurrently

---

core/commands/add.go
core/coreunix/add.go
test/sharness/t0042-add-skip.sh

Fixes ipfs/go-ipfs/#2145. The --hidden switch (still) only affects recursive adding.
License: MIT
Signed-off-by: Stephen Whitmore <noffle@ipfs.io>

Lets 'ipfs add' include top-level hidden files

---

core/bootstrap.go
core/core.go
test/sharness/t0121-bootstrap-iptb.sh

fix bootstrapping bug and add real test for bootstrapping

---

commands/http/handler.go
test/sharness/t0060-daemon.sh

Fix SetAllowedOrigins

---

commands/http/handler.go
test/sharness/t0230-channel-streaming-http-content-type.sh

Add Server field in HTTP API response header 

---

README.md
core/commands/add.go
core/commands/root.go

Generic doc fixes to `ipfs add`

---

core/commands/bitswap.go

Fixed up docs for bitswap

---

cmd/ipfs/daemon.go

See https://github.com/ipfs/go-ipfs/commit/dec4a72da1342eb750c581fb5072fccbdd79281f
License: MIT

Edited following @chriscool feedback

---

contribute.md

Because this requirement is not listed anywhere, but was mentioned in https://github.com/ipfs/go-ipfs/pull/2202#issuecomment-171876804.
License: MIT

Added squash note to contribute.md

---

core/commands/external.go

Adds an argument to the formatted error string.
License: MIT
Signed-off-by: Thomas Gardner <tmg@fastmail.com>

trivial: fix `ipfs update` error message

---

core/corehttp/gateway_handler.go
test/sharness/t0112-gateway-cors.sh

This potentially closes https://github.com/ipfs/go-ipfs/issues/934
`OPTIONS` is a noop request that is used by the browsers to check if server explicitly accepts  cross-site `XMLHttpRequest` (XHR).  The acceptance is indicated by the presence of CORS headers.
Before this fix user could enable CORS headers in the Gateway config (note that this disabled by default):
ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Headers '["X-Requested-With"]'
..but requests sent from JavaScript failed due to the lack of support for `OPTIONS` request type.
I described details of the problem with XHR in …

Gateway: add support for HTTP OPTIONS request type

---

core/corerepo/pinning.go
core/pathresolver.go
path/path.go
path/path_test.go
test/sharness/t0081-repo-pinning.sh

Fixes ipfs/go-ipfs#2155 by turning the hash path arguments into keys and unpinning directly, rather than running a full core.Resolve on them. This lets users fail fast when they try to remove pins that they don't have locally.
License: MIT
Signed-off-by: Stephen Whitmore <noffle@ipfs.io>

Resolve paths in 'pin rm' /wo network lookup

---

core/commands/dns.go
core/commands/id.go

The JSON package developers reckon no trailing newline is a feature;
it allows marshalled JSON to be embedded inside more JSON.[0]
--
[0] https://golang.org/pkg/encoding/json/
License: MIT
Signed-off-by: Thomas Gardner <tmg@fastmail.com>

fix #1083: Append a newline to `ipfs id` output.

---

Makefile

Makefile: add PHONY targets and a help message

---

cmd/ipfs/daemon.go

See https://github.com/ipfs/go-ipfs/pull/2180#issuecomment-171889567
License: MIT

Added small note about shutdown

---

CHANGELOG.md

finally add changelog for v0.3.11

---

namesys/dns.go
namesys/dns_test.go

Thus allowing to CNAME main site entry to gateway and still specify dnslink.
Resolves ipfs/notes#39. Option 4 and 5.
Would be great if merged with #2139, and shouldn't even conflict (depending on merger)
Also if you have any comments to the code, I would love to hear them. If anything could have been done better... I am not proficient in Go..

Make dns resolve paths under _dnslink.example.com

---

core/commands/ping.go
core/commands/swarm.go

Also fixes some grammar in pings.
See https://github.com/ipfs/go-ipfs/pull/2265#issuecomment-177062200
License: MIT

Added quotes to swarm and ping descriptions

---

commands/http/handler.go
commands/reqlog.go
commands/request.go
core/commands/active.go
core/commands/diag.go
test/sharness/t0065-active-requests.sh

This lets us see running commands and some basic info about them.
The next PR on this front will allow us to cancel requests by killing their contexts.

commands diagnostics

---

core/commands/config.go

This was coming up as an extra space. For instance:
```
$ curl -i http://localhost:5001/api/v0/config?arg=kitten
//"Message": "Failed to get config value:  key has no attributes",
```
Removing it here.
License: MIT

Removed extra space

---

core/commands/id.go

Cleaned up `ipfs id` mans

---

pin/gc/gc.go
repo/fsrepo/fsrepo.go

Wire ctx to getdag operations in gc.GC

---

core/commands/id.go

I was super confused how to use the `-f` flag. This helped, but I had to go into
the test files to find it. Added it here.
License: MIT

Added an example to `ipfs id`

---

core/commands/publish.go

This closes #2312
License: MIT

Added note about time formatting

---

cmd/ipfs/daemon.go
core/commands/mount_nofuse.go
core/commands/mount_unix.go
core/commands/mount_windows.go
core/core.go
fuse/ipns/ipns_test.go
fuse/mount/fuse.go
fuse/mount/mount.go
fuse/node/mount_darwin.go
fuse/node/mount_nofuse.go
fuse/node/mount_test.go
fuse/node/mount_unix.go
fuse/node/mount_windows.go

This lets FUSE mounts to track whether they are active or not by
tracking when fs.Serve terminates.
License: MIT
Signed-off-by: Stephen Whitmore <noffle@ipfs.io>

Mounts detect unmounts and track mount state.

---

commands/http/handler.go

This issue is referenced in the comments of  #2108.  Docker had a similar bug mentioned in golang/go#14001

fix go1.6rc2 panic where closenotify was called from wrong goroutine

---

core/corehttp/gateway_handler.go

Same cause/fix as  #2315:
```
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/128.104.184.236/tcp/4001
Swarm listening on /ip4/172.17.42.1/tcp/4001
Swarm listening on /ip6/2607:f388:1082:fff9:a248:1cff:fe90:c73a/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
panic: net/http: CloseNotify called after ServeHTTP finished
goroutine 180 [running]:
net/http.(*response).CloseNotify(0xc8220684e0, 0x0)
/home/r/go/src/net/http/server.go:1535 +0x9d
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/prometheus/client_golang/prometheus.(*fancyResponseWriterDelegator).CloseNotify(0xc820028318, 0xc821a0) …
```

fix another panic where CloseNotify was called from wrong goroutine

---

exchange/bitswap/bitswap_test.go
exchange/bitswap/wantmanager.go

https://travis-ci.org/ipfs/go-ipfs/jobs/107894026
In some of these bitswap tests, the peers werent making it into the wantmanager by the time `HasBlock` was called, meaning some peers missed the announcements. This slowed down most of the tests when it happened (as it caused them to wait for a rebroadcast), but in the test that was testing no rebroadcasts, it caused a timeout and failure. This should fix the issue.
License: MIT

wait for peers in wantmanager to all appear

---

README.md
test/integration/Makefile

I've set up automatic builds of the ipfs/go-ipfs image, but it looks like they prevent the existing jbenet/go-ipfs image from being automatically built. This seems to be due to the integration being done using github services instead of generic webhooks, and docker hub doesn't seem to offer using these webhooks instead. That's why only *one* automatic build can be triggered by pushing to the repo.
This PR updates all mentions of jbenet/go-ipfs in the repo, but I wanna give the old automated build a grace period, it's used wildly (>300k pulls). I'm not 100% sure how to maintain the automation here, but when in doubt a daily cronjob will do I guess?
Any more thoughts? @jbenet @Luzifer

Docker automatic builds

---

routing/dht/util.go

This has needed to be done for a while. Since we require that we receive 16 records from the dht before making a decision, we should probably store more than 16 records on the dht for a given put call.
License: MIT

bump kvalue from 10 to 20

---

core/commands/refs.go

Capitalized `Tokens`

---

docs/windows.md

This adds a lot of steps that were missing and makes it possible to build on Windows.
License: MIT

docs: improve windows.md

---

test/sharness/t0065-active-requests.sh

This failure: https://circleci.com/gh/ipfs/go-ipfs/2994
appears to be because the test thats failing gets run before the log tail command even gets to start.
License: MIT

add a pause to fix timing on t0065

---

core/commands/object/object.go
core/commands/object/patch.go

Capitalized Merkle, added single quotes, periods

---

README.md

Add information about installing gx into readme

---

commands/cli/parse.go
commands/cli/parse_test.go
core/commands/dht.go

fix panic in cli arg parsing

---

core/commands/get.go

Added ticks, `the`, and defaults to `get`

---

mfs/mfs_test.go

Addresses https://github.com/ipfs/go-ipfs/issues/2361.
This would happen once every blue moon when `rand.Intn(1024) == 0`.

Fixes range error by using > 0 length buffer.

---

core/commands/resolve.go

Removed double spaces, added `an`, siwitched carrot to dollar

---

core/commands/log.go

See https://github.com/ipfs/http-api-spec/pull/39#discussion_r53227906
License: MIT

Added a description to level argument

---

core/commands/cat.go
core/commands/get.go
core/commands/ls.go
core/commands/pin.go
core/commands/refs.go
core/commands/unixfs/ls.go

This should make it a bit easier to read. Cf https://github.com/ipfs/http-api-spec/pull/42#discussion_r53164138
Should also be applied to `cat`, `get`, and `unixfs/ls`, if this looks good to anyone. 
License: MIT

Edit the ls.go description

---

core/commands/files/files.go

Copy edited files command file

---

core/commands/ls.go
core/commands/object/object.go

Add option to display headers for « ipfs object links ».

---

commands/reqlog.go
core/commands/active.go

This way if we're wanting to inspect the commands over a longer period of time, we can increase the timeout (at the expense of memory), or leave it at zero to conserve memory.
License: MIT

add command to change keep time for reqlog objects

---

Makefile

This should help a bit with the random stalls we've been seeing, skip multireq altogether :D
License: MIT

force gx to use 0.4.0 gateways for now

---

core/commands/files/files.go
test/sharness/t0250-files-api.sh

This fixes issue #2379 (`ipfs files ls` should default to '/' if path is not given).

files: make 'files ls' defaults to /

---

mfs/dir.go
test/sharness/t0250-files-api.sh
unixfs/mod/dagmodifier.go
unixfs/mod/dagmodifier_test.go

Thanks to @RichardLitt for saying "truncate doesnt work" and making go try to prove him wrong and find a bug in the process.
License: MIT

fix minor mfs truncate bug

---

test/sharness/t0060-daemon.sh

Addresses https://github.com/ipfs/go-ipfs/issues/1936.
Removes all of the hardcoded ports and defaults to non-standard API,
Gateway, and Swarm ports.
A good next step would be to choose ports randomly in a looping fashion, so
that eventually a free set of ports can be found on the test machine.

Adds arbitrary port support to t0060-daemon.sh

---

README.md

cc @RichardLitt and @jbenet 
License: MIT

some fixes to the readme install instructions

---

core/commands/pin.go
core/commands/refs.go
merkledag/merkledag.go
test/sharness/t0081-repo-pinning.sh
unixfs/archive/tar/writer.go
unixfs/io/dagreader.go

I refactored the dagservice have one new `GetMany` method that just mimics the interface of the blockservices similar method. It takes some keys and returns a channel of nodes in no particular order.
I then removed the `GetDAG` and `GetNodes` methods from the dagservice interface and refactored them to `GetMany`. 
finally, I refactored `FetchGraph` to use `GetMany`, and in doing so, it has better error cases (can actually fail through from the blockservice layer) and uses wayyyy fewer goroutines. (though still a good number of them).
cc @noffle @lgierth for CR
cc @mildred since youre working on similar cleanup type stuff

refactor merkledag fetching methods

---

README.md

Otherwise there is invalid cert error.
License: MIT

Change link to dist to be under IPNS in readme

---

core/commands/bitswap.go

You can include an array of keys, not just a single key, but this isn't specified anywhere in the help text.

Noted ability to specify multiple keys in `bitswap unwant`

---

core/commands/config.go

Added defaults to config opts descriptions

---

test/sharness/lib/test-lib.sh
test/sharness/t0020-init.sh

This fixes some previous mistakes I made and replaces PR #2368

sharness: replace POSIX prereq with STD_ERR_MSG

---

core/commands/publish.go
fuse/ipns/ipns_test.go
test/sharness/lib/iptb-lib.sh
test/sharness/t0031-mount-publish.sh
test/sharness/t0045-ls.sh
test/sharness/t0121-bootstrap-iptb.sh

Addresses https://github.com/ipfs/go-ipfs/issues/1186.

Prevents 'ipfs name publish' when /ipns is mounted.

---

core/commands/files/files.go

addresses https://github.com/ipfs/go-ipfs/issues/2380 and https://github.com/ipfs/go-ipfs/issues/2380#issuecomment-188443493

makes 'ipfs files write' usage docs clearer

---

core/commands/dns.go

It is not useful. See https://github.com/ipfs/http-api-spec/pull/41#discussion_r53482505
License: MIT

Remove period from dns text examples

---

README.md

These changes are inspired by the numerous issues in `go-ipfs` and `support`
repos about users trying to install with `go get` alone and running into gx
error messages, with the intent of making the installation instructions more
clear and explicit.

Makes install from source instructions clearer.

---

misc/launchd/install.sh

OK, this checks that the actual value is above 10.9, since this should work on 10.10 as well (though I only tested 10.11).

More robust version checking

---

Makefile
bin/check_go_path

Make sure that the user cloned the code to the correct place, this is useful since go is very strict about paths.
cc @chriscool for some code review and @RichardLitt for doc stuff
License: MIT

assert that you must build from inside your gopath

---

core/commands/dns.go
core/pathresolver.go

dns: update dns command docs

---

commands/option.go
commands/option_test.go
commands/request.go
core/commands/pin.go

@RichardLitt  i made you a present.
ref: https://github.com/whyrusleeping/todo/issues/5
License: MIT

add default option value support to commands lib

---

core/commands/ls.go
core/commands/object/object.go
core/commands/unixfs/ls.go
core/corehttp/gateway_handler.go
core/corehttp/gateway_test.go
merkledag/coding.go
merkledag/merkledag.go
merkledag/merkledag_test.go
merkledag/node.go
merkledag/traverse/traverse_test.go
path/resolver.go
path/resolver_test.go
pin/pin_test.go
pin/set.go
pin/set_test.go
unixfs/mod/dagmodifier.go

- Remove usage of merkledag.Link.Node pointer outside of merkledag
- Make Node.Unmarshal() private: it is not used elsewhere
- Rename Decoded(= into DecodeProtobuf() to clearly give intent about the byte wire format
Obsoletes #1916 and #1902.
This prepares for inclusion of IPLD where the Node pointer might not be publicly accessible of even be there. We should probably move away from using the struct attributes and use functions to access them instead. This will make it easier to plug in IPLD in place of merkledag.

Simplify merkledag package interface to ease IPLD inclusion

---

core/commands/repo.go
core/corerepo/stat.go
test/sharness/t0080-repo.sh

Implements https://github.com/ipfs/go-ipfs/issues/1744
Builds on top of https://github.com/ipfs/go-ipfs/pull/2289
```sh
> ipfs repo stat
NumObjects      11
RepoSize        52064
RepoPath        /Users/david/.ipfs
```

Feature: `ipfs repo stat`

---

appveyor.yml

Not green, but at least it executes tests again (#2326). 
Before: https://ci.appveyor.com/project/kalmi/go-ipfs/build/1
After: https://ci.appveyor.com/project/kalmi/go-ipfs/build/3

Appveyor fix to make it execute tests again

---

bin/container_daemon

This somehow got lost on the way

docker: start daemon with --enable-gc

---

core/commands/pin.go

1. `ipfs pin ls` now defaults to "all", not "recursive".
2. `ipfs pin rm` should respond with `Unpinned: HASH`, not `Pinned: HASH`. This is a breaking change.
I don't know how you feel about multiple commits per pull but these were both trivial.

Pin command fixes

---

cmd/ipfs/daemon.go
cmd/ipfswatch/main.go
core/corehttp/gateway.go
core/corehttp/gateway_handler.go
core/corehttp/gateway_test.go
repo/config/gateway.go
repo/config/init.go
test/supernode_client/main.go

See https://github.com/ipfs/go-ipfs/pull/1971#discussion_r45099840 ff.
Only allow paths, so we stay local to this gateway,
and don't get tricked into linking to a different host,
or even redirecting to one.
I can't come up with a concrete attack right off the bat,
but who knows how things are going to change.
Not restricting it would be silly.
**Edit**:

gateway: harden path prefix

---

core/commands/object/object.go

This is my first crack at go code.. so feel free to criticize and make suggestions.
My goal here is to retain the current `ipfs object put` logic, but allow a --datafieldenc argument which accepts "text" ot "base64".  Default is "text" to retain previous functionality.  Then I can upload raw binary data using `--datafieldenc base64` and a base64 encoded data field.
Reference Issue #1582

Add option to decode 'Data' field as base64

---

cmd/ipfs/daemon.go
cmd/ipfs/ulimit_unix.go
test/sharness/t0061-daemon-opts.sh

try to raise ulimit if its too low

---

core/commands/dht.go
core/commands/dht_test.go
namesys/publisher.go

This broke at some point, i didnt notice. Now its fixed, and theres a test. (or will be soon, i realize as i type this that i forgot to add the test file, so hold on one second)
License: MIT

fix dht command key escaping

---

core/commands/root.go

We don't list `ipfs files` under the subcommands of `ipfs`.

Adds Files API cmd to helptext

---

core/corerepo/gc.go
repo/config/init.go

We didn't previously initialize the Datastore config section.
The respective function exists, but was dead code up until now.
This lead to weird decisions like the GC code deciding on defaults,
and writing these to the config file. Don't want GC to touch the config.
License: MIT

repo: properly init Datastore config, and leave it be

---

merkledag/merkledag.go
merkledag/merkledag_test.go
test/sharness/t0090-get.sh

This allows the nodepromise thing to fail. In cases such as `ipfs refs -r` run offline when not all blocks are local, ipfs currently hangs. 
License: MIT

allow promises to fail

---

repo/fsrepo/fsrepo.go

This makes the does-repo-exist check return true if 'config' exists OR
'datastore' exists, rather than a negated AND. This is helpful for js-ipfs or
other implementations which may not use a 'datastore' directory, since it
prevents false positives that could result in go-ipfs ovewriting another ipfs
implementation's repo.

Makes repo existance check more sensitive.

---

core/commands/add.go

This explains mostly what the wrap option does, because it was not entirely clear
License: MIT

Added a long description to add

---

test/sharness/Makefile

I think it is better to clean all the binaries.

sharness/Makefile: clean all BINS when cleaning

---

core/commands/resolve.go

Currently it prints out error message but should just print
the intermediate result as it is what we expect.
License: MIT

Make non recursive resolve print the result

---

core/commands/incfusever/doc.go
core/commands/incfusever/incfusever.go

fixes #2573 
Cleaned out all unused godeps back in #2557, without this in godeps, `core/commands/incfusever` fails to build. That code is unused, so i'm just going to remove it. Its only purpose was to prevent godeps from deleting the vendored go-fuse-version package.
License: MIT

clean up unused incfusever code

---

core/commands/add.go
core/commands/files/files.go
core/coreunix/add.go
mfs/dir.go
mfs/ops.go
test/sharness/t0040-add-and-cat.sh

This also fixes a bug where adding with -n would prevent directories from
being outputted. Addresses https://github.com/ipfs/go-ipfs/issues/2530.
Bonus: directories no longer appear at the end of the list for `ipfs add` --
they're in order! :dancers:

Outputs added directories as they are traversed.

---

core/commands/publish.go

This typo can be seen by running `ipfs name publish --help`

Fix a typo in publish.go

---

namesys/routing.go

IPNS name was prepended with '/ipns/' too early causing an error when decoding the multihash. 
Instead, the resolvers should handle name manipulation rather than `ipns.go`
Fixes #2527
Related #2565

ipfs name resolve --local fixed multihash error

---

core/commands/object/diff.go

`core.Resolve` is what we want for being able to resolve ipns names... not `node.Resolver.Resolve` somewhat confusing...
License: MIT

fix resolve call in object diff

---

core/commands/refs.go

Added default values to refs

---

commands/cli/cmd_suggestion.go
commands/cli/parse.go
commands/cli/parse_test.go
core/commands/root.go

Fixes #2501
parseOpts now does some preliminary path screening to prevent
command sequences like
`ipfs <hash> cat`
from succeeding. The tests affected by this have been slightly altered,
but should be restored once parseOpts is decoupled from path analysis.
Command suggestion printing has also been factored into a single
function.
License: MIT
Signed-off-by: Thomas Gardner <tmg@fastmail.com>

commands/cli: fix parsing of incorrect permutations

---

core/commands/dht.go
core/commands/swarm.go
test/sharness/t0170-dht.sh

addresses https://github.com/ipfs/go-ipfs/issues/2494

unix-friendly output for 'ipfs dht' commands

---

Godeps/_workspace/src/github.com/olekukonko/ts/.travis.yml
Godeps/_workspace/src/github.com/olekukonko/ts/LICENCE
Godeps/_workspace/src/github.com/olekukonko/ts/README.md
Godeps/_workspace/src/github.com/olekukonko/ts/doc.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_darwin.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_linux.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_other.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_test.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_unix.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_windows.go
Godeps/_workspace/src/github.com/olekukonko/ts/ts_x.go
Makefile

I had a check in the makefile to make sure that windows builds don't fail, but it only got run by `make test`, and our CI runs `make test_expensive`. I moved that check over to `test_expensive` so we don't miss this again.
License: MIT

re-add dep needed for windows builds

---

Dockerfile
test/Dockerfile

This error recently appeared when building the Dockerfile:
ERROR: unsatisfiable constraints:
go-1.5.4-r0:
breaks: world[go=1.5.3-r0]
It looks that now upstream requires go 1.5.4-r0 not 1.5.3-r0.
This should help fixing issue #2607.
License: MIT

Dockerfile: use go version 1.5.4-r0

---

Makefile
cmd/ipfs/Makefile

Move the go commands that should run under cmd/ipfs in the Makefile in
cmd/ipfs rather than doing a "cd cmd/ipfs && go ..." in the root
Makefile.
The "cd cmd/ipfs && go ..." lines causes problems with GNU Emacs's
compilation mode.  With the current setup Emacs is unable to jump to
the location of the error outputted by go compiler as it can not find
the source file.  The problem is that the embedded "cd" command causes
Emacs's compilation mode to lose track of the current directory and
thus attempts to look for the source file in the wrong directory.

Refactor Makefile.

---

Dockerfile
test/Dockerfile

This somehow got lost in the Dockerfile overhaul.

docker: allow IPFS_LOGGING to be passed

---

commands/cli/parse.go

Follow up to PR https://github.com/ipfs/go-ipfs/pull/2135.
When trying to add dot (current working directory) the input path was not previously standardized to forward slashes which would cause malformed directory listings like those in issue https://github.com/ipfs/go-ipfs/issues/1922.
This commit should sanitize the path in the same way it is done at other entry points in the parser and force the path to use forward slashes instead of the FS native delimiter.
Possibly related to issue https://github.com/ipfs/go-ipfs/issues/1691.

Fix dot path parsing on Windows

---

cmd/ipfs/init.go
repo/fsrepo/fsrepo.go
repo/fsrepo/fsrepo_test.go

After a discussion with @noffle, we decided its best not to have a `-f` option on init, git doesnt have one, and if we keep it, we need to not remove $IPFS_DIR recursively when we do.
ref #2478 
License: MIT

remove init -f option, its bad

---

README.md
cmd/ipfs/daemon.go
cmd/ipfs/init.go
cmd/ipfs/main.go
commands/cli/helptext.go
core/commands/add.go
core/commands/bootstrap.go
core/commands/config.go
core/commands/dht.go
core/commands/name.go
core/commands/object/object.go
core/commands/pin.go
core/commands/ping.go
core/commands/refs.go
core/commands/root.go
core/commands/swarm.go
core/commands/unixfs/unixfs.go
test/sharness/t0010-basic-commands.sh
test/sharness/t0040-add-and-cat.sh
test/sharness/t0044-add-symlink.sh
test/sharness/t0060-daemon.sh
test/sharness/t0235-cli-request.sh

Hi everyone!
I've made some changes to the `ipfs` CLI tool's output. These aren't major changes, but they're maybe enough to warrant talking about: nobody likes their CLI tool's output suddenly changing from underneath them. These changes are not major, but do represent **a** change.
That's very fair, so I wanted to share my design approach and goals to better justify the changes I've made here. I'm a fan of [esr's unix rules](https://en.wikipedia.org/wiki/Unix_philosophy#Eric_Raymond.E2.80.99s_17_Unix_Rules), and so my commits here reflect that (In particular, **discoverability**). The changes are broken down by the high level goal they fit under below.
I expect this to take several rounds to complete -- CLI output is not a standardized thing and is also ripe for bikeshedding. Let's try …

CLI: discoverability and consistency

---

blockservice/blockservice.go
exchange/bitswap/bitswap.go
exchange/bitswap/bitswap_test.go
exchange/bitswap/decision/engine.go
exchange/bitswap/decision/ledger.go
exchange/bitswap/wantlist/wantlist.go
exchange/bitswap/wantmanager.go
exchange/bitswap/workers.go

wire contexts into bitswap requests more deeply

---

core/commands/dht.go

A should be capitalised, as it is a new clause; `not` should not be capitalized, as there is no value judgement (it is a statement), and the emphasis is offputting without adding any technical backing. I just do not think it is necessaary.
License: MIT

Capitalized `a`, lowercased `not`

---

Makefile

I think the changes to use gx for iptb in https://github.com/ipfs/go-ipfs/pull/2545 require newer versions of gx and gx-go, so let's require that in the Makefile.

Makefile: update gx and gx-go versions

---

cmd/ipfs/init.go
test/sharness/t0022-init-default.sh

Modified init command to receive default configuration from stdin. The changes enable us to use existing key-pair, datastore configuration while initializing new ipfs node.
License: MIT
Signed-off-by: Sivachandran <sivachandran.p@gmail.com>
@whyrusleeping

Implements repository initialization with default config

---

core/commands/log.go

This uses a stringList to output each log command as an item in an array in an object called Strings, instead of using the MessageOutput func.
This closes #2636.
License: MIT

Marshal log ls better

---

test/sharness/lib/test-lib.sh

It is annoying to see `docker is /usr/bin/docker` at the beginning of the tests.

test-lib: make checking for docker silent

---

contribute.md

The link to the commit file shell link should be to the raw file. That makes it easier for peopel to wget it without caring about using GitHubs interface. Perhaps this should also be hosted on IPFS

Update shell link to allow wget

---

test/sharness/t0170-dht.sh

Here are a few cleanups or small fixes in t0170-dht.sh.

t0170 misc fixes

---

contribute.md

This should be more prominent. We also need a much better description of how to run tests - rigt now, we are dependant on Travis for the majority of testing, I believe. If there was a clear guide here on how to run the appropriate tests for each kind of PR, that would be fantastic.
We also really ought to have a section asking people to add all of the tests that they can think of.
License: MIT

Moved Tests up in Contribute.md

---

commands/cli/helptext.go

I think that this is useful, even though it is also shown in the Arguments and Options section below. What do you think, @noffle?
License: MIT

Show Synopsis in long help

---

core/commands/repo.go
core/commands/resolve.go
core/commands/root.go
core/commands/swarm.go
core/commands/version.go

Specifically, to `repo`, `resolve`, `swarm`, and `version`. Part of #2484.
License: MIT

Added Default false to all remaining options

---

core/commands/pin.go

'count' is never referenced in the code, and adds nothing when run with `ipfs pin ls` currently. I have removed it; add it again when there is actual logic to reflect. Also, added a Default(false) to quiet.
Part of #2484
License: MIT

pin ls: Remove count option, add Default to quiet

---

core/commands/mount_unix.go

The /ipfs and /ipns paths can be overridden by the options; this wasn't
in the help text for the options, but should be somewhere. Long help
seemed appropriate.
License: MIT

Added a note about the default values

---

.gitignore

Because these files are mussing up my clean history, and I think they change every time I run make install.
License: MIT

Add bin to gitignore

---

core/commands/object/object.go
core/commands/object/patch.go

Added Default logic to object object and patch

---

core/commands/object/diff.go
test/sharness/t0052-object-diff.sh

Also used `>` instead of `$`, per the guidelines.

Linted object diff help text

---

core/commands/diag.go

Added Default to `diag` cmd

---

core/corehttp/gateway_handler.go

Given that /ipfs/ resources never change, we can easily benefit from this new cache control extension.
Support for this is about to land in Firefox 49:
https://bugzilla.mozilla.org/show_bug.cgi?id=1267474
For more details, there is a good blogpost about this here:
https://bitsup.blogspot.de/2016/05/cache-control-immutable.html
This header is ignored by clients that don't support it.

Set Cache-Control immutable

---

core/commands/refs.go

Not sure about the switch statement. There may be a more elegant solution.
Part of #2484
License: MIT

Added Default logic to refs

---

core/commands/bootstrap.go

Added Default to `bootstrap` cmd

---

commands/command.go
commands/command_test.go
core/commands/root.go

This is the best place for inserting it that I found.
Test in #2648 should be modified to run `Root.ProcessHelp()`.
Resolves #2691.
License: MIT

Add logic for copying ShortDes to LongDesc if it is not present

---

core/commands/active.go
core/commands/dht.go

This required no change of the code. I also changed the message from `debug` to `extra`, which I think is closer to the truth. Part of #2484.
License: MIT

Added Default(false) to verbose for `active` and `dht` cmds

---

core/commands/publish.go

Added Default logic to publish

---

cmd/ipfs/daemon.go

Split from https://github.com/ipfs/go-ipfs/pull/2484.
License: MIT

Added Defaults to `ipfs daemon`

---

core/commands/ipns.go

Added Default logic per #2484, and also added the local option back in, because it exists in the code and should be shown as helptext, at least.
License: MIT

Added Default logic to `name` cmd, and local option

---

core/commands/stat.go

I've added: Synopsis, shortDescription, and longDescription for stats and stats bw.
I also added default(false) for poll and default("1s") for interval, and modified the logic to make it fit.
Part of #2484 and #2647.
License: MIT

Add helptext, default logic to `ipfs stats`

---

routing/dht/pb/message.go
routing/dht/pb/message_test.go

Should help prevent https://github.com/ipfs/go-ipfs/issues/2708
License: MIT

don't return nil multiaddrs from dht messages

---

blocks/blockstore/blockstore.go
blocks/blockstore/blockstore_test.go
blockservice/blockservice.go
blockservice/test/blocks_test.go
core/commands/object/patch.go
exchange/bitswap/bitswap.go
exchange/bitswap/bitswap_test.go
merkledag/merkledag.go
merkledag/merkledag_test.go
test/sharness/t0051-object.sh

246e5bf (jbenet, 2 minutes ago)
ipfs object patch add-link supports paths
previously, paths were not supported as link values. this would not work,
and now can:
ipfs object patch $root add-link foo /ipfs/$hash/foo/bar
4d09f29 (jbenet, 19 minutes ago)
add error checking for nil keys
Checks in:
- blockstore
- blockservice
- dagservice
- bitswap
Do not anger the pokemans #2715

Fix #2715 and patch add-link paths

---

Makefile
bin/dist_get

build: specify a dist.ipfs.io hash
Right now bin/dist_get trusts whatever DNS resolver is active.
This change enables it to verify what it downloads.
Verification itself remains TODO.
This will work best with a unixfs-hash tool which is TODO too.
It'd just do the equivalent of `ipfs add -n -r <dirOrFile>`.
License: MIT

build: specify a dist.ipfs.io hash

---

CHANGELOG.md
repo/config/version.go

Everybody PTAL -- did I overlook anything?

Add changelog for v0.4.2

---

test/sharness/t0170-dht.sh

tracked by https://github.com/ipfs/go-ipfs/issues/2620

marks dht query as known breakage for now

---

exchange/bitswap/message/message.go
exchange/bitswap/network/ipfs_impl.go

Filters out io.EOF errors in bitswaps stream handler and also reuses the delimited reader for repeated message receipts. 
fixes #2726 
License: MIT

fix receive loop error handling

---

core/commands/swarm.go

This is used like 'ipfs swarm peers -v'. It prints out the normal peers
information, but also the latency of each peer
License: MIT
Signed-off-by: Chris Sasarak <chris.sasarak@gmail.com>

Added a verbose option for swarm peers.

---

core/commands/files/files.go
test/sharness/t0250-files-api.sh

also add --hash and --size of hash and size only formats
This was on my QoL change list for a long time.
Resolves: https://github.com/ipfs/go-ipfs/issues/2461
License: MIT

Add --format option to mfs stat command

---

core/corehttp/metrics.go
core/corehttp/metrics_test.go

Gives us per-transport peers counts:
ipfs_p2p_peers_total{transport="/ip4/tcp"} 25
ipfs_p2p_peers_total{transport="/ip6/tcp"} 13
ipfs_p2p_peers_total{transport="/ip6/udp/utp"} 17
License: MIT

metrics: add transport label to p2p_peers_total

---

README.md

Recommend Go1.6.2
Note that Go1.5 is still supported
License: MIT

Remove note about Go1.6 not being supported

---

core/commands/active.go
core/commands/dht.go
core/commands/object/diff.go

Use one verbose flag description

---

Dockerfile
test/Dockerfile
test/sharness/t0300-docker-image.sh

The dockerfile assumes we're always on a branch, in which case it resolves the head ref in `.git/HEAD` via `.git/refs/`. Solarnet deploys are headless though, i.e. not on a branch but on a specific commit. In this case, Git puts that commit ref directly into `.git/HEAD`, so that the resolution step breaks.

docker: fix ipfs version --commit

---

commands/option.go
core/commands/publish.go

Allow to specify where to put default options in option desciption

---

core/commands/add.go
test/sharness/t0040-add-and-cat.sh

I didn't bother with Chunker, because I think that is a much wider PR. These should all be solid, though. Redid some of the logic to make it smoother.
Part of #2484.

Add Defaults to `ipfs add`

---

commands/http/handler.go
commands/response.go
core/commands/object/object.go
test/sharness/t0051-object.sh

It used to default to `application/json` but is now correctly set to
`application/protobuf`.
fixes #2469
License: MIT

Correctly set the content type for `object get --encoding=protobuf`

---

debug-guide.md

Remove conflict of names in the debugging guide

---

test/sharness/t0040-add-and-cat.sh

Add test for directly adding hidden file

---

cmd/ipfs/daemon.go
core/core.go
core/corehttp/gateway_handler.go
test/sharness/lib/test-lib.sh
test/sharness/t0040-add-and-cat.sh
test/sharness/t0061-daemon-opts.sh

Offline daemon mode

---

.dockerignore
Dockerfile
test/Dockerfile
test/sharness/t0300-docker-image.sh

`git rev-parse` simply needed `.git/packed-refs` and an empty `.git/objects/` directory.

docker: simplify git ref resolution, thanks @chriscool

---

test/sharness/t0030-mount.sh

This addresses t0030. t0040 still fails locally for the same reasons, but converting it is a big enough additional job that I wanted to get this PR in for now and tackel t0040 later.

Make t0030 use iptb for consistent test passing.

---

core/commands/commands.go
test/sharness/t0500-issues-and-regressions-offline.sh
test/sharness/t0501-issues-and-regressions-online.sh

It was caused by the cmds.Option struct being Interface not struct
The solution is to create struct and copy interesting data over.
Also removed the "ShowOptions" field from being sent via the HTTP API.
This introduces small change to the API.
I will yet add tests for this bug.
Resolves #2301
License: MIT

Fix commands --flags not showing flags via HTTP API

---

test/sharness/t0110-gateway.sh

Resolves https://github.com/ipfs/go-ipfs/issues/2194
License: MIT

Add check for HEAD response to be empty

---

core/commands/stat.go

stats: Aligned text to 78 ruler, fixed grammar error

---

cmd/ipfs/daemon.go
cmd/ipfs/init.go
core/commands/dht.go
core/commands/files/files.go
core/commands/get.go
core/commands/ls.go
core/commands/object/object.go
core/commands/object/patch.go
core/commands/pin.go
core/commands/stat.go
core/commands/swarm.go
core/commands/tar.go

This is just for the description, for now.
License: MIT

All commands: Align to under 78-ruler width

---

blocks/blocks.go
core/commands/add.go
core/coreunix/add.go
core/coreunix/add_test.go

Stable bits from Pull Request #2634.

Stable bits from Pull Request #2634

---

core/commands/version.go
test/sharness/t0010-basic-commands.sh
test/sharness/t0500-issues-and-regressions-offline.sh
test/sharness/t0600-issues-and-regressions-online.sh

Add version --all option

---

Dockerfile
Dockerfile.fast
test/3nodetest/Makefile
test/sharness/t0300-docker-image.sh

The two produce the same image, except one is optimized for image size, while the other is optimized for build time.

docker: make dockerfile differences more obvious

---

core/commands/repo.go
core/corerepo/stat.go
test/sharness/t0080-repo.sh

`ipfs repo version` command

---

routing/dht/providers.go
routing/dht/providers_test.go

This fixes a minor memory leak. When all providers for a given set would expire, the empty provider set object wouldnt get removed from the map it belongs to.
License: MIT

fix cleanup of empty provider sets

---

core/commands/add.go
core/coreunix/add.go
mfs/dir.go
mfs/file.go
test/sharness/t0250-files-api.sh
unixfs/format.go

rework add-mfs to not use caching

---

routing/dht/dht.go
routing/dht/dht_net.go
routing/dht/ext_test.go

DHT messages are pretty small, and the overhead of creating a new stream and sending multistream headers over it is fairly significant. If we can do it, reusing streams for multiple messages is a great way to save bandwidth.

reuse streams for dht messaging

---

Makefile
bin/check_go_path

Go's `GOPATH` environment variable can contain multiple paths, separated by a colon `:` similar to the `PATH` env var. In such cases Go uses the first path element to install any packages, however the remaining paths are still used to find dependencies. Because of this it's quite a common setup to have multiple paths listed in GOPATH (e.g. one for development and another for appengine, which has its special installer).
The current Makefile however erroneously assumes that `GOPATH` contains a single path element, and tries to locate go-ipfs within by appending a string to `GOPATH`, which is obviously cause an invalid path, and hence fail the `path_check` rule in the Makefile, even though the required condition is met.
~~This PR fixes it by moving path handling back into …

Makefile, bin: Support multiple GOPATH components

---

routing/dht/dht_net.go

If something weird happens during a dht request and the remote peer does not reply to our request, and *also* does not close the underlying connection, this has the possibility to hang.
That said, I think that the issue i noticed was caused by utp hanging up under the hood (the stack trace showed a few utp event loops running)
License: MIT

respect contexts while reading messages in dht

---

routing/dht/dht_test.go

Add some sanity tests for the misdial failure

---

core/commands/refs.go
test/sharness/t0600-issues-and-regressions-online.sh

Fix refs local marshalling

---

exchange/bitswap/decision/engine.go
exchange/bitswap/decision/ledger.go
exchange/bitswap/decision/peer_request_queue.go
exchange/bitswap/decision/peer_request_queue_test.go
exchange/bitswap/network/interface.go
exchange/bitswap/network/ipfs_impl.go
exchange/bitswap/testnet/virtual.go
exchange/bitswap/wantmanager.go
test/integration/addcat_test.go
test/integration/grandcentral_test.go
test/integration/three_legged_cat_test.go

Made a few changes to bitswap that significantly improve performance. By focusing on getting the cancel messages out to peers as fast as possible, and delaying sending blocks to peers we receive many cancels from we reduce the number of duplicate block receipts. I ran some tests on a network with 20ms latency between nodes (10ms per link) and have the results here: https://ipfs.io/ipfs/QmNyCqMQe1r3dQsAQEsncNqQGkF2YEyB5w6JRdNLRLDcox/smarter%20bitswap%20test%20info%20%2810ms%29.pdf
I can run more tests, but it takes a little while to do and these results are pretty good.
License: MIT

Make bitswap better

---

core/commands/ping.go

Part of https://github.com/ipfs/go-ipfs/issues/2803
License: MIT

Improve ping API a bit by returning failure in case of only failure

---

routing/dht/dht.go
routing/dht/routing.go
routing/kbucket/table.go

Was watching biham during a reproviding round. Its eating up some serious CPU time, this should help alleviate a small amount of that.
License: MIT

a few small changes to make the dht more efficient

---

Makefile

Due to SO_REUSEPORT it is possible for a localhost:0
address to repeat. This causes failure in DHT tests
where we spun up a lot of nodes inside test.
As for a birthday paradox it is enough to use 140
ports to get 20% chance for collision which was causing
failure in our case.
The fix is to disable REUSE_PORT routine for the
tests and leave it running for sharness tests where
not that many addresses are used at the same time.
Resolves https://github.com/ipfs/go-ipfs/issues/2745 https://github.com/ipfs/go-ipfs/issues/2809 https://github.com/ipfs/go-ipfs/issues/188

Fix DHT tests failing because of repeated addresses

---

repo/config/init.go
test/sharness/t0112-gateway-cors.sh

This will allow for weider use of local gateway from different sites.
For example: ipfs.pics could use JS to use either their global or user's local gateway.
I might work on piece of JS doing just that but I don't really like JS. :smile: 
License: MIT

Add CORS headers to Read Only Gateway Default config

---

cmd/ipfs/daemon.go
cmd/ipfs/ulimit_unix.go
commands/files/file_test.go
merkledag/merkledag_test.go
mfs/ops.go
mfs/system.go
routing/dht/dht_net.go
routing/dht/dht_test.go
unixfs/io/dagreader.go

Remove errors pointed out by govet

---

cmd/ipfs/init.go
commands/cli/parse.go
test/bin/.gitignore
test/bin/time-out
test/sharness/t0022-init-default.sh
test/sharness/t0500-issues-and-regressions-offline.sh

This PR changes how stdin is used while parsing arguments. Current behaviour is that stdin is used for non-required and variadic arguments which causes confusion.
After the change the stdin is used only in case of missing required argument or if explicitly mentioned by the user with `-`.
Question: Should we print on stderr when ipfs command is listening for stdin to clear up possible confusing hang even more?
Aims to resolve https://github.com/ipfs/go-ipfs/issues/2748
License: MIT

Change logic of stdin input to be last and only if required

---

routing/dht/dht_net.go

this should address #2835. I was able to reproduce the issue last night without this fix, but havent been able to reproduce the issue this morning (with or without the fix)
License: MIT

pass reference to reader instead of using the one on the object

---

blocks/blockstore/blockstore_test.go

Why is it failing:
process is started, cancel() is called,
between we satart listening to the channels
in select statemnet there is race of three things
that can happent:
1. Task can complete
2. Task can start closing <- expected
3. Task already closed
This race causes failures of the test.
It is basing heavily on race of conditions where
the task not closing, nor the task is completed
before channels are being listened.
It is quite impossible to resolve without
adding bunch of timings in there, which we
want to avoid, as there is no atomic
"send message on channel and select" in Golang
License: MIT

Remove failing blockstore with context test

---

blockservice/blockservice.go
cmd/ipfs/init.go
cmd/ipfs/main.go
commands/http/handler.go
core/commands/publish.go
diagnostics/diag.go
fuse/ipns/ipns_unix.go
fuse/readonly/readonly_unix.go
namesys/publisher.go
path/resolver.go
routing/dht/dht.go
routing/dht/dht_net.go
routing/dht/handlers.go
routing/dht/records.go
routing/dht/routing.go

According to golang standards, these should not be capitalized nor having a trailing period, AFAIK.
License: MIT

Decapitalized log.Debug messages

---

Makefile
bin/check_go_path

This reverts commit ff75bc0318579fa743a35d316c61d2f8c4ab92ce,
which broke building on windows. See ipfs/go-ipfs#2833.
cc @karalabe @djdv @jefft0

Revert "Makefile, bin: Support multiple GOPATH components"

---

core/commands/sysdiag.go
test/sharness/t0151-sysdiag.sh

As requested by @lgierth.
@RichardLitt this changes API.

Add way to check if node is online or offline

---

routing/dht/dht.go
routing/dht/dht_net.go

Very occasionally the remote side will stop sending on a stream, not close it, and not close the underlying tcp connection. This causes annoying hangs
License: MIT

implement some simple dht request read timeouts

---

thirdparty/delay/delay.go

Hey,
I saw the todo for random delays and thought I'd give it a go.
License: MIT
Signed-off-by: Or rikonor@gmail.com

Added variable latency delay, normal and uniform based

---

cmd/ipfs/daemon.go
cmd/ipfswatch/main.go
core/corehttp/gateway.go
core/corehttp/gateway_handler.go
core/corehttp/gateway_test.go
misc/completion/ipfs-completion.bash
test/sharness/t0061-daemon-opts.sh
test/sharness/t0110-gateway.sh
test/supernode_client/main.go

This patch is in preparation for the gateway's extraction.
It's interesting to trace technical debt back to its
origin, understanding the circumstances in which it
was introduced and built up, and then cutting it back
at exactly the right places.
- Clean up the gateway's surface
The option builder GatewayOption() now takes only
arguments which are relevant for HTTP handler muxing,
i.e. the paths where the gateway should be mounted.
All other configuration happens through the
GatewayConfig object.
- Remove BlockList
I know why this was introduced in the first place,
but it never ended up fulfilling that purpose.
Somehow it was only ever used by the API server,
not the gateway, which really doesn't make sense.
It was also never wired up with CLI nor fs-repo.
Eventually @krl started punching …

gateway: clean up its surface, and remove BlockList

---

core/commands/swarm.go
test/sharness/t0141-addfilter.sh

Swarm filters save config (fix #2878)

---

cmd/ipfs/daemon.go
cmd/ipfs/ulimit_unix.go

This changes the behaviour of the ipfs daemon to raise the file descriptor ulimit to 1024 if it is below 1024 when the daemon starts.
On linux, this will have no effect.
On OSX, this will raise the file descriptor limit every time the daemon is started (as the default there is 256).
License: MIT

raise file descriptor limit to 1024 by default

---

core/commands/pin.go
core/corerepo/gc.go
core/coreunix/add_test.go
merkledag/merkledag.go
merkledag/merkledag_test.go
pin/gc/gc.go
test/sharness/t0252-files-gc.sh

Add Files API root as best-effort pin

---

docs/github-issue-guide.md

See https://github.com/ipfs/go-ipfs/pull/2786
License: MIT

Added a How To File GitHub Issues guide

---

merkledag/merkledag.go

return a better error if the ref is not an object

---

test/sharness/lib/test-lib.sh
test/sharness/t0060-daemon.sh

add a test for auto-raising ulimit

---

commands/files/serialfile.go
core/commands/add.go

It turns out there was an actual bug in the computation of the add size. It was using the just filename, not the full path. So anytime you would try to add a path (as opposed to a single file or directory) it would fail out because it couldnt find what you were talking about.
License: MIT

fix progress bar in add

---

.travis.yml

There are so many of them that they are just annoyting
and for some reason there isn't feature of telling
Travis not to send notifications to me.
License: MIT

Disable Travis Email notifications

---

Dockerfile
Dockerfile.fast

docker: update to go 1.6.2 and alpine 3.4

---

blocks/blockstore/blockstore.go
blocks/blockstore/blockstore_test.go
core/builder.go
repo/config/datastore.go
repo/config/init.go
test/sharness/t0084-repo-read-rehash.sh

Resolves #2256
Enabled using `Datastore.HashOnRead: true` in IPFS config.

Add option for datastore read rehashing

---

commands/argument.go
commands/cli/parse.go
commands/cli/parse_test.go
core/commands/bitswap.go
core/commands/block.go
core/commands/bootstrap.go
core/commands/cat.go
core/commands/dht.go
core/commands/dns.go
core/commands/get.go
core/commands/id.go
core/commands/ipns.go
core/commands/ls.go
core/commands/object/object.go
core/commands/pin.go
core/commands/ping.go
core/commands/publish.go
core/commands/refs.go
core/commands/resolve.go
core/commands/swarm.go
core/commands/tar.go
core/commands/unixfs/ls.go
test/sharness/t0040-add-and-cat.sh

With verbose flag:
- remove EnableStdin() flags on all StringArg,
- remove all unneeded parsing code for StringArg, and print an
informative message if `ipfs` begins reading from a CharDevice,
- remove broken go tests for EnableStdin cli parsing, and add some
trivial test cases for reading FileArg from stdin,
- add a panic to prevent EnableStdin from being set on
StringArg in the future.
Resolves: #2877, #2870, #2868
License: MIT
Signed-off-by: Thomas Gardner <tmg@fastmail.com>

commands: remove EnableStdin support for StringArg [v2]

---

commands/cli/helptext.go
commands/cli/helptext_test.go
commands/command.go
commands/option.go
core/commands/active.go
core/commands/files/files.go
core/commands/mount_unix.go
core/commands/object/patch.go
core/commands/ping.go
core/commands/root.go
core/commands/stat.go
core/commands/unixfs/ls.go
core/commands/unixfs/unixfs.go
test/sharness/t0010-basic-commands.sh
test/sharness/t0040-add-and-cat.sh

Generates synopsis automagically
Few examples:
`ipfs add [--recursive | -r] [--quiet | -q] [--silent] [--[no-]progress] [--trickle | -t] [--only-hash | -n] [--wrap-with-directory | -w] [--hidden | -H] [--chunker=<chunker> | -s] [--[no-]pin] [--] <path>...`
` ipfs pin ls [--type=<type> | -t] [--quiet | -q] [--] [<ipfs-path>...]`
License: MIT

Add synopsis autogenerator

---

core/commands/ls.go

This makes ls return even if files referenced in the directory are not available.
It also introduces a `resolve-type` flag that forces the resolution of type.
Resolves https://github.com/ipfs/go-ipfs/issues/2820
License: MIT

Add flag to ls to not resolve type of subnodes

---

commands/cli/parse.go
test/sharness/t0044-add-symlink.sh

Resolves https://github.com/ipfs/go-ipfs/issues/2839
License: MIT

Resolve symlink if it is directly referenced in cli

---

Dockerfile
Dockerfile.fast

There's only ever one version of a given package
per Alpine release, so GO_VERSION is superfluous
and only breaks the build if the go packages is updated.
License: MIT

docker: remove go version constraint

---

commands/cli/parse_test.go

Resolves #2925
Docker still fails.
License: MIT

Resolve symlinks of testfiles

---

test/sharness/t0080-repo.sh

test: Run t0080-repo test offline

---

test/Makefile
test/sharness/t0300-docker-image.sh

The other commit makes sharness tests work with my symlinked-into-gopath setup.

docker: take -dev version suffix into account

---

routing/dht/routing.go
routing/record/validation.go
routing/record/validation_test.go

This fixes a couple bugs that made ipns not work well in cases where the peer ID had a '/' in it. 
It also fixes a bug where we would never succeed in updating the locally stored entry
License: MIT

fix handling of dht records and local fixups

---

core/commands/repo.go
test/sharness/t0084-repo-read-rehash.sh

add repo verify command

---

cmd/ipfs/daemon.go
test/Makefile
test/sharness/t0110-gateway.sh
test/sharness/t0400-api-security.sh

Resurrect --unrestricted-api

---

blocks/blockstore/blockstore.go

In order for AllKeysChan to really benefit from the larger buffer size for key only queries in the datastore it should increase it own channel buffer to the same size as the key only queries channel buffer.

Increase channel buffer size in blockstore.AllKeysChan().

---

blocks/blockstore/bloom_cache.go
blocks/blockstore/bloom_cache_test.go
blocks/blockstore/caching.go
cmd/ipfs/daemon.go
core/builder.go
exchange/bitswap/testutils.go

I will do nice and full refactor of the Online vs Ephemeral modes.
This PR includes parts of https://github.com/ipfs/go-ipfs/pull/2942 which cleanup passing of the context and options to the caches.
The important change is https://github.com/ipfs/go-ipfs/commit/697a3457041c42aba1ab61b5fd404320ea9585eb

core: do not run bloom in case of ephemeral node

---

core/commands/config.go
repo/config/identity.go
test/sharness/t0021-config.sh

**cc** @lgierth @whyrusleeping @jbenet

core/commands/config: do not show private key on local network

---

commands/argument.go
commands/cli/parse.go
commands/cli/parse_test.go
commands/command.go
commands/http/client.go
commands/reqlog.go
commands/request.go
core/commands/bitswap.go
core/commands/block.go
core/commands/bootstrap.go
core/commands/cat.go
core/commands/dht.go
core/commands/dns.go
core/commands/get.go
core/commands/id.go
core/commands/ls.go
core/commands/object/object.go
core/commands/pin.go
core/commands/ping.go
core/commands/publish.go
core/commands/refs.go
core/commands/resolve.go
core/commands/swarm.go
core/commands/tar.go
core/commands/unixfs/ls.go
test/sharness/t0022-init-default.sh
test/sharness/t0040-add-and-cat.sh
test/sharness/t0085-pins.sh
test/sharness/t0120-bootstrap.sh

rework stdin handling

---

core/builder.go
repo/config/datastore.go
repo/config/init.go

config: add config option for bloom filter

---

Makefile
bin/check_go_path

This request brings back in a reverted commit with a fix on top for platform delimiters.
Before this gets merged though I would like people to test it on various systems, it works for me in msys2 where it did not originally, but I only use a single GOPATH. If anyone could try building with this and report on the results I'd appreciate it.
@ChristianKniep 
Could you run this and see if you have any build issues? (In relation to https://github.com/ipfs/go-ipfs/issues/2947)
@jefft0
Could you run this inside of Cygwin? I'm not sure if Cygwin will get picked up as Windows or not with this condition.

Build: Fix Makefile on Windows

---

core/commands/files/files.go
mfs/ops.go
test/sharness/t0250-files-api.sh

There was a bug where running `ipfs files cp /something /adirectory/` would make a file with a zero length name inside `/adirectory`
License: MIT

mfs: fix copying into directory with no given filename

---

docs/config.md

cc @RichardLitt @lgierth @Kubuxu 
License: MIT

document the config options

---

Makefile

uses a newer version of gx that is much faster on the install process, should make CI run faster and produce fewer logs
License: MIT

update gx version

---

core/commands/object/object.go

This resolves #2938
License: MIT

Increase 512kbytes object put limit to 2mbytes

---

cmd/ipfs/daemon.go
core/commands/repo.go
core/commands/version.go
core/corerepo/stat.go
repo/fsrepo/fsrepo.go
repo/fsrepo/migrations/mfsr.go
repo/fsrepo/migrations/migrations.go
repo/fsrepo/migrations/unpack.go
repo/mock.go
test/sharness/t0066-migration.sh

This will prompt the user when a migration is needed to let ipfs try to automatically download and run the migrations.
If a version of the migrations tool is installed that is high enough, ipfs will use it instead of downloading its own.
Currently, the download its own function will fail as there is not a build of fs-repo-migrations with ipfs-3-to-4 up on the distributions page yet.
Resolves: https://github.com/ipfs/go-ipfs/issues/2907
License: MIT

Automatically download and run migrations if needed

---

core/commands/refs.go
test/sharness/t0500-issues-and-regressions-offline.sh

also change it to use format instead of separate variable
Resolves #3001 
License: MIT

commands: fix refs 'edges' option work

---

core/commands/add.go
test/sharness/t0040-add-and-cat.sh

Should fix issues seen in https://github.com/ipfs/js-ipfs-api/issues/323
License: MIT

default add progress to false, unless using CLI

---

core/coreunix/add.go
mfs/dir.go

This should prevent memory bloat during the finalize call of add
License: MIT

don't cache entire mfs tree on add finalize

---

blocks/blockstore/arc_cache.go
blocks/blockstore/arc_cache_test.go
blocks/blockstore/bloom_cache.go
blocks/blockstore/bloom_cache_test.go
blocks/blockstore/caching.go

it removes race condition that would happen during various calls
If tests are ok, it is good for review.
License: MIT

blockstore: extract ARC cache from Bloom cache

---

commands/cli/parse.go

cli: do ToSlash after EvalSymlinks to remove platform specific slashes

---

commands/cli/parse.go
test/sharness/t0040-add-and-cat.sh

Only print "Reading from /dev/stdin" message when we actually read from
stdin (and not in other cases such as ipfs add --help).
closes #3002 
License: MIT

commands/cli: fix reading from stdin message

---

core/commands/object/object.go

-enc is spelled with two dashes, not one

---

exchange/bitswap/workers.go

race detector picked up a minor race condition, Since loop iteration reuses the same local variable, its not safe to take its address and use it concurrently. The fix is to rebind the variable into a controlled scope (creating a new variable) and taking the address of that to pass outwards.
License: MIT

bitswap: fix a minor data race

---

cmd/ipfs/main.go
test/sharness/t0010-basic-commands.sh

Addresses Issue #2976. This is a pretty simple method since it looks like the main ipfs command pretty much just parses and launches the others. If you think it is likely that we'll have more 'alias' type things that people will want on ipfs (not its subcommands) in the future, I can probably write something (like a dict) mapping aliases to real commands.

Alias 'ipfs --version' to 'ipfs version'

---

README.md

- removed instructions to use boot2docker from README, which [has been deprecated](https://github.com/boot2docker/boot2docker-cli#deprecated) in favour of [docker-machine](https://docs.docker.com/machine/migrate-to-machine/).
- in most cases, [Docker for Mac/Windows](https://blog.docker.com/2016/07/docker-for-mac-and-windows-production-ready/) (now out of beta) will do the job => some [Mac users will still need docker-machine](https://docs.docker.com/docker-for-mac/#/what-to-know-before-you-install).

boot2docker-cli is deprecated, removed from README

---

commands/request.go
test/sharness/t0050-block.sh

commands: fix panic when stdin is empty for string args

---

CHANGELOG.md
package.json
repo/config/version.go

This should be the final release candidate. Unless something horribly wrong is found, this is it.
We're also waiting on go1.7 to be officially released so that the binaries we release will work on macOS Sierra.

Feat/changelog 0.4.3 rc3

---

test/ipfs-test-lib.sh

test_fsh() should quote its arguments before passing them
to `eval` otherwise there are problems when the arguments
contain spaces.
For example when running the following program:
```
#!/bin/sh
. ./ipfs-test-lib.sh
die () {
printf >&2 "%s\n" "$@"
exit 1
}
DIR1="test dir 1"
DIR2="test dir 2"
mkdir "$DIR1" "$DIR2" || die "Could not mkdir '$DIR1' '$DIR2'"
echo "in dir 1" >"$DIR1/file1" || die "Could not write into '$DIR1/file1'"
echo "in dir 2" >"$DIR2/file2" || die "Could not write into '$DIR2/file2'"
if test_cmp "$DIR1/file1" "$DIR2/file2"
then
echo "test_cmp succeeded!"
else
echo "test_cmp failed!"
fi
rm -rf "$DIR1" "$DIR2" || die "Could not rm -rf '$DIR1' '$DIR2'"
```
we get:
```
> diff -u test dir 1/file1 test dir 2/file2
diff: extra operand '1/file1'
diff: Try 'diff --help' for more …
```

ipfs-test-lib: fix test_fsh arg quoting

---

core/commands/dns.go

Closes https://github.com/ipfs/faq/issues/161

Update dns help with a correct domain name

---

core/commands/bitswap.go
core/commands/block.go
core/commands/bootstrap.go
core/commands/config.go
core/commands/diag.go
core/commands/dns.go
core/commands/files/files.go
core/commands/ipns.go
core/commands/mount_nofuse.go
core/commands/mount_unix.go
core/commands/name.go
core/commands/object/diff.go
core/commands/object/object.go
core/commands/pin.go
core/commands/refs.go
core/commands/repo.go
core/commands/swarm.go
core/commands/sysdiag.go
core/commands/tar.go
core/commands/tour.go
core/commands/version.go

A much smaller PR than #3018 . See discussion in https://github.com/ipfs/community/pull/150

Make all Taglines use imperative mood

---

core/commands/bitswap.go
exchange/bitswap/bitswap.go
exchange/bitswap/decision/engine.go
exchange/bitswap/decision/ledger.go

bitswap: add `ledger` subcommand

---

blocks/set/set_test.go

test: 100% coverage on blocks/set

---

core/commands/files/files.go
core/commands/ls.go
core/commands/unixfs/ls.go

Work on #3057 and #3056.
This pull request is as much about clarifying the different listing command's functionality as a proposal to document them a little better. Hence, an invitation for comments. :)
Also refer to https://github.com/ipfs/go-ipfs/issues/3081#issuecomment-239610857 and https://github.com/ipfs/go-ipfs/issues/3057#issuecomment-239610026.

Document listing commands better

---

bin/dist_get

@MrSparc I fixed it for you, can you signoff here in a comment.

bin: dist_get script: prevents get_go_vars() returns same values twice

---

Makefile
test/Makefile
test/sharness/Makefile

This can wait for after release but it shouldn't affect the release in any form either.
We might want to limit number of threads on the sharness or make output sequential of sharness because now they run in parallel.

Cleanup makefiles

---

README.md

should address #3049 
License: MIT

readme: add notes on building for uncommon systems

---

unixfs/io/dagreader.go
unixfs/mod/dagmodifier.go
unixfs/mod/dagmodifier_test.go

Second commit includes the fix, first is cosmetic change

unixfs: fix relative seek not expanding file properly 

---

blocks/blockstore/arc_cache_test.go
blocks/blockstore/blockstore_test.go
blocks/blockstore/bloom_cache_test.go
blocks/blockstore/caching_test.go

Coverage report available at: https://ipfs.io/ipfs/QmTuMtwGCfHrbYyZdQ1RaGNwS2MGsmAkjA8AaB69N7Ya1g/coverage.html#file0
Part of #3053
License: MIT

test: 81% coverage on blockstore

---

blocks/blockstore/arc_cache.go
core/commands/block.go
pin/pin.go
test/sharness/t0050-block.sh

This is a basic implementation for #2914.
It accepts multiple blocks to remove, however that does not provide any performance benifit just yet as it calls `pins.IsPinned()` for each block, which traverses every recursive pin to check for indirect pins.  This operation costs is O(P*N) where P is the number of pinned blocks and N is the number of blocks to be removed.  With a little effort this can be brought down to O(P) by checking for multiple pins at once.
Since the pin check is expensive it provides an option to ignore pins.  Removing a pinned block will break any command that checks for pins.  Right now if this happens recovering from the situation is very difficult.  At very least a command should be provided to list any broken or missing pins.  An additional optional command can be …

Add "ipfs block rm" command.

---

blocks/blocks.go
blocks/blocks_test.go

test: 82% coverage on blocks

---

contribute.md

I'd like to discuss standardizing our branch naming strategy. I've outlined what I aim for when creating branches, but if anyone else has thoughts on this please chip in, i'd love to hear pros and cons.
What i'm aiming for is,
A branch name should
- tell you immediately what type of change it is making
- give you a rough idea of what part of the codebase is being changed
- strive to be concise, screen real-estate is valuable
License: MIT

docs: add branch naming conventions

---

core/commands/cat.go

This functionality currently isnt very useful or reliable. Disabling it temporarily until we can refine the underlying code.
License: MIT

ipfs/cat: disable auto-gc check

---

core/core.go
docs/config.md
repo/config/config.go
repo/config/init.go
repo/config/reprovider.go

reprovider: add config option to set reprovide interval

---

exchange/bitswap/network/ipfs_impl.go
exchange/reprovide/reprovide.go
namesys/namesys.go
namesys/publisher.go
namesys/republisher/repub.go
namesys/routing.go
routing/routing.go

I've started to work on separating the content routing layer and the peer routing layer. The third bit that we glom into our current routing interface deals with direct values, i think thats what @diasdavid was starting to call the record store, but i'm not sure its the same scope. Definitely want some feedback here.
cc @jbenet @diasdavid 
License: MIT

routing: rework interfaces to make separation easier

---

core/builder.go
merkledag/merkledag_test.go
pin/pin.go
pin/pin_test.go

pin: use separate dagservice for storing pinsets

---

fuse/node/mount_darwin.go

fuse: make osxfuse check config check more permissive

---

core/builder.go
exchange/bitswap/bitswap.go
exchange/bitswap/bitswap_test.go
package.json

This is still a bit of a WIP, i'm not sure if we should inject the retry datastore in core/builder, or in the blockstore constructor.
License: MIT

datastore: blockstore should retry when it encounters temp errors

---

merkledag/merkledag_test.go
merkledag/node_test.go

improve test coverage on merkledag package

---

docs/AUTHORS

Updated authors doc

---

core/commands/dht.go
routing/dht/routing.go

cmds: implement ipfs dht provide command

---

blockservice/blockservice.go
exchange/bitswap/workers.go

Lots of operations will store the same block multiple times in rapid succession, we have optimizations to avoid putting those to disk multiple times, but nothing to avoid providing them multiple times.
This is *a* solution. The other option is to use the same logic as the blockstore (if we have the block already, noop) for providing. The issue with that is that you would no longer be able to re-add a file as a way to re-provide it.
cc @jbenet @Kubuxu for feedback
License: MIT

bitswap: don't re-provide blocks we've provided very recently

---

.travis.yml
Dockerfile
Dockerfile.fast
Makefile
README.md
circle.yml
package.json

CI is gonna be fun with this one...
License: MIT

bump go requirement to 1.7

---

commands/option.go
core/commands/publish.go

This way if we use <default> in description (we use thigns like <hash>
already), it won't conflict and modify the description in unwanted way.
Created because of: https://github.com/ipfs/go-ipfs/pull/2744#issuecomment-242655384
License: MIT

commands: replace <default> keyword with <<default>>

---

mfs/mfs_test.go
package.json

I want to continue doing things like this as we find deps are no longer needed. A smaller dependency tree is a happier one 
License: MIT

remove randbo dep, its no longer needed

---

commands/cli/parse.go

Also remove '\n' from msgStdinInfo as we use Fprintln.
This PR branches of v0.4.3-rc3 and merges to version/0.4.3-rc4 which is short lived branch.
As a guide, please keep changes in this branch as minimal as possible to reduce merge conflicts.
License: MIT

cli: Fix stdin help text being show multiple times

---

test/sharness/t0112-gateway-cors.sh

test: do explicit check of CORS headers

---

test/sharness/t0040-add-and-cat.sh

test: revert few stdin tests that were removed

---

cmd/ipfs/daemon.go
repo/fsrepo/migrations/migrations.go
test/sharness/t0066-migration.sh

No:
```
$ cmd/ipfs/ipfs daemon
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] n
Not running migrations of fs-repo now.
Please get fs-repo-migrations from https://dist.ipfs.io
Error: fs-repo requires migration
```
Programmatic No:
```
$ cmd/ipfs/ipfs daemon --migrate=false
Found outdated fs-repo, migrations need to be run.
Not running migrations of fs-repo now.
Please get fs-repo-migrations from https://dist.ipfs.io
Error: fs-repo requires migration
```
Yes with 404: (e.g. when we haven't pushed a migration to dist.ipfs.io yet)
```
$ cmd/ipfs/ipfs daemon --migrate=true
Found outdated fs-repo, migrations need to be run.
=> Looking for suitable fs-repo-migrations binary.
=> None found, …
```

fsrepo: improve migrations copy

---

commands/cli/parse.go
test/sharness/t0040-add-and-cat.sh
test/sharness/t0044-add-symlink.sh

Revert the original fix for #2839 and instead fix the original issue so that adding the current directory works as expected without changing the semantics of how symbolic links are handled.

Directly Fix #2839

---

.travis.yml
Dockerfile
Dockerfile.fast
Makefile
README.md
circle.yml
package.json

It replays: https://github.com/ipfs/go-ipfs/pull/3111 on version/0.4.3-rc4

Update release candidate branch to Go 1.7

---

ISSUE_TEMPLATE.md
docs/github-issue-guide.md

See https://github.com/ipfs/go-ipfs/pull/2883#issuecomment-227528997. Will need to change current issues.
License: MIT

Reverse label numbers

---

test/sharness/t0050-block.sh

was integrating CIDv0 into the codebase and flushed out this bug
License: MIT

sharness: fix typo in hash in t0050

---

test/sharness/t0252-files-gc.sh

Enhance tests for files API root best-effort pin.

---

cmd/ipfs/ulimit_unix.go
package.json
test/Makefile
test/sharness/Makefile
test/sharness/t0060-daemon.sh

Better tests for this, at least on linux we can check it externally. I don't know of a good way to do this on OSX

fdlimit: improve fdlimit autoraising tests

---

exchange/bitswap/workers.go

While messing around I noticed the lack of a space in my log.
A bitswap debug message was logged like this:
```
21:35:05.951 DEBUG    bitswap: 15keys in bitswap wantlist workers.go:172
```
Notice the "15keys" concatenation error. This PR fixes that.
License: MIT
Signed-off-by: Mateusz Naściszewski <matin1111@wp.pl>

Fix minor typo in bitswap debug logging

---

exchange/bitswap/bitswap.go
exchange/bitswap/bitswap_test.go
exchange/bitswap/decision/bench_test.go
exchange/bitswap/decision/engine.go
exchange/bitswap/decision/ledger.go
exchange/bitswap/decision/peer_request_queue.go
exchange/bitswap/decision/peer_request_queue_test.go
exchange/bitswap/message/message.go
exchange/bitswap/wantlist/wantlist.go
exchange/bitswap/wantmanager.go
exchange/bitswap/workers.go
test/sharness/t0220-bitswap.sh

This PR has been a long time coming. A recent race condition fix has lead to us *actually* rebroadcasting our wantlist every ten seconds as we claim to do (instead of just pretending to). As a result, the gateways have started catching on fire. The reason for this is that since we never remove elements from the wantlist, we now rebroadcast thousands of wantlist entries every ten seconds. Thats kinda bad.
The solution, is to reference count wantlist entries and remove them when no active requests are referencing them any longer.
A few notable sub-fixes happened to make this work:
- wantlist Entries are now stored as pointers. The reference count wasnt being changed before
- GetBlocks now tracks which blocks it has successfully fetch so it can cancel the rest as needed.
- Remove contexts …

Remove entries from wantlists when their related requests are cancelled

---

exchange/bitswap/workers.go

This has been an issue for a long time, but for some reason the changes to making providers more efficient has made this a much larger problem.
I'm not 100% sure this will solve the excess cpu usage problem we're seeing on the gateways, but its definitely fixing a bug.
License: MIT

bitswap: Don't clear 'active' until Connect calls are finished

---

core/commands/config.go
repo/config/identity.go
repo/fsrepo/fsrepo.go
test/sharness/t0021-config.sh

also add test for lower case config replace.

cmd: harden the security of privkey field in config show

---

blocks/blockstore/caching.go
docs/config.md

blockstore: change unit of bloom filter to byte from bits

---

blocks/blockstore/arc_cache.go
blocks/blockstore/arc_cache_test.go
blocks/blockstore/bloom_cache.go
blocks/blockstore/bloom_cache_test.go

Thanks @whyrusleeping for noticing it.
Removed PutMany logic in bloom cache as it can't help with anything.
Fixed ARC cache to use filtered results instead of all blocks.
Also add test case for it.

 	blockstore: fix PutMany with cache logic

---

bin/check_go_version
bin/check_gx_program
bin/check_version

License: MIT
Signed-off-by: Mateusz Naściszewski <matin1111@wp.pl>

Fixes #3133: Properly handle release candidates in version comparison

---

exchange/bitswap/workers.go

ref: https://github.com/ipfs/go-ipfs/pull/3182#issuecomment-244826036
This solution is strictly better than that of the current release. The current 'intended' behaviour is simply way too spammy, We can develop more intelligent solutions as we move forward.
License: MIT

bitswap: search for wantlist providers a little less often

---

blocks/blockstore/blockstore.go
blocks/blockstore/blockstore_test.go
core/builder.go
core/commands/repo.go

blockstore: rename RuntimeHashing to HashOnRead

---

diagnostics/diag.go
exchange/bitswap/network/interface.go
exchange/bitswap/network/ipfs_impl.go
routing/dht/dht.go

Default to using the correct protocol strings for bitswap dht and diagnostics
closes #3044 
cc @diasdavid 
License: MIT

use correct protocol names for ipfs services

---

routing/dht/dht_test.go
routing/dht/handlers.go
routing/dht/records.go

Last thing to go on the rc4 release, i promise.
License: MIT

dht: protect against a panic in case record on pbmessage is nil

---

CHANGELOG.md
docs/releases.md
package.json
repo/config/version.go

Please review in the rendered version to spot markup errors

changelog: add notes for 0.4.3-rc4

---

cmd/ipfs/dist/install.sh

Hello,
I made little changes for the installation script `install.sh`. The enhancements are:
* I use a for loop for the binpaths (following the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle)
* An error message was added in the end to inform the user when the script couldn't be installed.

Refactoring install.sh

---

routing/dht/dht_net.go

dht: add missing protocol ID to newStream call

---

cmd/ipfs/dist/README.md

A little change to `README.md` since most users will need `sudo` to run the installation script sucessfully.

README.md: Add sudo to install commands.

---

cmd/ipfs/daemon.go
cmd/ipfswatch/main.go
core/corehttp/gateway.go
core/corehttp/gateway_test.go
test/sharness/t0111-gateway-writeable.sh
test/supernode_client/main.go

Broke it in #2874... my unproven assumption apparantly was that `cfg.Gateway.Writable = true` would somehow magically make it into other instances of the config retrieved via `Repo.Config()`...
We're not overloading the repo config with this anymore now. We also have a test for `--writable` now.

gateway: fix --writable flag :|

---

ISSUE_TEMPLATE.md
contribute.md

I think this language makes it a bit more clear how we use issues in this repository.
License: MIT

Edit issue reporting guides

---

blocks/blockstore/arc_cache.go
blocks/blockstore/arc_cache_test.go
blocks/blockstore/bloom_cache.go
blocks/blockstore/caching.go
cmd/ipfs/daemon.go
core/builder.go
core/corehttp/metrics.go
package.json

It makes introducing metrics much easier.
The interface itself doesn't depend on prometheus, that means it is very light and without it (or other implementation) acts as a general noop.
Importing go-metrics-prometheus injects prometheus implementation.
Usage:
There are three most improtant functions in go-metrics-interface:
* `metrics.New(name, helptext)` - creates new metrics with given name and helptext
* `metrics.NewCtx(ctx, name, helptext)` - creates new metrics with given name and helptext in scope defined in the context
* `metric.CtxSubScope(ctx, name)` - returns context that is a subscope of scope defined in current ctx
As you can see it uses `context.Value` for passing the scope name of the metrics. In my opinion it is one of the better solutions as context is already required in …

metrics: introduce go-metrics-interface

---

package.json

Update goprocess dependency to 1.0.0 to avoid a version mismatch with what
go-datastore uses.
Part of #2634

Update goprocess dependency to 1.0.0

---

Makefile

License: MIT
Signed-off-by: Vasil Dimov <vd@FreeBSD.org>

use $(MAKE) instead of 'make' in Makefiles (follow-up to f3dc11c)

---

bin/dist_get

On FreeBSD the default one (if no -f is specified) is /dev/sa0,
not stdin.
License: MIT
Signed-off-by: Vasil Dimov <vd@FreeBSD.org>

Explicitly specify the input file to tar with "-f -"

---

exchange/bitswap/bitswap.go
exchange/bitswap/workers.go

should fix #3262 #3199 and #3246 
License: MIT

only pass keys down newBlocks chan in bitswap

---

cmd/ipfs/daemon.go
core/core.go
package.json
test/sharness/t0131-multinode-client-routing.sh

This allows you to start up an ipfs daemon with `--routing=dhtclient`. In that mode, your dht will not accept incoming requests, but will still be able to query the dht for providers and peer routing information.
License: MIT

add experimental dht client mode flag

---

commands/http/client.go

Better fix than #3230 to make sure errors from addAllAndPin make it to
the client.
License: MIT

Don't drop error in readStreamedJson.

---

contribute.md

Seems this doc now lives in the community repo.

contribute.md: fix broken link to 'ammending commits' doc.

---

core/commands/dht.go
core/commands/pin.go
core/core.go
core/corerepo/gc.go
core/coreunix/add_test.go
exchange/bitswap/bitswap.go
exchange/interface.go
exchange/offline/offline.go
merkledag/merkledag.go
merkledag/merkledag_test.go
pin/gc/gc.go
pin/pin.go
pin/pin_test.go

This method will use the (also new) LinkService if it is available to
retrieving just the links for a MerkleDAG without necessary having to
retrieve the underlying block.
For now the main benefit is that the pinner will not break when a block
becomes invalid due to a change in the backing file.  This is possible
because the metadata for a block (that includes the Links) is stored
separately and thus always available even if the backing file changes.
For context (and test cases) please see the original commits: 5a732268eecddd19034325e631742f3e8d88aebf 8b396fdf2e4cd7be40f982d6367867c117d5bc4e

Add DAGService.GetLinks() method and use it in the GC and elsewhere.

---

pin/set.go
pin/set_test.go

Sometime after having ~5000 items in a pinset, we start to get some hash collisions when mapping the 32bit int space over an 8 bit integer space. The easy enough fix is to modulo the hash output down into our final key space before we even get to that point.
Longer term, i want to see us using the HAMT code for this purpose (though its not yet ready).
License: MIT

fix bug in pinsets and add a stress test for the scenario

---

blocks/blocksutil/block_generator.go
blockservice/blockservice.go
blockservice/blockservice_test.go
blockservice/test/mock.go
cmd/ipfs/init.go
core/core.go
core/core_test.go
core/corerepo/stat.go
core/coreunix/cat.go
fuse/ipns/link_unix.go
fuse/node/mount_test.go
importer/helpers/helpers.go
merkledag/merkledag.go
merkledag/merkledag_test.go

Create a block service where all writes are guaranteed to go though to the blockstore.
Pull request #3105 (bitswap: don't re-provide blocks we've provided very recently) broke adding files via the filestore (i.e., --no-copy, #2634).  The first attempt to fix this was #3253, this is the second.
This also makes BlockService an interface, although in the end it was not strictly required.

Create a write-through block service

---

README.md

They didn't previously make sure the code was up-to-date.
License: MIT

readme: fix go get invocations

---

commands/cli/cmd_suggestion.go
commands/cli/parse.go

This is just a small refactor to expose some functionality needed by the filestore (#2634).
Hopefully it is uncontroversial, if you need more an an explanation let me know.

cli: refactor to expose argument parsing functionality
