ipfs/kubo

- core/commands/dht.go
- test/sharness/t0170-dht.sh
1. Document validators.
2. Pass DHT values as files as:
1. CLI arguments can't have nulls.
2. STDIN arguments can't have newlines. 
3. IPNS records can have _both_
fixes #5112
fixes #6749
> improve documentation and fix dht put bug

- cmd/ipfs/daemon.go
- plugin/daemoninternal.go
- plugin/loader/loader.go
This PR introduce a new kind of plugin able to directly use `IpfsNode`. As `IpfsNode` is considered internal, no guarantee is made about API stability. This is useful when a plugin needs a direct access to the internal and using `CoreApi` is not enough.
As introducing `PluginNode` make the naming a little akward, this PR also introduce a copy of `PluginDaemon` named `PluginApi` and deprecate `PluginDaemon`. As it is a separate commit, we can remove that easily if you don't like it.
> introduce IpfsNode Plugin

- core/commands/files.go
- test/sharness/t0250-files-api.sh
- Make `ipfs files rm --force /nonexistant` succeed when the path does not exist.
- Add shaness test for removing nonexistant paths
- Refactor duplicated code to find a parent dir into a function
I've been writing scripts against the files api, and having to stat things before removing them is a pain. So this PR aims to make --force do what I'd expect it to.
License: MIT
> fix: ignore nonexistant when force rm

- core/corehttp/gateway_handler.go
> fix #2203: omit the charset attribute when Content-Type is text/html

- README.md
testing out circleci build triggers with a PR that tidies up the README badges
- remove somewhat redundant `project: ipfs` badge so they fit on 1 line. The link to the website is the url field for the repo.
- Use shields.io "flat square" style for godoc badge to match the others
- Use shields.io for the circleci badge too.
- re-order to be more visually pleasing.
License: MIT
> chore: update readme badges to test ci

- core/core.go
- core/node/libp2p/transport.go
Due to https://github.com/libp2p/go-libp2p-core/pull/72#issuecomment-554602688
cc @Stebalien
> Change Reporter to BandwidthCounter in IpfsNode

- core/node/groups.go
- core/node/libp2p/pubsub.go
- core/node/libp2p/routing.go
- core/node/libp2p/topicdiscovery.go
- go.mod
- go.sum
Utilizes the persistent pubsub value store from libp2p along with the new pubsub support for topic-based peer discovery.
Blocked by https://github.com/libp2p/go-libp2p-pubsub-router/pull/37
> IPNS over PubSub as an Independent Transport

- core/commands/bitswap.go
- core/commands/dht.go
- core/commands/id.go
- core/commands/name/ipnsps.go
- core/commands/p2p.go
- core/commands/ping.go
- core/commands/stat.go
- core/commands/swarm.go
- core/node/groups.go
- docs/examples/go-ipfs-as-a-library/main.go
- docs/experimental-features.md
- docs/file-transfer.md
- docs/transports.md
- go.mod
- go.sum
- namesys/namesys.go
- namesys/routing.go
- test/3nodetest/client/run.sh
- test/3nodetest/server/run.sh
- test/sharness/lib/iptb-lib.sh
- test/sharness/t0120-bootstrap.sh
- test/sharness/t0121-bootstrap-iptb.sh
- test/sharness/t0140-swarm.sh
- test/sharness/t0180-p2p.sh
- test/sharness/t0182-circuit-relay.sh
See: https://github.com/libp2p/libp2p/issues/79
> update documentation for /ipfs -> /p2p multiaddr switch

- go.mod
- go.sum
* Fixes a panic on close/write race in the websocket transport (https://github.com/libp2p/go-libp2p-kad-dht/pull/422)
* Fixes recursive resolution of dnsaddrs (for bootstrapping).
> chore(dep): update go-libp2p

- core/corehttp/gateway_handler.go
- test/sharness/t0110-gateway.sh
This PR introduces hardening proposed in https://github.com/ipfs/go-ipfs/issues/4025#issuecomment-342250616 and closes #4025
cc @Stebalien @olizilla
js-ipfs version: https://github.com/ipfs/js-ipfs/pull/2682
> fix: limit SW registration to content root

- core/coreapi/unixfs.go
- core/coreunix/add.go
- core/node/core.go
- go.mod
- go.sum
- namesys/publisher.go
- namesys/publisher_test.go
As part of #6775, we need to add Sync calls into the appropriate places in go-ipfs (and its dependencies).
The places that were deemed important to have Sync calls include:
- Pinning: Any time the pin root is flushed all the puts it relies on should have completed
- Adding: After an add operation is completed the data should be synced
- MFS: Anytime the root is modified
- IPNS: When an update is submitted (before any network calls are made)
> Support Asynchronous Datastores

- test/sharness/lib/test-lib.sh
- test/sharness/t0010-basic-commands.sh
- test/sharness/t0060-daemon.sh
- test/sharness/t0061-daemon-opts.sh
- test/sharness/t0080-repo.sh
- test/sharness/t0095-refs.sh
- test/sharness/t0121-bootstrap-iptb.sh
- test/sharness/t0130-multinode.sh
- test/sharness/t0180-p2p.sh
- test/sharness/t0181-private-network.sh
- test/sharness/t0184-http-proxy-over-p2p.sh
- test/sharness/t0235-cli-request.sh
- test/sharness/t0236-cli-api-dns-resolve.sh
- test/sharness/t0280-plugin-git.sh
- test/sharness/t0300-docker-image.sh
- test/sharness/t0301-docker-migrate.sh
- test/sharness/t0600-issues-and-regressions-online.sh
This is the "no brainer" part of https://github.com/ipfs/go-ipfs/pull/6799
> Sharness macos no brainer fixes

- README.md
> Inclusion of the presence of the go-ipfs package in Solus

- go.mod
- go.sum
Go-ipfs now manually calls "sync" on the underlying datastore after adding data.
We can now write asynchronously and sync once at the end.
> feat: update go-ds-badger to use async writes by default.

- core/corehttp/gateway_handler.go
- core/corehttp/lazyseek.go
- core/corehttp/lazyseek_test.go
- go.mod
- go.sum
- test/sharness/t0113-gateway-symlink.sh
* Correctly calculate symlink sizes.
* Fix listing of directories with symlinks.
* Handle files without known sizes.
Note: This _doesn't_ provide actual symlink support. The gateway treats symlinks
like text files.
fixes #6203
> improve gateway symlink handling

- core/commands/cid.go
- test/sharness/t0290-cid.sh
This will be useful when testing `refs local, `repo gc`, and `repo verify` commands once we store blocks by multihash instead of by CID. At that point, these commands will return raw v1 CIDs as the blockstore won't actually remember the codec used to store the block.
Flags choice:
* Ideally, we'd use the `-f, --format` flags like every other command but we're already using `-f` (format) for the format string.
* Alternatively, I'd like to use `-c`. However, we're using _that_ for a global `--config` flag (bit of a waste given that it doesn't work...).
`--codec` will have to do for now.
Note: this patch also fixes `ipfs cid format -v 0 SOME_BASE32_CID` by implicitly converting to base58 (likely what the user intended).
> make it possible to change the codec with the `ipfs cid` subcommand

- plugin/plugins/badgerds/badgerds.go
We already do this in the datastore _profile_, but we should do this in the
plugin as well. I'm pretty sure this makes absolutely no difference.
> fix(badgerds): turn off sync writes by default

- docs/config.md
adds docs for Gateway.PathPrefixes. Taken from great commit notes by @lgierth (thank you!) https://github.com/ipfs/go-ipfs/commit/09937f84b64212896e1d80147f828d86ebc19d68
> docs: define Gateway.PathPrefixes

- Dockerfile
This PR:
* Updates docker deps (go -> 1.13.5, tini -> 0.18.0)
* Builds go-ipfs using openssl. We don't distribute go-ipfs with OpenSSL support by default to avoid depending on external libraries. However, we completely control the docker environment so there's no reason not to build with OpenSSL support. This significantly reduces CPU usage.
* Explicitly set the permissions on start_ipfs so we don't inherit the defaults set by the host OS.
> update dockerfile and use openssl

- bin/collect-profiles.sh
Due to the bash args used, collect-profiles.sh would fail if `which ipfs` failed to find an ipfs binary on the path, like when running ipfs in docker. Fixes that by using a check for the command that wont error if it's not found.
Also
- adds a comment to explain when to use the script and what it does.
- be less chatty. Simplify the output so it's clearer what it's doing. Experts can read the script or set the -x flag themselves.
- allow profiling of remote nodes via https.
License: MIT
> fix: dont fail to collect profiles if no ipfs bin

- .circleci/config.yml
> Parent: https://github.com/ipfs-shipyard/ipfs-webui/issues/1164
This PR adds CircleCI config for running ipfs-webui's end to end tests against `ipfs` binary produced by this repo.
It does not increase CI time, as its runs in parallel to interop tests, and those take much longer:
> ![times](https://user-images.githubusercontent.com/157609/72531440-c2ddd800-3871-11ea-8785-df2873b24a04.png)
The goal is to catch regressions in go-ipfs+ipfs-webui interop, such as this one (hardened go-ipfs was unable to connect to peer that used weak key size):
> ![Screenshot_2020-01-15 ipfs-webui (23414) - ipfs go-ipfs](https://user-images.githubusercontent.com/157609/72459462-1d702900-37cb-11ea-81b4-693533fd9c47.png)
When everything works as expected, it looks like this:
> …
> test: E2E tests against ipfs-webui HEAD

- core/node/libp2p/relay.go
- go.mod
- go.sum
Unfortunately, we don't currently have any way to pick out good relays from bad.
That means we keep searching, trying bad relays, searching some more, trying
_the same relays_, etc. until we randomly find 3 good stable relays. In
practice, this means we just keep searching forever and keep thrashing the DHT.
see https://github.com/libp2p/go-libp2p/issues/694
> fix: use pre-defined relays for autorelay

- docs/RELEASE_ISSUE_TEMPLATE.md
We no longer need to manually test the webui on release.
> doc(release): move WebUI from manual tests to automated tests section

- core/corehttp/webui.go
@Stebalien this is a PR against `release-0.4.23` backporting https://github.com/ipfs/go-ipfs/pull/6778 for v0.4.23 as requested in https://github.com/ipfs/go-ipfs/issues/6837#issuecomment-576880452
> chore: webui 2.7.2 for v0.4.23

- CHANGELOG.md
- Dockerfile
- README.md
GOFLAGS will _override_ all the flags. If we just want to set a tag e.g., enable OpenSSL, we should set GOTAGS=openssl.
fixes https://github.com/ipfs/go-ipfs/issues/6622#issuecomment-576713181
> fix(build): instruct users to use GOTAGS, not GOFLAGS

- fuse/readonly/readonly_unix.go
We likely encountered a file that misreported its size. That or there was no bug here and we hit an issue somewhere else. Regardless, there's no reason not to simplify this code and this should fix the issue.
> fix: fix a potential out of bounds issue in fuse

- Dockerfile
These changes allowed me to build arm Docker images to run on my Raspberry Pi. I used the new `docker buildx` feature to cross-build them. Let me know how else you'd like that documented / integrated into this repo.
The images I built are hosted here: https://hub.docker.com/repository/docker/cryptorado/go-ipfs
> Allow building non-amd64 Docker images

- docs/config.md
Trying to make this a bit more consistent and structured.
* Fix wrapping.
* Use headings for all config values.
> doc(config): cleanup

- core/commands/keystore.go
It's already the default when initializing the node, we might as well make it the default when creating new keys.
fixes #6861
> fix: make rsa the default key type

- .circleci/config.yml
- go.mod
- go.sum
Related to #6802, but I'm not sure if it fixes it.
Definitely fixes #6759.
> chore(dep): update go-multistream to fix a potential panic

- core/commands/id.go
- core/commands/swarm.go
Instead of manually creating multiaddr strings, use the multiaddr logic to format them. We were still using `/ipfs` multiaddrs instead of `/p2p` multiaddrs.
> fix: fix id addr format

- core/commands/add.go
> doc(add): document hash stability

- Dockerfile
- plugin/plugins/peerlog/peerlog.go
- allow IPFS_PLUGINS build-arg to be passed to docker build command
- remove annoying logging from peerlog plugin that appears multiple times in docker logs
usage:
```console
$ docker build --build-arg IPFS_PLUGINS="foo bar baz"
```
License: MIT
> feat: pass IPFS_PLUGINS to docker build

- test/sharness/t0001-tests-work.sh
Make sure they:
1. Report that they're done. Otherwise, we'll silently succeed.
2. Have a description.
3. Make sure we cleanup IPFS.
These are simple sanity checks to make sure we're not ignoring bugs in our tests.
> test(sharness): test our tests

- README.md
Encourage initial bug reports to security@ to be unencrypted for faster triage
> remove expired GPG key from README

- CHANGELOG.md
The year should be "2020," not "2019."
> Fix typo in 0.4.23 release date

- core/commands/files.go
* Adds the `--parents` option to the first command so that it is runnable
* Updates the description to specify the option to use if you _do_ want nonexistant intermediate directories created
> docs: fix example for files.write

- core/commands/dht.go
Turns out that our CLI help text doesn't indicate whether or not a command takes
a file.
> doc(commands): document that `dht put` takes a file

- go.mod
- go.sum
This also updates graphsync to use the new peertaskqueue.
Depends on https://github.com/ipfs/go-graphsync/pull/54
> chore(dep): update bitswap

- cmd/ipfs/main.go
- cmd/ipfs/util/ui.go
- cmd/ipfs/util/ui_windows.go
Resolves: https://github.com/ipfs/go-ipfs/issues/6633
Hacky but maybe acceptable.
If we're not launched from a terminal, we launch the daemon by default.
If we're inside of a terminal, we print help.
https://youtu.be/diam0dQaBdw
(for some reason my cursor didn't get recorded)
> cmd: ipfs handle GUI environment on Windows

- core/corehttp/gateway_handler.go
- core/corehttp/hostname.go
- test/sharness/t0114-gateway-subdomains.sh
> This is a PR against [`feat/gateway-subdomains` branch](https://github.com/ipfs/go-ipfs/pull/6096) to resolve concerns from https://github.com/ipfs/go-ipfs/issues/6975
Return payload with HTTP 301 response:
- curl returns exit code 0 on 301, so no script will fail
- web browsers close connection after reading HTTP 301 and `Location` header, so there should not be any bandwidth wasted
- just to be sure browsers don't store anything we return `Clear-Site-Data` header with such response
When request is sent to `http://localhost:8080/ipfs/$cid` HTTP 301 status code with  "Location" header redirect client to subdomain destination at `$cid.ipfs.localhost:8080`
Redirects are not followed by `curl` in default mode, but will be respected by user agents that follow redirects by default, namely …
> fix(subdomain-gw): curl on localhost (Option A: HTTP301+payload)

- test/sharness/t0026-id.sh
- version.go
Go-ipfs user agents usually look like go-ipfs/VERSION/COMMIT_or_EMPTY. However,
we changed this to /go-ipfs/VERSION(/COMMIT)? on master for a while. This change
reverts this to make parsing the user agent simpler.
> fix: revert changes to the user agent

- go.mod
- go.sum
- test/sharness/t0040-add-and-cat.sh
Still throws an error when a pipe is encountered during directory recursion.
~**WILL NOT** pass CI without https://github.com/ipfs/go-ipfs-cmds/pull/184~
> Support pipes when named on the cli explicitly

- core/commands/add.go
- go.mod
- go.sum
- test/sharness/t0042-add-skip.sh
- add the `gitignore` or `ignore options to the add command
rebase of https://github.com/ipfs/go-ipfs/pull/6901
> feat(file-ignore): add ignore opts to add cmd

- core/coreapi/name.go
* Support peer IDs encoded as CIDs.
* Support looking up the identity key by peer ID.
> feat: improve key lookup

- .circleci/config.yml
- keystore/keystore.go
- keystore/keystore_test.go
- keystore/memkeystore.go
- keystore/memkeystore_test.go
- repo/fsrepo/fsrepo.go
Ported from https://github.com/ipfs/go-ipfs/pull/6012
---
Encoding the key's filename with base32 introduces coherent behaviour
across different platforms and their case-sensitive/case-insensitive
file-systems. Moreover it allows wider character set to be used for the
name of the keys as the original restriction for special FS's characters
(e.g. '/', '.') will not apply.
License: MIT
Signed-off-by: Adam Uhlir <uhlir.a@gmail.com>
> Introducing EncodedFSKeystore with base32 encoding (#5947)

- cmd/ipfs/daemon.go
Not sure why CI didn't catch this
> Forgotten go-fmt

- keystore/keystore.go
Instead of checking then performing a file operation, perform the file operation and check the error.
Merge to master after the base PR. I'm just filing this now so I don't forget.
> fix(keystore): avoid racy filesystem access

- keystore/keystore.go
```
keystore: Switch from Bytes() to MarshalPrivateKey()
Bytes is deprecated.
```
```
keystore: create new keys with 0400 permissions (as spec'ed) 
Spec is pretty much out of date but specifies this.
https://github.com/ipfs/specs/blob/master/KEYSTORE.md
```
> Keystore: minor maintenance

- core/commands/dag/dag.go
This is the simple, non-controversial, export-progress-meter modeled on how `ipfs cat` works. R made agains the base mplementing branch for ease of review.
> Add simple byte-counting export progress

- core/node/groups.go
- core/node/libp2p/transport.go
- docs/examples/library-experimental-features/README.md
- docs/experimental-features.md
- go.mod
- go.sum
Switches to TLS as the default security transports.
> feat: tls by default

- core/builder.go
Instead of feeding through the top-level context, feed through a cancel-free context (that still carries the same context values). Then, when the top-level context is canceled, call `stop` to shut everything down in-order. Finally, cancel the inner context to make sure everything has been cleaned up.
Ideally, we just wouldn't use contexts for this. But this is strictly better than what we have.
> fix: get rid of shutdown errors

- core/node/libp2p/relay.go
- test/sharness/t0182-circuit-relay.sh
This logic collects a list of known relays by testing every new connection.
It exists so we can dial /p2p-circuit/p2p/QmFoobar addresses (circuit addresses that don't specify the relay). However, this kind of address is useless outside of basic demos as a random relay is practically guaranteed to not be connected to the target peer. Picking a random relay to connect to some peer is almost _never_ the desired behavior.
> fix: remove internal relay discovery

- core/commands/files.go
> Fix #4996: Improve help text for "ipfs files cp"

- test/sharness/t0142-testfilter.sh
> Filter dials to blocked subnets, even when using DNS.

- test/sharness/t0054-dag-car-import-export.sh
Fixes ( or at least makes cleaner ) https://github.com/ipfs/go-ipfs/issues/7123
At this point I am convinced that this comment I made way back is in fact real: https://github.com/ipfs/go-ipfs/pull/7011/files/aa5019413741f2d34c9723d376591cf8c4b6b465#diff-15172926c4147422f472139313467179R330-R341
We did switch away from gclock a while back, and likely other changes I made cause it to trigger less frequently. Reproducing this locally is nigh impossible however :(
So instead the timeout+QUIT contraptions should tell us more next time it happens on the slower circleci boxes.
> Beef up and harden import/export tests

- core/node/storage.go
- go.mod
- go.sum
And remove retry logic. This was flatfs specific and we've moved the logic down into flatfs itself.
This update:
* Retries in more cases when we run out of file descriptors.
* Ensures we don't leak temporary files on batch put.
> chore: update flatfs

- test/sharness/t0054-dag-car-import-export.sh
I am going to rig a more robust version and run it locally to crash
Disabling in master in order to validate the pipe reading itself
works correctly and reliably
> Temporarily disable gc-race test

- namesys/cache.go
- namesys/namesys.go
- test/sharness/t0160-resolve.sh
If we fail to publish, _invalidate_ our cache. The publish may have partially succeeded.
fixes #7117
All credit goes to @aschmahmann for tracking this down.
> fix: invalidate cache on failed publish

- core/commands/dht.go
- core/core.go
- core/coreapi/test/api_test.go
- core/mock/mock.go
- core/node/libp2p/routing.go
- core/node/libp2p/routingopt.go
- go.mod
- go.sum
- namesys/republisher/repub_test.go
- test/integration/three_legged_cat_test.go
- test/sharness/t0170-dht.sh
And only join the WAN DHT if we're publicly reachable.
TODO:
> feat: introduce the dual WAN/LAN DHT

- test/sharness/t0054-dag-car-import-export.sh
* Instead of ensuring that we GC nothing, verify that the repo validates.
* Avoid a race between removing the fifos and trying to read from them.
* Avoid all 'bash -c' invocations. Instead, make liberal use of subshells and wait.
Hopefully fixes #7123.
> test(sharness): improve CAR tests to remove some potential races

- cmd/ipfs/daemon.go
It looks like the incorrect address passed into the logger in case of error
> fix the typo in the serveHTTPApi

- core/corehttp/webui.go
(supersedes v2.7.3, so no need to keep old one around)
Release notes: https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.7.4
@Stebalien can we include this in 0.5.0-rc2 ? (cc https://github.com/ipfs/go-ipfs/issues/7109, @jessicaschilling )
> feat: webui v2.7.4

- core/node/groups.go
- core/node/libp2p/nat.go
- docs/config.md
- go.mod
- go.sum
- test/sharness/t0185-autonat.sh
1. Enable AutoNATService on _all_ nodes by default. If it's an issue, we can disable it in RC3 but this will give us the best testing results.
2. Expose options to configure AutoNAT rate limiting.
> add autonat config options

- core/corehttp/gateway_handler.go
- test/sharness/t0114-gateway-subdomains.sh
Closes #7164
Note: due to the way `http` in golang works, status code can be set only once. 
There is a known issue with `prometheus/client_golang`: it sometimes produces `superfluous response.WriteHeader call` and if it is executed first, the status code set in our code is ignored. 
In this PR I set the redirect status code before executing the template to avoid potential race condition, feels like the least invasive way of making this work reliably.
> fix: subdomain redirect for dir CIDs

- test/integration/wan_lan_dht_test.go
This adds an integration test.
Currently, an `*IpfsDHT` is exposed by the core, which will not be populated due to the use of the `dual` DHT. this test will not be able to refresh the routing table as a result, and will fail at present on the `feat/dual-dht` branch.
> integration test for the dual dht

- Dockerfile
Currently docker container pulls default amd64 version of tini.
I add platform chooser for tini binary into docker building process
> Choose architecture when download tini into docker container

- core/commands/log.go
It looks like "warning" and "critical" levels were removed, but the help text wasn't updated to reflect this.
```
> ipfs.exe version --all
go-ipfs version: 0.5.0-rc3
Repo version: 9
System version: amd64/windows
Golang version: go1.13.10
> ipfs.exe log level all warning
Error: unrecognized level: "warning"
> ipfs.exe log level all critical
Error: unrecognized level: "critical"
```
> update log helptext to match actual levels

- docs/experimental-features.md
This PR adds a note about global side effect of setting `ShardingEnabled` to `true`
Right now it is a global setting  which will impact the final CID of all directories produced by `ipfs.add`
People may assume that HAMT sharding gets enabled only for directories over some arbitrary threshold. 
(I did. And took me a moment to understand why CID of WebUI is no longer reproducible. Embarrassingly long moment.. :grimacing:  )
cc https://github.com/ipfs/interface-go-ipfs-core/issues/48
> docs: note that ShardingEnabled is a global flag

- .github/ISSUE_TEMPLATE/config.yml
I figured we can actually link specific go-ipfs docs when users want to open an issue. Particularly the Config reference, the Experimental Features and the API reference. My personal perception is these 3 are the most sought after and I'm not sure they are very well linked from the docs site.
> Add additional documentation links to the new issue screen

- go.mod
- plugin/plugins/peerlog/peerlog.go
Avoid ever blocking new connections in the peer logger. Instead:
1. Send all new peers to a highly buffered channel.
2. Emit "dropped event" errors whenever we detect that we're dropping events and falling behind.
3. Don't log protocols, they're too large.
4. Don't log disconnects, we don't need them.
> fix: non-blocking peerlog logging

- go.mod
- go.sum
Removes any and all requirements on CGO. Previously, ipfs would fail to build if CGO wasn't explicitly disabled and no C compiler was available.
> chore: update sockaddr

- CHANGELOG.md
- docs/plugins.md
- version.go
> feat: release 0.5.0

- .github/config.yml
I'd like to trial usage of this feature: first-time posters receive a welcome message that explains some things on how we work and what to expect.
This is only for the first issue opened by a user in the repository.
Thoughts?
> Welcome message for users opening their first issue

- CHANGELOG.md
This PR 
- fixes invalid examples for subdomain gateway in CHANGELOG for v0.5.0
- fixes ENS example 
(I already fixed this in https://github.com/ipfs/go-ipfs/releases/tag/v0.5.0)
cc @raulk @Stebalien
> docs: fix subdomain examples in CHANGELOG

- .github/auto-comment.yml
* Give a few tips on linking relevant discussions, self reviews, additional
reviews and code contribution guidelines
* Be explicit about the next steps and what to expect.
I would like to trial this. A potential problem I see is that this will comment on every PR (including ours) and might be annoying for the people that sends most PRs. We can switch to commenting on only first-time PRs but then we miss the chance to remind people that only occasionally contribute (and ourselves about the process to follow).
> Auto-comment on submitted PRs

- namesys/publisher.go
fixes #7244
Sometimes IPNS publishes can take longer than a minute. Since DHT lookups now terminate without needing to query a huge portion of the network (even if the lookups take a while until more of the network upgrades to v0.5.0+), we should allow the user's IPNS queries to go on until they're ready to cancel them.
Note: There's still a 30 second timeout on doing a record Get before Publishing, however this doesn't bother me too much since it both doesn't cause an error to be returned and the whole code path is a bit strange in general since it seems to only get called if either:
1) The IPNS key is first being used (in which case we expect the Get to return no info, so we might as well have a timeout)
2) The datastore (not the blocks section, but the rest of the datastore) has been …
> fix: do not use hard coded IPNS Publish maximum timeout duration

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_test.go
For gateway directory listings, always the absolute path and the CID of the current directory. Even for dnslink websites.
fixes https://github.com/ipfs/go-ipfs/issues/7205
> feat(gateway): show the absolute path and CID every time

- misc/completion/ipfs-completion.bash
The `compopt` bash builtin is not supported by zsh's bash compatibility
features. By checking for zsh presence and using `complete` instead,
this script becomes suitable for use with both bash and zsh.
> Updates bash completions to be compatible with zsh

- core/corehttp/gateway_handler.go
- go.mod
- go.sum
This fixes https://github.com/ipfs/go-ipfs/issues/7252 by replacing  `http.DetectContentType()` with `mimetype.Detect()` from https://github.com/gabriel-vasile/mimetype library.
I've tested locally with the ODS files, mp3 files and html files. Please let me know if there's anything further that needs to be done!
> Fixes #7252 - Uses gabriel-vasile/mimetype to support additional content types

- misc/systemd/ipfs.service
General help text added to instruct new user to make permanent changes to the service files
<strike>Add a longer timeout for startup and shutdown</strike> _Removed after discussions_
> systemd: add helptext

- CHANGELOG.md
- go.mod
- go.sum
- namesys/publisher.go
- version.go
Hot on the heels of 0.5.0 is 0.5.1 with some important but small bug fixes. This release:
1. Removes the 1 minute timeout for IPNS publishes (fixes #7244).
2. Backport a DHT fix to reduce CPU usage for canceled requests.
3. Fixes some timer leaks in the QUIC transport ([ipfs/go-ipfs#2515](https://github.com/lucas-clemente/quic-go/issues/2515)).
Full changelog:
- github.com/ipfs/go-ipfs:
- IPNS timeout patch from master ([ipfs/go-ipfs#7276](https://github.com/ipfs/go-ipfs/pull/7276))
- github.com/libp2p/go-libp2p-core (v0.5.2 -> v0.5.3):
- feat: add a function to tell if a context subscribes to query events ([libp2p/go-libp2p-core#147](https://github.com/libp2p/go-libp2p-core/pull/147))
- github.com/libp2p/go-libp2p-kad-dht (v0.7.10 -> v0.7.11):
- fix: optimize for the case where we're not …
> feat: release 0.5.1

- repo/fsrepo/fsrepo.go
Fix: #7227 
Signed-off-by: Tiger <rbalajis25@gmail.com>
> write api file automically

- bin/mkreleaselog
This will include:
* Commits to master.
* Squashed merges.
In the release notes.
> fix(mkreleasenotes): include commits directly to master

- bin/mkreleaselog
1. Cd into the repo root before running `go list`.
2. Make sure the repo lives in the GOPATH.
fixes https://github.com/ipfs/go-ipfs/pull/7296#discussion_r422461135
> fix(mkreleaselog): make robust against running in different working directories

- docs/config.md
Additional note about running subdomain gateway behind reverse proxy with TLS.
`X-Forwarded-Proto: https`
cc @MichaelMure @Stebalien
> docs: X-Forwarded-Proto: https

- core/commands/commands_test.go
- core/commands/stat.go
- core/commands/stat_dht.go
Currently, it just prints out the routing tables.
TODO
> feat: add a dht stat command

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_test.go
I noticed ipfs/ipfs#167 and thought this might be an elegant solution for allowing the gateway to show helpful information when requested files aren't found.
When a requested file isn't found `ipfs-404.html` is looked for in the same directory, rolling up through any of its parents, and displayed (without immutable cache headers) if present.
Run this patch locally and query the following for a demonstration:
* [Pretty 404 page](http://127.0.0.1:8080/ipfs/QmTLbqrzBgRCB2weXi1dmZiNZQW7wfUW4k3gRu7UTcXaoi/nope) at /nope
* [More specific pretty 404 page](http://127.0.0.1:8080/ipfs/QmTLbqrzBgRCB2weXi1dmZiNZQW7wfUW4k3gRu7UTcXaoi/deeper/nope) at /deeper/nope
* [Fallback pretty 404 page](http://127.0.0.1:8080/ipfs/QmTLbqrzBgRCB2weXi1dmZiNZQW7wfUW4k3gRu7UTcXaoi/nope/nope) at /nope/nope
> Gateway renders pretty 404 pages if available

- fuse/ipns/ipns_unix.go
- test/sharness/t0030-mount.sh
fixes https://github.com/ipfs/go-ipfs/issues/7246
> fix: correctly trim resolved IPNS addresses

- docs/config.md
- docs/experimental-features.md
* sort config sections (ignore that commit when reviewing)
* add a pubsub config section
* update pubsub experimental feature.
> misc config/experimental-features doc fixes

- core/corehttp/gateway_handler.go
Files already have an explicit Content-Type set. Be sure to do this for
directory listings as well to avoid a fallback to autodetection in
net/http. That fallback fails when a ResponseWriter is installed that
performs compression.
> fix(gateway): ensure directory listings have Content-Type text/html

- docs/config.md
GitHub shows big red highlighted text through the document when doing a diff (e.g. on future PRs) if the code fragments labeled JSON appear to be improperly formatted. I've just gone and added some curly braces.
If we think they're a pain/annoying we can just drop this PR. Additionally, if we'd like to remove the wrapping `{}` that is around some, but not all of the json fragments to make them smaller I'm fine doing that as well.
> docs: cleanup config formatting

- docs/experimental-features.md
Updates the IPNS over PubSub experimental feature to encompass the latest changes to the feature.
> docs: update experimental-features doc with IPNS over pubsub changes.

- test/sharness/t0031-mount-publish.sh
We count "mount" IPNS if it refers to a file instead of a directory.
> test(sharness): fix fuse tests

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_test.go
fixes https://github.com/ipfs/go-ipfs/pull/4233#issuecomment-631454543
Basically, there's a trade-off here:
1. We can support directory listings while supporting 404 pages (this PR).
2. If a 404 page is present, directory listings don't work.
Given that option 1 is more flexible and users shouldn't be _too_ confused if they land on a directory with no index.html page, I've gone with that option.
> fix: support directory listings even if a 404 page is present

- core/node/libp2p/host.go
- core/node/libp2p/routingopt.go
- go.mod
- go.sum
Otherwise, we could end up with only DHT clients and never re-bootstrap.
I've left the default go-ipfs bootstrapping code in for now as it's technically possible to disable the DHT entirely.
> feat: bootstrap in dht when the routing table is empty

- assets/assets.go
- assets/bindata_version_hash.go
- core/corehttp/gateway_handler.go
While the content of raw files retrieved via the gateway should never
change, the look and feel of the directory index can and will change
between versions of go-ipfs.
Incorporate the hash of assets/bindata.go into the ETag when appropriate
@Stebalien this is what we spoke about <gulp> last year @ camp. Goes with @jessicaschilling's recent changes.
> Include the git blob id of the dir-index bundle in the ETag

- core/core.go
- core/node/groups.go
- core/node/peering.go
- docs/config.md
- go.mod
- go.sum
- peering/peering.go
- peering/peering_test.go
- test/sharness/t0171-peering.sh
MVP for #6097
This feature will repeatedly reconnect (with a randomized exponential backoff) to peers in a set of "peered" peers.
In the future, this should be extended to:
1. Include a CLI for modifying this list at runtime.
2. Include additional options for peers we want to _protect_ but not connect to.
3. Allow configuring timeouts, backoff, etc.
4. Allow groups? Possibly through textile threads.
5. Allow for runtime-only peering rules.
6. Different reconnect policies.
But this MVP should be a significant step forward.
> feat: implement peering service

- core/node/groups.go
- core/node/libp2p/transport.go
- docs/experimental-features.md
- go.mod
- go.sum
- test/sharness/lib/iptb-lib.sh
- test/sharness/t0125-twonode.sh
- test/sharness/t0191-noise.sh
We can add a proper configuration option in a followup patch after the RC.
> feat: add noise support

- .mailmap
- bin/mkreleaselog
* The first patch adds a mailmap file. Mailmap files are used by git to deduplicate authors.
* The second patch uses the mailmap file when generating contributor stats in the release notes.
> mailmap support

- core/corehttp/webui.go
It seems to have been overlooked.
https://github.com/ipfs-shipyard/ipfs-webui/releases/v2.8.0
> chore: update WebUI to 2.8.0

- core/corehttp/webui.go
Release Notes: https://github.com/ipfs-shipyard/ipfs-webui/releases/v2.9.0
@Stebalien any chance we can squeeze this into 0.6.0-rc2 (https://github.com/ipfs/go-ipfs/issues/7347), or is it too late?
This and v2.8.0 bring i18n updates and various UI bugfixes / improvements only.
(no changes to HTTP client libs, APIs etc, afaik no surface for regressions)
> feat: webui v2.9.0

- docs/config.md
> Update docs-beta links to final URLs

- .github/ISSUE_TEMPLATE/config.yml
- docs/config.md
The legacy IPFS Docs site has been deprecated, so links to `docs-beta.ipfs.io` will auto-redirect to `docs.ipfs.io`. This PR doesn't change much from the user's perspective, but it makes things a bit tidier.
> Updates docs link to non-beta site.

- .circleci/config.yml
> fix: update node to fix mocha tests

- core/commands/pubsub.go
- core/coreapi/coreapi.go
- core/coreapi/pubsub.go
- core/node/libp2p/pubsub.go
1. Flood for first pubsub hop to ensure the message gets broadcasted even if some of our peers are overloaded.
2. Remove discovery logic. This is now handled by pubsub internally.
> fix two pubsub issues.

- go.mod
- go.sum
This is a _protocol breaking_ change for the QUIC transport, the last one before
we stabilize it.
> chore: update quic transport

- core/commands/id.go
- test/sharness/t0140-swarm.sh
Consistently append `/p2p/QmMyId` to addresses when calling `ipfs id Me` and `ipfs id NotMe`.
Fixes https://github.com/ipfs/go-ipfs/issues/7378.
> fix(commands): print consistent addresses in ipfs id

- core/commands/refs.go
- core/coreapi/dag.go
This isn't perfect (we only use sessions after resolving the root cid) but it's
better than what we have. The real solution is #7198 so we can use sessions
everywhere.
> fix: use bitswap sessions for ipfs refs

- .circleci/config.yml
- Dockerfile
- README.md
- mk/golang.mk
due to major bugfixes in the .4 release
> go: bump minimal dependency to 1.14.4

- repo/fsrepo/migrations/migrations.go
1. Don't add quic addresses when they're already present (correctly detect quic addresses).
2. Correctly distinguish between quic addresses and quic + relay addresses.
3. Only add quic addresses to mirror tcp addresses, not tcp/ws addresses.
fixes #7444
> fix(migration): correctly migrate quic addresses

- repo/fsrepo/migrations/migrations.go
1. We should have done this in 7-to-8 anyways, but didn't in some cases.
2. We assume these addresses use /p2p/ in the 9-to-10 migration.
This should be the final iteration of this migration...
> fix(migration): migrate /ipfs/ bootstrappers to /p2p/

- Dockerfile
Building the go-ipfs docker image from the zip archive fails because it has no `.git` folder.
The `mkdir .git/objects` is at fault here. I fixed it by adding `-p` to it.
This fixes #7420
> fix: Use the -p option in Dockerfile to make parents as needed

- README.md
- misc/README.md
Currently the Readme links to the old repository [ipfs/website](https://github.com/ipfs/website) for informations about init systems.
This PR changes the link to the [misc folder](https://github.com/ipfs/go-ipfs/tree/master/misc) of this repo and imports the [old readme](https://github.com/ipfs/website/tree/master/static/docs/examples/init) to this folder (which needs some :heart: ).
fixes https://github.com/ipfs/website/issues/383
Authors of the readme from ipfs/website:
@lgierth @CameronNemo @jessicaschilling
> Readme: Update link about init systems (and import old readme)

- misc/systemd/ipfs-hardened.service
- misc/systemd/ipfs.service
Currently, the service files will create a hidden directory '/var/lib/ipfs/.ipfs/' which is not necessary for a system-user installation since it won't store any additional files - like in a regular user directory.
This change will set the directory to '/var/lib/ipfs/' to avoid this.
> systemd: specify repo path, to avoid unnecessary subdirectory

- cmd/ipfs/daemon.go
- core/node/groups.go
- core/node/libp2p/libp2p.go
- core/node/libp2p/relay.go
- core/node/libp2p/sec.go
- core/node/libp2p/smux.go
- core/node/libp2p/transport.go
- docs/config.md
- docs/environment-variables.md
- docs/experimental-features.md
- go.mod
- go.sum
- repo/fsrepo/fsrepo.go
- test/sharness/t0125-twonode.sh
- test/sharness/t0130-multinode.sh
- test/sharness/t0190-quic-ping.sh
- test/sharness/t0191-noise.sh
Add a config section for configuring transports. This way, users can disable transports (especially QUIC), and set muxer/security transport priorities.
> feat: transport config

- core/coreapi/name.go
- core/corehttp/hostname.go
- namesys/namesys.go
Alone, these three bugs were benign. But all together, they'd cause us to slowly leak `name.Search()` goroutines when resolving a name failed in some cases.
* We were using the wrong context to resolve dnslink records.
* We weren't reading the entire channel returned by `api.Name().Search()` but _also_ weren't canceling the context.
* We were returning results after returning errors. If we were canceling the context, or reading the entire channel, this would have been fine. But we shouldn't be doing this anyways.
The last bug fix (closing the response channel) was actually my first attempt to fix the bug, but it's related to this issue.
> fix 3 bugs responsible for a goroutine leak (plus one other bug)

- core/corehttp/webui.go
Release Notes:
* https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.10.0
> chore: bump webui version

- Dockerfile
This is more robust cross-platform/architecture.
fixes #7422
> fix: use static binaries in docker container

- core/corehttp/hostname.go
- docs/config.md
- test/sharness/t0114-gateway-subdomains.sh
Chained after https://github.com/ipfs/go-ipfs/pull/7461
This PR add support for `X-Forwarded-Host` to use the original host of the request when a proxy is used.
cc @lidel
> feat: support X-Forwarded-Host header

- core/corehttp/hostname.go
- core/corehttp/hostname_test.go
- test/sharness/t0114-gateway-subdomains.sh
- test/sharness/t0184-http-proxy-over-p2p.sh
> The goal of this PR is to be alternative to #7358 and solve #7318 in a way that makes it possible to have functional TLS for IPNS on public subdomain gateways.
If we split original CID into multiple sub labels (#7358) DNS resolution will work, but **no public gateway will be able to get TLS certificate** that supports double wildcards like `*.*.ipfs.example.com`. 
When splitting is used, visitors using web browsers will see a [TLS Error page](https://user-images.githubusercontent.com/157609/86123445-cc829180-bad9-11ea-8471-83683ee48654.png), which effectively kills UX and defeats the purpose of subdomain gateway (one step forward  by increasing security by providing Origin isolation, two steps backward by removing ability to do TLS validation when loading website backed by a long CID). …
> feat: support ED25519 at subdomain gw with TLS

- cmd/ipfs/daemon.go
- cmd/ipfs/init.go
- go.mod
- go.sum
- test/sharness/lib/test-lib.sh
- test/sharness/t0020-init.sh
- test/sharness/t0114-gateway-subdomains.sh
> Choose Key type at initialization

- mk/golang.mk
That way we can combine our GOFLAGS with the user specified ones.
This also switches to the new -trimpath build flag for reproducible builds.
fixes #7475
> fix: override GOFLAGS

- .circleci/config.yml
Changes the CI pipeline to use a published version of the `ipfs-interop` module instead of whatever's the HEAD of master in order to control the versions of what's being tested.
Otherwise it becomes hard to release breaking changes in an ordered fashion.
> chore: use published ipfs-interop module instead of master branch

- .gitignore
- Dockerfile
- snap/snapcraft.yaml
Simplify keeping the snap package up to date by including the snapcraft.yaml in the repo.
We can then wire up the snapstore to autobuild the package for amd64, i386, arm* etc.
Many thanks to @elopio for the work of getting ipfs into the snap store in the first place, and to @bertrandfalguiere and @mkg20001 for pushing it forwards.
To try it out, install `snapcraft` and run it from the root of the project folder. That will build go-ipfs and create a .snap file for your current system architecuture. See: https://github.com/ipfs-shipyard/ipfs-snap for more information.
Fixes #7250
WIP #3595
License: MIT
> feat: add snap package configuration

- core/commands/name/ipns.go
We were previously using `int` instead of `uint` which caused the `rcok` to always be false.
We should probably have a test that makes sure the various flags work, but in the sake of expediency with the upcoming release and the fact that this small fix looks right I didn't bother.
Would welcome a test here.
> ipfs name resolve --dht-record-count flag fix

- docs/production/reverse-proxy.md
see https://github.com/ipfs/go-ipfs/issues/6402
> doc: document reverse proxy bug

- plugin/loader/load_nocgo.go
- plugin/loader/load_noplugin.go
- plugin/loader/load_unix.go
- plugin/loader/loader.go
- test/sharness/t0280-plugin.sh
partially fixes #7305
The other half is to actually _build_ with CGO support by default.
> feat: nice errors when failing to load plugins

- core/commands/id.go
This is really useful for debugging.
TODO: fix tests if @aschmahmann and @achingbrain OK this change.
> feat: return supported protocols in id output

- namesys/ipns_resolver_validation_test.go
- namesys/routing.go
As described in: https://github.com/ipfs/go-ipfs/issues/6360#issuecomment-657817622 and https://github.com/ipfs/specs/issues/250
We really do not need to be resolving public keys before resolving IPNS records any more. This just makes IPNS resolution slower and makes using IPNS over PubSub (without DHT support) fail when peers do not already have access to the IPNS public key (e.g. commonly for keys other than `self`)
> Stop searching for public keys before doing an IPNS Get

- core/node/libp2p/sec.go
- test/sharness/t0060-daemon.sh
Disabling SECIO by default.
closes #7530
> Disable secio by default

- core/corehttp/hostname.go
- core/corehttp/hostname_test.go
- docs/config.md
- test/sharness/t0114-gateway-subdomains.sh
This is a preview for feedback. Some things are obviously missing, like the documentation.
Add support for one or more wildcards in the hostname definition
of a public gateway. This is useful for example to support easily
multiples environment.
Wildcarded hostnames are set in the config as for example `*.domain.tld` or even `*.*.domain.tld`
This PR address https://github.com/ipfs/go-ipfs/issues/7317 as well 
cc @lidel  @Stebalien
> feat: wildcard support for public gateways

- core/commands/keystore.go
- test/sharness/t0027-rotate.sh
It's currently possible to backup your Identity with the `self` name when rotating keys, `ipfs key rotate -o self`. This results in a second `self` key in the keystore list. The name is now checked to avoid this.
I also updated the help text to be a bit clearer. It wasn't apparent that key rotation only applied to the Identity key.
> fix(key): dont allow backup key to be named 'self'

- docs/config.md
This PR  fixes the header for `Peering`, which was under pubsub for some reason.
That looked like a mistake: Peering is top level namespace.
cc @aschmahmann
> docs(config): fix Peering header

- core/corehttp/gateway_test.go
https://golang.org/pkg/testing/#B.Cleanup
> use t.Cleanup() to reduce the need to clean up servers in tests

- namesys/republisher/repub.go
- namesys/republisher/repub_test.go
> namesys: fixed IPNS republisher to not overwrite IPNS record lifetimes

- core/commands/keyencode/keyencode.go
- core/commands/keystore.go
- core/commands/name/ipnsps.go
- core/commands/name/publish.go
This PR first refactors `--ipns-base` by putting all the options in one location and then removes the empty alias that was being used.
> Fix --ipns-base alias

- core/commands/id.go
> fix: remove the (empty) alias for --peerid-base

- core/corehttp/webui.go
Bumps to new Webui: https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.1
cc https://github.com/ipfs/go-ipfs/issues/7560
> chore: webui v2.11.1

- cmd/ipfs/util/ulimit_test.go
- cmd/ipfswatch/ipfswatch_test.go
- cmd/ipfswatch/main.go
- cmd/seccat/seccat.go
- cmd/seccat/seccat_plan9.go
- cmd/seccat/seccat_posix.go
- core/commands/add.go
- core/commands/dag/dag.go
- core/commands/get.go
- fuse/ipns/ipns_test.go
- fuse/ipns/ipns_unix.go
- fuse/ipns/link_unix.go
- fuse/mount/fuse.go
- fuse/node/mount_notsupp.go
- fuse/node/mount_test.go
- fuse/node/mount_unix.go
- fuse/readonly/ipfs_test.go
- go.mod
- go.sum
Fixes #7575
Fixes #7671
~~https://github.com/ipfs/go-ds-badger/pull/100 should be merged before this PR. I'm using an indirect dependency as a workaround.~~ (done)
> fix build on Plan 9

- core/corehttp/gateway_handler.go
- docs/gateway.md
- test/sharness/t0110-gateway.sh
This PR improves the way gateway supports `Content-Disposition`, an HTTP header used by browsers as a name hint when saving a file:
- ASCII-only fallback for old browsers that do not implement RFC 5987 (Closes #7648)
- Support for direct download mode with `Content-Disposition: attachment` when `?filename` is accompanied by `&download=true` 
This is a fully backward-compatible change, sharness tests included.
cc (https://github.com/ipfs/go-ipfs/pull/4177  – @voker57 @crackcomm @radfish) https://github.com/ipfs/in-web-browsers/issues/132 @andrew @gozala @autonome
> feat(gateway): Content-Disposition improvements

- docs/RELEASE_ISSUE_TEMPLATE.md
Suggested as I noticed the CLI docs hadn't been updated since 0.5: https://github.com/ipfs/ipfs-docs/pull/484
> Add task for updating CLI docs right after updating the HTTP-api docs

- core/corehttp/webui.go
Bumps webui to https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.2
> chore: webui v2.11.2

- docs/config.md
This fixes the mistake where `X-Forwarded-Host` was named `X-Forwarded-Proto` and makes it easier to discover both options.
> docs(config): X-Forwarded-Host

- coverage/Rules.mk
Some packages can contain both external and internal tests. Listing these packages twice causes us to create two targets (which fails).
Instead, use a single go list statement.
> fix error when computing coverage

- plugin/loader/load_nocgo.go
- plugin/loader/load_unix.go
Go plugins are supported on FreeBSD, but build tags in `plugin/loader/load_unix.go` enable IPFS plugins only on Linux and Darwin.
> Add missing plugin support on FreeBSD

- docs/snap.md
Explaining how the ipfs snap at https://snapcraft.io/ipfs gets published.
fixes: #7679
License: MIT
> docs: how the ipfs snap is built and published

- core/corehttp/gateway_handler.go
- test/sharness/t0110-gateway.sh
> **TLDR** We were losing query params on redirect, this PR fixes that.
This PR preserves query parameters during internal redirect of http gateway and adds sharness test to guard against regression in the way `index.html` detection works.
When  `/foo?bar=buz` was requested and `/foo/index.html` existed, 
gateway redirected to `/foo/` and that redirect did not preserve query params.
Problematic code was:
1. https://github.com/ipfs/go-ipfs/blob/v0.7.0/core/corehttp/gateway_handler.go#L180
2. https://github.com/ipfs/go-ipfs/blob/v0.7.0/core/corehttp/gateway_handler.go#L283-L285
cc @mburns  @hsanjuan
> fix(gw): preserve query on website redirect

- core/commands/dag/dag.go
`ipfs dag import/export` were directly using the `IpfsNode` instead of a `CoreAPI` which meant that `--offline` doesn't "automatically" work unless we actually do some manual work inside of the code (i.e. `cmdenv.GetNode(env)` doesn't do anything special with the offline flag).
While we could add some magic there to make this problem less common we could also just move more towards the CoreAPI. This PR attempts that latter.
Note: Draft one has only fixed Export, still need to do Import.
cc @ribasushi
> fix: ipfs dag export uses the CoreAPI and respects the offline flag

- core/commands/files.go
- core/commands/ls.go
- core/commands/unixfs/ls.go
Closes https://github.com/ipfs/ipfs-docs/issues/301
As mentioned in https://discuss.ipfs.io/t/why-is-ipfs-files-ls-being-deprecated/7881/9
> Clarify the differences between all the file APIs.

- .github/ISSUE_TEMPLATE/doc.md
Uses the correct URL for the documentation repo
> Update GitHub documentation issue template

- core/corehttp/p2p_proxy.go
- test/sharness/t0184-http-proxy-over-p2p.sh
Added a few checks to the p2p proxy to return errors to the client rather than just logging them on the daemon.
> More p2p proxy checks

- cmd/ipfs/daemon.go
- core/corehttp/metrics.go
- go.mod
- go.sum
- plugin/loader/preload.sh
This PR exposes OpenCensus metrics from go-ipfs to enable the collection and export of QUIC metrics. This was done on a separate port to the prometheus metrics as there were issues getting OC metrics into the prometheus registry. I have gotten it to work the other way but I can't seem to get to work this way. 
There is also a small fix to the plugin loading script.
> Register oc metrics

- .circleci/config.yml
The internal bin path for js-ipfs changed recently so a major bump to the interop tests was required, this PR updates to the new version.
> chore: update interop tests and js-ipfs version

- core/commands/add.go
- core/commands/cmdenv/env.go
- core/commands/cmdenv/env_test.go
- core/commands/dns.go
- core/commands/keystore.go
- core/commands/ls.go
- core/commands/mount_unix.go
- core/commands/name/publish.go
- core/commands/object/object.go
- core/commands/pin/remotepin.go
- core/commands/pubsub.go
- core/commands/unixfs/ls.go
- test/sharness/t0045-ls.sh
Replaces control characters and non-printable characters with escape sequences, in any fields that are printed by the CLI, which could have been user input.
Output from `ipfs cat` is unchanged.
> Escape non-printable characters in user output

- core/corehttp/hostname.go
- core/corehttp/hostname_test.go
- docs/config.md
- test/sharness/t0114-gateway-subdomains.sh
>  Closes https://github.com/ipfs/in-web-browsers/issues/169, Closes https://github.com/ipfs/in-web-browsers/issues/174
>  cc @aschmahmann  @autonome @gozala @gmasgras @mburns 
>  :point_right:  I marked this as P0 because we want `dweb.link` to run this patch  when support for `ipns://{dnslink-name}` resolution lands in Brave stable  (https://github.com/brave/brave-browser/issues/10220). Without it, onboarding will include the TLS error, which is really bad UX. Ideally, we would include this  in 0.8 (https://github.com/ipfs/go-ipfs/issues/7707).
This PR enables users of public gateways to load DNSlink websites without TLS error described in https://github.com/ipfs/in-web-browsers/issues/169.
It not only makes DNSLink websites more resilient, but makes it easier to resolve `ipns://` URIs …
> feat(gw): DNSLink names on https:// subdomains

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_test.go
- test/sharness/t0114-gateway-subdomains.sh
@lidel This PR attempts to close #7686 
---
This commit adds support for requests produced by navigator.registerProtocolHandler on gateways. Now one can register `dweb.link` as an URI handler for `ipfs://`:
```
navigator.registerProtocolHandler('ipfs', 'https://dweb.link/ipfs/?uri=%s', 'ipfs resolver')
```
Then opening `ipfs://QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR` will produce an HTTP GET call to:
```
https://dweb.link/ipfs?uri=ipfs%3A%2F%2FQmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR
```
The query parameter `uri` will now be parsed and the given content identifier resolved via:
`https://dweb.link/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`
--- 
Note: 
1. If the path parameter `ipfs` and scheme of the `uri` param value don't match we'll redirect to the `uri` param …
> feat(gw): URI router for Web API navigator.registerProtocolHandler

- core/commands/pin/remotepin.go
- test/sharness/t0700-remotepin.sh
> Closes #7824 cc @Gozala needed for 0.8.0 (#7707)
This PR ensures `ipfs pin remote service ls --enc=json`returns a valid JSON with an empty list, even when `Pinning.RemoteServices` is missing from the config (eg. right after `ipfs init`, before any services are added/removed)
```console
$ ipfs pin remote service ls --stat --enc=json
{"RemoteServices":[]}
```
> fix: remote services ls always return a list

- cmd/ipfs/pinmfs.go
- cmd/ipfs/pinmfs_test.go
- test/sharness/t0700-remotepin.sh
This is a refactor of #7798 that replaces the existing MFS root pin (if present) instead of creating a new pin.
- find by name all pre-existing pins across all Statuses (not just 'pinned')
- replace pre-existing pin (or create a new one if none found)
Without this we would be adding duplicate pins when pinning service
is still processing previous pin request (queued, pinning):
```
QmV6QnQNuyJFq88fSVVY9u5fxftQEKu6unsD62QpLQSefP  queued  policy/12D3KooWEcsoib3zFds4USH9bASPWBvJHRvfHYbxjR8QCHQ7y1vj/mfs
QmbnBveHJSqcqmVK8UE64riotVzMGirCKYE1SQLXcG25dT  queued  policy/12D3KooWEcsoib3zFds4USH9bASPWBvJHRvfHYbxjR8QCHQ7y1vj/mfs
Qmf1FHNVp74F4TGtNg1myXZgaV4ApwmYgC8iXcUX8cidDy  queued  policy/12D3KooWEcsoib3zFds4USH9bASPWBvJHRvfHYbxjR8QCHQ7y1vj/mfs
QmXnVAeJ9braE7ho7hdPqkmd9cB2ewKtzXNcFFFm3W32EA  queued …
```
> fix: replace pre-existing pins for MFS root

- core/commands/pin/remotepin.go
- go.mod
- go.sum
Allows for passing comma separated lists of CIDs and Statuses in `ipfs pin remote ls/rm` on the CLI without exposing that behavior over the HTTP API.
> pin remote commands are comma delimited on the CLI only

- core/commands/pin/remotepin.go
> Part of https://github.com/ipfs/go-ipfs/issues/7559 and https://github.com/ipfs/go-ipfs/issues/7707 closes #7825
This PR adds docs in form of a longer description that is displayed when `--help` is passed on the CLI.
Those are pretty important, as CLI crowd often does not read docs online, and prefer to explore features this way. 
While at it, unified some language to match fields in the config file and other places (thx @Gozala!) + included some tips and best practices which should improve onboarding experience.
@jessicaschilling this falls under our effort to improve onboarding: lmk if anything sounds awkward, or we could rephrase to make it even more intuitive.
cc @ipfs/wg-pinning-services 
Below are previews of the initial version of this PR:
<details>
<summary>Click to expand: ipfs …
> docs: improved --help for pin remote commands

- core/commands/pin/remotepin.go
- core/commands/pin/remotepin_test.go
- test/sharness/t0700-remotepin.sh
> Closes #7826 reported by @gozala, needed for 0.8.0 (#7707)
This PR adds URI normalization for HTTP-based remote pinning service endpoint and applies it:
1. before endpoint is stored in  `$IPFS_PATH/config` (when user adds via `pin remote service add`)
2. after endpoint is read from config (in case someone entered it up manually)
ps. alternative approach is to address this upstream in [go-pinning-service-http-client](https://github.com/ipfs/go-pinning-service-http-client), but by doing it in `pin remote` command code we ensure invalid/malformed URIs are not saved to the config file, which is a better UX.
> fix: normalize remote service endpoint

- core/commands/pin/remotepin.go
This adds clarification suggested in https://github.com/ipfs/go-ipfs/pull/7823#pullrequestreview-577889138
I believe it is enough to mention it in `pin remote ls` to avoid noise, but lmk  @aschmahmann @jessicaschilling
> docs: comma delimited options in pin remote --help

- cmd/ipfs/init.go
- core/commands/keystore.go
- test/sharness/t0165-keystore.sh
Fixes Issue #7814
ipfs key commands that open the repo directly will not work when another process has the repo open and locked.  For this reason these commands cannot run when the ipfs daemon is running, and an informative error message should be given to the user.
This is already done for the `ipfs key rotate` command, and should be done for other commands that directly open and lock the repo.  This PR applies the same PreRun check to these commands as is used for `ipfs key rotate`.
While unlikely, it is possible to see the error reported if another process opens the repo at the same moment.  In that case the "someone else has the lock" error is shown.
> Improve error message when running key command that locks repo

- peering/peering_test.go
This test takes a full minute to run, and I was honestly thinking my run
of "go test -v" had simply hung, as I saw no output and no apparent
resource usage.
The least we can do is print a few log messages before the potentially
long waits, to hint that we're still making progress. Each of these
"Eventually" and "Never" calls ends up blocking the test for a few
seconds at a time.
> peering: add logs before many-second waits

- go.sum
Fix minor build issue with go1.16:
```
../../../go/pkg/mod/github.com/ipfs/go-merkledag@v0.3.2/coding.go:8:2: missing go.sum entry for module providing package github.com/ipfs/go-block-format (imported by github.com/ipfs/go-ipld-format); to add:
go get github.com/ipfs/go-ipld-format@v0.2.0
```
Fixed by running `go mod tidy`
> Fix build issue with go1.16

- docs/config.md
This PR adds docs for `Pinning.RemoteServices.Policies` 
cc https://github.com/ipfs/go-ipfs/issues/7559 https://github.com/ipfs/ipfs-docs/pull/369 https://github.com/ipfs/ipfs-gui/issues/91
> docs: Pinning.RemoteServices.Policies.MFS

- docs/config.md
@aschmahmann  this PR fixes unfortunate typo due to additional negation and my lack of coffee I guess.
> docs: fix DNSLink gw recipe

- docs/config.md
As suggested by @aschmahmann  this moves debug top from release notes to config docs.
> docs: tips on debugging Policies.MFS

- bin/check_version
- mk/util.mk
Looks like darwin-386 is in the list of supported platforms still as of 0.8.0, which won't compile on go-1.15 and up. And now there's darwin-arm64 (native Apple M1) starting on Go 1.16
This PR set supported platforms correctly by go version (no darwin-386 for >=1.15, no darwin-arm64 unless >=1.16)
It also makes a change to check-version as \+ is interpreted literally for `expr` on several POSIX systems including Mac.
License: MIT
Signed-off-by: hannahhoward <hannah@hannahhoward.net>
> Set supported platforms by go-version

- .circleci/config.yml
- test/sharness/t0165-keystore.sh
1. We need netstat and sharness seems to silently fail when we don't have it.
2. `test_must_fail` still needs to go inside a `test_expect_success`.
> fix some sharness-in-CI issues

- test/sharness/t0275-cid-security.sh
It takes a number, not a duration. Unfortunately, it will _also_ exit with a status of 1 in this case so the test passes.
> test(sharness): pass correct timeout format to go-timeout

- core/commands/dag/dag.go
- core/commands/dag/export.go
- core/commands/dag/get.go
- core/commands/dag/import.go
- core/commands/dag/put.go
- core/commands/dag/resolve.go
- core/commands/dag/stat.go
This splits what previously was an ~800 line file into separate files for each of the 6 subcommands that are exposed by this portion of the API.
No functional code change. Just moving code into new files.
> split core/commands/dag into individual files for different subcommands

- cmd/ipfs/init.go
The InitializeKeyspace functionality is go-ipfs specific but lives in the
go-namesys repo.
It is only called from initializeIpnsKeyspace, and therefore the code is
directly added to this function. The original function will be removed from
go-namesys.
> Feat: Re-import InitializeKeyspace code from go-namesys

- core/corehttp/gateway_handler.go
- test/sharness/t0110-gateway.sh
This PR enables Gateways to recover from invalid paths like  `/ipfs/ipfs/{cid}`  and redirect them to proper one, when possible.
_raison d'être_  is to 
- smooth out unforeseen addressing issues during initial adoption, and fix cosmetic mistakes like the value in `image` tag [here](https://dweb.link/ipfs/bafybeien3m7mdn6imm425vc2s22erzyhbvk5n3ofzgikkhmdkh5cuqbpbq/metadata.json)  :cat2::rainbow_flag:  
-  make broken URIs resolve in Brave and Opera (because thats where most of people will paste those broken `ipfs://` URI to address bar)
- provide hint to developers on what should be fixed
cc @autonome
> feat(gw): /ipfs/ipfs/{cid} → /ipfs/{cid}

- docs/RELEASE_ISSUE_TEMPLATE.md
- docs/releases.md
1. All releases may contain unannounced security fixes.
2. By default, security fixes will not be backported.
> doc: document security fix policy

- core/coreapi/pin.go
When fetching all pins, the recursive pins are fetched from the pinner two times.  The second fetch is unnecessary and copies all recursive pins into a slice again.
Additionally, the output channel is now buffered.  This allows the goroutine to exit in the case the pinner returns an error and there is no reader for the output channel.  This might be possible if a canceled context causes the caller to abandon waiting to read the output of Ls().
> Do not fetch recursive pins from pinner unnecessarily

- README.md
> Fix text contrast for dark mode

- cmd/ipfs/daemon.go
- core/corehttp/gateway_handler.go
- docs/config.md
Context: https://github.com/ipfs/go-ipfs/issues/7702 and @Stebalien comments there 
This PR deprecates `Gateway.PathPrefixes` and `X-Ipfs-Gateway-Prefix` header:
- marks `Gateway.PathPrefixes` as deprecated in `docs/config.md`
-  logs error during startup if `Gateway.PathPrefixes` is used  (not empty)
- I went with log because it prints red ERROR that makes it hard to miss (but lmk if should be regular stderr instead):
> ![2021-03-20--01-05-06](https://user-images.githubusercontent.com/157609/111852739-67e1be00-8918-11eb-8671-437bec710c09.png)
> chore: deprecate Gateway.PathPrefixes

- README.md
- core/commands/add.go
- core/commands/config.go
- core/commands/dag/dag.go
- core/commands/files.go
- core/commands/id.go
- core/commands/keystore.go
- core/commands/name/ipnsps.go
- core/commands/object/diff.go
- core/commands/object/object.go
- core/commands/object/patch.go
- core/commands/p2p.go
- core/commands/pin/pin.go
- core/commands/root.go
- core/commands/shutdown.go
- core/commands/stat.go
- core/commands/stat_dht.go
- core/commands/tar.go
- core/commands/version.go
People fixed a bunch of style issues in https://docs.ipfs.io/reference/http/api/
Unfortunately, those API docs are generated from go-ipfs sources via https://github.com/ipfs/http-api-docs tool,  so it all gets lost when API docs for new version are re-generated.
This PR:
-  Re-applies manual fixes from https://docs.ipfs.io/reference/http/api/  to `--help` text in go-ipfs.
This way the next time http-api-docs are re-generated, those changes stay.
- Updates and reorders  operations on `ipfs --help`  to prioritize 'dag' and 'files' over legacy 'object'
Context: https://github.com/ipfs/go-ipfs/issues/7936
- Clarifies that `ipfs object` only works with `dag-pb` ([multiformats/table.csv#L42](https://github.com/multiformats/multicodec/blob/909e183da65818ecd1e672904980e53711da8780/table.csv#L42)) …
> docs: cosmetic fixes of help text

- core/corehttp/hostname.go
- docs/config.md
- test/sharness/t0114-gateway-subdomains.sh
This PR removes use of buggy  `Clear-Site-Data` header and solves issue with Firefox: https://github.com/ipfs-shipyard/ipfs-companion/issues/977 
(Chromium browsers are not impacted, but they also barely support this header)
-  Opening https://dweb.link/ipns/en.wikipedia-on-ipfs.org returns  `Clear-Site-Data` header and in Firefox it clears cookies before redirecting to  https://en-wikipedia--on--ipfs-org.ipns.dweb.link (afaik it should ignore the header on redirects, but that is not the case in Firefox 84)
- `Clear-Site-Data` support across vendors  is buggy in general, and  that is not just Firefox
- This PR removes `Clear-Site-Data` from the path-based router, fixing Firefox issue described in https://github.com/ipfs-shipyard/ipfs-companion/issues/977  
We used `Clear-Site-Data` as a …
> fix(gw): remove use of Clear-Site-Data in subdomain router

- go.mod
- go.sum
The new version has an improved resolve error and fixes #8000 
Changelog: https://github.com/ipfs/go-namesys/releases/tag/v0.1.1
> go-namesys v0.1.1

- bin/push-docker-tags.sh
- add guard for rc releases; publish them to docker hub with the matching git tag
- make the semver regex stricter and only publish as latest when a full semver tag with no pre-release suffix is the name of the git tag.
- add `release` tag as an alias of `latest` as per https://github.com/ipfs/go-ipfs/issues/3999#issuecomment-742228981
Tested manually as the push-docker-tag.sh script is set up for it:
```shell
./push-docker-tags.sh $(date -u +%F) testingsha release v0.9.0-test dry
Nothing to do. No docker tag defined for branch: release, tag: v0.9.0-test
./push-docker-tags.sh $(date -u +%F) testingsha release v0.9.0-rc1 dry
DRY RUN! I would have tagged and pushed the following...
docker tag ipfs/go-ipfs:wip ipfs/go-ipfs:v0.9.0-rc1
docker push ipfs/go-ipfs:v0.9.0-rc1
./push-docker-tags.sh …
```
> chore: dont docker tag rc as latest

- core/commands/root.go
* move the `cid` command to the "datastructures" section.
* document bitswap & pubsub commands
fixes #8047
> fix: update root help

- core/corehttp/hostname.go
This PR closes #7317 by removing hard-coded PL hostnames from the default config, making the localhost the only implicit gateway hostname defined out-of-the-box.
@mburns to double-check if `dweb.link` uses explicit [`Gateway.PublicGateways`](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#gatewaypublicgateways-usesubdomains) config so it is not impacted by this change.
> fix(gw): remove hardcoded hostnames

- repo/fsrepo/migrations/migrations.go
- repo/fsrepo/migrations/migrations_test.go
Migrations were logging to a mix of stdout and stderr.  This was due to the individual migration binaries logging non-error output to stdout, while the migration library (which downloads and executed these migrations) was logging to stderr.  This inconsistency can be confusing.  Also, previous versions of go-ipfs wrote non-error output to stdout. This PR fixes this so that non-error output from the migrations library is written to stdout.
- Do not use global logger
- Added test to look for expected log output.
Note to reviewers: This change does not affect sharness tests in PR #8053
> Make migrations log output to stdout

- test/sharness/t0066-migration.sh
With the new migrations, go-ipfs no longer uses `fs-repo-migrations` to do repo migrations, and was downloading real migration binaries from the network and running them.  This caused failure, but was not caught because the test was expecting `ipfs daemon --migrate` to fail for other reasons.
This PR fixes the migration tests by creating the appropriate fake migration binaries in the `PATH` so that those are run instead of downloading the real ones.  This also fixes a test that was previously marked broken.
> Update migration sharness tests for new migrations

- bin/mkreleaselog
We can now handle v2 modules that use tags, but not v2 modules that use
v2 sub-directories.
> fix(mkreleaselog): partially handle v2 modules

- misc/systemd/ipfs-hardened.service
- misc/systemd/ipfs.service
fixes #7269
fixes #8034
fixes #6741
> fix: set systemd startup timeout to infinity

- test/sharness/t0275-cid-security.sh
Fix broken sharness in ipld-in-ipfs branch
The test was failing cause it was using murmer3-128 as an insecure hash function, which has been removed from go-multihash 0.15. (meaning it produces a different "unknown hash function" error). I switched to shake-128 which repeduces the correct error.
> Switch insecure hash function sharness test

- core/commands/pin/pin.go
Otherwise, we get messages of the form `{Pins: null, Progress: 100}`. After this change, we'll get `{Progress: 100}`.
> fix: omit empty pins slice when reporting pin progress

- README.md
- core/commands/object/object.go
- core/commands/object/patch.go
- core/commands/root.go
Part of https://github.com/ipfs/go-ipfs/issues/7936
This PR makes it very explicit that `ipfs object` commands are deprecated:
- removes it from `ipfs --help` so it is not even a thing new CLI users see
- removes CLI examples from `ipfs object --help` text for each command, and points at modern replacement under `ipfs dag` and/or `ipfs files` (where possible)
- taglines are longer and include alternatives because [ipfs/http-api-docs](https://github.com/ipfs/http-api-docs) reuses them on: https://docs.ipfs.io/reference/http/api/
> docs: deprecate object commands

- core/corehttp/webui.go
> chore: update webui to 2.12.2

- core/commands/commands_test.go
- core/commands/root.go
- test/sharness/t0110-gateway.sh
- add dag/export to read-only root. it's ready only, so why the heck not!
- test that i didn't expose other dag subcommands
License: MIT
> feat(gw): expose /api/v0/dag/export on gateway port

- core/commands/keystore.go
- test/sharness/t0165-keystore.sh
This PR enables apps like Brave browser to do import/export without stopping/starting daemon.
Export does not require repo lock, and afaik it is safe to do even when ipfs daemon is running. 
Ref. https://github.com/brave/brave-browser/issues/15422 (cc @spylogsster)
> feat: allow key export in online mode

- .circleci/config.yml
- Dockerfile
- README.md
- go.mod
- mk/golang.mk
bumping minimum version to 1.15 to indicate we are no longer explicitly supporting 1.14, and bumping CI testing to use 1.15.
> chore: bump minimum go version to 1.15

- .circleci/config.yml
12 is no longer supported, latest js-ipfs requires 14 (current LTS)
https://blog.ipfs.io/2021-05-11-js-ipfs-0-55/
> chore: switch CI to nodejs 14.x 

- core/corehttp/hostname.go
- core/corehttp/hostname_test.go
- go.mod
- go.sum
Closes #8060
I switched `IsDomain()` from `jbenet/go-is-domain`  to `IsDomainName` from `github.com/miekg/dns` as suggested.
I had to change one of the tests for everything to pass. This may be an error on my side. However, I could not understand why `http://k51qzi5uqu5di608geewp3nqkg0bpujoasmka7ftkyxgcm3fh1aroup0gsdrna.ipns.localhost/` was expected?
> feat: support DNSLink on non-ICANN DNS names

- core/commands/commands_test.go
- core/commands/stat.go
- core/commands/stat_provide.go
- core/node/groups.go
- core/node/provider.go
- docs/experimental-features.md
- go.mod
- go.sum
Adds an experimental provider system that makes use of the experimental dht client.
Depends on https://github.com/ipfs/go-ipfs-provider/pull/34, links to #8061 
The point of this system is to be able to quickly provide by being sympathetic to how Kademlia works. For the time being it tries to get records into the DHT very quickly at the expense of having a spike in resource usage during that time.
It also comes with a few extras that have been added for sanity purposes during testing/evaluation and that may be useful in production including:
- A stat command to track how many provider records we are emitting (only for the experimental system)
- Tracking when we last provided our records so that rebooting the node doesn't cause us to automatically start reproviding unless we need to
> experimental provider system

- core/commands/commands_test.go
- core/commands/dht.go
- core/commands/stat.go
- core/commands/stat_dht.go
- core/commands/stat_provide.go
- core/core.go
- core/node/groups.go
- core/node/libp2p/host.go
- core/node/libp2p/routing.go
- core/node/libp2p/routingopt.go
- core/node/provider.go
- docs/experimental-features.md
- go.mod
- go.sum
This feature enables an option for an experimental DHT client that makes a few key optimizations over the standard client.
1. It periodically crawls the network to find all the peers and then finds the closest peers to the target in Kademlia space based on the local list of peers
2. It does not wait on all peers from a given query to return, but instead tries to guess when we'll be done hearing from peers and instead be waiting on timeouts.
- The current metric is to wait for some percentage (30%) of the closest bucket-size (i.e. 20) peers to return and then wait for some dead time (a few hundred ms) where no new responses come in
Depends on:
A couple quirks about the current state of this PR and the client:
- I've manually set the experimental option to always on for debugging purposes …
> Experimental dht client

- peering/peering_test.go
This PR is intended to correct the test for `peering.PeeringService`.
The current master code tests that `h1` is connected to `h2` on L69.
I have modified it to check `h3`.  
This test appeared to be intended to test that `host.Connect` is working correctly after the PeeringService has been started.
```
// h1 is now connected to h2 and h4
h1 -> [h2, h4]
// then explicitly connect to h3 
h1 -> [h2, h4, h3]
// now we want to test is h3
h1 -> h3
```
This is the first time I'm commiting to this repository. Please point it out if this PR breaks any conventions.
I've read and respect [CONTRIBUTING.md](https://github.com/ipfs/community/blob/master/CONTRIBUTING.md) and [CONTRIBUTING_GO](https://github.com/ipfs/community/blob/master/CONTRIBUTING_GO.md). Thank you.
> fix(peering_test) : Fix the peering_test to check the connection explicitly added

- cmd/ipfs/pinmfs.go
- cmd/ipfs/pinmfs_test.go
Add an error log message to `remotepinning/mfs`, in case a pin request failed.
> Note from @lidel: this gets us closer to  addressing https://github.com/ipfs/go-ipfs/issues/7917  by adding error logging on node start, but proper fix requires a larger refactor in a separate PR.
> refactor(pinmfs): log error if pre-existing pin failed

- core/corehttp/webui.go
This PR bumps ipfs-webui to the bugfix release based on feedback from 0.9.0-rc1:
https://github.com/ipfs/ipfs-webui/releases/tag/v2.12.3
@aschmahmann fixed bugs are pretty annoying, so we really should include this in 0.9.0-rc2 (https://github.com/ipfs/go-ipfs/issues/8058) :)
> fix: webui-2.12.3

- core/commands/stat_provide.go
This adds a text output encoding to the `ipfs stats provide` command for easier glance value
It looks something like:
```
❯ ipfs stats provide
TotalProvides: 7084
AvgProvideDuration: 15.358954ms
LastReprovideDuration: 58.3776802s
LastReprovideBatchSize: 3542
```
It could be a little prettier, but here's a first stab so at least we have something.
> feat: add a text output encoding for the stats provide command

- go.mod
- go.sum
@Stebalien is this required to resolve https://github.com/libp2p/go-libp2p-yamux/issues/36 until a new version of go-libp2p is released?
> chore: manually add later version of go-yamux

- cmd/ipfs/pinmfs.go
- cmd/ipfs/pinmfs_test.go
- core/commands/stat_provide.go
- core/corehttp/webui.go
- go.mod
- go.sum
- version.go
> v0.9.0 rc2

- cmd/ipfs/daemon.go
This PR fixes the typo reported in https://github.com/brave/brave-browser/issues/16128 :)
> fix: typo in migration error

- cmd/ipfs/daemon.go
This PR aims to improve UX when bootstrap fails.
It will print ERROR to log if daemon running in online mode has no peers after one minute since start:
```console 
$ ipfs daemon
...
Daemon is ready
2021-05-31T15:28:34.403+0200	ERROR	cmd/ipfs	ipfs/daemon.go:527	failed to bootstrap (no peers found): consider updating Bootstrap or Peering section of your config
```
> feat: print error on bootstrap failure

- bin/mkreleaselog
At commit 0, there is no parent.
> fix(mkreleaselog): handle commit 0

- bin/mkreleaselog
This will output one entry per commit author in the "stat" log, instead of just crashing.
> fix(mkreleaselog): support multiple commit authors

- core/commands/pin/remotepin.go
Closes #7915. When running `ipfs pin remote add <cid>`,
1. If CID isn't in blockstore, local node isn't origin, so send `Pin.origins = []`
2. <del>If address is loopback, remove address from `Pin.origins`</del>
3. <del>If address is in [`NoAnnounce`](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#addressesnoannounce), remove address from `Pin.origins`</del>
> Improve peer hints for pin remote add

- README.md
- Remove ipn.io link...
- Remove chat "badges" and replace with a single link.
- Remove reference to weekly meetings that no longer exist.
fixes #8190
> doc(README): update chat links (and misc fixes)

- core/corehttp/webui.go
RELEASE NOTES: https://github.com/ipfs/ipfs-webui/releases/tag/v2.12.4
@aschmahmann this is a bugfix release, if you plan to ship 0.9.1 this should be included in it – it fixes a bunch of UX issues identified in Brave
> feat: webui v2.12.4

- test/sharness/t0055-dag-put-json-new-line.sh
Write a `sharness` test that expects failure documenting the issue
raised in #3503. The issue may get resolved in the refactoring of
`ipfs dag get` command to support go-ipld-prime (e.g. #8171). For now
add a `sharness` test that expects failure. We will then flip the
expectation to success in the rewriting PR to check if #3503 gets
resolved.
Relates to:
- https://github.com/ipfs/go-ipfs/issues/3503
> Add test with expected failure for #3503

- go.mod
- go.sum
- test/sharness/t0053-dag.sh
- test/sharness/t0275-cid-security.sh
Pending https://github.com/ipld/go-ipld-prime/pull/202 and https://github.com/ipld/go-ipld-prime/pull/203
* I've massaged one of the main fixtures so that it's pre-sorted according to DAG-CBOR rules since go-ipld-prime as yet doesn't apply any sorting, I didn't want to treat that as a blocker for this PR but it may have to be treated as a blocker for release (similar change to https://github.com/ipld/go-ipld-prime/pull/203, but there's deep background here ... cans of worms).
* `dag get` doesn't print a newline now, which I think is the right behaviour since it can now do any codec and newlines are going to be a problem for the stricter binary formats than dag-json, so I've adapted the fixtures.
* The proper DAG-PB `Data` / `Links` changes show up here and are now correct, as are the new …
> fix dag test fixtures for go-ipld-prime codecs

- bin/mkreleaselog
1. Allow matching the entire module instead of just github orgs/usernames.
2. Allow excluding some modules.
3. Ignore files using a github pathspec and apply the same ignore patterns to the "contributors" section.
> feat: improve mkreleaslog

- core/commands/commands_test.go
- core/commands/diag.go
- core/commands/profile.go
- core/commands/sysdiag.go
- core/commands/version.go
- docs/debug-guide.md
- test/sharness/lib/test-lib.sh
- test/sharness/t0152-profile.sh
This should replace the "collect-profiles.sh" script and allow users to easily collect profiles.
Usage: `ipfs diag profile` or `ipfs diag profile -o my-profile.zip`.
At the moment, it just dumps all profiles into a single zip file. It does this server-side so it's easy fetch them with curl.
In the future, it would be nice to add:
1. Progress indicators (cpu profiles take 30 seconds).
2. An option to specify which profiles to collect.
But we can handle that later.
Unfortunately, this command doesn't produce symbolized svgs as I didn't want to depend on having a local go compiler.
> feat: add an "ipfs diag profile" command

- .circleci/config.yml
- test/sharness/t0700-remotepin.sh
DOCKER_HOST is a special environment variable of the Docker CLI
so there's risk of creating conflicts whenever attempting to use `docker`
in the test suite; it also makes it difficult to run the same full suite
locally using the same setup since DOCKER_HOST is a fixed variable in
t0700-remotepin.sh
> Rename DOCKER_HOST to TEST_DOCKER_HOST to avoid conflicts

- core/commands/dag/dag.go
- core/commands/dag/put.go
- go.mod
- go.sum
- plugin/plugins/git/git.go
- test/sharness/t0051-object.sh
- test/sharness/t0280-plugin-git.sh
@mvdan this extends your last commit to the branch to do `mh.Set()` for `hash` as well.
It also revives t0280 for the git-plugin. The diff with master is the most interesting bit now:
```diff
diff --git a/test/sharness/t0280-plugin-git.sh b/test/sharness/t0280-plugin-git.sh
index e7bc06427..d90df46bc 100755
--- a/test/sharness/t0280-plugin-git.sh
+++ b/test/sharness/t0280-plugin-git.sh
@@ -17,7 +17,7 @@ test_expect_success "prepare test data" '
test_dag_git() {
test_expect_success "add objects via dag put" '
-    find objects -type f -exec ipfs dag put --format=git --input-enc=zlib {} \; -exec echo \; > hashes
+    find objects -type f -exec ipfs dag put --format=git-raw --input-enc=3145848 --hash=sha1 {} \; -exec echo -n \; > hashes
'
test_expect_success "successfully get added objects" …
```
> (ipld-prime) Use mh.Set() for "hash" -> mhType & Make git plugin test work again

- test/sharness/lib/test-lib.sh
- test/sharness/t0023-shutdown.sh
- test/sharness/t0040-add-and-cat.sh
- test/sharness/t0045-ls.sh
- test/sharness/t0061-daemon-opts.sh
- test/sharness/t0080-repo.sh
- test/sharness/t0081-repo-pinning.sh
- test/sharness/t0085-pins.sh
- test/sharness/t0087-repo-robust-gc.sh
- test/sharness/t0095-refs.sh
- test/sharness/t0100-name.sh
- test/sharness/t0114-gateway-subdomains.sh
- test/sharness/t0115-gateway-dir-listing.sh
- test/sharness/t0250-files-api.sh
- test/sharness/t0271-filestore-utils.sh
- test/sharness/t0272-urlstore.sh
- test/sharness/t0600-issues-and-regressions-online.sh
In connection with #8131.
_Does not have any change in logic, just naming. The commits should be reviewed separately; we can drop the second one if too invasive._
Do not use online/offline naming system when starting the daemon in tests but the more specific "with network".
Particularly in the files tests (`t0250`) the online/offline names were _also_ being used to signal if the daemon was running or not. They were even used what appears to be incorrectly as `"online"` meant `"no-daemon"` (now renamed as such) so the internal logic of `tests_for_files_api` should be reviewed (left a `FIXME` note for that).
> Disambiguate online/offline naming in sharness tests

- README.md
This is only a docs update.
We use go-ipfs name now, to make it clear that it is not ipfs-desktop.
> docs: chocolatey package name

- core/corehttp/gateway_handler.go
- core/corehttp/metrics.go
This is an important performance metric that PL uses for gateway monitoring, so enabling it by default.
This is cherry-picked from 44fcc1558a65de37cbc74fd383cedfc6f29979fd
> feat: register first block metric by default

- docs/environment-variables.md
- repo/fsrepo/migrations/fetcher.go
This PR updates go-ipfs to use signed migrations on macOS.
Uses: https://github.com/ipfs/fs-repo-migrations/releases/tag/v2.0.2 signed in https://github.com/ipfs/distributions/pull/381
Closes #8240
cc @autonome @bbondy @spylogsster  – fysa the plan is for this to land in go-ipfs 0.10
All good,  confirmed this works as expected in Brave (without fs-repo-10-to-11 signed by Brave):
> ![vtQC6sJ](https://user-images.githubusercontent.com/157609/128773383-11e359c6-d104-48c9-9631-776a66f28ee8.png)
> ![wfCj33T](https://user-images.githubusercontent.com/157609/128773451-cecc48d4-2629-478a-ab4c-46963984c43b.png)
`IPFS_DIST_PATH=/ipfs/QmP7tLxzhLU1KauTRX3jkVkF93pCv4skcceyUYMhf4AKJR` works fine:
> ![XS2BOv6](https://user-images.githubusercontent.com/157609/128772043-4a16cac9-72d0-4c66-9b0a-9353542e608a …
> fix: macos notarized fs-repo-migrations

- core/core.go
The current type of `IpfsNode.Peering` is `PeeringService`.
It is different from the type `*PeeringService` returned from `node.Peering` provided in core/node/groups.go:270 .
This difference prevents fx from injecting `IpfsNode.Peering`.
The current `node.PeeringService` on the daemon is a zero value.
I also cannot get the valid `PeeringService` on `SwarmAddCommand` in  https://github.com/ipfs/go-ipfs/pull/8147 due to this problem.
I propose to fix the type of `IpfsNode.PeeringService` from `PeeringService` to `*PeeringService`.
> Fix: Use a pointer type on IpfsNode.Peering

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_indexPage.go
The panic is caught higher up the stack so it can't crash the node, but it's still "not good".
> fix: avoid out of bounds error when rendering short hashes

- core/node/bitswap.go
- core/node/core.go
This PR is against  https://github.com/ipfs/go-ipfs/pull/8268  for easier review:
-  extracts bitswap init to separate file and defines implicit defaults as consts
- fixes a typo where BitswapTaskWorkerCount was 128 (instead of 8 ) and BitswapEngineBlockstoreWorkerCount was 8 (instead of 128)
> refactor: core/node/bitswap.go

- .circleci/config.yml
followup to https://github.com/ipfs/go-ipfs/pull/8324, missed the 1.16.6 -> 1.16.7 change in the CircliCI config
> ci: use Go 1.16.7 in .circleci/config.yml

- bin/mkreleaselog
Specifically, if you specify a commit, you get only that commit. This means you get _nothing_ if you specify a merge commit.
Now, we specify to diff between a commit and it's (merge) parent.
> fix(mkreleaselog): specify the parent commit when diffing

- README.md
- added dynamic buttons for packages/downloads which shows the latest version where possible
- dynamic next milestone buttons
- reordered to have package managers and docker on top, manual downloads afterwards
- remove the docker and the cli section, since they are covered equally in the docs + button links
- added more sections to the navigation, to find stuff easier
- dynamic go requirement version button
- some social media buttons
- general cleanup
> add more buttons; remove some sections covered in the docs; general cleanup

- .circleci/main.yml
This was accidentally bumped up, but it doesn't need to be and slows
things down rather than helps.
> ci: drop unit tests make jobs back to 1

- cmd/ipfs/daemon.go
- core/commands/id.go
- core/corehttp/gateway.go
- core/corehttp/gateway_test.go
- core/node/libp2p/libp2p.go
- test/sharness/t0026-id.sh
- version.go
Preliminary design for feedback to add the option storing it inside the `IpfsNode` structure.
(Test and minor fixes will follow after this design is validated.)
Closes https://github.com/ipfs/go-ipfs/issues/7898.
> feat(cli): add daemon option --agent-version-suffix

- core/corehttp/webui.go
Release Notes: https://github.com/ipfs/ipfs-webui/releases/tag/v2.13.0
It already shipped with ipfs-desktop [v0.16.3](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.16.3)
> feat: ipfs-webui v2.13.0

- core/commands/dag/dag.go
- core/commands/dag/import.go
- test/sharness/lib/test-lib.sh
- test/sharness/t0041-ping.sh
- test/sharness/t0054-dag-car-import-export.sh
I'm just taking a stab at this and am unsure if I'm following the right pattern here so feedback would be appreciated.
Currently `dag import` only reports pinned CIDs and an error on pinning. If you `pin-roots=false` then you get nothing. I'm working on the JS version of this, including the HTTP client, and I'd really like to get a bit more information out of this process. The minimum I think is simply a report of how many blocks were imported (although in the current form it's not counting unique blocks, just total processed blocks).
So we end up with this slightly awkward event: `{BlockCount:uint64, Root:*RootMeta}` - where the first one is expected to be `Root==nil` and `BlockCount` telling you how many blocks, and any remaining should have `Root!=nil` and reporting pin status if you …
> feat: dag import --stats (#8237)

- core/coreapi/test/path_test.go
- docs/examples/go-ipfs-as-a-library/go.sum
- go.mod
- go.sum
https://github.com/ipfs/go-path/pull/44
> chore: update go-path

- core/commands/dag/dag.go
- core/commands/dag/put.go
- test/sharness/t0053-dag.sh
- test/sharness/t0055-dag-put-json-new-line.sh
- test/sharness/t0280-plugin-git.sh
> change names of ipfs dag put flags to make changes clearer

- core/commands/dag/dag.go
- core/commands/dag/get.go
- test/sharness/t0053-dag.sh
Change `ipfs dag get --format` to `ipfs dag get --output-codec` to be closer to https://github.com/ipfs/go-ipfs/pull/8439.
TODO: Merge to master after #8439
> change ipfs dag get flag name from format to output-codec

- core/node/libp2p/discovery.go
- docs/examples/go-ipfs-as-a-library/go.sum
- go.sum
Looks like we forgot to enable our old (now legacy) mDNS implementation when we merged the update to go-libp2p v0.15.
> enable the legacy mDNS implementation

- core/commands/object/patch.go
- test/sharness/t0051-object.sh
Trying not to be too invasive as this is just an ad-hoc check for a deprected command I have added the check at the CLI level; otherwise I can go deeper in the `ObjectAPI`.
If the placement of the check is correct will add a test as a sharness. If instead the check should go deeper in the stack then the test should likely be written in Go. Waiting on an initial review to decide course.
Optional additional proposals to the current PR:
* Add the same check for the (less common) `set-data` and `append-data` commands which can potentially go over the BS limit just as well.
* Add the check to `rm-link` _but only as a warning_ to flag if the current block being manipulated is already over the limit.
Fixes https://github.com/ipfs/go-ipfs/issues/7421.
> fix(cli): object add-link: do not allow blocks over BS limit

- .circleci/config.yml
- .circleci/main.yml
When the config was wrapped in a continuation so that params could be
dynamically generated, this broke tag workflows since there was no
explicit tag filter anymore in config.yml. This attempts to fix that.
I may have gotten this wrong, since this is intrinsically hard to
test. We'll see next time we tag something.
> ci: trigger continuation on tags

- .circleci/main.yml
- .github/workflows/docker-image.yml
- bin/push-docker-tags.sh
This PR aims to close #8330 and unblock 0.10.0-rc2
- using temporary credentials for testing, need to switch to ones from `ipfsbot` but we can do that later this week
> ci: move Docker image build to Actions

- core/corehttp/metrics_test.go
Attempting to address https://github.com/ipfs/go-ipfs/issues/8135.
It unclear why in unsuccessful tests, we observe two transport types and what they are, so we are logging this now to see what is going on.
> add more logging to TestPeersTotal

- docs/examples/go-ipfs-as-a-library/go.mod
- docs/examples/go-ipfs-as-a-library/go.sum
- go.mod
- go.sum
This PR bubbles up go-ipfs-files release with some fixes for open issues in this repo.
Release Notes: https://github.com/ipfs/go-ipfs-files/releases/tag/v0.0.9
Closes #8445  – @aschmahmann iiuc this is unblocking support for go1.17  (or is there another blocker?)
Closes #8406
> chore: go-ipfs-files v0.0.9

- core/commands/files.go
- test/sharness/t0250-files-api.sh
#8395
Now it removes all the listed files or directories:
```
root@cc7fe284ba6d:/go-ipfs# ./ipfs files ls
bar
foo
tmp
root@cc7fe284ba6d:/go-ipfs# ./ipfs files rm -r /foo /bar
root@cc7fe284ba6d:/go-ipfs# ./ipfs files ls
tmp
root@cc7fe284ba6d:/go-ipfs#
```
In case if it can't remove some of files -- the behavior is similar to unix `rm` -- we `Emit` an error about specific file and continue.
```
root@cc7fe284ba6d:/go-ipfs# ./ipfs files ls
bar
foo
tmp
root@cc7fe284ba6d:/go-ipfs# ./ipfs files rm -r /foo /wrong /bar /wrong2/test
"/wrong: file does not exist"
"/wrong2/test: parent lookup: file does not exist"
Error: can't remove some files
root@cc7fe284ba6d:/go-ipfs# ./ipfs files ls
tmp
root@cc7fe284ba6d:/go-ipfs#
```
> Add support for multiple files to `ipfs files rm`.

- test/sharness/t0250-files-api.sh
- test/sharness/t0260-sharding.sh
Merge sharness tests from https://github.com/ipfs/go-ipfs/pull/8114 into https://github.com/ipfs/go-ipfs/pull/8527.
Closes https://github.com/ipfs/go-ipfs/pull/8114.
> Add automatic sharding/unsharding tests

- core/corehttp/hostname.go
- core/corehttp/hostname_test.go
Having multiple gateways on the same domain currently results in the subdomain returning 404.
For example, with two gateways (gateway.example.com and dev.gateway.example.com), dev.gateway.example.com would return 404 rather than functioning as a separate gateway.
> fix: multiple subdomain gateways on same domain

- cmd/ipfs/daemon.go
- docs/environment-variables.md
This PR ensures hard deprecation.
`IPFS_REUSEPORT=false ipfs daemon`  refuses to start:
```
Daemon is ready
2021-11-23T20:49:02.160+0100	FATAL	cmd/ipfs	ipfs/daemon.go:567	Support for IPFS_REUSEPORT was removed. Use LIBP2P_TCP_REUSEPORT instead.
```
> feat: hard deprecation of IPFS_REUSEPORT

- cmd/ipfs/daemon.go
- docs/config.md
- docs/experimental-features.md
- test/sharness/t0183-namesys-pubsub.sh
- test/sharness/t0320-pubsub.sh
Depends on https://github.com/ipfs/go-ipfs-config/pull/145
> feat: enabling pubsub and ipns-pubsub via config flags

- core/node/groups.go
- core/node/libp2p/relay.go
- docs/config.md
This PR won't build. It needs rebasing once #8522 or https://github.com/ipfs/go-ipfs/pull/8563 is merged.
Opening it now so we don't forget it for the v0.11 release.
> feat: Swarm.EnableHolePunching flag

- core/corehttp/metrics.go
- core/corehttp/metrics_test.go
Following upstream fix in https://github.com/libp2p/go-libp2p-swarm/commit/0538806be79cf321e79253cecaec8c9b0d2a7167.
Fixes https://github.com/ipfs/go-ipfs/issues/8135.
> fix(corehttp): adjust peer counting metrics

- core/corehttp/metrics.go
- core/corehttp/metrics_test.go
- go.mod
- go.sum
- version.go
1) Rebase + merge when ready
2) After the merge tag v0.11.0-rc2 on the `release-v0.11.0` branch and push the tag
> v0.11.0 rc2

- .github/workflows/sync-release-assets.yml
This is a quick fix for #8494  
- `tar.gz`s got mangled because of reasons known to github and nodejs (had no bandwidth to dig why)
- this does the correct upload every time by reading file as Buffer and forcing github to interpret payload as an opaque stream of bytes of a known length without anything fancy – makes this as future-proof as possible
- I confirmed this fix works in https://github.com/libp2p/go-libp2p-relay-daemon/releases/tag/v0.1.0  (reuploaded `_linux-amd64.tar.gz` was the same as on dist.ipfs.io)
> fix(ci): dist.ipfs.io sync preserving binaries

- CHANGELOG.md
- go.mod
- go.sum
- version.go
- Note: We tag on the `release` branch rather than the `release-v0.11.0` branch
- Let's rebase + merge when this is ready
> Ready for Release v0.11.0

- .circleci/main.yml
- Dockerfile
Waiting on https://github.com/CircleCI-Public/cimg-go/pull/142
> chore: bump Go version to 1.16.12

- .github/workflows/sync-release-assets.yml
I want to replace the ipfs build, init and ipfs daemon start logic here with common actions(https://github.com/ipfs/download-ipfs-distribution-action + https://github.com/ipfs/start-ipfs-daemon-action) to minimise duplication. This is part of work related to this issue: https://github.com/ipfs/go-ipfs/issues/8511
The new logic replaces ipfs build logic with downloading latest stable(non rc) release of go-ipfs from dist.ipfs.io.
> chore: use common ipfs/*-actions in sync-release-assets

- .circleci/main.yml
Ref. https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/CHANGELOG.md#0610-2021-12-15
This PR aims to restore interop running using release versions:
> test: restore ipfs-interop

- .circleci/main.yml
`parallelism: 4` on circleci broke when require got replaced with modern import statement in [ipfs-interop//test/node.js](https://github.com/ipfs/interop/blob/v8.0.0/test/node.js)
Since then, CI run all tests four times.. every time, taking more than it should :upside_down_face: 
This fix also makes the split smarter – based on timing of previous runs: https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-by-timing-data which should shave some time, if some files take way longer than others.
> fix(ci): interop test parallelism

- docs/config.md
This PR updates docs with current status of badger, 
which  should fix the issue of users thinking badger is "no-brainer faster choice for repos bigger than 10GB"
...and then running into problems.
> docs: badger in config.md

- core/commands/id.go
- test/sharness/t0026-id.sh
Closes https://github.com/ipfs/go-ipfs/issues/8481.
> feat(cmds): ipfs id: support --offline option

- core/node/dns.go
- docs/config.md
- go.mod
- go.sum
Expose `WithMaxCacheTTL` option of go-doh-resolver within IPFS node config.
This allows to cap the Time-To-Live suggested by the DNS response. This includes resolution of DNSLink captured by the custom resolver URLs.
This change relies on [go-ipfs.config](https://github.com/ipfs/go-ipfs-config/pull/161) change. The change of go.mod and go.sum would have to be updated accordingly at this time.
Before merging, both go-doh-resolver and go-ipfs-config have to be updated.
Tagging @vyzo and @marten-seemann , as they reviewed the [go-doh-resolver change](https://github.com/libp2p/go-doh-resolver/pull/12).
> feat: DNS.MaxCacheTTL for DNS-over-HTTPS resolvers

- repo/fsrepo/migrations/fetcher.go
This is to make it easier to understand why the multifetcher is falling back to a different fetcher.
Example output from unit test:
```
Fetching with HTTP: "bad-url/ipns/dist.ipfs.io/versions"
Error fetching: http.DefaultClient.Do error: Get "bad-url/ipns/dist.ipfs.io/versions": unsupported protocol scheme ""
Fetching with HTTP: "http://127.0.0.1:33923/ipns/dist.ipfs.io/versions"
```
> feat: log multifetcher errors

- repo/fsrepo/migrations/fetch.go
- repo/fsrepo/migrations/fetch_test.go
- repo/fsrepo/migrations/fetcher.go
- repo/fsrepo/migrations/httpfetcher.go
- repo/fsrepo/migrations/ipfsfetcher/ipfsfetcher.go
- repo/fsrepo/migrations/ipfsfetcher/ipfsfetcher_test.go
- repo/fsrepo/migrations/migrations.go
- repo/fsrepo/migrations/migrations_test.go
- repo/fsrepo/migrations/retryfetcher.go
- repo/fsrepo/migrations/versions.go
> feat: refactor Fetcher interface used for downloading migrations

- .circleci/main.yml
I noticed `gobuild` takes nearly as much time as sharness.
This PR runs `gobuild` job with more vCPUs (20 instead of 3) and shaves off some time (~5m instead of ~11m, both with cache) without  the need for rewriting logic behind `make cmd/ipfs-try-build`
> fix(ci): faster gobuild job

- .github/workflows/docker-image.yml
- bin/get-docker-tags.sh
Use docker/build-push-action to build Docker images for multiple cpu architectures
Close: #4931
Close: #8614
> docker: build for arm cpu

- core/corehttp/gateway_handler.go
- docs/gateway.md
This PR tries to solve this issue https://github.com/ipfs/go-ipfs/issues/7873 
Please let me know if my approach is ok with the code and the issue.
Thanks!
> chore(gateway): debug logging for the http requests

- core/commands/pin/remotepin.go
- test/sharness/t0700-remotepin.sh
Resolves #8418 
The warning is printed only when being online matters (if CID to be pinned remotely is in a local store)
> feat: warn user when 'pin remote add' while offline

- core/commands/files.go
Simplify `ipfs rm` command logic by extracting it into a separate function instead of having a giant loop.
This PR is actually needed for https://github.com/ipfs/go-ipfs/pull/8447 but it's submitted separately because it's:
* independent to be reviewed on its own
* delicate enough to be valuable to extract it from the original PR diff
* can catch any problems sooner rather than later
(simpler to review with a split diff, and also maybe with the [whitespace](https://github.com/ipfs/go-ipfs/pull/8574/files?w=1) option)
> chore(cmds): encapsulate ipfs rm logic in another function

- bin/check_go_version
* Closes https://github.com/ipfs/go-ipfs/issues/8672
This allows using `make install` with beta versions of Golang.
```yaml
go-ipfs version: 0.13.0-dev-653dbff13-dirty
Repo version: 12
System version: amd64/linux
Golang version: devel go1.18-becaeea119 Tue Dec 14 17:43:51 2021 +0000
```
> fix(build): Recognize Go Beta versions in makefile

- cmd/ipfs/dist/install.sh
I think it's good practice that users don't need to run `sudo`
to install something just to try it out. With this change, the
local bin directory is tried first, which usually is also in the
`PATH`. This way the installation script can be run without
`sudo` and should still work.
> fix: installation without sudo

- .github/workflows/testground-on-push.yml
Closes   #8731
Fixes hanging builds problem with https://github.com/coryschwartz/testground-github-action/pull/2 (detailed description of the problem and testing performed).
Additionally, it adds a 5 minutes timeout on testground jobs - they finish in ~2 minutes if everything goes smoothly.
I'll reenable the workflow after the fix is in place.
> fix(ci): testground workflow hanging indefinitely

- CHANGELOG.md
Add line to the breaking changes section indicating that there's a new version of ipfs-update needed to install go-ipfs v0.12.0.
I added this to the tag + GH issue, but didn't get it into the release notes before the tag.
> docs(changelog): update v0.12.0 release notes

- core/commands/repo.go
- test/sharness/t0080-repo.sh
> feat(cmd): add silent option for command repo gc

- core/node/libp2p/libp2p.go
- core/node/libp2p/libp2p_test.go
- core/node/libp2p/sec.go
Looks like we've been prioritizing `mplex` over `yamux` since at least June 2020. This is really, really bad.
> fix prioritization of stream muxers

- core/corehttp/webui.go
This bumps webui to latest release 
Release Notes: 
- https://github.com/ipfs/ipfs-webui/releases/tag/v2.14.0 (small bugfixes + support for permanent peering via peers screen)
- https://github.com/ipfs/ipfs-webui/releases/tag/v2.15.0 (remote pinning that works with rate-limited services like Pinata)
> feat: ipfs-webui v2.15

- core/commands/cat.go
- core/commands/get.go
Add a `-p=false` flag to not show the progress bar (true by default to keep the current behavior).
Closes https://github.com/ipfs/go-ipfs/issues/8470.
> fix(cmds): option for progress bar in cat/get

- core/commands/block.go
- core/commands/cmdutils/utils.go
- core/commands/dag/dag.go
- core/commands/dag/import.go
- core/commands/dag/put.go
- core/commands/get.go
- core/commands/object/patch.go
- test/sharness/t0050-block.sh
- test/sharness/t0051-object.sh
- test/sharness/t0053-dag.sh
- test/sharness/t0054-dag-car-import-export.sh
Had to create a new sub-package to share information between root `commands` package and child `objectcmd` package to avoid import cycles.
Closes https://github.com/ipfs/go-ipfs/issues/8696.
> feat(cmds): extend block size check for dag|block put

- core/corehttp/commands.go
- test/sharness/t0401-api-browser-security.sh
- fixes #8689
- Adds the chrome-extension ids for ipfs-companion and
ipfs-companion-beta to the allowed origins list, this
allows us to accesss ipfs api from a manifest v3 extension.
- added tests in t0401-api-browser-security.sh
> fix: allow ipfs-companion browser extension to access RPC API

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_handler_block.go
- core/corehttp/gateway_handler_car.go
- core/corehttp/gateway_handler_unixfs.go
- core/corehttp/gateway_handler_unixfs_dir.go
- core/corehttp/gateway_handler_unixfs_file.go
fixes #8441
@gmasgras did you want both the summary and histogram exposed, or should I just switch the summary over to a histogram?
Any preference on the metric name? For example, if replacing the summary metric we may still want a different name so infra that's running the older version and the newer version can have the metrics play together a little nicer.
> feat: add gateway histogram metrics

- core/commands/dag/dag.go
- core/commands/name/ipnsps.go
- core/commands/object/diff.go
- core/commands/object/object.go
- core/commands/object/patch.go
- core/commands/p2p.go
- core/commands/pubsub.go
- core/commands/repo.go
- core/commands/unixfs/ls.go
- core/commands/unixfs/unixfs.go
- core/commands/urlstore.go
- go.mod
- go.sum
go-ipfs part of  https://github.com/ipfs/go-ipfs-cmds/issues/93
This PR adds the programmatic Status annotation introduced in https://github.com/ipfs/go-ipfs-cmds/pull/225
and applies it to for already deprecated / experimental commands.
The main purpose of these annotations is to separate "stable|deprecated|experimental" commands when generating https://docs.ipfs.io/reference/http/api/ (implemented in https://github.com/ipfs/ipfs-docs/pull/1086), but we also show them in `--help` text in CLI:
```console
$ ipfs object patch --help
WARNING:   DEPRECATED, command will be removed in the future
USAGE
ipfs object patch - Deprecated way to create a new merkledag object based on an existing one. Use MFS with 'files cp|rm' instead.
...
```
```console
$ ipfs name pubsub state --help
WARNING: …
```
> feat(cmds): document deprecated RPC API commands

- .circleci/main.yml
This test is actually testing is the ipfs binary (from the path).
Using the go-ipfs-http-client code.
But most PR only update the binary. HOWEVER Golang does not check PATH for caching.
So as far as golang knows: go-ipfs-http-client is old, it havn't changed, and it doesn't run it.
That leads us to this test not running on most important PR.
> CI: force running go-ipfs-http-client tests

- cmd/ipfs/main.go
- cmd/ipfs/pinmfs.go
- cmd/ipfs/pinmfs_test.go
- cmd/ipfswatch/main.go
- commands/context.go
- core/commands/cmdenv/env.go
- core/commands/mount_unix.go
- core/mock/mock.go
- repo/fsrepo/fsrepo.go
Closes https://github.com/ipfs/go-ipfs/issues/7481.
From the issue description:
> The config attached to the command context is not the same config returned by repo.Config(). The commands context should just ask the repo for the config.
> fix(core/commands): do not cache config

- docs/gateway.md
Adds link to relevant pages at docs.ipfs.io, should be safe to merge as soon someone :eyes:  if this reads ok.
> docs: gateway.md

- .circleci/main.yml
- .dockerignore
- test/dependencies/pollEndpoint/main.go
- test/ipfs-test-lib.sh
- test/sharness/t0300-docker-image.sh
- test/sharness/t0301-docker-migrate.sh
The Docker sharness tests were disabled years ago when go-ipfs moved
from Travis to CircleCI. This makes the tweaks necessary to re-enable
them.
The Docker image has since moved to be based on BusyBox which doesn't
have the requisite wget version for the existing tests to work, so
this adds some functionality to the pollEndpoint program to support
polling HTTP endpoints as well.
> feat: re-enable docker sharness tests

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_handler_car.go
- test/sharness/t0118-gateway-car.sh
CAR responses were added in https://github.com/ipfs/go-ipfs/pull/8758
This PR adds validation of `application/vnd.ipld.car;version=n` passed  in the `Accept` header by HTTP clients.
We need this to align Gateway behavior with the spec submitted to IANA (https://github.com/ipfs/in-web-browsers/issues/192).
tl;dr:
- Gateway returns HTTP 400 Bad Request error when request is for unsupported CAR version (right now we only support CARv1)
- Proper parsing of media types using `mime.ParseMediaType` means we don't need to worry about clients adding/removing whitespace or using custom case
> fix(gw): validate requested CAR version

- go.mod
- go.sum
- test/sharness/t0040-add-and-cat.sh
This PR incorporates the `go-ipfs-cmds` [fix](https://github.com/ipfs/go-ipfs-cmds/pull/220) that makes the `ipfs add` command not ignore repeated entries. This fix conflicts with another bug in the `ipfs add -w` variant of the command which can't correctly process files with the same name (I think this was uncovered here and we don't have a specific issue for it). This is shown by the shanress test failing (see more details below). We need to first fix the `ipfs add -w` issue before landing this so we can be confident this is the correct fix.
---------------------------------------------------
The `ipfs add -w (repeats)` test now fails. This is expected because:
* we repeatedly add the `m/4r93` file
* ignored before, these extra/repeated files are now sent to the core UnixFS API `Add()` …
> fix(cli): ipfs add with multiple files of same name

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_handler_block.go
- core/corehttp/gateway_handler_car.go
- core/corehttp/gateway_handler_unixfs.go
- core/corehttp/gateway_handler_unixfs_dir.go
- core/corehttp/gateway_handler_unixfs_file.go
- docs/debug-guide.md
- mk/golang.mk
This PR extends #8595 with spans for each response type from https://github.com/ipfs/go-ipfs/pull/8758
Adds more visibility into how long generic lookup takes vs producing specific response type.
| CAR | Block | File | Directory |
| ---- | ---- | ---- | ---- |
| ![2022-04-01_01-46](https://user-images.githubusercontent.com/157609/161167986-951d5c8c-9a5e-464d-bc20-81eb5ccbdc22.png) | ![block_2022-04-01_01-47](https://user-images.githubusercontent.com/157609/161167983-e8cac0ce-0575-4271-8cb8-4d44a0d5d786.png) |  ![2022-04-01_01-49](https://user-images.githubusercontent.com/157609/161167978-e19aa44c-f5a4-45f4-b7c7-14c313ab1dee.png) |  ![dir_2022-04-01_01-48](https://user-images.githubusercontent.com/157609/161167981-456ca52b-3e87-4042-916b-8db149071228.png) |
> feat(gw): tracing spans per response type

- blocks/blockstoreutil/remove.go
- core/commands/block.go
- core/coreapi/block.go
- go.mod
- go.sum
- test/sharness/t0050-block.sh
- test/sharness/t0054-dag-car-import-export.sh
- test/sharness/t0080-repo.sh
- test/sharness/t0081-repo-pinning.sh
- test/sharness/t0085-pins.sh
Blocking PRs and replace rules to be removed:
> chore: bump go-ipld-format v0.4.0 and fix related sharness tests

- core/node/groups.go
- core/node/libp2p/rcmgr.go
- go.mod
Part of #8761 
Adds basic metrics under `libp2p_rcmgr_*`
````
libp2p_rcmgr_conns_allowed_total{direction="inbound",usesFD="false"} 682
libp2p_rcmgr_conns_allowed_total{direction="inbound",usesFD="true"} 614
libp2p_rcmgr_conns_allowed_total{direction="outbound",usesFD="false"} 7647
libp2p_rcmgr_conns_allowed_total{direction="outbound",usesFD="true"} 9107
libp2p_rcmgr_conns_blocked_total{direction="inbound",usesFD="false"} 2274
libp2p_rcmgr_conns_blocked_total{direction="inbound",usesFD="true"} 1938
libp2p_rcmgr_conns_blocked_total{direction="outbound",usesFD="false"} 15206
libp2p_rcmgr_conns_blocked_total{direction="outbound",usesFD="true"} 16344
libp2p_rcmgr_memory_allocations_allowed_total 9808
libp2p_rcmgr_memory_allocations_blocked_total 0
libp2p_rcmgr_peer_blocked_total 0 …
```
> feat: export rcmgr metrics to prometheus

- core/commands/tar.go
Closes #7951
It will scream in CLI `--help` and https://docs.ipfs.io/reference/http/api/ – see https://github.com/ipfs/ipfs-docs/pull/1086
> chore: deprecate tar commands

- cmd/ipfs/add_migrations.go
> fix: unknown fetcher type error

- core/node/libp2p/rcmgr.go
- core/node/libp2p/rcmgr_defaults.go
- go.mod
- go.sum
Part of https://github.com/ipfs/go-ipfs/issues/8761, based on #8680 
This PR removes hardcoded defaults and switches to ones from go-libp2p.
To safeguard against silent changes that could impact our users, adds a simple check that will scream loud and clear every time go-libp2p libraries change any of the limit defaults related to go-libp2p-resource-manager. This was suggested during recent go-ipfs sync.
- relevant structs are serialized to JSON zand compared
- if there are any unexpected changes, go-ipfs will refuse to start, forcing us to review impact of go-libp2p update
- diff between expected and actual limits is returned in JSON Patch format
- Initially, I just printed JSON for "before" and "after" and compared normalized strings,
but given how many values we have it was difficult …
> feat: detect default limit changes in go-libp2p-resource-manager

- .circleci/main.yml
- CHANGELOG.md
- Dockerfile
- go.mod
- go.sum
- version.go
Relates to [v0.11.1](https://github.com/ipfs/go-ipfs/pull/8860).
This will get merged into release and tagged on the release branch (and we can merge back into master as well).
TODO:
> Release v0.12.2

- core/corehttp/gateway_handler.go
Just fixing a small bug I noticed when working on [a project](https://github.com/AgregoreWeb/agregore-ipfs-daemon) for Agregore Mobile, something I discussed with @lidel.
> fix(gw): missing return if dir fails to finalize

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_handler_block.go
- core/corehttp/gateway_handler_car.go
- core/corehttp/gateway_handler_unixfs.go
- core/corehttp/gateway_handler_unixfs_dir.go
- core/corehttp/gateway_handler_unixfs_file.go
This ensures that child contexts are passed around between the
handlers so that traces show the call hierarchy correctly.
> fix(tracing): context plumbing in gateway handlers

- Dockerfile
- README.md
- bin/container_daemon
- bin/container_init_run
- test/ipfs-test-lib.sh
- test/sharness/t0300-docker-image.sh
- test/sharness/t0301-docker-migrate.sh
This is a proposal to help solve advanced initialization in container environments being discussed in several issues. It follows the model used by postgres container: https://hub.docker.com/_/postgres
This PR adds support for an optional `/container-init.d` directory in the container that can be mounted with custom configuration scripts. These scripts are executed if they have +x permission, otherwise they are just sourced.
This model also allows passing environment variables to the custom scripts when launching the container.
This grants flexibility to and delegates the responsability of bulding complex initializations to the users and administrators.
-----------
License: MIT
Signed-off-by: Caian Benedicto <caianbene@gmail.com>
> feat(docker): /container-init.d for advanced initialization

- core/corehttp/gateway_handler.go
Another take at https://github.com/ipfs/go-ipfs/pull/8883 from my personal account this time.
> chore(gw): extract logical functions to improve readability

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_handler_unixfs_dir.go
- core/corehttp/gateway_test.go
- test/sharness/t0116-gateway-cache.sh
> Part of https://github.com/ipfs/go-ipfs/issues/8717 / https://github.com/ipfs/in-web-browsers/issues/132 
Improves the way we handle [`If-None-Match`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) header:
- Fixed support for more than one Etag passed in `If-None-Match`
- Match both strong and weak Etags to maximize caching across  various HTTP clients and libraries (some send weak Etags by default)
- Support for wildcard `If-None-Match: *` (e.g. when client has a dir listing and does not care if there is a newer version)
- End-to-end tests for `If-None-Match` behavior
Closes  #3861 (we've been setting correct Etag on `/ipns/` in `master`  already, but this PR adds tests)
> fix(gw): Etag and If-None-Match

- CHANGELOG.md
- core/commands/block.go
- core/commands/cid.go
- core/coreapi/block.go
- go.mod
- go.sum
- test/sharness/t0050-block.sh
- test/sharness/t0110-gateway.sh
- test/sharness/t0290-cid.sh
- This PR requires https://github.com/ipfs/interface-go-ipfs-core/pull/80 to land first. Go there first.
- `ipfs block` commands
- `ipfs block put` now produces CIDv1 with `raw` codec by default now
- `ipfs block put --cid-codec` makes `block put` return CID with alternative codec
-  this impacts only the returned CID, it does  not trigger any validation or data transformation
- codec names are validated against tables from https://github.com/multiformats/go-multicodec
- `ipfs block put --format` is deprecated. It used incorrect codec names and should be avoided for new deployments. Use it only if you need the old, invalid behavior, namely:
- `ipfs block put --format=v0` will produce CIDv0 (implicit dag-pb)
- `ipfs block put --format=cbor` will produce CIDv1 with dag-cbor (!)
- `ipfs …
> fix(cmds): use ipld multicodecs for cmds block put and cid

- core/commands/dns.go
- core/commands/root.go
Closes #8607  – will be picked up by https://github.com/ipfs/ipfs-docs/pull/1086 after go-ipfs 0.13 ships.
> chore: deprecate /api/v0/dns

- .github/ISSUE_TEMPLATE/config.yml
Fixing the link to the RPC API  docs (it was pointing at `#api-v0-add` for some reason :see_no_evil: )
> chore: improve new issue  links

- cmd/ipfs/daemon.go
- cmd/ipfs/main.go
- config/config.go
- core/commands/config.go
- core/commands/root.go
- repo/fsrepo/fsrepo.go
- repo/fsrepo/migrations/ipfsfetcher/ipfsfetcher.go
- repo/fsrepo/migrations/ipfsfetcher/ipfsfetcher_test.go
- repo/fsrepo/migrations/migrations.go
- repo/fsrepo/migrations/migrations_test.go
- test/sharness/t0020-init.sh
- test/sharness/t0021-config.sh
First iteration, still incomplete. Review needed at this point to move forward.
Depends on https://github.com/ipfs/go-ipfs-config/pull/162.
Closes https://github.com/ipfs/go-ipfs/issues/8067.
> feat(cmds): allow to set the configuration file path

- config/swarm.go
- core/commands/swarm.go
- core/node/libp2p/rcmgr.go
- go.mod
- go.sum
- test/sharness/t0139-swarm-rcmgr.sh
>  Part of https://github.com/ipfs/go-ipfs/issues/8761, follow-up after https://github.com/ipfs/go-ipfs/pull/8680
This changes the "ipfs swarm limit" command so that When limit changes
are applied via the command line, they are persisted to the repo
config, so that they remain in effect when the daemon restarts.
This also removes limit.json support, to simplify the behavior. The
schema for Swarm.ResourceMgr.Limits is exactly the same as limit.json,
so existing limit.json can be dropped into the IPFS config easily
using something like:
```console 
$ cat ~/.ipfs/config | jq ".Swarm.ResourceMgr.Limits = $(cat limit.json)" | sponge ~/.ipfs/config
```
This upgrades to Resource Manager v0.3.0, which exports the config
schema so that we don't have to maintain our own copy of it.
> feat: persist limit changes to config

- core/commands/log.go
This is one-line change to ensuring people are aware the `log tail` is unstable and will change.
This hint will be picked up by docs.ipfs.io thanks to https://github.com/ipfs/ipfs-docs/pull/1086.
Context: https://github.com/ipfs/go-ipfs/pull/8765#issuecomment-1109884874
> chore: mark 'log tail' experimental

- .circleci/main.yml
- core/node/libp2p/relay.go
- docs/config.md
- go.mod
- go.sum
This PR continues epic from https://github.com/ipfs/go-ipfs/pull/8562:
- This enables the  [Direct Connection Upgrade through Relay (DCUtR)](https://github.com/libp2p/specs/blob/master/relay/DCUtR.md) client (introduced in 0.11: https://github.com/ipfs/go-ipfs/pull/8562, [docs](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#swarmenableholepunching)).
-  needs https://github.com/ipfs/interop/pull/443
- rebase on top of  https://github.com/ipfs/go-ipfs/pull/8868
```
ipfsfetcher_test.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1533fd9]
```
- upstream bug: https://github.com/libp2p/go-libp2p/issues/1448
- potential fix: https://github.com/libp2p/go-libp2p/pull/1467
> feat: EnableHolePunching by default

- cmd/ipfs/dist/install.sh
On macOS Monterey there is no `/usr/local/bin` folder and we need to create it.
Closes #8347.
> Ensure that folder exists before moving ipfs binary.

- core/commands/pubsub.go
Adds clarification for pubsub multibase encoding over HTTP RPC for issue https://github.com/ipfs/ipfs-docs/issues/1007
> pubsub multibase encoding

- core/commands/commands_test.go
- core/commands/repo.go
- repo/fsrepo/migrations/ipfsfetcher/ipfsfetcher.go
- test/sharness/t0066-migration.sh
This PR replaces #7658 that was originally contributed by @zaibon, in order to move code into a branch and avoid some CI problems.
The command allows the user to run the repo migration without starting the daemon.
resolves #7471
> Add 'ipfs repo migrate' command

- .circleci/main.yml
Sometimes docker pull fails, this will retry.
Ref. example of a failed job: https://app.circleci.com/pipelines/github/ipfs/go-ipfs/6709/workflows/ca83ade9-ebaa-4ed3-b77b-2147dbdf719a/jobs/72873?invite=true#step-107-29
> fix(ci): fix flaky t0081-repo-pinning.sh

- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-image.yml
- .github/workflows/sync-release-assets.yml
- .github/workflows/testground-on-push.yml
This PR makes sure that none of the workflows, except for `go-test`, do not run in future forks of `go-ipfs`. 
It does so by adding a check whether `github.repository` (this variable holds the full name of a reposiotry in which the workflow is being run) is equal to `ipfs/go-ipfs`. 
It also ensures that each of the "disabled" workflows can be executed explicitly using `workflow_dispatch`.
> ci: disable workflows in forks

- go.mod
- go.sum
Context: https://github.com/libp2p/go-libp2p/releases/tag/v0.19.2
> fix: holepunch in go-libp2p 0.19.2

- .circleci/main.yml
- core/node/libp2p/rcmgr_defaults.go
Quick band-aid for https://github.com/ipfs/go-ipfs/issues/8949 to fix master before https://github.com/ipfs/go-ipfs/pull/8954 lands.
> fix(node/libp2p): disable rcmg checkImplicitDefaults

- cmd/ipfs/daemon.go
- core/commands/mount_nofuse.go
- core/commands/mount_unix.go
- core/commands/root.go
- docs/config.md
- docs/experimental-features.md
- docs/fuse.md
FUSE  works only on some platforms, and does not work reliably.
This OR corrects our error of not setting expectations right and marks FUSE as EXPERIMENTAL.
> chore: mark fuse experimental

- core/commands/get.go
Fixes #8957
The context was only checked while reading data.
Not while writing data to the http connection.
So since the data flow through an io.Pipe the closing didn't flowed through and left the writer open hanging.
Co-authored-by: Antonio Navarro Perez <antnavper@gmail.com>
> fix: hanging goroutine in get fileArchive handler

- core/corehttp/gateway.go
- test/sharness/t0112-gateway-cors.sh
This fix safelists additional headers allowing JS running on websites to read them when IPFS resource is downloaded via Fetch API.
These headers allow for making smart caching decisions (https://github.com/ipfs/go-ipfs/pull/8720)  when IPFS resources are downloaded via Service Worker or a  similar middleware on the edge. 
@guseggert  If possible, we should include it in 0.13 (I forgot to safelist them in https://github.com/ipfs/go-ipfs/pull/8720), but if it is too late, then please reassign this to 0.14.
> fix: JS caching via Access-Control-Expose-Headers

- docs/examples/go-ipfs-as-a-library/main.go
It was causing some build timeout errors because CircleCI was throttling
WAN connections.
It closes #8956 (was flaky test)
> fix(ci): make go-ipfs-as-a-library work without external peers

- core/node/libp2p/rcmgr_defaults.go
The Accelerated DHT client periodically refreshes its routing table,
including at startup, and if Resource Manager throttling causes the
client's routing table to be incomplete, then content routing may be
degraded or broken for users.
This adjusts the default limits to a level that empirically doesn't
cause Resource Manager throttling during initial DHT client
bootstrapping. Ideally the Accelerated DHT client would handle this
scenario more gracefully, but this works for now to unblock the 0.13
release.
> fix: adjust rcmgr limits for accelerated DHT client rt refresh

- core/commands/config.go
This is a tiny patch to make the `ipfs config edit` subcommand work on Windows.
Closing #8844
> fix(cmd/config): make config edit subcommand work on windows

- core/corehttp/gateway_handler_block.go
- core/corehttp/gateway_handler_car.go
- test/sharness/t0117-gateway-block.sh
- test/sharness/t0118-gateway-car.sh
Fixes #9027. Please let me know if there is anything else I need to do before this can be merged.
> fix: honour url filename when downloading as CAR/BLOCK

- docs/config.md
We forgot to set proper expectations in https://github.com/ipfs/go-ipfs/pull/9003 – this makes it clear that  the feature is still being fleshed out and YMMV.
Limits config may change due to https://github.com/libp2p/go-libp2p-resource-manager/pull/48 so we should be proactive and warn users about it.
> docs(config): mark Swarm.ResourceMgr as experimental

- config/discovery.go
- config/init.go
- core/node/groups.go
- core/node/libp2p/discovery.go
- docs/config.md
- go.mod
- go.sum
This PR removes the ancient `mdns_legacy` implementation.
- The modern DNS-SD compatible [zeroconf implementation](https://github.com/libp2p/zeroconf#readme) (based on [new specs here](https://github.com/libp2p/specs/blob/master/discovery/mdns.md)) has been running next to the legacy one for a while (since v0.11)
- This means we were sending twice as many packets, most likely contributing to issues like  ipfs/go-ipfs#8695
- [@libp2p/mdns](https://github.com/libp2p/js-libp2p-mdns) used by js-ipfs implements and runs both [old](https://github.com/libp2p/js-libp2p-mdns/tree/master/src/compat) and [new](https://github.com/libp2p/js-libp2p-mdns/tree/master/src), so we won't lose any interop connectivity. 
@marten-seemann @schomatis thoughts on removing old one? any concerns?
> fix: remove mdns_legacy

- README.md
- SECURITY.md
This moves existing security policy from README to SECURITY.md
which has a [special meaning on Github](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository).
This is already done in Lotus, and they get this additional option when someone reports a bug in their repo:
> ![2022-06-26_19-02](https://user-images.githubusercontent.com/157609/175825988-d6e0cd9e-f1db-4fa6-95ac-dda92d298703.png)
> docs: add SECURITY.md

- core/corehttp/gateway_handler_car.go
- test/sharness/t0118-gateway-car.sh
Context: https://github.com/ipfs/specs/pull/295
> fix(gw): correct cache-control in car responses

- core/corehttp/gateway.go
- core/corehttp/gateway_handler.go
- test/sharness/t0116-gateway-cache.sh
This PR implements support for requests sent with `only-if-cached` prerequisite, as documented in Gateway specs:
[PATH_GATEWAY.md#cache-control-request-header](https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#cache-control-request-header):
> Client can send Cache-Control: only-if-cached to request data only if the gateway already has the data (e.g. in local datastore) and can return it immediately.
> 
>  If data is not cached locally, and the response requires an expensive remote fetch, a [412 Precondition Failed](https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#412-precondition-failed) HTTP status code should be returned by the gateway without any payload or specific HTTP headers.
[PATH_GATEWAY.md#only-if-cached-head-behavior](https://github.com/i …
> feat(gw): Cache-Control: only-if-cached

- core/commands/cid.go
- go.mod
- go.sum
- test/sharness/t0290-cid.sh
- test/sharness/t0295-multibase.sh
This add supports for base256emoji. :rocket: 
https://github.com/multiformats/go-multibase/pull/46
> chore: update go-multibase 🚀

- .circleci/main.yml
This PR aims to fix ipfs-webui tests run on CI. Testing Kubo against ipfs-webui main branch fails right now:
https://app.circleci.com/pipelines/github/ipfs/kubo/7228/workflows/528ee100-ccc9-4e9c-8bb4-46cdbbe4e306/jobs/78516
```
npm ERR! notsup Unsupported engine for ipfs-webui@2.16.0: wanted: {"node":"=16.12.0","npm":"=8.1.0"} (current: {"node":"14.18.2","npm":"6.14.15"})
npm ERR! notsup Not compatible with your version of node/npm: ipfs-webui@2.16.0
npm ERR! notsup Not compatible with your version of node/npm: ipfs-webui@2.16.0
npm ERR! notsup Required: {"node":"=16.12.0","npm":"=8.1.0"}
npm ERR! notsup Actual:   {"npm":"6.14.15","node":"14.18.2"}
```
cc @SgtPooki:
Let's see if  CI is green (then it will auto-merge, fixing master).
If it fails, we need to  fix it after Iceland (added to …
> fix(ci): ipfs-webui requires node 16.12.0

- assets/dir-index-html/dir-index.html
- assets/dir-index-html/src/dir-index.html
- core/corehttp/gateway_handler_unixfs_dir.go
- core/corehttp/gateway_test.go
- test/sharness/t0115-gateway-dir-listing.sh
This PR removes "one level up" backlink when listing a content root (the root CID being an UnixFS directory).
Closes #9071
> ![Screenshot 2022-07-18 at 23-43-37 Files on IPFS](https://user-images.githubusercontent.com/157609/179622812-73d73b3f-3b9e-4ba6-bdf8-bf22443006c9.png)
> ![Screenshot 2022-07-18 at 23-43-58 Files on IPFS](https://user-images.githubusercontent.com/157609/179622848-263c2dc8-87b9-4357-98f2-6139ed2e0c6e.png)
> fix(gw): no backlink when listing root dir

- LICENSE
https://github.com/ipfs/kubo/issues/9130
chose to used repaired apache link instead of using opensource.org host.
> docs(license): fix broken link to apache-2.0

- core/corehttp/gateway_handler_unixfs_dir.go
- test/sharness/t0116-gateway-cache.sh
- test/sharness/t0117-gateway-block.sh
This PR fixes a regression introduced in 0.13.0:
- websites hosted via  `index.html` placed in UnixFS directory were always returned with `Cache-Control: public, max-age=29030400, immutable`  even when loaded from **mutable** `/ipns/*`  content path
- this contributed to weird stale cache behaviors like the one at https://github.com/ipfs/ipfs-website/issues/141
- adds missing tests of `Cache-Control` on `/ipfs/` and `/ipns/` namespaces  :skull: 
Thank you, @thattommyhall,  for help with debugging and finding this.
> fix(gw): correct cache-control of index.html websites

- core/corehttp/gateway_handler_unixfs_dir.go
- core/corehttp/gateway_test.go
- test/sharness/t0110-gateway.sh
- test/sharness/t0113-gateway-symlink.sh
- test/sharness/t0114-gateway-subdomains.sh
- test/sharness/t0115-gateway-dir-listing.sh
This PR fixes a regression around directory listing and index.html hosting,
and makes Kubo behavior compliant with desired [Gateway Specs here](https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#use-in-directory-url-normalization).
Seems that during one of recent refactors code changed and we no longer check for trailing slash in HTTP request path.  Most likely, this happened when we switched from raw URL path to content path.
This regression meant Kubo was not following specs at
[/ipfs/specs/http-gateways/PATH_GATEWAY.md#use-in-directory-url-normalization](https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#use-in-directory-url-normalization).
This PR: 
- cleans things up so we always redirect directories from `/ipfs/cid/foo` to `/ipfs/cid/foo/`
- …
> fix(gw): directory URL normalization

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_handler_unixfs.go
- core/corehttp/gateway_test.go
- test/sharness/t0110-gateway.sh
This PR makes sure gateway returns 404 (Not Found) only when a valid DAG is missing the requested child.
In other cases, 400 (Bad Request) is returned.
Uses `ipld.IsNotFound` added in https://github.com/ipfs/kubo/pull/8838
Closes #8924 
Closes #9064
> fix(gw): 404 when a valid DAG is missing link

- docs/config.md
A small typo fix in config.md from docs
> Fixed md link syntax typo for AutoNAT.ServiceMode

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/doc.yml
- README.md
- core/corehttp/hostname_test.go
- docs/README.md
- docs/changelogs/v0.10.md
- docs/changelogs/v0.11.md
- docs/changelogs/v0.12.md
- docs/changelogs/v0.13.md
- docs/changelogs/v0.14.md
- docs/changelogs/v0.9.md
- docs/config.md
- docs/gateway.md
- misc/systemd/ipfs-hardened.service
- misc/systemd/ipfs.service
The PR to fix the redirecting URL in README.md
> docs: replace `docs.ipfs.io` with `docs.ipfs.tech`

- cmd/ipfs/daemon.go
- repo/fsrepo/fsrepo.go
- repo/mock.go
- repo/repo.go
- test/sharness/t0110-gateway.sh
The file contains the gateway your node is hosting in the http://<host>:<port> format.
Structurally it works exactly the same as the API file.
IPIP: https://github.com/ipfs/specs/pull/280
> feat: add $IPFS_PATH/gateway file

- docs/config.md
this clarifies that `Experimental` is in fact a top level configuration key, and links to the most current documentation
> Add reference to Experimental config doc

- go.mod
- go.sum
- test/sharness/t0275-cid-security.sh
- test/sharness/t0290-cid.sh
- test/sharness/t0800-blake3.sh
Support hashes from 20 <= x <= 128 bytes, but does not yet have any option to generate anything else than 32 bytes hashes.
This will be forward compatible when we add such option.
This is #9073 with squashes.
> feat: add blake3 support

- core/builder.go
- go.mod
- go.sum
- plugin/fx.go
- plugin/loader/loader.go
- plugin/loader/preload.go
- plugin/loader/preload_list
- plugin/plugins/fxtest/fxtest.go
- test/sharness/t0280-plugin-fx.sh
This adds a plugin interface that lets the plugin modify the fx
options that are passed to fx when the app is initialized. This means
plugins can inject their own implementations of IPFS interfaces. This
enables granular customization of go-ipfs behavior by plugins, such
as:
- Bitswap with custom filters (e.g. for CID blocking)
- Custom interface implementations such as Pinner or DAGService
- Dynamic configuration of libp2p ...
One downside of this is that we're exposing the entire dependency
graph, init hooks, initialization, etc. to users, so this comes with a
caveat that we reserve the right to make breaking changes to the graph
structure and initialization logic (although this historically happens
rarely). If these things are changed, we should mention them in
release notes and …
> feat: add fx options plugin

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/workflows/sync-release-assets.yml
- README.md
- cmd/ipfs/daemon.go
- core/corehttp/hostname.go
- core/corehttp/hostname_test.go
- core/node/groups.go
- docs/PATCH_RELEASE_TEMPLATE.md
- docs/RELEASE_ISSUE_TEMPLATE.md
- docs/changelogs/v0.11.md
- docs/changelogs/v0.12.md
- docs/changelogs/v0.14.md
- docs/changelogs/v0.4.md
- docs/changelogs/v0.5.md
- docs/changelogs/v0.7.md
- docs/changelogs/v0.9.md
- docs/windows.md
- repo/fsrepo/migrations/fetch.go
- repo/fsrepo/migrations/fetcher.go
- test/sharness/t0066-migration.sh
> Part of https://github.com/protocol/bifrost-infra/issues/2018
This PR replaces all mentions of `dist.ipfs.io` with `dist.ipfs.tech`
> chore: switch to dist.ipfs.tech

- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
See the release notes: https://github.com/gabriel-vasile/mimetype/releases/tag/v1.4.1
This is a valuable release with already public security fixes (which don't affect us AFAIT but better safe than sorry).
More mimetypes and bug fixes.
> chore: update github.com/gabriel-vasile/mimetype

- test/sharness/t0112-gateway-cors.sh
This PR cleans up old CORS tests and adds more resolution:
- Descoped as it needs to be revisited given the latest sources and gateway practices, let's continue in https://github.com/ipfs/go-ipfs/issues/7667
> test(gw): improve CORS tests

- core/commands/add.go
- core/commands/dag/dag.go
First stab at better 'ipfs add --help'  docs, based on the  feedback from
https://discuss.ipfs.io/t/ipfs-for-publishing-research-data-car-files/14748
cc @2color @hsanjuan
> docs: clarify CID determinism in add command

- docs/config.md
@aschmahmann thoughts on mentioning this in config docs? IMO has way more utility than the indexer on its own.
> docs(config): mention routing.delegate.ipfs.io

- docs/config.md
`config.md` states that `Reprovider.Interval` is of type `array[peering]`, however is used as a string which is parsed into a `time.Duration` type. 
This PR corrects documentation so the Reprovider.Interval type is listed as a `string` in `config.md`.
Signed-off-by: Oleg Silkin <16809287+osilkin98@users.noreply.github.com>
> correct data type for Reprovider.Interval

- README.md
This PR updates Docker section to point at the images under the new name:
- https://hub.docker.com/r/ipfs/kubo/ (i've updated it to point at useful docs)
> docs(readme): update Docker section

- cmd/ipfs/daemon.go
- config/gateway.go
- core/corehttp/gateway.go
- docs/config.md
Closes #7702 – should be part of 0.14, keeping as draft so we don't forget.
> chore: remove Gateway.PathPrefixes

- README.md
This PR updates README and makes it clear which packages are official, and which ones are not, to align better with https://docs.ipfs.tech/install/command-line/#official-distributions 
It also moves `ipfs-update` and `dist.ipfs.tech` based Update into Official section.
cc @2color @TMoMoreau
> docs(readme): official vs unofficial packages

- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
Workaround for #8762
Depends on ipfs/go-pinning-service-http-client#20
> chore: update go-pinning-service-http-client to include up to nano precision

- cmd/ipfs/daemon.go
This rewords the help description for DHTClient so it isn't described as experimental, and it has the relevant ipfs config command which was previously marked as not existing.
> Update `ipfs daemon --help` text for DHTClient

- README.md
Changes code example to use (what I believe is the) correct installation: https://community.chocolatey.org/packages/go-ipfs
> Readme: change windows choco install command example to point to go-ipfs

- config/dns.go
- docs/config.md
This PR adds documentation for using [eth.limo](https://eth.limo) as an alternative DoH resolver for `eth.` domains.
> docs: fix broken ENS DoH example

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
This PR  makes Kubo ignore V1 signatures when validating IPNS records, and always require V2.
See https://github.com/ipfs/go-ipns/pull/41 for low level details.
Closes https://github.com/ipfs/kubo/issues/9240
- IPNS Records that do not have V2 but have V1 signature will no longer pass validation, even if V1 is correct. V2 is mandatory to pass validation. See "Record validation" in https://github.com/ipfs/specs/pull/319 for details.
> fix: require IPNS V2 signatures

- docs/changelogs/v0.16.md
cc https://github.com/ipfs/kubo/issues/9237
@BigLep @2color  lmk if we should elaborate more on anything, or if this is enough for release notes.
> docs: document remaining 0.16.0 features

- core/node/libp2p/rcmgr_logging.go
- test/sharness/t0139-swarm-rcmgr.sh
`swarm stats all` requires that the ResourceManager instance implements `rcmgr.ResourceManagerState`, and `loggingResourceManager` was not implementing it, so the command was failing.
Also added a sharness test to check that the command is executing correctly because `jq -e` doesn't return an error if the JSON is nil.
Closes #9284 
> Fix: `swarm stats all` command

- README.md
It was missing an “and” and was a little awkward doing was/is
thanks for all your interplanetary hard work
> Fix typo & grammar in first sentence of README

- config/gateway.go
- core/corehttp/hostname.go
- core/corehttp/hostname_test.go
- docs/config.md
- test/sharness/t0114-gateway-subdomains.sh
> fix: add InlineDNSLink flag to PublicGateways config

- config/internal.go
- core/node/bitswap.go
Fixes https://github.com/ipfs/go-ipfs/issues/8807
> feat: remove provider delay interval in bitswap

- core/commands/swarm.go
> fix ipfs swarm peering crash in offline mode

- core/commands/dag/import.go
- test/sharness/t0054-dag-car-import-export.sh
Closes https://github.com/ipfs/kubo/issues/9198.
> chore(cmds): dag import: use ipld legacy decode

- core/commands/commands_test.go
- core/commands/repo.go
Added sub command "ls" under "repo" command and gave RefsLocalCmd. 
This helps to maintain both the commands for backward compatibility and easy modification which reflects in "repo ls".
> add refs local alias repo ls

- test/sharness/t0054-dag-car-import-export.sh
This ensures we have full test coverage for fix from https://github.com/ipfs/kubo/pull/9219, 
including all variants what will be introduced in https://github.com/ipfs/kubo/pull/9335 (cc @hacdias :))
> test(car): export/import of (dag-)cbor/json codecs

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Ref: https://github.com/ipld/go-ipld-prime/releases/tag/v0.19.0
> deps: upgrade go-ipld-prime to v0.19.0

- core/commands/pin/remotepin.go
It accepts only one arg, and it is usually a CID.
> docs: pin remote arg

- core/commands/swarm.go
This error nicely instead of ooming when trying to use a json file so big it would oom.
> fix: error when using huge json limit file

- core/commands/log.go
I'm not sure what the proper fix @Jorropo or other maintainers had in mind was, but disabling `ipfs log tail` until https://github.com/ipfs/kubo/issues/9245 is resolved is one path. Just opening this to push the short conversation @Jorropo and I had on slack forward.
> docs: note log tail is broken

- core/corehttp/webui.go
Release Notes: https://github.com/ipfs/ipfs-webui/releases/tag/v2.20.0
This includes two important things for Kubo 0.17-rc1 (https://github.com/ipfs/kubo/issues/9319):
- updated geoip database for Peers screen (https://github.com/ipfs-shipyard/ipfs-geoip/pull/97)
- support for `/webtransport` on Status page (https://github.com/ipfs/ipfs-webui/issues/2033).
> feat: ipfs-webui 2.20.0

- config/swarm.go
This is a cosmetic fix that removes `null` values from the default config:
```json
"ResourceMgr": {
"MaxMemory": null,
"MaxFileDescriptors": null
}
```
```json
"ResourceMgr": {}
```
:)
> fix(config): skip nulls in ResourceMgr

- docs/config.md
> docs: Deprecate Reframe on docs.

- .circleci/main.yml
| before | after (this PR) | 
| ---- | ---- |
| ![2022-11-15_18-18](https://user-images.githubusercontent.com/157609/201984487-183a750b-cb75-4d7c-b21e-e0693fc9c15d.png) |  ![2022-11-15_19-05](https://user-images.githubusercontent.com/157609/201993460-5b78e1cb-8f9d-450c-b83b-b6719861e7cf.png)  |
- `webui` and `interop` tests take nearly as long as `sharness`
- `webui` flakiness will be addressed upstream in ipfs-webui repo (tracked in https://github.com/ipfs/ipfs-webui/issues/2065), but this PR should decrease how often it occurs + make CI faster (making the sharness the longest one again)
> chore(ci): bigger box for webui and interop

- config/init.go
- config/profile.go
- config/swarm.go
- core/node/groups.go
- core/node/libp2p/rcmgr_defaults.go
- docs/changelogs/v0.17.md
- docs/config.md
Fixes https://github.com/ipfs/go-ipfs/issues/8845.
Sorry for the delay. I was digging around config's `Optional` structs implementation to look for a cleaner approach but that shouldn't be blocking this (it can be addressed later in a separate issue).
> refactor(config): remove Swarm.ConnMgr defaults

- docs/changelogs/v0.17.md
Context https://github.com/libp2p/go-libp2p-relay-daemon/issues/18#issuecomment-1276212041 and https://github.com/libp2p/go-libp2p/pull/1834  – part of https://github.com/ipfs/kubo/issues/9319 and #9204
> docs: document /wss fix in 0.17 (go-libp2p 0.23.3)

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
https://github.com/ipfs/go-unixfs/releases/tag/v0.4.1
I created this issue pointing to master, but we can change it to add it to the v0.17 release. (@lidel will cherry-pick so its in both places)
It closes #9063
> fix: update go-unixfs to v0.4.1

- core/node/libp2p/rcmgr.go
- core/node/libp2p/rcmgr_defaults.go
- docs/changelogs/v0.17.md
- docs/config.md
This is part of https://github.com/ipfs/kubo/issues/8761
This was done by taking a fresh look for someone learning about the resource manager being enabled by default.
Moved and expanded documentation to the right places for more visibility.
Added an initial changelog entry.
> Doc improvements and changelog for resource manager

- docs/config.md
Since we describe how limits are being computed, also added the docs on how to find out what ended up being computed.
This is following up on https://github.com/ipfs/kubo/issues/8761#issuecomment-1318077660
> Update config.md for resource management limits

- README.md
We really should remove all mentions of "IPFS will replace HTTP".  It distracts people from the killer features (content addressing, and full interop with HTTP).
> docs(readme): improve tldr

- config/pubsub.go
- core/node/groups.go
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/integration/pubsub_msg_seen_cache_test.go
Here's a PR for [this](https://github.com/ipfs/kubo/issues/9371) issue, @lidel.
cc @stbrody
Closes #9371
> feat: Pubsub.SeenMessagesTTL

- core/node/libp2p/rcmgr_logging.go
- core/node/libp2p/rcmgr_logging_test.go
This PR makes a cosmetic change to message produced by ResourceMgr as suggested in https://github.com/ipfs/kubo/issues/9432#issuecomment-1334160936:
BEFORE:
```
ERROR resourcemanager libp2p/rcmgr_logging.go:53    Resource limits were exceeded 2 times with error "system: cannot reserve inbound connection: resource limit exceeded".
```
AFTER:
```
ERROR resourcemanager libp2p/rcmgr_logging.go:53    Protected from exceeding resource limits 2 times: "system: cannot reserve inbound connection: resource limit exceeded".
```
> fix(rcmgr): improve error phrasing

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
It will avoid a deadlock when using parallel router to compose routers.
Closes #9445
> chore: Update go-routing-helpers dependency

- core/commands/add.go
- core/commands/files.go
- core/commands/object/object.go
- core/coreapi/object.go
- core/coreapi/unixfs.go
- core/coreunix/add.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- test/sharness/t0042-add-skip.sh
0.8.0 not yet released, this is testing https://github.com/ipfs/go-merkledag/pull/92 which, if merged, will be 0.8.0. I'm using this to CI test that branch for now but will update if/when we get a tag.
> deps: go-merkledag@0.8.1

- core/node/groups.go
- core/node/libp2p/libp2p.go
- test/sharness/t0026-id.sh
This PR fixes  #9456 and adds end-to-end test which confirms suffix is exposed over [identify](https://github.com/libp2p/specs/tree/master/identify) protocol.
Pinging bunch of folks for review / FYI.
`--agent-version-suffix` introduced in https://github.com/ipfs/kubo/pull/8419 was not applied when `libp2p.UserAgent` was initialized, which meant the suffix was always absent from libp2p's [identify](https://github.com/libp2p/specs/tree/master/identify) protocol.  
The result: [we were not getting information about `/brave` `/desktop` and `/docker` nodes :'(](https://user-images.githubusercontent.com/157609/205760808-8a1e0cb5-21f6-4ad4-8508-0d48d0591ab4.jpg)  
Good news is that Kubo 0.18.0-rc1 will have this fixed, unblocking https://github.com/protocol/network-measurements/issues/24
> fix: expose agent-version-suffix via identify protocol

- test/sharness/t0042-add-skip.sh
I was too much trigger happy and caught #9297's regression test in the workaround revert.
> Partial Revert "Revert "fix: ensure hasher is registered when using a hashing function""

- core/node/libp2p/rcmgr_defaults.go
Added a comment next to the value to make possible to people to grep over the code and find where that value is set.
> Fix: RM: Set no-limit value to 1e9 (1000000000).

- config/routing.go
- core/node/libp2p/routingopt.go
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- routing/delegated.go
- routing/delegated_test.go
- routing/wrapper.go
- test/sharness/t0702-delegated-routing-http.sh
- test/sharness/t0702-delegated-routing-http/FindProvidersResponse
Added the new HTTP delegated routing as a possible routing system that can be added to provide and resolve content locations.
> feature: delegated-routing: Add HTTP delegated routing.

- core/commands/swarm.go
- core/node/libp2p/rcmgr.go
- core/node/libp2p/rcmgr_test.go
- test/sharness/t0139-swarm-rcmgr.sh
As per https://github.com/ipfs/kubo/issues/9001 `min-used-limit-perc` was intended to be used only on the `all` scope.
Fixed the percentage calculation to be more precise and added a sharness test checking error output.
It closes https://github.com/ipfs/kubo/issues/9473
> Fix: Resource Manager: Filter stats correctly by %

- core/node/libp2p/rcmgr.go
- core/node/libp2p/rcmgr_defaults.go
- test/sharness/t0060-daemon.sh
Improved init message explaining what RM is doing. Output example:
```
Kubo version: 0.18.0-dev-a3913d9f9-dirty
Repo version: 12
System version: amd64/linux
Golang version: go1.19.3
Computing default go-libp2p Resource Manager limits based on: 
- 'Swarm.ResourceMgr.MaxMemory': "8GB"
- 'Swarm.ResourceMgr.MaxFileDescriptors': 524288
Applying any user-supplied overrides on top.
Run 'ipfs swarm limit all' to see the resulting limits.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/16.0.0.1/tcp/4001
Swarm listening on /ip4/16.0.0.1/udp/4001/quic
Swarm listening on /ip4/16.1.0.1/tcp/4001
Swarm listening on /ip4/16.1.0.1/udp/4001/quic
Swarm listening on /ip4/16.10.0.1/tcp/4001
Swarm listening on …
```
> Fix: RM: Improve init RM message and fix final memory value.

- config/init.go
- docs/config.md
This PR aims to close #9420 by lowering the implicit defaults for `Swarm.ConnMgr`.
It will not only help with https://github.com/ipfs/kubo/issues/9442 but also decrease bitswap gossip.
To apply change to legacy nodes that were initialized before https://github.com/ipfs/kubo/pull/8913, we need to perform config migration described in https://github.com/ipfs/kubo/pull/8913#pullrequestreview-1176651149
- this has to be done in https://github.com/ipfs/fs-repo-migrations – not blocking review of this PR
> feat(connmgr): lower the default connection pool

- core/commands/swarm.go
- core/node/libp2p/rcmgr_logging.go
- core/node/libp2p/rcmgr_logging_test.go
- docs/config.md
- docs/libp2p-resource-management.md
In an attempt to address some of the resource manager integration concerns from https://github.com/ipfs/kubo/issues/9442 , this is a start to docs dedicated on Kubo's integration with libp2p resource management.  A lot of this information previously lived in the config docs, but since the scope was expanding beyond configuration, it was pulled into its own doc.
This isn't currently complete, but is hopefully a starting branch for others to expand and improve upon.
For anyone looking at this, these docs are assuming functionality that will land for 0.18 as being tracked in https://github.com/ipfs/kubo/issues/9442
> docs: libp2p resource management

- config/init.go
- config/profile.go
- config/reprovider.go
- config/types.go
- core/node/groups.go
- core/node/provider.go
- docs/changelogs/v0.18.md
This PR aims to increase `kubo`'s default republish interval from `12h` to `22h` based on [RFM17](https://github.com/protocol/network-measurements/blob/master/results/rfm17-provider-record-liveness.md) as discussed in [libp2p/specs#451](https://github.com/libp2p/specs/pull/451#issue-1372605284).
The measurements from RFM17 were surprising and promising for the steady provider record's liveness gathered in the IPFS live network. Based on the average of 70% of online PR holders and 70% of PR holders being among the 20 closest peers for over +48 hours, we suggest increasing the republish interval for the CIDs and extending the expiration time to help reduce part of the overhead that providing large sets of CIDs implies.
**Why 22 hours?**
Since the current `expiration time` for the PR is set …
> feat: increase default republish interval

- config/init.go
- docs/config.md
This is follow-up for https://github.com/ipfs/kubo/pull/9467
https://github.com/ipfs/kubo/pull/9467#issuecomment-1341678826 from @BigLep :
>  I sanity checked the number of Low=50, High=150
> 
> By default if a Kubo node has 8GB of total memory, a maxMemory for libp2p will be set to 2GB.  That will cause System.ConnsInbound to be 128 I believe (looks like 64 per GB of memory here: https://github.com/libp2p/go-libp2p/blob/master/p2p/host/resource-manager/limit_defaults.go#L345 since Kubo is using those same libp2p defaults: https://github.com/ipfs/kubo/blob/master/core/node/libp2p/rcmgr_defaults.go#L94).  As a result, in this particular setup, our high water mark may not get hit (unless there are sufficient outbound connections).  I know there isn't a perfect number here and we have no …
> feat: adjust ConnMgr to 32/96

- core/corehttp/webui.go
https://github.com/ipfs/ipfs-webui/releases/tag/v2.21.0
We need this fix in 0.18 (https://github.com/ipfs/kubo/issues/9417), otherwise Status screen in webui will fail when `/quic-v1` listener is enabled (https://github.com/ipfs/kubo/issues/9410).
> fix: support /quic-v1 in webui v0.21

- README.md
This was signalled in https://github.com/ipfs/kubo/issues/8576
> docs: review package managers section of the readme

- assets/dir-index-html/dir-index.html
- assets/dir-index-html/src/dir-index.html
- assets/dir-index-html/test/main.go
- config/gateway.go
- core/coreapi/unixfs.go
- core/corehttp/gateway.go
- core/corehttp/gateway_handler_unixfs_dir.go
- core/corehttp/gateway_indexPage.go
- docs/changelogs/v0.18.md
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/sharness/t0115-gateway-dir-listing.sh
Closes #9058.
Loads `bafybeiggvykl7skb2ndlmacg2k5modvudocffxjesexlod2pfvg5yhwrqm` (10k items) extremely fast, and with size!
> feat: fast directory listings with DAG Size column

- docs/EARLY_TESTERS.md
Removing QRI from early testers since the organization isn't operating.
This came up in https://github.com/ipfs/kubo/issues/9417#issuecomment-1349690750
> Removing QRI from early tester

- test/sharness/t0175-provider.sh
- test/sharness/t0240-republisher.sh
- test/sharness/t0600-issues-and-regressions-online.sh
This PR stabilizes some sharness tests by ensuring deterministic providers exist thanks to unique time-based CID (instead of hardcoded one). 
This should fix failing master.
> fix(test): stabilize flaky provider tests

- core/node/libp2p/routingopt.go
- docs/environment-variables.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- routing/composer.go
- test/sharness/t0172-content-routing-over-http.sh
Applying A solution from https://github.com/ipfs/kubo/issues/9504
Closes #9504
> fix: disable provide over HTTP with Routing.Type=auto

- core/node/libp2p/routingopt.go
- docs/environment-variables.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- routing/composer.go
- test/sharness/t0172-content-routing-over-http.sh
Closes https://github.com/ipfs/kubo/issues/9504
Is there a reason why we didn't merge https://github.com/ipfs/kubo/pull/9511 into `master`? As I understand the usual procedure is to merge stuff to `master` and then cherry-pick to `release` branch. Here we have a reversed order. This PR cherry-picks https://github.com/ipfs/kubo/commit/d6069b93ee8a2f23ca478fbc5938b5e9231a0f22 that's currently in https://github.com/ipfs/kubo/pull/9498 and proposes merging it to `master`.
> fix: disable provide over HTTP with Routing.Type=auto (#9511)

- docs/config.md
> docs: Add ProviderSearchDelay config param

- config/routing.go
> docs: fix Router config Godoc

- test/sharness/t0125-twonode.sh
- test/sharness/t0172-content-routing-over-http.sh
This PR is a sidequest to make is clear why flaky test fails:
```
expecting success:
ipfsi 0 bitswap stat > stat0 &&
test_should_contain "blocks sent: 126" stat0 &&
test_should_contain "blocks received: 5" stat0 &&
test_should_contain "data sent: 228113" stat0 &&
test_should_contain "data received: 1000256" stat0
'stat0' does not contain 'blocks sent: 126', it contains:
bitswap status
provides buffer: 0 / 256
blocks received: 5
blocks sent: 134
data received: 1000256
data sent: 231966
dup blocks received: 0
dup data received: 0
wantlist [0 keys]
partners [1]
not ok 31 - node0 data transferred looks correct
```
Seems this was always flaky, everyone just learned to re-run it.
I had no bandwidth to debug, but to save us all time, I made it retry until success or hits 60s timeout.
> fix(ci): retry flaky t0125-twonode.sh

- core/corehttp/gateway_handler.go
- test/sharness/t0123-gateway-json-cbor.sh
This PR fixes #9520 by adding basic support for `Accept` headers with a list of content types (pick the first matching one).
cc @hacdias if you have time to eyeball – would like to include this in 0.18.
Block/CAR responses introduced in https://github.com/ipfs/go-ipfs/pull/8758 always had single explicit type, and we did not bother with implementing/testing lists.
With the introduction of JSON  added in https://github.com/ipfs/kubo/pull/9335 (Kubo 0.18) people started passing a list, as noted in #9520.  
Note: this PR does not implement weights because afaik  [golang still does not include this in standard library](https://groups.google.com/g/golang-dev/c/5pOqD2wKpN4/m/G5rfULC2KZ0J), and I wanted to avoid adding dependency like https://github.com/aohorodnyk/mimeheader.  Returning the …
> fix(gateway): JSON when Accept is a list

- cmd/ipfs/daemon.go
- docs/changelogs/v0.18.md
cc https://github.com/ipfs/kubo/issues/9507
> feat: add warning if daemon uses an RSA peer id

- core/node/libp2p/routing.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/stats_test.go
Fixes `auto` from https://github.com/ipfs/kubo/issues/9482 but `custom` needs more work.
> fix: `stats dht` command when using default config.

- docs/README.md
Avoid confusion about what kind of documentation we have on this folder.
> docs: improve docs/README

- .github/workflows/docker-image.yml
- .github/workflows/gobuild.yml
- .github/workflows/sharness.yml
Fixes:
- the way in which we set `tags` step output
- where runner.yml workflow is sourced from
Changes:
- where we retrieve `DOCKER_USERNAME` from
> fix: docker image publishing and experimental gh workflow

- test/sharness/Rules.mk
- test/sharness/lib/download-saxon.sh
- test/sharness/lib/test-generate-junit-html.sh
Fixes #9551
My theory is that the problems with HTML report generation were caused by the fact that we generate both a multi-page report and a single-page report. Two separate tasks generate those. They both download Saxon. I think, sometimes, the errors were happening when the first task finished the download and started generation, while the second one only just started downloading and was trying to replace Saxon while the first task was using it.
This PR extracts Saxon downloading to a separate task that the generation tasks will depend on.
> fix: do not download saxon in parallel

- core/node/libp2p/rcmgr.go
- test/sharness/t0139-swarm-rcmgr.sh
Fixes: https://github.com/ipfs/kubo/issues/9549
> fix: refuse to start if soft ConnMgr limits are bigger than hard ResourceMgr limits

- config/init.go
- core/node/libp2p/rcmgr_defaults.go
- docs/libp2p-resource-management.md
- test/sharness/t0139-swarm-rcmgr.sh
> fix: ensure ConnMgr is smaller than autoscalled ResourceMgr limits

- .circleci/main.yml
- .github/workflows/build.yml
This PR aims to fix [circleci failrues](https://app.circleci.com/pipelines/github/ipfs/kubo/8779/workflows/6d37de2b-7501-43dc-9204-31a22e23db43), but also update to the lastest version.
- ipfs-interop fails to download libp2p-relay-daemon for the [similar reason](https://app.circleci.com/pipelines/github/ipfs/kubo/8792/workflows/d898c874-bc0f-4c48-98ef-a45bd300da29/jobs/95234?invite=true&invite=true#step-105-88) – json does not have expected field.
- ipfs-webui fails due to npm-go-ipfs line: ``const data = await got(`${distUrl}/go-ipfs/${version}/dist.json`).json()``  which fails [here](https://app.circleci.com/pipelines/github/ipfs/kubo/8792/workflows/7a65fee9-a2da-4f0a-9010-d421953f29eb/jobs/95231?invite=true#step-105-88)
- bumped to the latest versions from upstream repo …
> fix(ci): ipfs-interop and ipfs-webui

- core/corehttp/gateway_handler.go
- core/corehttp/gateway_handler_codec.go
- docs/changelogs/v0.18.md
- test/sharness/t0123-gateway-json-cbor.sh
In the spirit of https://github.com/protocol/bifrost-infra/issues/2290 and https://github.com/ipfs/specs/pull/328#pullrequestreview-1254267132, this PR removes implicit conversion from UnixFS/RAW to DAG-* when `json` is requested, and performs the conversion only when expliti `dag-json`  is present in the request.
We also fixed handling of CID with `json` and `cbor` codecs + added more tests.
Weird, unrelated things, are happening in the CI. – tracked in https://github.com/ipfs/kubo/pull/9570
> fix(gateway): undesired conversions to dag-json and friends

- core/commands/commands_test.go
- core/commands/name/name.go
- core/coreapi/name.go
- core/corehttp/gateway_test.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/sharness/t0100-name.sh
It turns out that the option `--ttl` in `ipfs name publish` was never being used, and all IPNS records were being published with a `TTL` of 0. This was happening because the TTL was being passed to a different package through context, but because types are different (and context is not designed for that), the value would never get to `namesys`.
I updated the required packages to add the options and consolidate `Publish` and `PublishWithEOL` into a single function with optional options. See linked PRs.
> fix: honour --ttl flag in 'ipfs name publish'

- core/commands/routing.go
- core/coreapi/coreapi.go
- core/coreapi/routing.go
- core/corehttp/gateway.go
- core/corehttp/gateway_handler.go
- core/corehttp/gateway_handler_ipns_record.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/sharness/t0124-gateway-ipns-record.sh
- test/sharness/t0170-legacy-dht.sh
- test/sharness/t0170-routing-dht.sh
Implementation of **IPIP-351**: IPNS Signed Records Response Format on HTTP Gateways (https://github.com/ipfs/specs/pull/351)
- The sharness test `put round trips (#3124)` was failing. I understand that it expected some output, but the test doesn't validate the output so it's not clear to me what it was. When refactoring the `Routing` API to the `CoreAPI` interface, I used the direct calls to the internal routing value store to get or put a value, instead of listening to events on the context field. 
This changes output of selected RPC commands (https://docs.ipfs.tech/reference/kubo/rpc/):
-  `/api/v0/dht/get`  and `/api/v0/routing/get` 
-  `/api/v0/dht/put`  and `/api/v0/routing/put`
```diff
-{
-  "Extra": "<string>",
-  "ID": "<peer-id>",
-  "Responses": [
-    {
-      "Addrs": [
- …
```
> feat(gateway): IPNS record response format (IPIP-351)

- docs/libp2p-resource-management.md
We have `const` which may change, let's use its name in user docs.
> docs: DefaultResourceMgrMinInboundConns

- cmd/ipfs/daemon.go
- config/gateway.go
- config/init.go
- core/corehttp/gateway.go
- core/corehttp/gateway_writable.go
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/sharness/t0111-gateway-writeable.sh
This PR updates the Gateway code to use the newer interface from `go-libipfs` (https://github.com/ipfs/go-libipfs/pull/145).
> refactor: new go-libipfs/gateway API, deprecate Gateway.Writable

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
See https://github.com/ipfs/go-libipfs/pull/155.
> chore: update go-libipfs for more gateway metrics

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
This include a fix where FindProvidersAsync with the parallel composer would not close the channel ASAP when the count was reached, this save finality time when count is reached.
> chore: bump go-libp2p-routing-helpers to v0.6.1

- core/commands/routing.go
- test/sharness/t0170-routing-dht.sh
Partially addresses #9638. I can only revert the wire format for `routing/get`. For `put`, we would need more information from the `.Routing.Put` to tell us in which peers the record was stored. However, that implies we would need to change the interface yet again. I would rather not do it, or do it in a different PR.
Closes #9638
> fix: restore wire format for /api/v0/routing/get

- docs/changelogs/v0.18.md
Every team I talk with has some random ResourceMgr limits set up, usually invalid.
It is way better if we ask  people to start fresh.
> docs(0.18.1): guide users to clean up limits

- docs/libp2p-resource-management.md
Being more clear that the "remote" string means its from a remote peer.
This came up in:
https://github.com/ipfs/kubo/issues/9432#issuecomment-1402022085
https://github.com/ipfs/kubo/issues/9432#issuecomment-1402276883
https://github.com/ipfs/kubo/issues/9432#issuecomment-1410444354
> docs: "remote" errors from resource manager 

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/gateway_test.go
> fix(gateway): return HTTP 500 on namesys.ErrResolveFailed

- core/coreapi/block.go
- core/coreapi/dag.go
- core/coreapi/object.go
- core/coreunix/add.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
Tandem PR with https://github.com/ipfs/go-ipfs-pinner/pull/23
Will obviously need to have a proper release for `go-ipfs-pinner`.
> feat(pinning): connect some missing go context

- core/commands/bitswap.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/gateway_test.go
See https://github.com/ipfs/go-libipfs/pull/182.
Requires:
> feat(gateway): error handling improvements (500, 502, 504)

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
[v0.26.1](https://github.com/libp2p/go-libp2p/releases/tag/v0.26.1) contains two fixes that should probably make it into the final release.
> chore: update go-libp2p to v0.26.1

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-build.yml
- .github/workflows/docker-image.yml
- .github/workflows/gobuild.yml
- .github/workflows/golang-analysis.yml
- .github/workflows/golint.yml
- .github/workflows/gotest.yml
- .github/workflows/runner.yml
- .github/workflows/sharness.yml
- .github/workflows/sync-release-assets.yml
This PR sets timeouts on GHA jobs. The values are quite generous because we want the timeouts to only catch degenerate cases - tests never finishing for example - that would have otherwise keep running for 6 hours (I noticed that being the case for a sharness job and an interop job). I looked at https://protocollabs.grafana.net/d/gieYOhbVk/github-actions-ipfs-kubo?orgId=1&from=now-3d&to=now to come up with value proposals.
> ci: set sensible timeouts on all gha jobs

- Rules.mk
By default, `go install` will install go $GOBIN and not $GOPATH. In most cases there is no functional difference -- `go install` falls back to $GOPATH when $GOBIN is empty.
> fix: typo in documentation for install path

- docs/EARLY_TESTERS.md
This PR sorts early testers list and adds bifrost to it.
@gmasgras Early testers are mentioned in a comment in a Kubo release issue every time a new Kubo release (including RCs) is available. This signal is to replace the protocol/bifrost-infra issues that we've been creating in the past (related to https://github.com/ipfs/kubo/issues/9574).
Should we be mentioning anyone other bifrost team members?
> docs: add bifrost to early testers

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
This does nothing, just move from an untagged commit to a tagged commit but contain the same things.
> chore: bump go-libipfs v0.6.1

- fuse/node/mount_test.go
- repo/fsrepo/config_test.go
- repo/fsrepo/fsrepo_test.go
- test/bench/bench_cli_ipfs_add/main.go
- test/bench/offline_add/main.go
A testing cleanup. 
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
if err != nil {
t.Fatal(err)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
> test: use `T.TempDir` to create temporary test directory

- test/cli/rcmgr_test.go
- test/cli/testutils/asserts.go
example flake: https://app.circleci.com/pipelines/github/ipfs/kubo/9370/workflows/f817e02d-3d2a-43ab-b090-e95a5bcd34b5/jobs/101311
> test: fix flaky rcmgr test

- core/node/libp2p/rcmgr.go
- core/node/libp2p/rcmgr_defaults.go
- test/cli/rcmgr_test.go
> fix: preserve Unlimited StreamsInbound in connmgr reconciliation

- core/corehttp/redirect.go
- test/cli/gateway_test.go
> fix: apply API.HTTPHeaders to /webui redirect

- core/corehttp/gateway_writable.go
- core/corehttp/redirect.go
@lidel I did not use `.Set` because that does not allow us to define multiple values, which the user can.
> Set sets the header entries associated with key to the single element value. It replaces any existing values associated with key. https://pkg.go.dev/net/http#Header.Set
> fix: canonicalize user defined headers

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
Required by https://github.com/ipfs/kubo/issues/9502#issuecomment-1475294853
> chore: update go-libp2p to v0.26.3

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/gateway_test.go
- test/sharness/t0090-get.sh
See https://github.com/ipfs/go-libipfs/pull/205.
> feat(gateway): invalid CID returns 400 Bad Request

- docs/plugins.md
In practice there are cases when fx.Replace doesn't work as expected, so this updates the documentation to recommend using fx.Decorate instead which is a bit easier to use.
> docs: use fx.Decorate instead of fx.Replace in examples

- core/commands/dag/import.go
This fixes a deadlock introduced in 1457b4fd4abff0bdcdccbacc26934cb7fa8e8a43.
We can't use the coreapi here because it will try to take the PinLock (RLock) again, so revert this small part of 1457b4fd4abff0bdcdccbacc26934cb7fa8e8a43.
This used cause a deadlock when concurrently running `ipfs dag import` concurrently with the GC.
The bug is that `ipfs dag import` takes an RLock with the PinLock. *the cars are imported, leaving a wide window of time* Then GC Takes a Lock on that same RWMutex while taking the GC Lock (it  blocks because it waits for the RLock to be released). Then the car imports are finished and `ipfs dag import` tries to aqcuire the PinLock (doing an RLock) again in `Api().Pin`.
However at this point the RWMutex is starved, the runtime put a fence in front of RLocks if a …
> fix: deadlock while racing `ipfs dag import` and `ipfs repo gc`

- test/integration/pubsub_msg_seen_cache_test.go
This test flakes very often and we plan on removing this feature entirely, so disabling this test since its failures are pretty disruptive.
> test: skip flaky pubsub test

- test/cli/dht_autoclient_test.go
- test/cli/harness/buffer.go
The test trims all whitespace bytes from the output of 'ipfs cat' but if the random bytes end in a whitespace char then it trims that too, resulting in random test failure.
Instead this updates the test harness to only trim a single trailing newline char, so that it doesn't end up chomping legitimate output.
> test: fix autoclient flakiness

- core/commands/swarm.go
- test/cli/harness/peering.go
- test/cli/peering_test.go
- test/cli/swarm_test.go
It adds the feature requested on [#9578](https://github.com/ipfs/kubo/issues/9578). This PR adds a new opt-in flag called identify that adds Identify values to the command output.
> feat: add identify option to swarm peers command

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-build.yml
- .github/workflows/gobuild.yml
- .github/workflows/golang-analysis.yml
- .github/workflows/golint.yml
- .github/workflows/gotest.yml
- .github/workflows/sharness.yml
This is pretty common when working through PRs and ends up causing tons of in-flight GitHub Actions workflows running because they aren't currently canceled when a new commit is added. This will cancel previous runs if a new commit is added on a branch (which is the behavior we had on CircleCI).
> test: cancel workflows on same branch when new commit is added

- .github/workflows/build.yml
This PR ignores some of the js-js interop test cases which were previously run by default by https://github.com/ipfs/interop
It does so by passing a `grep` argument which uses negative lookahead to exclude test case names that include:
- either `js(:number:)? -> js(:number)?`
- or `js-js-js`
> ci: ignore js-js interop test cases

- core/core.go
- core/coreapi/coreapi.go
- core/coreapi/path.go
- core/node/core.go
- core/node/groups.go
- fuse/readonly/readonly_unix.go
In order to make it possible to easily-overwrite the path Resolvers (i.e. via plugins), this creates resolvers as part of the Node rather than creating them ad-hoc.
> Allow injecting custom path resolvers.

- .github/workflows/gotest.yml
Compare this test run with https://github.com/ipfs/kubo/actions/runs/4610952102, test run time decreases from 7 min to 2 min.
> test: use self hosted runner for go tests

- core/node/libp2p/routing.go
- core/node/libp2p/routingopt.go
- docs/changelogs/v0.19.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- version.go
This PR creates release v0.19.1
> Release: v0.19.1

- docs/environment-variables.md
Ports were colliding (two ports were being assigned to the same local port).
> docs: fix jaeger command

- .github/workflows/docker-image.yml
- Dockerfile
Building [docker images in this repo](https://github.com/ipfs/kubo/actions/workflows/docker-image.yml) takes ~1h:
>  ![2023-04-06_14-28](https://user-images.githubusercontent.com/157609/230378816-f919c981-c6dd-449b-91d2-df87a1e97eab.png)
This PR is doing two things (iiuc -- please verify my assumptions :pray: ):
- speed up arm builds by allowing cross-comp from go instead of slow QEMU
- take a stab at caching buildx layers, without infinite growth
- works with both `docker buildx build` and the regular `docker build`
This fix was already applied in https://github.com/ipfs/bifrost-gateway/commit/14cfa48bed514fb8b865d41df3cecb5f827e54ab and seems to reduce [docker build times there](https://github.com/ipfs/bifrost-gateway/actions/workflows/docker-image.yml) from **20m** to **3m** …
> fix(ci): speed up docker build

- config/experiments.go
- core/node/libp2p/host.go
- core/node/libp2p/routingopt.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- docs/experimental-features.md
- go.mod
- go.sum
- test/cli/dht_opt_prov_test.go
- test/cli/harness/node.go
- test/cli/testutils/random.go
This adds the ability to enable "optimistic provide" to the default
DHT client, which enables faster provides and reprovides.
For more information about optimistic provide, see:
https://protocollabs.notion.site/Optimistic-Provide-2c79745820fa45649d48de038516b814
Note that this feature only works when using non-custom router
types. This does not include the ability to enable optimistic provide
on custom routers for now, to minimize the footprint of this
experimental feature. We intend on continuing to test this and improve
the UX, which may or may not involve adding configuration for it to
custom routers. We also plan on refactoring/redesigning custom routers
more broadly so I don't want this to add more effort for maintainers
and confusion for users.
> feat: add experimental optimistic provide

- test/ipfs-test-lib.sh
- test/sharness/t0002-docker-image.sh
- test/sharness/t0003-docker-migrate.sh
GH Actions recently changed their Docker build implementation and it has a different output than previously, causing the tests that parse its output to fail.
This switches the test to not parse Docker build output. The parsing was used to extract the image ID while still showing logs. A better way to show logs and still know the image ID is to tag it, which is what this now does.
This also renames the Docker tests so that they run earlier. This takes better advantage of the fact that the sharness tests are run in parallel. Since the Docker test are quite long, and are at the end of the list, the test runner is not running other tests in parallel while the Docker tests are running.
> test: fix Docker tests in GH Actions

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
This lets Kubo discover our public webtransport addrs.
> deps: bump go-libp2p to v0.27.1

- cmd/ipfs/daemon.go
- core/node/groups.go
- core/node/libp2p/routing.go
- core/node/libp2p/routingopt.go
I wrote some tests for this but I couldn't get them to be non-racy, so I'm excluding from this for expediency's sake. I'll keep trying to get them to work and hopefully I can include them in a followup PR. We don't otherwise have any integ tests for the accelerated DHT client.
Otherwise, I tested this by running locally and looking at the prometheus metrics.
> fix: use default HTTP routers when FullRT DHT client is used

- core/mock/mock.go
- core/node/groups.go
- core/node/libp2p/addrs.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/harness/peering.go
- test/cli/transports_test.go
Fixes #9838.
Notes:
- Public Slack thread: https://filecoinproject.slack.com/archives/C03K82MU486/p1683208653452199
> fix: deadlock on retrieving WebTransport addresses 

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/content_routing_http_test.go
- test/cli/delegated_routing_http_test.go
Updates Kubo with https://github.com/ipfs/boxo/pull/18. 
This is blocking other PRs, such as https://github.com/ipfs/boxo/pull/292.
> feat: update boxo with routing streaming

- core/commands/name/name.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
Sister PR in boxo: https://github.com/ipfs/boxo/pull/294
Extracts the ipns verification code out of kubo to boxo. This makes the verification code reusable, for example, with gateway-conformance testing (https://github.com/ipfs/gateway-conformance/pull/37)
Relates to https://github.com/ipfs/specs/issues/376
> feat: reusable ipns verify

- docs/RELEASE_ISSUE_TEMPLATE.md
- docs/releases_thunderdome.md
The Thunderdome testing will probably need additional documentation as we refine the process, and it's complicated enough that putting it inline in the release checklist is a bit much, so I've split it into its own file.
> docs: add Thunderdome docs for releases

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/gateway_test.go
Closes https://github.com/ipfs/kubo/issues/9749
Do not use base58-encoded multihash peer IDs for IPNS tests. Required for https://github.com/ipfs/boxo/pull/236, otherwise tests will fail since we will be redirecting. Redirection tests are included in the referenced PR.
> feat(gateway): redirect /ipns/b58mh to /ipns/cidb36

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/content_routing_http_test.go
Tests are failing in Boxo PRs because of https://github.com/ipfs/boxo/commit/a8533c998f499d23284774a07e976c383a2e29af.
Updates Boxo and fixes the test function signature.
> chore: upgrade boxo and fix test function signature

- config/gateway.go
- core/corehttp/gateway.go
- core/corehttp/gateway_test.go
- docs/changelogs/v0.21.md
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/gateway_test.go
Pair PR of https://github.com/ipfs/boxo/pull/252.
I simply update Kubo to use the new configuration structure and I keep **all the defaults of Kubo**, that is, everything is a **trusted gateway** unless `DeserializedResponses` is set to `false` in the configuration. Also added a simple test to check if `DeserializedResponses` is honoured. Further tests can be found in Boxo.
Steps:
> feat: Gateway.DeserializedResponses config flag

- client/rpc/README.md
- client/rpc/api.go
- client/rpc/api_test.go
- client/rpc/apifile.go
- client/rpc/block.go
- client/rpc/dag.go
- client/rpc/dht.go
- client/rpc/errors.go
- client/rpc/errors_test.go
- client/rpc/key.go
- client/rpc/name.go
- client/rpc/object.go
- client/rpc/path.go
- client/rpc/pin.go
- client/rpc/pubsub.go
- client/rpc/request.go
- client/rpc/requestbuilder.go
- client/rpc/response.go
- client/rpc/routing.go
- client/rpc/swarm.go
- client/rpc/unixfs.go
- docs/changelogs/v0.21.md
- docs/http-rpc-clients.md
Migration will happen with stub types pushed at: https://github.com/ipfs/go-ipfs-http-client/pull/180
this our last PR cycle with `go-ipfs-http-client` so I'll merge this here first and update kubo's version in `go-ipfs-http-client` once kubo v0.21.0 is released.
> client/rpc: rename package name to match rpc and edit migration story

- core/commands/root.go
- core/commands/routing.go
- test/cli/routing_dht_test.go
> fix: 'ipfs routing findpeer' explicitly fails when searching for self

- client/rpc/pin.go
- core/commands/pin/pin.go
This also fix a leaking goroutine bug on `client/rpc.PinAPI.Ls`, we would deadlock if context was canceled while writing the keys.
> client/rpc: use streaming pin listing

- core/commands/dag/stat.go
- docs/changelogs/v0.21.md
> docs: changelog for dag stat

- cmd/ipfs/daemon.go
- core/core_test.go
- core/node/libp2p/routingopt.go
- core/node/libp2p/routingopt_test.go
Fixes https://github.com/ipfs/kubo/issues/9823
CC @lidel
> fix: correct list of addresses for delegated routing

- core/node/libp2p/rcmgr.go
- test/sharness/t0060-daemon.sh
This was proposed by @lidel as an easy alternative to #9826.
It helps by trimming down the wall of text:
```console
$ ipfs daemon
Kubo version: 0.21.0-dev
Repo version: 14
System version: amd64/linux
Golang version: go1.19.10
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/127.0.0.1/udp/4001/quic-v1
Swarm listening on /ip4/127.0.0.1/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
Swarm listening on /ip4/172.17.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/udp/4001/quic
Swarm listening on /ip4/172.17.0.1/udp/4001/quic-v1
Swarm listening on /ip4/172.17.0.1/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4 …
```
> fix: print rcmgr to logger

- .github/workflows/build.yml
- core/corehttp/webui.go
use https://github.com/ipfs/ipfs-webui/releases/tag/v4.0.1
> feat: webui@4.0.1

- core/commands/dag/dag.go
- core/commands/dag/import.go
This PR aims to improve UX  of importing broken (truncated)  CARs.
Most of the time, the error during `ipfs dag import` is caused by either a bitflip in one of the blocks, or a truncation of the car stream. This PR improves returned error with context that allows the user to understand what happened, and at which place in the car stream, making debug more humane:
```console
$ ipfs dag import ./truncated.car
Error: import failed after block "bafkreieyn4jhc5ht6qmhhqklqi2xvq3mjgn6z5r5mi4ri4hyvpaq3ojvde": unexpected EOF
```
Also, improved pin error on partial CAR import:
```console
$ curl -v 'http://127.0.0.1:8080/ipns/docs.ipfs.tech?format=car&dag-scope=entity' > ./partial-entity.car # Kubo 0.21.0-rc1 with IPIP-402
```
Before: 
```console
$ ipfs dag import --stats --pin-roots=true …
```
> fix(cmd): useful errors in dag import

- Dockerfile
Fixes: #8725
When running the health check command without passing the `--api` command line flag and if the Kubo daemon is not active, executing `ipfs dag stat` will initialize the repository. It is common for the health check command to be run with root privileges. As a result, the repository will be owned by the root user. Then, if the Kubo daemon process attempts to access the repository later on, it will encounter a permission denied error because it runs as a non-privileged user by default.
Hence, this PR simply provides the `--api` flag to the `ipfs dag stat` command. Given that we are operating on a docker container, we can make some assumptions. I can't come up with a scenario where one would desire to assign a different port to the internal API rather than using the default 5001. …
> fix: docker repository initialization race condition

- .github/workflows/build.yml
Following up on https://github.com/ipfs/kubo/pull/9813#discussion_r1230014449
This will be tested by CI
> ci: fix checking state of CI in ipfs-webui

- config/init.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- test/sharness/t0112-gateway-cors.sh
This PR closes #9983 which is regression since 0.20.
We should include this fix  in Kubo 0.21 (https://github.com/ipfs/kubo/issues/9814).
Depends on https://github.com/ipfs/boxo/pull/395
> fix(gateway): include CORS on subdomain redirects

- config/config.go
- config/types.go
- plugin/loader/loader.go
readPluginsConfig was copied from ReadMigrationConfig and switched  erroring fields to a bool so it can be omitemptied.
> fix: correctly handle migration of configs

- docs/config.md
https://github.com/ipfs/kubo/pull/9994 made these defaults implicit  (defined in boxo if missing from user config) + these values in docs were out of date anyway.  This PR reflects the current state of things.
> docs: Gateway.HTTPHeaders

- .github/workflows/build.yml
Follow up from https://github.com/ipfs/kuboreleaser/issues/3
> ci: disable js-rv-js tests in interop

- .github/workflows/build.yml
- Dockerfile
- config/config.go
- config/init.go
- config/types.go
- docs/changelogs/v0.21.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- plugin/loader/loader.go
- test/dependencies/go.mod
- test/dependencies/go.sum
- test/sharness/t0112-gateway-cors.sh
- version.go
This PR creates release v0.21.0 (https://github.com/ipfs/kubo/issues/9814).
This release is **scheduled for Monday 2023-07-04.**
> Release: v0.21.0

- .github/pull_request_template.md
- .github/workflows/build.yml
- .github/workflows/changelog.yml
Related to https://github.com/ipfs/boxo/pull/398
This PR adds a CI workflow which checks whether the PR contains docs/changelogs/ modifications. 
The check can be skipped by either adding `[skip changelog]` to the PR title or labelling the PR with `skip/changelog`. These instructions are included in the PR template and in the workflow failure message.
The check succeeds if docs/changelogs/ was modified and fails otherwise.
Tested in https://github.com/galargh/.github/pull/40
---
If we ever decide to use this beyond kubo/boxo, we should consider turning this into a reusable workflow.
> ci: add changelog update checker workflow [skip changelog]

- docs/RELEASE_ISSUE_TEMPLATE.md
Every time we bump IPFS Desktop, we should also ask Brave to upgrade.
I do this every time but would be good to make it part of the checklist. 
It is handled by Brave team, they use `dist.ipfs.tech` artifacts, so all we need to do is to fill issue in their bug tracker.
@galargh  issue creation is just copying&pasting + updating number in links, would it be possible to automate via something like `./kuboreleaser release --version vX.Y.Z(-rcN) update-brave` ?
> docs: add Brave to RELEASE_ISSUE_TEMPLATE.md

- docs/changelogs/v0.22.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Adds support for IPIP-412 parameters.
> feat(gateway): support for ipip-412 parameters

- core/node/libp2p/routing.go
- core/node/libp2p/routingopt.go
- docs/changelogs/v0.22.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- routing/delegated.go
That means if the DHT has finished searching and no one responded over pubsub *yet*, we will not spend 1 minute searching for no reason.
This also include other error handling bug fixes inside `go-libp2p-routing-helpers`.
Fixes: #9927
Depends on https://github.com/libp2p/go-libp2p-routing-helpers/pull/75
> fix: mark all routers DoNotWaitForSearchValue

- .github/workflows/docker-build.yml
- .github/workflows/docker-image.yml
- Dockerfile
- bin/container_daemon
This change splits the builder stage into builder and utilities stages. This is to make the distinction between buildtime and runtime dependencies clearer. More importantly, this makes sure that the runtime dependencies we download are for the target platform.
It also install `tini` and `su-exec`* from APT repository rather than GitHub. This makes the installs simpler because we don't have to checkout git repos anymore.
Finally, it replaces `su-exec` with `gosu`. This is because `su-exec` is not distributed through APT. However, `gosu` comes in at around 2MB while `su-exec` is ~20KB. Let me know if we should go back to `su-exec` for the size benefits.
This PR adds bare minimum testing of produced images. It adds it to both `docker-build` and `docker-image` workflows (Should we get rid of …
> ci: simplify Dockerfile and add docker image testing

- .github/workflows/build.yml
- docs/RELEASE_ISSUE_TEMPLATE.md
> ci: switch from testing against js-ipfs to helia

- .github/workflows/gateway-conformance.yml
- docs/changelogs/v0.21.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- version.go
Depends on https://github.com/ipfs/boxo/pull/425
For #10048
> Release v0.21.1

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
> chore: bump go-libp2p v0.29.2

- config/swarm.go
- core/node/libp2p/smux.go
- docs/changelogs/v0.23.md
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/transports_test.go
This is a partial revert of 7220409394005c85509448217686e79b1779554b.
Closes #9958
> feat: allow users to optin again into mplex

- core/commands/cid.go
- core/commands/pin/pin.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- gc/gc.go
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- thirdparty/verifbs/verifbs.go
This is a Q&D fix to get kubo building again, this is completely equivalent to what we used to have. I'll submit a patch that DI the verifcid.Allowlist interface with fx later but this is needed to unblock something else.
> chore: bump boxo for verifcid breaking changes

- .github/workflows/gotest.yml
- README.md
- core/commands/commands.go
- core/commands/commands_test.go
- core/commands/completion.go
- docs/command-completion.md
- test/cli/completion_test.go
This PR is related to #8908 issue.
[add zsh support](https://github.com/ipfs/kubo/commit/8b08765b989281ccefbee1f274e422da9bc733f6)
[add zsh to doc](https://github.com/ipfs/kubo/commit/df91baa5e2c225aaa9a52fa1b3419e255366ed83)
> feat: add zsh completions

- .github/workflows/gateway-conformance.yml
Upload the JSON logs as an artifact that the dashboard generation scripts can retrieve and process.
Support for https://github.com/ipfs/gateway-conformance/pull/146
> ci: upload conformance logs

- Dockerfile
Because Kubo is the part changing more often it's better to copy after so docker can reuse the utilities layers.
> dockerfile: reorder copy order for better layer caching

- fuse/readonly/readonly_unix.go
the underlying error when a protobuf is not able to be converted as expected during a fuse read is not being lost but silently dropped
> [skip changelog] improve error in fuse node failures

- docs/experimental-features.md
"Accelerated DHT Client" is no longer an experimental feature and the link I'm suggesting to remove is currently pointing nowhere.
This is a minor change but I think it will avoid confusion.
> docs: remove link to deleted #accelerated-dht-client [skip changelog]

- repo/fsrepo/fsrepo.go
- repo/fsrepo/migrations/fetcher.go
https://github.com/ipfs/distributions/pull/1001
> chore: bump repo version to 15

- .github/workflows/build.yml
- .github/workflows/gobuild.yml
- .github/workflows/golint.yml
- .github/workflows/gotest.yml
- .github/workflows/sharness.yml
https://github.com/ipfs/kubo/pull/9976 updated setup-go action to v4, which comes with cache enabled by default. We can now remove our custom go caching action.
> ci: remove obsolete protocol/cache-go-action

- docs/changelogs/v0.22.md
The IPIP got merged, this updates changelog for 0.22 with link to latest validation spec.
> docs(changelog): link to relevant IPIP-428

- fuse/readonly/readonly_unix.go
> docs: fix typo [skip changelog]

- client/rpc/dht.go
- client/rpc/swarm.go
- config/init.go
- core/commands/dht_test.go
- core/commands/name/ipns.go
- core/commands/ping.go
- core/commands/pubsub.go
- core/commands/routing.go
- core/commands/swarm.go
- core/coreapi/test/api_test.go
- core/node/builder.go
- core/node/libp2p/hostopt.go
- core/node/libp2p/rcmgr.go
- fuse/ipns/ipns_test.go
- fuse/ipns/ipns_unix.go
- p2p/local.go
- p2p/remote.go
- plugin/plugins/peerlog/peerlog.go
The `go-libp2p` peerID Pretty method is already deprecated, switch it to call String method.
Signed-off-by: Icarus9913 [icaruswu66@qq.com](mailto:icaruswu66@qq.com)
> refactor: stop using go-libp2p deprecated peer.ID.Pretty

- .github/workflows/build.yml
- .github/workflows/docker-build.yml
- .github/workflows/gateway-conformance.yml
- .github/workflows/gobuild.yml
- .github/workflows/golang-analysis.yml
- .github/workflows/golint.yml
- .github/workflows/gotest.yml
- .github/workflows/sharness.yml
- Dockerfile
> chore: update to build with Go 1.21

- repo/fsrepo/migrations/fetcher.go
> migration: update 14-to-15 to v1.0.1

- repo/fsrepo/migrations/httpfetcher.go
- repo/fsrepo/migrations/migrations.go
This is a quick fix which replaces `ipfs.io` with `dweb.link` to allow users who's ISP is blocking ipfs.io gateway ([like COX.NET here](https://github.com/ipfs/ipfs-desktop/issues/2572#issuecomment-1725932197)) to still benefit from HTTPS mirror.
I've confirmed this works (v0.18.0→v0.22.0), because golang's http client follows redirect to subdomain gateway:
```console
Run migrations now? [y/N] y
[...]
Downloading migration: fs-repo-13-to-14...
Fetching with HTTP: "https://dweb.link/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/versions"
Fetching with HTTP: "https://dweb.link/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/v1.0.0/fs-repo-13-to-14_v1.0.0_linux-amd64.tar.gz"
Downloaded and unpacked migration: …
```
> fix(migrations): use dweb.link instead of ipfs.io

- config/gateway.go
- core/corehttp/gateway.go
- docs/changelogs/v0.23.md
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/gateway_test.go
- test/dependencies/go.mod
- test/dependencies/go.sum
Context: https://github.com/ipfs/boxo/pull/463
> feat: add Gateway.DisableHTMLErrors option

- core/bootstrap/bootstrap.go
- core/bootstrap/bootstrap_test.go
- core/core.go
A panic occurs when the first bootstrap round runs is these functions are not assigned in the configuration:
- `LoadBackupBootstrapPeers`
- `SaveBackupBootstrapPeers`
This fix assumes that it is acceptable for these functions to be `nil`, as it may be desirable to disable the backup peer load and save functionality.
> core/bootstrap: fix panic without backup bootstrap peer functions

- docs/config.md
- docs/delegated-routing.md
- docs/experimental-features.md
This PR adds "Amino" is places where we meant "Public IPFS DHT" / WAN thing implemented in [go-libp2p-kad-dht](https://github.com/libp2p/go-libp2p-kad-dht/)
Context: https://github.com/ipfs/ipfs/discussions/473
> docs: s/ipfs dht/amino dht/

- Dockerfile
I am not certain if such a small change needs a changelog, as there is no actual change in the IPFS behaviour.
Closes #10134
> fix(docker): allow nofuse builds for MacOS

- README.md
This cosmetic PR applies some improvements from https://github.com/ipfs/npm-kubo, links to community chat and forum, and improves "featureset" section.
Creates better first impression:
> ![Screenshot 2023-09-22 at 19-36-14 kubo_README md at 1f827543da8cba99fcda173d6edc13022de89c56 · ipfs_kubo](https://github.com/ipfs/kubo/assets/157609/6a31c3a3-3c39-42b5-86a5-3197280cc6bb)
> docs(readme): header improvements

- docs/changelogs/v0.23.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Fixes #9044 = regression introduced in 0.13.0 of FUSE access to some files
> Update go-unixfsnode to 1.8.0

- .github/workflows/build.yml
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Helia CI started fialing on 2023/09/26 for some reason.
https://github.com/ipfs/kubo/actions/runs/6310698354/job/17133242193
This is trying to fix this but right now is unsuccessful, this removes workarounds that are not relevant anymore.
> Fix helia ci

- core/commands/cid.go
- core/commands/cid_test.go
This fixes #9556 
I'm some sort of beginner when it comes to contributing to open source. I think the tests could be better (I just don't know how), especially the second test since I couldn't read the response body to compare with the expected CID. So in the second test case the only test is really just asserting no error is returned.
I see in the pull request a message telling me to update "docs/changelogs", since I don't know what to update on it I won't touch it.
> fix: error when v -0 is present and custom -b is passed && upgrade CID to V1 when custom -b is present and -v is not specified

- CHANGELOG.md
- core/corehttp/gateway.go
- docs/changelogs/v0.24.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/gateway_range_test.go
- test/dependencies/go.mod
- test/dependencies/go.sum
> feat(gateway): update gateway api, no multi-range support

- misc/README.md
- misc/systemd/ipfs-hardened.service
- misc/systemd/ipfs.service
The current documentation (cmd/ipfs/dist/README.md), installation scripts, and Docker files all indicate that the default installation path for the IPFS binary is **/usr/local/bin/ipfs**. Moreover, following the official installation guide [here](https://docs.ipfs.tech/install/command-line/#install-official-binary-distributions) also places the binary in **/usr/local/bin/.**
However, the systemd service files reference a different path **(/usr/bin/ipfs**), which can lead to inconsistencies and potential operational issues.
This PR adjusts the systemd unit files to align with the predominant and documented installation path, ensuring consistency and reliability for users following the official guidelines.
> Align systemd unit file with the default IPFS installation path

- README.md
I believe that this was using the OpenSSL "feature" of go-libp2p, which we removed a couple of releases ago. I couldn't find any `openssl` build tag in Kubo nor in Boxo, but I haven't checked any other dependencies than that.
> remove OpenSSL section from README

- docs/config.md
In the examples for the "PublicGateways" config setting, remove extra commas in the JSON so it will not throw syntax errors
> docs/config: remove extra commas in PublicGateways example entries

- docs/experimental-features.md
This ensures https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#accelerated-dht-client still works and points people at new config option.
> docs: fix accelerated-dht-client

- docs/changelogs/v0.24.md
- docs/config.md
I missed the addition of WebRTC Direct and read about it in changelog and took me a moment to understand how to enable it :sweat_smile: 
This PR sets the expectations as "not production ready", but also gives users hint how to enable it via [`Swarm.Transports.Network.WebRTCDirect`](https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmtransportsnetworkwebrtcdirect) and by adding `/udp/4001/webrtc-direct` listener.
> docs(changelog): clarify webrtc in v0.24

- core/commands/dns.go
Seems we've introduced regression to the deprecated  `dns` command, it now requires `/ipns/` path, which breaks every software which used it for DNSLink lookups.
It was already deprecated, so no need for patch release, but let's fix it and improve helptext that is displayed at https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-dns  when the next release ships.
```consome
$ ipfs dns dist.ipfs.tech
Error: invalid path "dist.ipfs.tech": path does not have enough components
```
```consome
$ ipfs dns dist.ipfs.tech
/ipfs/QmXZX3Jiw2p1DKyShCKCbfNBCEL7eYW57B1asPr8FKPPmm
```
> fix: regression in 'ipfs dns'

- client/rpc/auth/auth.go
- cmd/ipfs/daemon.go
- cmd/ipfs/main.go
- config/api.go
- config/api_test.go
- core/commands/config.go
- core/commands/root.go
- core/corehttp/commands.go
- docs/changelogs/v0.25.md
- docs/config.md
- test/cli/auth_test.go
- test/cli/harness/node.go
- test/cli/rpc_auth_test.go
Closes #10187 ← see design requirements and purpose there. 
I tried not to touch [`go-ipfs-cmds`](https://github.com/ipfs/go-ipfs-cmds). However, what I did in Kubo could've been done there too.
Closes #1532
Closes #2389
CC https://github.com/ipfs/ipfs-webui/issues/1586 https://github.com/ipfs/go-ipfs-api/issues/172 
--- 
This PR provides Kubo users with a basic HTTP Auth primitives for locking the RPC API down, and exposing only a subset of commands per access token defined in `API.Authorization` map. 
Future work, such as UCANs mentioned [here](https://github.com/ipfs/kubo/issues/1532#issuecomment-976425630), or sandboxing MSF, keys, IPNS names per user hinted [here](https://github.com/ipfs/kubo/issues/10187#issue-1968824281), could be built on top of this at a later time.
> feat(rpc): Opt-in HTTP RPC API Authorization

- docs/config.md
> docs: clarify WebRTCDirect cannot reuse the same port as QUIC

- core/corehttp/webui.go
- docs/changelogs/v0.25.md
CID `bafybeidf7cpkwsjkq6xs3r6fbbxghbugilx3jtezbza7gua3k5wjixpmba`
--- 
* peers table can be filtered ([#2181](https://github.com/ipfs/ipfs-webui/issues/2181)) ([37b5880](https://github.com/ipfs/ipfs-webui/commit/37b5880fa0bca201e04737e3e4de0d48283eb95a))
* **pinning:** add Scaleway pinning service ([#2132](https://github.com/ipfs/ipfs-webui/issues/2132)) ([0cc3b04](https://github.com/ipfs/ipfs-webui/commit/0cc3b0495bc9895cf9b7520eaec7a0c0e94e6a30))
* error loading scaleway template URL ([7a3388e](https://github.com/ipfs/ipfs-webui/commit/7a3388e3d17560d3e376e57361dd78b8c7fdf8e9))
* replace estuary with web3 for pinning ([#2182](https://github.com/ipfs/ipfs-webui/issues/2182)) ([e2fc7c8](https://github.com/ipfs/ipfs-webui/commit/e2fc7c8a92d737e2f1cfadb360b06fbe3d54748f))
* status page …
> chore: webui v4.2.0 [skip changelog]

- core/commands/name/ipns.go
- core/commands/resolve.go
this fixes lint errors in RPC docs that were raised by vole in https://github.com/ipfs/ipfs-docs/pull/1772
so we don't get them in kubo 0.25
> docs(cli): fix spelling

- client/rpc/key.go
- core/commands/commands_test.go
- core/commands/keystore.go
- core/coreapi/key.go
- core/coreiface/key.go
- core/coreiface/tests/key.go
- docs/changelogs/v0.25.md
Closes #10230 by adding `key sign|verify` commands that facilitate offline key ownership proofs.
Notes:
- Output response is a bit different than the suggested in #10230 in order to match the remaining `key/*` endpoints. Similarly, `Err` field is not included as there's already a common way for the API to error, and that is not by adding a field to the output.
- In `key/verify`, the signature URL param is base64url encoded. None of the other things have to be encoded. The rest of the binary data goes in the body, so it does not relate to the issues in #7939.
- `self` is used as a default key. Happy to change this.
- Paid some debt by changing the current key tests to `require.` and `assert.`
- ⚠️ Helia test failures tracked on [Slack](https://filecoinproject.slack.com/archives/C04M8232QRW/ …
> feat: ipfs key sign|verify

- cmd/ipfs/daemon.go
- test/cli/daemon_test.go
- test/cli/harness/ipfs.go
> fix: allow daemon to start correctly if the API is null

- docs/http-rpc-clients.md
In the README under the "Getting Started" Section there is a link to HTTP RPC clients and examples.
When you click on "List of HTTP/RPC clients" you are directed to the following page currently
If you select the link to the Go client it is currently broken.
I think it is meant to go up two levels to the client/rpc page in the kubo repo which shows an example there and is more useful.
> Fix broken link in HTTP RPC client doc [skip changelog]

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Include memory usage fixes from libp2p/go-libp2p-asn-util#33.
> chore: update go-libp2p-asn-util

- client/rpc/pin.go
- cmd/ipfs/kubo/init.go
- core/commands/dag/import.go
- core/commands/pin/pin.go
- core/coreapi/block.go
- core/coreapi/dag.go
- core/coreapi/object.go
- core/coreapi/pin.go
- core/coreiface/options/pin.go
- core/coreiface/pin.go
- core/coreunix/add.go
- docs/changelogs/v0.26.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- fuse/ipns/common.go
- gc/gc.go
- gc/gc_test.go
- go.mod
- go.sum
- test/cli/pins_test.go
- test/dependencies/go.mod
- test/dependencies/go.sum
Closes #4586. **Requires** https://github.com/ipfs/boxo/pull/525.
A name will apply to all CIDs being pinned. So if you `ipfs pin add --label A [CID1] [CID2] [...]`, all CIDs will have label "A".
> feat: support optional pin names

- .github/workflows/docker-image.yml
- mk/util.mk
Reverts ipfs/kubo#10272 due to #10276. @Jorropo feel free to submit a new PR.
> Revert "build,docker: add support for riscv64"

- core/commands/pin/pin.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/pins_test.go
- test/dependencies/go.mod
- test/dependencies/go.sum
Closes #10277. Requires  https://github.com/ipfs/boxo/pull/537.
> feat(pinning): allow for overwriting local pin name

- .github/dependabot.yml
We update go packages as part of the release cycle, dependant bots also never fixup all the `go.sum` in the repo so this is noisy failing PRs.
> dependabot: only update github-actions

- core/corehttp/gateway.go
We were missing the OTel handler in the hostname option, so not all requests with traceparent were getting attached to the traceparent header.
> core/corehttp: wrap hostname option with otelhttp

- docs/RELEASE_CHECKLIST.md
- docs/RELEASE_ISSUE_TEMPLATE.md
Update release issue template to be more in line with what we do nowadays:
- Moved checklist to separate file, as we use it as comment, not in the main issue comment.
- Updated issue template to match what we've doing for the last releases.
> docs: improve release issue template

- core/commands/name/name.go
- test/cli/name_test.go
@2color this applies idea from [this chat](https://filecoinproject.slack.com/archives/C04M8232QRW/p1705497820293959?thread_ts=1705495369.535199&cid=C04M8232QRW) – lmk if this can be phrased better.
> docs(cli): name inspect --verify

- config/gateway.go
- config/init.go
Closes #8059 (we are shifting ecosystem towards removing /api/v0 from Gateway instad of fixing this)
> chore: remove Gateway.APICommands

- cmd/ipfs/kubo/daemon.go
- config/discovery.go
- config/gateway.go
- config/init.go
- config/swarm.go
- core/node/groups.go
- core/node/libp2p/sec.go
- core/node/libp2p/smux.go
- docs/config.md
Most of the removed options are many years old. In addition, they've all been removed in past iterations of Kubo. Some options were marked as removed in the config.md, but we still had a warning in the code to let users know they have been removed.
I think it's been long enough for all of this options, and enough Kubo iterations in order to alert the users. It is good to keep it in the config.md for now so that people can actually check. However, I think it's time to remove them from the code itself.
> config: remove all options that are marked as REMOVED

- cmd/ipfs/kubo/daemon.go
- core/corehttp/commands.go
- core/corehttp/gateway.go
- core/corehttp/gateway_test.go
- core/corehttp/routing.go
- docs/changelogs/v0.27.md
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- test/sharness/t0112-gateway-cors.sh
> core/corehttp: wrap gateway with headers, deprecate gateway /api/v0

- .github/workflows/gateway-conformance.yml
- Rules.mk
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
This PR aims to do end-to-end smoke-test and validation of upstream fixes:
- Run tests from https://github.com/ipfs/gateway-conformance/pull/190
- Against fix from https://github.com/ipfs/boxo/pull/523
- done, small fixes of top of Hannah's changes: https://github.com/ipfs/gateway-conformance/pull/190/commits/7ed58d142a6a8295777f5a6a5bd4f8e68c179355, https://github.com/ipfs/boxo/pull/523/commits/c3931cfaf4b36ec0e5def1499177a2b3c3bf6478
> fix(gw): negative entity-bytes beyond file size

- config/ipns.go
- core/coreapi/coreapi.go
- core/corehttp/gateway.go
- core/node/groups.go
- core/node/ipns.go
- docs/changelogs/v0.27.md
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Closes https://github.com/ipfs/boxo/issues/545.
> feat: add Ipns.MaxCacheTTL

- core/commands/add.go
In that situation, the data is not written to permanent storage, so a reference in MFS would be to p2p blocks at best.
The /add command in that situation is also likely to hang as it reads immediately the root node without being able to get it (it falls back to bitswap).
> commands/add: return an error when using --only-hash and --to-files

- docs/changelogs/v0.27.md
- docs/gateway.md
- go.mod
- go.sum
- repo/fsrepo/migrations/fetch_test.go
- repo/fsrepo/migrations/httpfetcher.go
- repo/fsrepo/migrations/migrations_test.go
- repo/fsrepo/migrations/setup_test.go
- repo/fsrepo/migrations/versions_test.go
- test/sharness/t0003-docker-migrate.sh
Closes #9159. This changes the current `HttpFetcher` to use CAR files. Because we have `/ipns/dist.ipfs.tech` as default (even though not used), I also implemented DNSLink resolution, as well as IPNS record fetching and verification.
Go tests were updated such that the test server now uses a CAR file backed gateway. This CAR file is generated on the fly before the tests begin. The reasoning behind this versus a static CAR is that the migration file names depend on the platform that they are being run on. 
You can also test this locally by spawning a repository, downgrading the version, and running the migrations:
```bash
make build
export IPFS_PATH=$(mktemp -d)
./cmd/ipfs/ipfs init
echo 13 > $IPFS_PATH/version
./cmd/ipfs/ipfs daemon
```
> repo/fsrepo/migrations: verified HTTP migrations

- test/cli/content_blocking_test.go
This is a small cleanup / refactor after reviewing draft from https://github.com/ipfs/kubo/pull/10359
I've found a bug in ?format=car, not a regression or a blocker – filled separate bug https://github.com/ipfs/kubo/issues/10361
> test: cleanup content blocking tests

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- .github/ISSUE_TEMPLATE/feature.yml
- README.md
- cmd/ipfs/dist/README.md
- docs/RELEASE_CHECKLIST.md
- docs/gateway.md
- docs/http-rpc-clients.md
- docs/windows.md
Bunch of cosmetic docs fixes and improvement I had accumulated in local branch:
- `discuss.ipfs.io` → `discuss.ipfs.tech`
- improved Docker section in README
- added links to some specs, in relevant places
> docs: updated links and refs to external resources

- core/commands/name/publish.go
- core/commands/routing.go
- docs/changelogs/v0.4.md
- docs/changelogs/v0.5.md
- test/3nodetest/bin/save_profiling_data.sh
> chore: remove repetitive words

- cmd/ipfs/kubo/daemon.go
While reviewing Kubo's usage here I found this workaround for an issue I introduced initially (Sorry!).
Now that Kubo is on the latest go-libp2p, the workaround is no longer needed.
> Cleanup old workaround for libp2phttp

- core/coreapi/unixfs.go
- core/node/builder.go
- core/node/groups.go
- core/node/storage.go
It looks to me that we don't need to create a full `IpfsNode` for `--only-hash`, we only need a null blockstore to simulate adding the data.
This also remove entirely the `NilRepo` option when creating `IpfsNode`, as it looked like a no longer necessary workaround to me.
> coreapi/unixfs: don't create an additional IpfsNode for --only-hash

- client/rpc/errors.go
- test/cli/dag_test.go
- test/sharness/t0119-prometheus.sh
> Fix some typos

- config/profile.go
We missed this in https://github.com/ipfs/kubo/pull/9708
Closes #9480 (no need for delay, even when HTTP and DHT are raced, lowpower benefits from cached HTTP responses)
> fix: switch lowpower profile to autoclient

- cmd/ipfs/kubo/daemon.go
- config/routing.go
- core/node/groups.go
- core/node/libp2p/routing.go
- docs/config.md
> config: make Routing.AcceleratedDHTClient a Flag

- core/corehttp/webui.go
Patch release that removes unnecessary requests to countly.ipfs.io which is no longer online
https://github.com/ipfs/ipfs-webui/releases/tag/v4.2.1
@hacdias ok to include in [0.28 RC1](https://github.com/ipfs/kubo/issues/10353)?
> chore: webui v4.2.1

- docs/RELEASE_CHECKLIST.md
- change thunderdome to after the dockers and binaries are released
- simplify the tag command for final releases
- add link to IPFS Companion issue about E2E tests
> docs: update release checklist

- core/corehttp/commands.go
- go.mod
- go.sum
- test/sharness/t0150-clisuggest.sh
- CORS package [has removed](https://github.com/rs/cors/commit/5288ed0d501c57cc8a517aa7e0a1f1b5bdbf4d69) 'Origin' from default 'Allowed Headers' so I had to update that.
- The package used to calculate the word distance for the CLI suggestions has also been updated so we now get slightly different options, so I updated the test.
> chore: bump to go-ipfs-cmds @ v0.11

- core/node/provider.go
While I was running kubo on my instance, I was encountering somewhat frequent crashes of the process with the following stack trace:
```
2024-04-25 20:41:17.361	
2024-04-25T11:41:17.331332+00:00 cannon-repo-snap-154780564-4013d1 systemd[1]: ipfs.service: Consumed 5min 27.300s CPU time.
2024-04-25 20:41:17.361	
2024-04-25T11:41:17.331245+00:00 cannon-repo-snap-154780564-4013d1 systemd[1]: ipfs.service: Failed with result 'exit-code'.
2024-04-25 20:41:17.361	
2024-04-25T11:41:17.330698+00:00 cannon-repo-snap-154780564-4013d1 systemd[1]: ipfs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
2024-04-25 20:41:17.361	
2024-04-25T11:41:17.296960+00:00 cannon-repo-snap-154780564-4013d1 ipfs[23032]: #011github.com/ipfs/boxo@v0.13.1/provider/reprovider.go:227 +0x88
2024-04-25 …
```
> fix: divide by zero fatal crash for reprovide rate check

- fuse/readonly/readonly_unix.go
This PR fixes missing prefix (closes #10242).
> fix(fuse): path parsing 

- core/commands/pin/pin.go
- core/coreapi/pin.go
- core/coreiface/options/pin.go
- docs/changelogs/v0.29.md
- test/cli/pins_test.go
Closes #10281.
This PR introduces the possibility to perform a search on pin names (case-sensitive, exact search). The command `ipfs pin ls --name "pinName"` will return all the pins labeled as `pinName`.
Notes:
- The  [condition](https://github.com/ipfs/kubo/compare/master...gystemd:feat/cmd/pin-name?expand=1#diff-095e9f00f8915b84abaca1d8f94c5d557ab78dc205fa217842679fb12dfd036fR402) `displayNames || name != ""`  is implemented to prevent redundancy in specifying the `--name `option. This ensures that users can simply use `ipfs ls --name A `instead of `ipfs ls --names --name A`.
> feat: enables searching pins by name

- config/config.go
- config/import.go
- config/profile.go
- core/commands/add.go
- core/commands/block.go
- core/commands/dag/dag.go
- core/commands/dag/put.go
- core/commands/files.go
- docs/changelogs/v0.29.md
- docs/config.md
- test/cli/add_test.go
This is an initial draft for an idea that @lidel and I were speaking about: a config section with the default data ingestion options. This would allow to easily change the defaults across the code-base easily in the future.
The largest problem at the moment is that the CID Version is, by default, 1 in some commands (`dag put`, `block put`) and 0 in others (`add`, except in cases where certain options are used). This was also the largest use case for this config section: being able to upgrade the default CID version in the future. However, we can't use this configuration option since not all commands use the same default at the moment.
My suggestion would be to investigate the possibility of changing the default of `ipfs add` to CIDv1, since this one seems to be the only one that still …
> config: introduce Import section

- client/rpc/pin.go
- core/commands/pubsub.go
- core/node/helpers.go
- go.mod
Looks like `github.com/pkg/errors` isn't used in `kubo`. There were few places where `errors` from stdlib will work perfectly. One `errors.Wrap(err, "...")` got replaced with `fmt.Errorf`.
> [skip changelog] Stop using github.com/pkg/errors

- core/node/libp2p/rcmgr.go
- docs/changelogs/v0.28.md
It seems like when configuring custom resource manager limits, the node fails to start with an error:
> Unable to initialize libp2p due to conflicting resource manager limit configuration.\nresource manager System.Streams (5000) must be bigger than ConnMgr.HighWater (2000)
With this fix the node starts - same if condition exists a few lines above for `rcm.System.ConnsInbound` and `rcm.System.Conns`.
Configure `ConnectionManager`:
```
"ConnMgr": {
"GracePeriod": "20s",
"HighWater": 2000,
"LowWater": 1500,
"Type": "basic"
},
```
and enable `ResourceManager`:
```
"ResourceMgr": {
"Enabled": true,
},
```
and configure some resource limits, especially **streams**:
```
> cat libp2p-resource-limit-overrides.json
{
"System": {
"Streams": 5000,
"StreamsInbound": 3500,
"StreamsOutbound": 1500, …
```
> fix(libp2p): streams config validation in resource manager

- core/commands/pin/pin.go
- docs/changelogs/v0.29.md
- test/cli/pins_test.go
This is a cosmetic fix for UX bug found during testing 0.29.0-rc2. 
- `pin add --name` had shorthand `-n`
- `pin ls --name` had no shorthand, and `--names` had `-n`
This PR unifies `-n`  making it a shorthand for the same parameter in both `pin ls` and `pin add`.
cc https://github.com/ipfs/kubo/pull/10412 https://github.com/ipfs/kubo/issues/10398
> fix(cli): unify `--name` shorthand in `pin ls` and `pin add`

- .github/workflows/gateway-conformance.yml
This PR aims to test and switch to v6 with changes from https://github.com/ipfs/gateway-conformance/pull/211
> chore: gateway-conformance v6

- config/autonat.go
- core/node/groups.go
- core/node/libp2p/nat.go
- docs/changelogs/v0.30.md
- docs/config.md
This PR is part of #10091 proposed by @sukunrt. 
It enables V2 (https://github.com/libp2p/specs/pull/538) alongside V1, and adds configuration option that allows disabling V2 (just in case).
> feat: run AutoNAT V2 service in addition to V1

- cmd/ipfs/kubo/daemon.go
- docs/changelogs/v0.30.md
- test/sharness/t0060-daemon.sh
This PR is based on today's colo discussion, aims to address two problems with `ipfs daemon` output during startup:
It no longer makes sense to list  all listener and announced multiaddrs when the node starts. Modern libp2p node will have 3-4 transports sharing the same UDP port, and also have a very long list of webtransport and webrtc direct certhashes inlined in the address.
This makes startup output hard to parse, and what is worse, there is no PeerID, making printing these addresses not very useful without calling 'ipfs id' anyway.
This change removes announced and discovered multiaddrs from the stdout and replaces them with prompt to run "ipfs id".  This allows user to learn about public address obtained via relays or UPnP.
Second change is to replace list of listeners in multiaddr …
> feat(daemon): improve stdout on startup

- version.go
> (generated by `kuboreleaser`)
This PR bumps master branch version as part of the v0.30 release (https://github.com/ipfs/kubo/issues/10436)
From now on, things that land in master needs will not be included in 0.30, and if need to, have  to be cherry picked to `release-v0.30.0` to be included in https://github.com/ipfs/kubo/pull/10490
> Update Version: v0.30 [skip changelog]

- docs/config.md
- docs/datastores.md
- docs/libp2p-resource-management.md
- docs/specifications/keystore.md
Hello
I found and fixed several spelling issues.
Br, Elias.
> Docs fix spelling issues

- go.mod
- go.sum
- test/bench/bench_cli_ipfs_add/main.go
- test/bench/offline_add/main.go
- test/integration/addcat_test.go
- Benchmarks were failing with error setting number of bits for ed25519 keys, which are the default now.
- Update the random data generation package to remove a dependency.
> fix: error during config when running benchmarks

- cmd/ipfs/kubo/start.go
- docs/changelogs/v0.30.md
- test/sharness/t0235-cli-request.sh
- Replaces PR #10233 by @softwareplumber
- Add test to check for hostname in HTTP header
Note: It is necessary to keep the call to `resolveAddr` to check for a resolvable address, otherwise the host is reported as offline when the address should be reported as not resolvable.
Closes #10232
Thank you @softwareplumber for this solution.
> fix(cli): preserve hostname specified with --api in http request headers

- README.md
- docs/changelogs/v0.30.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- test/sharness/lib/install-sharness.sh
> chore: boxo v0.23.0 and go-libp2p v0.36.3

- .github/workflows/interop.yml
We were running fix from https://github.com/ipfs/helia/pull/584, once it ships it is time to switch back to released version.
Context:
https://github.com/ipfs/helia/pull/584#issuecomment-2343839607
> chore: switch back to release helia-interop

- config/profile.go
- docs/config.md
- docs/datastores.md
Improves docs related to profiles:
> docs(config): improve profile descriptions

- core/corehttp/webui.go
- https://github.com/ipfs/ipfs-webui/releases/tag/v4.3.1
- https://github.com/ipfs/ipfs-webui/releases/tag/v4.3.2
> feat: use ipfs-webui@4.3.2

- docs/config.md
This PR updates documentation of [`Gateway.PublicGateways`](https://github.com/ipfs/kubo/blob/master/docs/config.md#gatewaypublicgateways) and makes it clear it is not about "defining a pool of gateways for http client for retrieval", abut "http server" for running own gateway.
I've seem people making this assumption multiple times, hopefully this will help (phrasing improvements welcome).
cc @SgtPooki @2color
> docs: clarify Gateway.PublicGateways

- cmd/ipfs/kubo/daemon.go
- cmd/ipfs/kubo/pinmfs.go
- cmd/ipfs/kubo/pinmfs_test.go
- core/commands/pin/remotepin.go
MFS pinning logis was returning errors on a channel, only to be logged by a separate goroutine. The errors were not used for any other purpose, so the logic could be significantly simplified by logging the error where it happened instead of returning it on a channel to be logged. This PR removes the unnecessary channel and logging goroutine.
A couple other minor simplifications and consistency changes were also made, such as passing a context as the first argument.
> refactor: simplify logic for MFS remote pinning

- config/internal.go
- core/node/bitswap.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Allow configuration of the bitswap server's replace WantHave with WantBlock maximum block size using the `Internal.Bitswap.WantHaveReplaceSize` config item. This sets the maximum size of a block in bytes up to which we will replace a want-have with a want-block. Setting a size of 0 disables this replacement and means that block sizes are not read for WantHave requests.
See https://github.com/ipfs/boxo/pull/672 for more details
> feat(bitswap): allow configuring WithWantHaveReplaceSize

- cmd/ipfs/kubo/daemon.go
- config/profile.go
- docs/changelogs/v0.31.md
- docs/config.md
This PR aims to fix footgun that is `lowpower` profile + warn users who already sabotaged themselves by disabling reprovide system (not announcing to DHT).
Users running on raspberrypi or other "lowpower" server often sabotaged themselves by disabling announcements when applying poorly documented `lowpower` profile ([example](https://discuss.ipfs.tech/t/understanding-long-access-times/18514/3)). 
To make matters worse,  we've been prominently hinting that user should enable this profile to save resources, we did that in examples and docs ([example](http://web.archive.org/web/20240924162820/https://docs.ipfs.tech/install/command-line/#system-requirements) – i've hidden this footgun from our docs, but the harm is already done)
This PR moves announcement settings to a separate profile, …
> feat: reprovider warning and announce-on|off profiles

- docs/changelogs/v0.31.md
- docs/config.md
Provide additional information about some key behaviors that may be useful for deciding what datastore to use.
> chore: update config doc with more info about pebble 

- cmd/ipfs/kubo/daemon.go
Closes #10515
```console
$ ipfs daemon
...
RPC API server listening on /ip4/0.0.0.0/tcp/5001
WebUI: http://0.0.0.0:5001/webui
```
```console
$ ipfs daemon
...
RPC API server listening on /ip4/0.0.0.0/tcp/5001
WebUI: http://127.0.0.1:5001/webui
```
> fix(daemon): webui URL when RPC listener is 0.0.0.0

- config/routing.go
- core/node/libp2p/routingopt.go
- docs/environment-variables.md
- routing/delegated.go
This PR applies [IPIP-484](https://github.com/ipfs/specs/pull/48) (cc @2color) protocol filtering to IPNI responses from `cid.contact/routing/v1/`.
-  this is ok because today's `cid.contact` implement backward-compatibility from https://specs.ipfs.tech/routing/http-routing-v1/#streaming and returns JSON instead of error
> feat(routing/http): support IPIP-484 and streaming

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
https://github.com/libp2p/go-libp2p/releases/tag/v0.36.5
> chore: go-libp2p v0.36.5

- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-build.yml
- .github/workflows/gateway-conformance.yml
- .github/workflows/gobuild.yml
- .github/workflows/golang-analysis.yml
- .github/workflows/golint.yml
- .github/workflows/gotest.yml
- .github/workflows/interop.yml
- .github/workflows/sharness.yml
- Dockerfile
- docs/changelogs/v0.31.md
- docs/examples/kubo-as-a-library/go.mod
- go.mod
[go1.23.2 includes potential fix](https://github.com/golang/go/issues?q=milestone%3AGo1.23.2+label%3ACherryPickApproved) for issue described in https://github.com/ipfs/kubo/issues/10501
Closes #10501
> chore: go 1.23(.2)

- core/corehttp/webui.go
https://github.com/ipfs/ipfs-webui/releases/tag/v4.3.3
> feat: ipfs-webui v4.3.3

- docs/changelogs/v0.32.md
- docs/config.md
Small note to ensure that a separate port is used for the AutoTLS listener.
> docs: add note about separate port use

- core/node/groups.go
- core/node/libp2p/addrs.go
- docs/config.md
This slipped through the crack, but it's basically the same fix as https://github.com/ipfs/kubo/pull/10492. We meant to get this in between when that PR landed and the initial AutoTLS one did but forgot. Could use a test to make sure it's correct before merging so we don't have to test it out with multiple repo paths manually.
> fix(autotls): store certificates at the location from the repo path

- go.mod
- go.sum
Testing latest commit before tagging a release in https://github.com/ipfs/go-ipfs-cmds/pull/269
Ref. https://github.com/ipfs/go-ipfs-cmds/releases/tag/v0.14.0
> chore: go-ipfs-cmds@v0.14.0

- client/rpc/api.go
- cmd/ipfswatch/main.go
- config/config.go
- docs/changelogs/v0.32.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- misc/fsutil/fsutil.go
- misc/fsutil/fsutil_test.go
- plugin/plugins/pebbleds/pebbleds.go
- repo/fsrepo/fsrepo.go
- repo/fsrepo/migrations/ipfsdir.go
- repo/fsrepo/misc.go
The `github.com/mitchellh/go-homedir` repo is archived, no longer needed, and no longer maintained.
- `homedir.Dir` is replaced by the stdlib `os.UserHomeDir`
- `homedir.Expand` is replaced by `fsutil.ExpandHome` in the `github.com/ipfs/kubo/misc/fsutil` package.
Additional functionality, such as `DirWritable` and `FileExists` was moved into or included in the `github.com/ipfs/kubo/misc/fsutil` package.
> chore: stop using go-homedir

- docs/changelogs/v0.32.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Ref. https://github.com/libp2p/go-libp2p-kad-dht/releases/tag/v0.28.0
- done, no red flags, [internal notes here](https://www.notion.so/Kubo-0-31-0-vs-0-32-0-12f1def3428780c0acd4cbdb4b14598a?pvs=4#13d1def3428780e5882ef8179729373b)
> fix: go-libp2p-kad-dht v0.28.0

- docs/RELEASE_CHECKLIST.md
Fixes to manual instructions identified during #10547
> docs: update RELEASE_CHECKLIST.md

- cmd/ipfs/kubo/daemon.go
- core/node/helpers.go
- core/node/ipns.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
> chore: update to boxo without goprocess

- core/node/provider.go
We had "magic number" 128 without any explanation.
Turns out the number informs many things, namely:
- The size of a batch that will be used for calculating average announcement time per CID, inside of `boxo/provider.ThroughputReport`
- the batch size in the output of `ipfs stats provide` command
This PR updates description + increases batch to 1000k to avoid false-positives asking users to enable accelerated clients when a desktop is under temporary load spike.
> fix: increase provider sample size

- docs/add-code-flow.md
- docs/datastores.md
> fix some typos in docs

- test/cli/delegated_routing_v1_http_proxy_test.go
The issue is that for dht providing to work correctly, at least two nodes must have dht routing.
Before, dht providing in the test always failed, but the test succeeded when the tested-CID was the one that the failure happened with (the first in the list for ProvideMany).
Follow up to #10595 .
> [skip changelog] tests/cli: fix flapping tests

- test/cli/harness/run.go
I did this to be able to obtain actual daemon output on the screen while debugging tests. Might be useful in the future even though it needs to manually set verbose somewhere.
> tests(cli/harness): use unused Verbose flag to pipe daemon outputs

- tracing/doc.go
The previous link has expired and has been replaced with the latest address.
> chore: fix broken url in comment

- client/rpc/pin.go
- client/rpc/unixfs.go
- cmd/ipfs/kubo/pinmfs.go
- core/commands/ls.go
- core/commands/pin/pin.go
- core/commands/pin/remotepin.go
- core/coreapi/pin.go
- core/coreapi/unixfs.go
- core/coreiface/pin.go
- core/coreiface/tests/block.go
- core/coreiface/tests/pin.go
- core/coreiface/tests/unixfs.go
- core/coreiface/unixfs.go
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Asynchronous functions should return errors over channels instead of embedding the error in the result type.
Closes #9974
> refactor(cmds): do not return errors embedded in result type

- core/commands/add.go
- docs/changelogs/v0.33.md
- test/sharness/t0040-add-and-cat.sh
Fixes #10611.
When we are adding to an MFS folder ("--to-files=folder/"), we append the filename to the folder name.
However, when wrapping, the wrapping folder has no name and `path.Base("")` returns `.`.
This creates a folder named "." inside the previous one. But mfs operations like `ls` think that "." is the current folder, and does not contemplate the option of a folder of name ".".
Dealing with unnamed files in MFS is in general a footgun, so this commits attempts to prohibit that case.
> fix(cmds/add): disallow --wrap with --to-files

- docs/changelogs/v0.33.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Boxo release PR https://github.com/ipfs/boxo/pull/746
https://github.com/ipfs/boxo/releases/tag/v0.25.0
> chore: boxo v0.25.0

- cmd/ipfs/kubo/daemon.go
- cmd/ipfs/kubo/init.go
- core/commands/add.go
- core/commands/cat.go
- core/commands/cid.go
- core/commands/dht.go
- core/commands/files.go
- core/commands/id.go
- core/commands/keystore.go
- core/commands/p2p.go
- core/commands/routing.go
- core/commands/stat.go
- core/coreapi/coreapi.go
- core/coreapi/key.go
- core/coreapi/name.go
- core/coreapi/routing.go
- core/coreapi/unixfs.go
- core/node/groups.go
- core/node/libp2p/rcmgr.go
- core/node/libp2p/smux.go
use errors.New to replace fmt.Errorf with no parameters
> chore: use errors.New to replace fmt.Errorf with no parameters

- cmd/ipfs/kubo/pinmfs.go
- cmd/ipfs/kubo/pinmfs_test.go
This mitigates slow mfs writes when the pinmfs daemon calls mfs.RootNode()
When writing lots of files to MFS, this call triggers a mfs directory cache sync operations. The cache grows forever and is unbounded. The more files added to a directory, the longer it takes. In the meantime, writing to mfs is locked.
The pinmfs, even when no remote pinning services are configured, will trigger this issue. When RootNode() takes more than 30 seconds, the issue will be triggered continuously causing a write-deadlock onto MFS.
This commit does not fix the fact that if you write 1M items into an MFS directory, the first time that the directory is traversed it will still have to sync those 1M items. It does at least prevent writes from stalling after about ~6000 items.
> [skip changelog] pinmfs: mitigate slow mfs writes when it triggers

- core/commands/files.go
- docs/changelogs/v0.33.md
This is a mitigation to increased MFS memory usage in the course of many writes operations.
The underlying issue is the unbounded growth of the mfs directory cache in boxo. In the latest boxo version, this cache can be cleared by calling Flush() on the folder. In order to trigger that, we call Flush() on the parent folder of the file/folder where the write-operations are happening.
To flushing the parent folder allows it to grow unbounded. Then, any read operation to that folder or parents (i.e. stat), will trigger a sync-operation to match the cache to the underlying unixfs structure (and obtain the correct node-cid).
This sync operation must visit every item in the cache. When the cache has grown too much, and the underlying unixfs-folder has switched into a HAMT, the operation can take …
> cmd/files: flush parent folders

- docs/config.md
This PR adds clarification about what current `Swarm.ResourceMgr.MaxMemory` does and mentions `GOMEMLIMIT`.
Goal here is point users at something other than touching resource manager, until we figure out what to do with problem described in #10621.
> docs: clarify Swarm.ResourceMgr.MaxMemory

- config/init.go
- docs/changelogs/v0.33.md
- docs/datastores.md
This is change in defaults which we discussed during one of colos last week to compliment other default change in https://github.com/ipfs/kubo/pull/10614.
> feat(flatfs): default to sync=false

- core/corehttp/webui.go
- docs/changelogs/v0.33.md
https://github.com/ipfs/ipfs-webui/releases/tag/v4.4.2 with IPLD Explorer fix for https://github.com/ipfs/ipld-explorer-components/issues/464
> fix: ipfs-webui v4.4.2

- .github/workflows/gateway-conformance.yml
- docs/changelogs/v0.33.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- test/sharness/t0115-gateway-dir-listing.sh
When a director gets redirected to a URL with a treailing slash, special chars in the directory name must be escaped in the redirect URL. This upgrades to a version of box that has that fix.
Depends on: https://github.com/ipfs/boxo/pull/779
Closes #10536
> fix/gateway: escape directory redirect url

- config/profile.go
- core/commands/cmdenv/cidbase.go
- core/node/libp2p/routing.go
- docs/content-blocking.md
- docs/debug-guide.md
- docs/delegated-routing.md
- docs/environment-variables.md
- docs/file-transfer.md
- test/cli/basic_commands_test.go
Accumulate trivial textual changes into this PR.
> chore: fix typos and comment formatting

- cmd/ipfs/kubo/start.go
- docs/changelogs/v0.33.md
- go.mod
- go.sum
- test/cli/cli_https_test.go
> fix(cli): support HTTPS in ipfs --api

- README.md
Adds https://github.com/taw00/ipfs-rpm to README.
> [skip changelog] docs: Add Fedora COPR to README

- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
> Upgrade to go-ds-pebble v0.4.2

- config/autotls.go
- core/node/libp2p/addrs.go
- docs/changelogs/v0.33.md
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/harness/peering.go
- test/dependencies/go.mod
- test/dependencies/go.sum
This PR is part of #10560 and #10580 
- updates to p2p-forge/client to version with fix from https://github.com/ipshipyard/p2p-forge/pull/42
- adds `AutoTLS.ShortAddrs` flag and enables it by default to benefit from shorter addrs discussed in https://github.com/ipshipyard/p2p-forge/pull/40
> fix(autotls): renewal and AutoTLS.ShortAddrs

- docs/changelogs/v0.33.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Ref. https://github.com/quic-go/quic-go/releases/tag/v0.49.0 with important QUIC fixes, including:
- https://github.com/quic-go/quic-go/pull/4804
- https://github.com/quic-go/quic-go/pull/4852
- https://github.com/quic-go/quic-go/pull/4844 
- https://github.com/quic-go/quic-go/pull/4883
> fix: quic-go v0.49.0

- test/sharness/t0060-daemon.sh
- test/sharness/t0061-daemon-opts.sh
Resolves #10682 
This PR adds [sloppy error handling flag](https://linux.die.net/man/1/socat) to the socat calls that started failing after the self-hosted GitHub Actions runners upgrade to Ubuntu 24.04.
It was tested here: https://github.com/ipfs/kubo/actions/runs/13038855183
> test: fix the socat tests after the ubuntu 24.04 upgrade

- core/commands/config.go
* `Datastore.Path` has been deprecated more than [7 years ago](https://github.com/ipfs/kubo/commit/5027b4b14f2fc60e808a39d3b3efc9316d8e511d#diff-757e54613dd89da7749369ffb9650951bf704bcbe1114de7390857092d1ef454R361)
* Replace it from `ipfs config --help` with `Routing.Type`
> fix: config help

- docs/changelogs/v0.33.md
- docs/changelogs/v0.34.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
https://github.com/ipfs/boxo/releases/tag/v0.27.4
> fix: boxo v0.27.4

- core/commands/config.go
- docs/changelogs/v0.33.md
- docs/changelogs/v0.34.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- version.go
https://github.com/ipfs/kubo/issues/10580#issuecomment-2634561087:
> Release v0.33.1

- README.md
https://docs.ipfs.tech/install/command-line/#system-requirements  states 6 GiB, updating readme to match that
> docs: update min requirements

- docs/changelogs/v0.34.md
- plugin/plugins/pebbleds/pebbleds.go
If the pebble database format is not explicitly set in the config, then set it to the latest format version by default. This will ensure that the database format is sufficiently up-to-date to be compatible with a major version upgrade of pebble.
> Update pebble db to latest format by default

- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/bin/Rules.mk
- test/dependencies/dependencies.go
- test/dependencies/go.mod
- test/dependencies/go.sum
- test/sharness/Rules.mk
- test/sharness/t0040-add-and-cat.sh
- test/sharness/t0043-add-w.sh
- test/sharness/t0045-ls.sh
- test/sharness/t0046-id-hash.sh
- test/sharness/t0080-repo.sh
- test/sharness/t0082-repo-gc-auto.sh
- test/sharness/t0087-repo-robust-gc.sh
- test/sharness/t0131-multinode-client-routing.sh
- test/sharness/t0181-private-network.sh
- test/sharness/t0231-channel-streaming.sh
- test/sharness/t0271-filestore-utils.sh
- test/sharness/t0272-urlstore.sh
- test/sharness/t0276-cidv0v1.sh
- test/sharness/t0500-issues-and-regressions-offline.sh
Needed in prep for go1.24 due to change in `rand.Seed` behavior.
> Replace go-random with random-data from go-test package

- core/node/provider.go
- docs/changelogs/v0.34.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Fixes #10596.
The reproviding process can take long. Currently, each CID to be provided is
obtained by making a query to the pinner and reading one by one as the CIDs
get provided.
While this query is ongoing, the pinner holds a Read mutex on the pinset.
If a pin-add-request arrives, a goroutine will start waiting for a Write mutex
on the pinset. From that point, no new Read mutexes can be taken until the writer
can proceed and finishes.
However, no one can proceed because the read mutex is still held while the
reproviding is ongoing.
The fix is mostly in Boxo, where we add a "buffered" provider which reads the
cids onto memory so that they can be provided at its own pace without making
everyone wait.
The consequence is we will need more RAM memory. Rule of thumb is 1GiB extra per 20M …
> provider: buffer pin providers

- README.md
- docs/config.md
cc @2color @hsanjuan  for proof-reading :pray:
> docs(readme): update min. requirements + cleanup

- core/node/provider.go
Fixes https://github.com/ipfs/kubo/issues/10714
Only register the callback function if reprovides are enabled.
+ typos in warning
> fix: reprovides warning

- config/init.go
- config/routing.go
- core/node/bitswap.go
- docs/changelogs/v0.35.md
- docs/config.md
Adds `Routing.IgnoreProviders`.
This requires initializing a custom providerQueryManager and using it instead of the default created internally in Bitswap. Since the default is created with some internal default configuration options (MaxProviders), this hardcodes it.
> Support WithIgnoreProviders() in provider query manager

- docs/changelogs/v0.34.md
I've stumbled upon this because it was shown on https://github.com/ipfs/kubo/pull/10770/files as:
> Unchanged files with check annotations (Preview)
> docs: Fix typo in v0.34 changelog [skip changelog]

- fuse/node/mount_unix.go
Add IPFS & IPNS path details to error.
This can make debugging issues such as #10762 more straightforward.
> fix: Add IPFS & IPNS path details to error (re. #10762) [skip changelog]

- docs/experimental-features.md
cc @ipfs/kubo-maintainers @Stebalien if there is more to add here or in https://github.com/ipfs/kubo/issues/7161
> docs: known issues with file/urlstores

- core/corehttp/webui.go
- docs/changelogs/v0.35.md
https://github.com/ipfs/ipfs-webui/releases/tag/v4.7.0
- part of https://github.com/ipfs/kubo/issues/10760
> feat: ipfs-webui v4.7.0

- config/internal.go
- core/node/bitswap.go
- docs/changelogs/v0.35.md
- docs/config.md
This PR is replacing hardcoded integer from https://github.com/ipfs/kubo/pull/10765 with named default and expose config option for adjusting it, like we do in Rainbow.
> feat(config): expose ProviderSearchMaxResults

- docs/fuse.md
Installing `fuse` with `apt-get` on Debian Bookworm breaks dependencies. The latest package name (that should come preinstalled) is `fuse3`.
Update the docs example with the correct name.
> docs(fuse): use latest package name

- docs/changelogs/v0.35.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
update `go-libp2p-pubsub` to [v0.13.1](https://github.com:/libp2p/go-libp2p-pubsub/releases/tag/v0.13.1)
> Update go-libp2p-pubsub to v0.13.1

- cmd/ipfs/kubo/daemon.go
- config/experiments.go
- config/profile.go
- config/provider.go
- config/routing.go
- core/commands/routing.go
- core/node/bitswap.go
- core/node/groups.go
- core/node/provider.go
- docs/changelogs/v0.35.md
- docs/config.md
- docs/experimental-features.md
- test/cli/provider_test.go
Kubo 0.35.0-rc1 had issues on Staging environment due too OOMs ([internal notes](https://www.notion.so/Kubo-0-34-1-vs-0-35-0-1ed1def342878037b7c1f8b67d7c986b?pvs=4#1ed1def342878070ba3ec1e526d86761)).
@guillaumemichel and @gammazero  suggested that the problem is related to provides, which should be disabled on that box.  This PR aims to implement ability to fully disable provides (and reprovides) as noted in #10803 and unblock Kubo 0.35 (https://github.com/ipfs/kubo/issues/10760)
> fix(config): wire up `Provider.Enabled` flag

- docs/changelogs/v0.35.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- Includes fix from https://github.com/ipshipyard/p2p-forge/pull/68
- Partially helps with https://github.com/ipfs/kubo/issues/10570
> fix(autotls): ignore /p2p-circuit addrs

- docs/changelogs/v0.35.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- Changelog: https://github.com/libp2p/go-libp2p-kad-dht/releases/tag/v0.33.1
- Smoke tests from https://github.com/ipfs/kubo/pull/10812 looked good to include this in https://github.com/ipfs/kubo/issues/10760
> fix: go-libp2p-kad-dht v0.33.1

- .github/workflows/gateway-conformance.yml
- docs/changelogs/v0.36.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
- Closes https://github.com/ipfs/kubo/issues/10808
- RN: https://github.com/ipfs/gateway-conformance/releases/tag/v0.8.0
> fix(gateway): gateway-conformance v0.8

- docs/fuse.md
> Update fuse docs with FreeBSD specifics

- core/commands/files.go
To avoid the blank Error: file does not exist and specify which file we failed to find.
Error before: `Error: file does not exist`
Error after: `Error: /my-cat-pic.jpg: file does not exist`
Closes #8671
> wrap user-facing mfs.Lookup error

- config/init.go
- config/swarm.go
- core/node/groups.go
- core/node/libp2p/libp2p.go
- docs/changelogs/v0.36.md
- docs/config.md
Allows users to set the connmgr silence period.
> config/swarm/connmgr: expose silence period

- core/node/bitswap.go
Similar to broadcast control. Useful for debugging/info purposes.
> core:constructor: add a log line about http retrieval

- docs/changelogs/v0.36.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
Go 1.25 incompatibility detected in
* https://github.com/Homebrew/homebrew-core/pull/226636
then:
* reported upstream in https://github.com/cockroachdb/swiss/issues/48
* fixed upstream https://github.com/cockroachdb/swiss/pull/49
The fix was brought to github.com/cockroachdb/pebble/v2 in
* https://github.com/cockroachdb/pebble/pull/4954
And released in https://github.com/cockroachdb/pebble/releases/tag/v2.0.6
Which is now used in this PR.
Full changelog: https://github.com/cockroachdb/pebble/compare/v2.0.3...v2.0.6
> chore: Upgrade github.com/cockroachdb/pebble/v2 to v2.0.6 for Go 1.25 support

- docs/changelogs/v0.37.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/dependencies/go.mod
- test/dependencies/go.sum
This fixes a couple of bugs that are causing problems with the AutoTLS address advertisement.
> chore: update go-libp2p and p2p-forge

- cmd/ipfs/kubo/daemon.go
This PR adds a note on `ipfs daemon` startup when accelerated DHT client is enabled, informing user that it may take a few minutes for performance to improve.
(original idea by @mishmosh in https://github.com/probe-lab/website/issues/176#issuecomment-3014345222)
cc may help with bringing clarity to users experiencing things like #10891
> feat(daemon): accelerated client startup note

- core/commands/commands_test.go
- core/commands/provide.go
- core/commands/stat_provide.go
- core/commands/stat_reprovide.go
- docs/changelogs/v0.37.md
- Move `ipfs stat reprovide` to `ipfs provide stat`
- Mark `ipfs stat provide` as deprecated and replaces by `ipfs provide stat`
- Mark `ipfs stat reprovide` as deprecated and replaces by `ipfs provide stat`
- Remove redundant code from deprecated subcommands
Closes #10869
> refactor: move `ipfs stat provide/reprovide` to `ipfs provide stat`

- fuse/readonly/ipfs_test.go
Test was failing becuase path passed to `path.NewPath` (from boxo) did not include a required namespace. Prepending the namespace to the path with "/ipfs/" fixes this.
> Fix failing FUSE test

- Dockerfile
- mk/golang.mk
Docker started failing in master and PRs – see https://github.com/ipfs/kubo/pull/10905#issuecomment-3186036451
Looked into this and I am more confused than I was before. `GOFLAGS=-buildvcs=false` IS in the `Dockerfile`. The problem is that the `Makefile`'s `$(shell ...)` commands don't inherit this environment variable.
This isn't a regression from a Go 1.25 update, image/ci uses 1.24. I suspect the issue has likely always existed but may have been masked or only recently become apparent due to (guessing):
1. Changes in how Docker caches layers
2. Changes in GitHub Actions environment
3. The specific conditions in the PR build environment
The root cause is that `$(shell ...)` in Make creates a new shell that doesn't inherit the parent's environment variables unless explicitly passed. My …
> fix(ci): docker build

- test/cli/harness/nodes.go
Connecting nodes in parallel can cause TLS handshake failures. For each node, connect to the other nodes serially. It is not necessary to connect in parallel as it does not save any significant time.
Closes #10932
> fix: harness tests random panic

- config/plugins.go
- test/cli/harness/node.go
- test/cli/telemetry_test.go
- test/sharness/lib/test-lib.sh
Disable the plugin in cli tests and sharness by default. Enable only in telemetry tests.
There are cases when tests get stuck or get killed and leave daemons hanging around. We don't want to be getting telemetry from those.
> fix: disable telemetry in test profile

- core/node/provider.go
If Sweeping Provider is enabled, but no DHT is supplied, `SweepingProviderOpt()` shouldn't return an error.
We want to transition Sweeping Provider to being the default provide mode, and it should be OK for a kubo node not to use a DHT. DHT provides will not happen, but fx shouldn't fail.
IIRC this was included in https://github.com/ipfs/kubo/pull/10834 but probably overwritten due to conflicts in https://github.com/ipfs/kubo/pull/10951/
> fix: SweepingProvider shouldn't error when missing DHT

- core/node/provider.go
> fix: SweepingProvider slow start 

- core/commands/add.go
- core/commands/cmdutils/utils.go
- core/commands/pin/pin.go
- core/commands/pin/remotepin.go
- docs/changelogs/v0.38.md
- test/cli/pin_name_validation_test.go
Kubo 0.38 ships with fixes that make it easier for users to name pins. Not having a limit comes with a risk of future limit breaking existing users. Let's add limit before it becomes a problem.
This PR adds validation to ensure pin names don't exceed 255 bytes across all commands that accept pin names. this prevents issues with filesystem limitations and improves compatibility.
255 was picked as lowest common denominator for max filename length in operating systems (mac/linux/windows).
affected commands:
- ipfs pin add --name
- ipfs add --pin-name
- ipfs pin ls --name (filter)
- ipfs pin remote add --name
- ipfs pin remote ls --name (filter)
- ipfs pin remote rm --name (filter)
> fix: limit pin names to 255 bytes

- config/internal.go
- core/commands/files.go
- core/node/core.go
- docs/changelogs/v0.38.md
- docs/config.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
- test/cli/files_test.go
- test/dependencies/go.mod
- test/dependencies/go.sum
This PR prevents unbounded memory growth while avoiding the data corruption risks of auto-flushing flagged by @hsanjuan
We need to remove automatic flush from boxo introduced in https://github.com/ipfs/kubo/pull/10971, it may lead to silent issues that are hard to debug. Instead counts `--flush=false` operations and errors to encourage users to develop a habit of calling `ipfs files flush` periodically. Users should have enough intuition to flush at sensible interval/batch, minimizing risks.
Boxo will no longer auto-flush (I'm reverting https://github.com/ipfs/boxo/pull/1037 in  https://github.com/ipfs/boxo/pull/1041) to avoid creating surface for more corruption issues. Kubo applies the limit to `ipfs files` commands instead.
This PR adds a global counter that tracks consecutive `ipfs …
> fix(mfs): add soft limit for `--flush=false`

- core/corehttp/webui.go
- https://github.com/ipfs/ipfs-webui/releases/tag/v4.9.1
> fix: update webui to v4.9.1

- .github/legacy/Dockerfile.goipfs-stub
- .github/legacy/goipfs_stub.sh
- .github/workflows/docker-image.yml
- bin/get-docker-tags.sh
- docs/changelogs/v0.39.md
implements docker part of #10941 by creating a stub image that redirects users from `ipfs/go-ipfs` to `ipfs/kubo`. we will ship this in 0.39.
- Closes https://github.com/ipfs/kubo/issues/10941
- add stub dockerfile and script in `.github/legacy/`
- modify `docker-image.yml` to push stub to `ipfs/go-ipfs` with same tags as `ipfs/kubo`
- remove `ipfs/go-ipfs` from `get-docker-tags.sh` to prevent docker-hub job from pushing to legacy name
- stub displays clear deprecation message directing users to `ipfs/kubo:release`
```console
$ docker run --rm -it --net=host ipfs/go-ipfs:staging-2025-09-30-239669e
...
Status: Downloaded newer image for ipfs/go-ipfs:staging-2025-09-30-239669e
ERROR: The name 'go-ipfs' is no longer used.
Please update your Docker scripts to use 'ipfs/kubo' instead of …
```
> feat: add docker stub for deprecated ipfs/go-ipfs name

- docs/changelogs/v0.39.md
- docs/examples/kubo-as-a-library/go.mod
- docs/examples/kubo-as-a-library/go.sum
- go.mod
- go.sum
This fixes a panic that happens when reusing a go-datastore Batch.
See: https://github.com/ipfs/go-ds-pebble/pull/61
> Upgrade go-ds-pebble to v0.5.3
